### ISSUE TITLE
Portal-Firewall rules diff from documentation

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#10]
The Firewall Rules for Portal seem a little bit messed up according to this Documentation:
https://enterprise.arcgis.com/en/portal/latest/administer/linux/ports-used-by-portal-for-arcgis.htm
compared with 
https://github.com/Esri/arcgis-powershell-dsc/blob/2fcd4f56ad07870cc7e788308a2a94f40b1890d3/Modules/ArcGIS/Configuration/ArcGISConfigure.ps1#L751-L828

From my perspective following Things should be reviewed:

- Open 7080 in first else branch as well.
- Don't open 6443 on any part as it is ArcGIS Server Port and is only necessary if ArcGIS Server is installed on that machine.
- Port 5703 is missing for HA-Portal (IsMultimachinePortal)
- According to Docu Ports 7120, 7220 and 7654 are only local ports (so Outbound should be sufficent)

Could you please advise on these findings?

**Comment by shailesh91** [comment]
- Opened 7080 in first else branch as well.
- Opening 6443 ArcGIS Server Port if ArcGIS Server is installed on that machine.
- Added Port 5703 for HA-Portal (IsMultimachinePortal)
- Port 7654 Requires Inbound and Outbound Rules as PGSQL needs for a Master-Slave Relationship
- Still Evaluating permission required on ports 7120, 7220.

**Comment by spitzerr** [comment]
@shailesh91 Did you come around this:

> Still Evaluating permission required on ports 7120, 7220.

**Comment by shailesh91** [comment]
@spitzerr For now, we are opening both inbound and outbound ports for 7120 and 7220 in case of HA Portal.
