### ISSUE TITLE
ArcGISFederation throws an error when installing a standalone server.

### ISSUE THREAD

**Issue by HakonD** [Esri/arcgis-powershell-dsc#106]
When installing a standalone ArcGIS server it seems like the script still wants to federate it with a nonexisting Portal resulting in this exception:

```
Finished DSC Job:- ArcGISConfigure. Time Taken - 00:05:55.6852990
ArcGISConfigure - Completed
Dot Sourcing the Configuration:- ArcGISFederation
Compiling the Configuration:- ArcGISFederation
PSDesiredStateConfiguration\Node : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\1.1.0\Configuration\ArcGISFederation.ps1:28 char:5
+     Node $AllNodes.NodeName
+     ~~~~
    + CategoryInfo          : MetadataError: (:) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ArgumentIsEmpty,PSDesiredStateConfiguration\node

Compilation errors occurred while processing configuration 'ArcGISFederation'. Please review the errors reported in error stream and modify your configuration code appropriately.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (ArcGISFederation:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration
```

Except for this, the install seems to be ok.

Configuration:

```
    "AllNodes": [
        {
            "NodeName": "localhost",
            "Role": [
                "ServerWebAdaptor"
            ]
        },
        {
            "NodeName": "theServername",
            "Role": [
                "Server"
            ],
            "SslCertifcate": {
                "Path": "somepath\\theCert.pfx",
                "Password": "aPassword",
                "Alias": "anAlias",
                "Target": ["Server"]
            }
        }
    ],
    "ConfigData": {
        "Version": "10.6",
        "ServerContext": "server02",
        "ServerRole": "GeneralPurposeServer",
```

**Comment by shailesh91** [comment]
@HakonD Now the federation part should be skipped with PR #99

**Comment by dellenbach** [comment]
Still a Problem with 1.1.1?

Finished DSC Job:- ArcGISConfigure. Time Taken - 00:00:15.0667168
ArcGISConfigure - Completed
Dot Sourcing the Configuration:- ArcGISFederation
Compiling the Configuration:- ArcGISFederation
Starting DSC Job:- ArcGISFederation
Start-DscConfiguration : The computer name was not specified and the configuration directory does not have any configuration 
files.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\1.1.1\ArcGIS.psm1:218 char:16
+ ...      $Job = Start-DscConfiguration -Path ".\$($ConfigurationName)" -F ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-DscConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDscConfigura 
   tionCommand

**Comment by HakonD** [comment]
Great, will give it a test tomorrow 👍
