### ISSUE TITLE
Patches from UNC-path throws error

### ISSUE THREAD

**Issue by dellenbach** [Esri/arcgis-powershell-dsc#109]
```
Cannot find path '\\_software\ESRI\AGS\patches' because it does not exist.
The PowerShell DSC resource '[ArcGIS_InstallPatch]ServerInstallPatch' with SourceInfo 'C:\Program Files\Win
dowsPowerShell\Modules\ArcGIS\1.1.3\Configuration\ArcGISInstall.ps1::78::25::ArcGIS_InstallPatch' threw one o
r more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to
 the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
The SendConfigurationApply function did not succeed.
```

**Comment by shailesh91** [comment]
@dellenbach PatchesDir param supports UNC paths. Can you tell me the path that you passed for PatchesDir param? And please make sure that the local system account and the account which is running configure-arcgis has permissions on that share.

**Comment by dellenbach** [comment]
The PatchesDir is something like '\\\\server\\dir... '. The install account has rights. The local system account has no access. Why does the local system account need access rights, while I am installing with a domain account. m 02.11.2018 8:20 nachm. schrieb Shailesh Goel <notifications@github.com>:@dellenbach PatchesDir param supports UNC paths. Can you tell me the path that you passed for PatchesDir param? And please make sure that the local system account and the account which is running configure-arcgis has permissions on that share.

**Comment by shailesh91** [comment]
The DSC Configuration runs as a Local System Account unless you run Configure-ArcGIS with -Credentials Parameter (I am assuming that you are running without that param. And you are talking about the domain account specified in the JSON Config File). DSC Script needs to look up for patches to install in that folder, hence the local system account of the orchestrating machine needs to have access to the Path.

**Comment by dellenbach** [comment]
I used the Configure-ArcGIS with -Credentials and a domain account. The Installation Files throw no Problems with UNC. Only the patches. Am 02.11.2018 10:15 nachm. schrieb Shailesh Goel <notifications@github.com>:The DSC Configuration runs as a Local System Account unless you run Configure-ArcGIS with -Credentials Parameter (I am assuming that you are running without that param. And you are talking about the domain account specified in the JSON Config File). DSC Script needs to look up for patches to install in that folder, hence the local system account of the orchestrating machine needs to have access to the Path.

**Comment by shailesh91** [comment]
@dellenbach Can you please try mapping the drive to check if the file share path is indeed accessible to the domain user you are running the powershell script as.
Below is a powershell you can use to do so. You will be able to see Q drive in your windows explorer. 
```
$net = New-Object -comobject Wscript.Network
$net.MapNetworkDrive("Q:","\\path\to\share",0,"domain\user","password")
```

**Comment by dellenbach** [comment]
I testet it with the same credentials as I used wit Configure-ArcGIS
`Configure-ArcGIS \\bulkfs\prjdaten\_software\ESRI\AGS\dev-t04_serveronly_unc.json -Credential $credentials`
That worked fine. Access granted and Q mapped.
It seems as if the configure script doesn't use the "Credential" User to Access the patch UNC path.

**Comment by shailesh91** [comment]
@dellenbach Actually it does indeed use it. Otherwise, you wouldn't have been able to install the server and portal in the same share. We start the DSC script with the user credential you provide as part of the configure-arcgis command. Any command executed as part of this script is executed as that credential if specified otherwise. 
I have tried on my dev environment I recreated your use case it worked for me. Can you please try, create a different share path on the unc then try once again. (And do check the permission on the sub folders)
-Shailesh

**Comment by dellenbach** [comment]
I had success with an new UNC Path. (?)
Thanks for you help!

**Comment by shailesh91** [comment]
Resolved.
