### ISSUE TITLE
Wait for Server after Cert-Installation

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#110]
After installing Root or Intermediate Certificates in Server the Server Restarts. In some configurations there is a racing condition, as the Server is not already up again as other parts try to Access it. The resource ArcGIS_Server_TLS which installs the certificates waits for the Windows-Service to come up again. Maybe it should wait for the url /ArcGIS/rest/info to lookup if the Server is operational again.

**Comment by shailesh91** [comment]
@scma-esrich yes you can submit a PR. We will try to review it ASAP.

**Comment by scma-esrich** [comment]
#114 is in.

**Comment by shailesh91** [comment]
Merged!
