### ISSUE TITLE
Attempt to configure data store failed

### ISSUE THREAD

**Issue by hmelendez** [Esri/arcgis-powershell-dsc#111]
I'm trying to deploy a two machine base deployment, Web Server with webadaptors and App Server with Portal, GIS Server and Data Store and a separete Orchestrating VM. [debugInstall_1061.log](https://github.com/Esri/arcgis-powershell-dsc/files/2659228/debugInstall_1061.log)
[BaseDeployment-TwoMachines_1061.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2659231/BaseDeployment-TwoMachines_1061.txt)

The machines are not domain join and I'm using the same local admin account for all. I've try to run the DSC script multiple time and it fails on the fallowing steps:

- Creating the Data Store: PowerShell DSC resource ArcGIS_DataStore  failed to execute Set-TargetResource functionality with error message: Register Data Store Failed after multiple attempts. @{code=500; message=Attempt to configure data store failed.. Extended error message: Attempt to configure data store failed.. Extended error message: Attempt to configure data store failed.. Extended error message: null; details=} 

- Registering the Portal Web Adator: PowerShell DSC resource MSFT_WaitForAll  failed to execute Set-TargetResource functionality with error message: Resource '[ArcGIS_Portal]Portalhrm-app-base' on machine(s) 'hrm-app-base' is not ready after '90' retries with retry interval of '60' second(s). 
The SendConfigurationApply function did not succeed.

**Comment by shailesh91** [comment]
@hmelendez 
For the first error, on the datastore machine can you check if the "https://hrm-app-base.1ukjfl4fnoqe1psswma00gvpkg.qx.internal.cloudapp.net:6443/arcgis/admin" is accessible and you are able to log in. 
For the second error, can you please check if you can PowerShell Remote from your web adaptor machine to your portal machine?

**Comment by hmelendez** [comment]
I had PSRemoting enable on all VMs but only the orchestrating machine was able to connect on that port to all VMs, I did not expect other machines to be PSRemoting to each other. My question is do all of them need to PSRemote between them or is it limited to the portal WebAdaptor and Portal VM?

**Comment by shailesh91** [comment]
There are more dependencies like portal web adaptor and portal VM. Some of them are the primary server and datastore, Portal and Standby Portal, server and another server node, primary data store, and standby data store, etc. Based on the config you create we build a dependency graph (This is what we need WaitFors').
