### ISSUE TITLE
ArcGIS_WebAdaptor - Test-TargetResource - check for portal-URL also

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#118]
We had issues with a broken environment, when the IIS-service or a WA-site within IIS was stopped due to a problem in a former setup-run. I think, this had to do with how the check for the WA is currently done:

Within _ArcGIS_WebAdaptor.psm1_ in the _Test-TargetResource_-function you are checking for an available URL-endpoint only in the case of server, not for portal. For portal, the check is done based on values of the _WebAdaptor.config_ but this doesn't check for real availability of the portal-WA-website within IIS, during runtime. This leads to a missing endpoint for future operations that rely on an available portal-WA.

Or do I misinterpret that?

**Comment by scma-esrich** [comment]
@spitzerr, FYI.

**Comment by shailesh91** [comment]
@scma-esrich The rationale behind the availability check for the server was to see if admin endpoint was enabled or not. It wasn't intended to check for the availability of server endpoint in general.
But your's is also a valid point. If you can please submit a PR for the same, it would be great.

**Comment by scma-esrich** [comment]
@shailesh91, thanks for the answer. I will try to prepare a PR.

**Comment by shailesh91** [comment]
@scma-esrich Closing this issue. Fixed in release v2.0.0!

**Comment by scma-esrich** [comment]
Thanks @shailesh91 !
