### ISSUE TITLE
Parameter "Portal > ContentDirectoryLocation" - misleading behavior during setup

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#119]
If you specify your own full path for the parameter "Portal" > "ContentDirectoryLocation", you cannot use subdirectories that haven't been created manually before, because only the portal-REST-interface "/portaladmin/createnewsite" is used to "create" that location.

You should use PowerShell instead for testing and/or creating the path first and then switch to using the portal-REST-interface "/portaladmin/createnewsite" just for the portal-site-folder itself.

At the moment you get back a misleading error because the REST-interface finds you don't have sufficient write-privileges, which is true for the portal-process trying to do the work but not for the PowerShell-DSC-account used for the setup.

**Comment by scma-esrich** [comment]
@spitzerr, FYI

**Comment by cameronkroeker** [comment]
@scma-esrich I'm not quite sure I understand the issue. Could you expand or elaborate a bit more?

The "Portal" > "ContentDir" (exmaple: CONTENTDIR="C:\arcgisportal") is used by the Portal setup to create the local directories:
C:\arcgisportal\content
C:\arcgisportal\db 
C:\arcgisportal\index
C:\arcgisportal\logs

https://enterprise.arcgis.com/en/portal/latest/install/windows/silently-installing-portal-for-arcgis.htm#GUID-590EF5CB-BBDA-45B4-A3CB-5FE922B43063

And the "Portal">"ContentDirectoryLocation" is used for Portal site creation which creates the content directory. This can be a local or shared path.

**Comment by scma-esrich** [comment]
@cameronkroeker it's a long time ago, I hope I can recall everything correctly here:
I was talking about the "ContentDirectoryLocation" specifically. Lets say, we set this config-parameter to the UNC-location "\\MYSHARE\arcgis\portal\contendirectory". "\\MYSHARE" already exists, the subfolders "arcgis" and "portal" don't. Then the setup will fail. It needs all subfolders except "contentdirectory" already present.
The last time I had a look at the code, only our REST-interface "/portaladmin/createnewsite" was used and it seemed that our Portal-service was not allowed to create the subfolders ("arcgis" and "portal" in this case) permission-wise. Therefore I suggest to check with PowerShell if the full path down to "\\MYSHARE\arcgis\portal\" already exists and if not to create it. After that you could trigger the "/portaladmin/createnewsite" REST-interface and it should work just fine.
This behavior should be identical, no matter if you use a UNC-path or a local one.
