### ISSUE TITLE
SSL certificate installation fails

### ISSUE THREAD

**Issue by carstenpiepel** [Esri/arcgis-powershell-dsc#121]
SSL certificate installation fails when using the `SslCertifcate `configuration node as documented in the [wiki](https://github.com/Esri/arcgis-powershell-dsc/wiki/Variables-reference-page-for-JSON-configuration-files). Looking at the code, the node name is actually `SslCertifcates`. Both names are spelled incorrectly as it should be either` SslCertif**i**cate` or` SslCertif**i**cates`.

Please fix the spelling and update the documentation.

**Comment by shailesh91** [comment]
Closing this issue. Fixed with release v2.0.0!
