### ISSUE TITLE
No Portal-Token on Portal_TLS

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#122]
We tried to run PowerShell DSC on a three server deployment in Azure. The Script failed on implementing the SSLCertificate in Portal as it gets not token. From our perspective it is because of these lines:
https://github.com/Esri/arcgis-powershell-dsc/blob/ec532e72f6a9068160ec26b6a33e316a2318410c/Modules/ArcGIS/DSCResources/ArcGIS_Portal_TLS/ArcGIS_Portal_TLS.psm1#L92-L101
The Portal is "created" with the Node-Name we provided in the [configuration.json.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2816307/configuration.json.txt). But at these lines it finds the "Azure internal machine name" to generate the Token-URL. This URL redirects to the intended URL, but the DSC is obviously not following the redirect and gets no token. Wen could come around this by using $CName instead of $FQDN for creating the Token-URL.

Same needs to be changed in Test-Target...

https://github.com/Esri/arcgis-powershell-dsc/blob/ec532e72f6a9068160ec26b6a33e316a2318410c/Modules/ArcGIS/DSCResources/ArcGIS_Portal_TLS/ArcGIS_Portal_TLS.psm1#L209-L221

**Comment by shailesh91** [comment]
@spitzerr does Wait-ForUrl check fail at line 100?

**Comment by spitzerr** [comment]
@shailesh91 yes line 100 fails.

**Comment by shailesh91** [comment]
@spitzerr this needs to happen on internal URL as CName could very well be an external load balancer endpoint which might not have been configured. I tried to check if this is indeed a problem on Azure, but couldn't repro this. Can you please run the following script on your azure portal machine. It will prompt you for a credential, please provide a primary site admin account credential.
```powershell
function Wait-ForUrl
{
    [CmdletBinding()]
    param
    (
		[Parameter(Position = 0, Mandatory=$true)]
        [System.String]
		$Url, 

        [System.Int32]
		$MaxWaitTimeInSeconds = 150, 

        [System.Int32]
		$SleepTimeInSeconds = 5,

        [switch]
		$LogFailures,

        [System.String]
		$HttpMethod = 'GET',

        [System.Int32]
	    $MaximumRedirection=5,

		[System.Int32]
	    $RequestTimeoutInSeconds=15
    )

    [bool]$Done = $false
    [int]$TotalElapsedTimeInSeconds = 0
    Write-Verbose "Waiting for Url $Url"
    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
    [System.Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls
    while((-not($Done)) -and ($TotalElapsedTimeInSeconds -lt $MaxWaitTimeInSeconds)) {
	    try {
			if($HttpMethod -ieq 'GET') {
				[System.Net.HttpWebRequest]$webRequest = [System.Net.WebRequest]::Create($Url)
				$webRequest.Timeout  = ($RequestTimeoutInSeconds * 1000)
                $webRequest.AllowAutoRedirect = $MaximumRedirection -gt -1
                $webRequest.MaximumAutomaticRedirections = [System.Math]::Max(1, $MaximumRedirection)
				$resp = $webRequest.GetResponse()
				Write-Verbose "Url is $($resp.StatusCode)"
                $Done = $true
			}
			else {
				$resp = Invoke-WebRequest -Uri $Url -UseBasicParsing -UseDefaultCredentials -ErrorAction Ignore -TimeoutSec $RequestTimeoutInSeconds -Method $HttpMethod -DisableKeepAlive -MaximumRedirection $MaximumRedirection
				if($resp) {
					if(($resp.StatusCode -eq 200) -and $resp.Content) { 
						$Done = $true
						Write-Verbose "Url is ready : $Url"
					}else{
						Write-Verbose "[Warning]:- Response:- $($resp.Content)"
					}
				}else {
					Write-Verbose "[Warning]:- Response from $Url was NULL"
				}
			}
        }
        catch {
            Write-Verbose "[Warning]:- $($_)"
        }
        if(-not($Done)) {
            Sleep -Seconds $SleepTimeInSeconds
            $TotalElapsedTimeInSeconds += $SleepTimeInSeconds
        }
    }
}

function Get-PortalToken 
{
    [CmdletBinding()]
    param(
		[Parameter(Mandatory=$true)]		
        [System.String]
		$PortalHostName, 

		[Parameter(Mandatory=$false)]
        [System.String]
		$SiteName = 'arcgis', 

		[parameter(Mandatory = $true)]
		[System.Management.Automation.PSCredential]
		$Credential,

		[Parameter(Mandatory=$true)]
        [System.String]
		$Referer,

        [Parameter(Mandatory=$false)]
        [System.Int32]
		$Port = 7443,

        [System.Int32]
        $MaxAttempts = 10
    )
    $url = ("https://$($PortalHostName):$($Port)/$SiteName/sharing/rest/generateToken")
    $ServicePoint = [System.Net.ServicePointManager]::FindServicePoint($url)
    $ServicePoint.CloseConnectionGroup("")
    $token = $null
    $Done = $false
	$NumAttempts = 0
	while(-not($Done) -and ($NumAttempts -lt $MaxAttempts)) {
		try {
			$token = Invoke-ArcGISWebRequest -Url $url -HttpFormParameters @{ username = $Credential.UserName; password = $Credential.GetNetworkCredential().Password; referer = $Referer; f = 'json' } -Referer $Referer -LogResponse  
		}
		catch {
			Write-Verbose "[WARNING]:- Portal at $url did not return a token on attempt $($NumAttempts + 1). Retry after 15 seconds"
		}
		if($token) {
			Write-Verbose "Retrieved server token successfully"
			$Done = $true
		}else {
			Start-Sleep -Seconds 15
			$NumAttempts = $NumAttempts + 1
		}
    }
    $token
}

function To-HttpBody($props)
{
    [string]$str = ''
    foreach($prop in $props.Keys){                
        $key = [System.Web.HttpUtility]::UrlEncode($prop)
        $value = [System.Web.HttpUtility]::UrlEncode($props[$prop])
        $str += "$key=$value&"
    }
    if($str.Length -gt 0) {
        $str = $str.Substring(0, $str.Length - 1)
    }
    $str
}

function Invoke-ArcGISWebRequest
{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [System.String]
		$Url, 

        [Parameter(Mandatory=$true)]
        $HttpFormParameters,
        
        [Parameter(Mandatory=$false)]
        [System.String]
		$Referer = 'http://localhost',

        [Parameter(Mandatory=$false)]
        [System.Int32]
		$TimeOutSec = 30,

        [Parameter(Mandatory=$false)]
        [System.String]
		$HttpMethod = 'Post',

		[Parameter(Mandatory=$false)]
		[switch]
		$LogResponse
    )

    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true} # Allow self-signed certificates
	[System.Net.ServicePointManager]::DefaultConnectionLimit = 1024
	[System.Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls
    $HttpBody = To-HttpBody $HttpFormParameters
    $Headers = @{'Content-type'='application/x-www-form-urlencoded'
                    'Content-Length' = $HttpBody.Length
                    'Accept' = 'text/plain'     
                    'Referer' = $Referer             
                }
    if($HttpMethod -ieq 'GET') {
        $UrlWithQueryString = $Url
        if($UrlWithQueryString.IndexOf('?') -lt 0) {
            $UrlWithQueryString += '?'
        }else {
            $UrlWithQueryString += '&'
        }
        $UrlWithQueryString += $HttpBody
        $wc = New-Object System.Net.WebClient
        if($Referer) {
            $wc.Headers.Add('Referer', $Referer)
        }
        $res = $wc.DownloadString($UrlWithQueryString)
		if($LogResponse) { 
			Write-Verbose "Response:- $res"
		}
		if($res) {
			$response = $res | ConvertFrom-Json
			$response
		}else {
			Write-Verbose "Response from $Url is NULL"
		}
     }else {
        $Headers = @{'Content-type'='application/x-www-form-urlencoded'
                'Content-Length' = $HttpBody.Length
                'Accept' = 'text/plain'     
                'Referer' = $Referer             
            }        
        $res = Invoke-WebRequest -Method $HttpMethod -Uri $Url -Body $HttpBody -Headers $Headers -UseDefaultCredentials -DisableKeepAlive -UseBasicParsing -TimeoutSec $TimeOutSec   
        if($res -and $res.Content) {          
			if($LogResponse) { 
				Write-Verbose "Response:- $($res.Content)"
			}
            $response = $res.Content | ConvertFrom-Json
            $response  
        }else { 
            throw "Request to $Url failed. Response returned NULL"
        }
    }    
}

$MachineEndPoint = $env:COMPUTERNAME
$FQDN = $MachineEndPoint
if($FQDN.IndexOf('.') -lt 0) {
    $FQDN = Get-FQDN $MachineEndPoint
}
$PortalUrl = "https://$($FQDN):7443"  
$Referer = $PortalUrl
$SiteName = "arcgis"
Wait-ForUrl "https://$($FQDN):7443/$($SiteName)/sharing/rest/generateToken" -Verbose
$token = Get-PortalToken -PortalHostName $FQDN -SiteName $SiteName -Credential $SiteAdministrator -Referer $Referer -Verbose
```

**Comment by spitzerr** [comment]
@shailesh91 unfortunately I cannot access our test-installation right now. As soon as I get access I'll try the script and give feedback to you.

 I think the problem occurs because the "Webcontexturl" is already set to the CName at these step. To come around this problem another solution could be to change the sequence and first do the Portal_TLS and setting the WebcontextURL at last or allowing the request to follow the redirect and send the Token-Request to the redirected URL.

**Comment by shailesh91** [comment]
@spitzerr I tried it on a configured portal. But I will try to check if this is indeed the problem.

**Comment by spitzerr** [comment]
@shailesh91 I tried your script and it fails at getting the token:
```
VERBOSE: Waiting for Url https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/generateT
oken
VERBOSE: Url is OK
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 1. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 2. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 3. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 4. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 5. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 6. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 7. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 8. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 9. Retry after 15 seconds
VERBOSE: [WARNING]:- Portal at https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net:7443/arcgis/sharing/rest/gen
erateToken did not return a token on attempt 10. Retry after 15 seconds
```

Just one thought about (not) using the cname here. As far as I could see the cname is used for federating the server with portal I think its absolutely useful and the expected behavior. Therefor if using an external LB for CName it hast to be configured at this point of time anyways. As Portal_TLS starts afterwards there should be no problem in using cname?

**Comment by spitzerr** [comment]
@shailesh91 
P.S.: If I open the Token-URL from above in a browser I'll get redirected to the given Nodename from the Config.json:
`https://esriportal-vm.esri.local:7443/arcgis/sharing/rest/generateToken`

**Comment by shailesh91** [comment]
@spitzerr in the context of Azure deployment this might be true where the Load balancer configurations might have happened before. But this might not always be the case. I will have to give this a little more thought. 
Maybe we need to find a better way to handle redirections when making this get portal token call.

**Comment by shailesh91** [comment]
@spitzerr Can you try the Invoke-WebRequest in the script with -PreserveAuthorizationOnRedirect switch parameter.

**Comment by spitzerr** [comment]
@shailesh91 I couldn't test this switch parameter as it is introduced in PowerShell 6 and I'm on PowerShell 5.1 (which is latest Desktop version). I also tried using PowerShell Core 6, but this does not work either as the dnsclient module and therefor Get-FQDN is not applicable.

Maybe it is not about the redirect itself but about the certificate error before the redirection? As the url is an external (https://EsriPortal-vm.wefjosdfkjsldkfjojosidfbvsdf.ax.internal.cloudapp.net) it maybe checks the certificate (which it does not on localhost) and fails as the cert is for https://esriportal-vm.esri.local and it will not get to the redirection? I tried -SkipCertificateCheck but its also introduced in PowerShell 6 so I couldn't get this running...

I added the following to the Invoke-ArcGISWebRequest and now I get an response. But the response is the generateToken Website in HTML so maybe the HTTP-Body gets lost on Redirect?
```


if (-not ([System.Management.Automation.PSTypeName]'ServerCertificateValidationCallback').Type)
{
$certCallback = @"
    using System;
    using System.Net;
    using System.Net.Security;
    using System.Security.Cryptography.X509Certificates;
    public class ServerCertificateValidationCallback
    {
        public static void Ignore()
        {
            if(ServicePointManager.ServerCertificateValidationCallback ==null)
            {
                ServicePointManager.ServerCertificateValidationCallback += 
                    delegate
                    (
                        Object obj, 
                        X509Certificate certificate, 
                        X509Chain chain, 
                        SslPolicyErrors errors
                    )
                    {
                        return true;
                    };
            }
        }
    }
"@
    Add-Type $certCallback
 }
[ServerCertificateValidationCallback]::Ignore()
```

**Comment by shailesh91** [comment]
@spitzerr Can you please try the script I gave once again with the following change. (Adding a trailing slash to the following line). 
```$url = ("https://$($PortalHostName):$($Port)/$SiteName/sharing/rest/generateToken")```
According to Nikhil this is sometime one of the reasons for redirections.
I am trying to setup a deployment for azure and run the module there meanwhile. If you could provide me a sense of your Azure Resources being used or if you have an arm template that would be great.

**Comment by spitzerr** [comment]
@shailesh91  I tried the trailing slash, but it does not help at all. It is redirecting because of the privatePortalURL is different to the URL you find by Get-FQDN. Why are you not using the node-name here?

I got your sample working by adding these two lines:

>         $request = Invoke-WebRequest -Method $HttpMethod -Uri $Url -Body $HttpBody -MaximumRedirection 0 -ErrorAction Ignore -Headers $Headers -UseDefaultCredentials -DisableKeepAlive -UseBasicParsing -TimeoutSec $TimeOutSec
>         $Url = $request.Headers.Location

About our Azure Environment I attached the [ARM-Template](https://github.com/Esri/arcgis-powershell-dsc/files/2869301/ARM-Template.zip) to this post. We did 3 Maschines with the same template and used them according to the configuration.json from my first post.
We also created first a DNS Private Zone for esri.local:
https://docs.microsoft.com/nb-no/azure/dns/private-dns-overview
https://docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-cli
https://azure.microsoft.com/de-de/blog/azure-dns-private-zones-now-available-in-public-preview/

If you like it is also possible to make a skype session and look at our environment...

**Comment by shailesh91** [comment]
@spitzerr node name is not always a reliable endpoint to make a web request as we have seen in our testing. I am validating the fix for the script you have provided. Can you try the portal function (with changes you made) in the above script by replacing it over here
https://github.com/Esri/arcgis-powershell-dsc/blob/0fa1ca8dcadaaa83b791bf48468787458a76dd3c/Modules/ArcGIS/ArcGISUtility.psm1#L43-L69

**Comment by spitzerr** [comment]
@shailesh91 I think we get redirected because the privatePortalUrl is set to the Nodename in our case. I understand that it is not reliable, but these lines figure out the private portal url and configures them at the portal. this privateportalurl should be used in any further request to portal as it redirects to this url from now on:
https://github.com/Esri/arcgis-powershell-dsc/blob/0fa1ca8dcadaaa83b791bf48468787458a76dd3c/Modules/ArcGIS/DSCResources/ArcGIS_Portal/ArcGIS_Portal.psm1#L568-L580

I'll try the fix you mentioned and come back to you with the results

**Comment by spitzerr** [comment]
@shailesh91 It works by replacing Get-PortalToken with the following:

```
    $url = "https://$($PortalHostName):$($Port)/$SiteName/sharing/rest/generateToken"
    [System.Net.HttpWebRequest]$wr = [System.Net.WebRequest]::Create($url)
    $wr.Timeout = (15 * 1000)
    $wr.AllowAutoRedirect = $true
    $wr.MaximumAutomaticRedirections = 1
    $resp = $wr.GetResponse()
    $url = $resp.ResponseUri.OriginalString
    Invoke-ArcGISWebRequest -Url $url -HttpFormParameters @{ username = $Credential.UserName; password = $Credential.GetNetworkCredential().Password; referer = $Referer; f = 'json' } -Referer $Referer -LogResponse  

```

**Comment by shailesh91** [comment]
@spitzerr I was trying to recreate your environment in Azure, but I am getting winrm errors about the machines not being in the trusted host list. Can you please lmk how did you counter this error.

**Comment by spitzerr** [comment]
@shailesh91 
First we did a `winrm quickconfig` on each machine and then we added all machines to the trusted hosts like this `Set-Item WSMan:\localhost\Client\TrustedHosts -Value 'esriportal-vm.esri.local,esriserver-vm.esri.local,esriwa-vm.esri.local,esriadmin-vm.esri.local'`.
Further more we used an additional administration-machine to start the DSC-Script from, which is not part of the ArcGIS Enterprise Environment.

You are very invited to inspect our Environment by skype meeting if you like.

**Comment by shailesh91** [comment]
@spitzerr I recreated your environment, I was not able to repro the redirection. 
When I open the generate token endpoint in a browser window, it is not redirected to private portal URL or the webcontexturl. If you want we can compare our environments tonight if you want on skype.

**Comment by shailesh91** [comment]
@spitzerr https://github.com/Esri/arcgis-powershell-dsc/blob/0fa1ca8dcadaaa83b791bf48468787458a76dd3c/Modules/ArcGIS/Configuration/ArcGISConfigure.ps1#L785-L795

To Portal_TLS resource just add the portalendpoint property
``` Portalendpoint = $MachineFQDN ``` 

This should hopefully resolve your problem of not being able to get the token.

**Comment by spitzerr** [comment]
@shailesh91  yeah
the suggested fix from https://github.com/Esri/arcgis-powershell-dsc/issues/122#issuecomment-468460658 with `PortalEndPoint` in camelcase did the trick.
Do you implement this in the 10.7 release?

**Comment by shailesh91** [comment]
@spitzerr this will indeed be implemented in the new version of Module which will be backward compatible.

**Comment by shailesh91** [comment]
@spitzerr Closing this issue. Implement in release v2.0.0!
