### ISSUE TITLE
Firewall not opened on server

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#123]
On our [configuration.json.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2816318/configuration.json.txt) we have defined a server which should be federated, but as there is no DataStore the Server will not be set as hosted Server. Additionally the WebAdaptor is installed on a different machine as the ArcGIS Server. Therefor the ArcGIS Server needs to accept communication on Ports 6080/6443 from WebAdaptor Machine.
Unfortunately at this scenerio the following if-clause will be $false:
https://github.com/Esri/arcgis-powershell-dsc/blob/ec532e72f6a9068160ec26b6a33e316a2318410c/Modules/ArcGIS/Configuration/ArcGISConfigure.ps1#L157-L163

from our perspective there needs to be an addional check if the WebAdaptor for Server is installed on a different machine.

**Comment by shailesh91** [comment]
Closing this issue. Fixed with release v2.0.0!
