### ISSUE TITLE
Additional PowerShell DSC settings may be required

### ISSUE THREAD

**Issue by joekayaker** [Esri/arcgis-powershell-dsc#125]
We successfully installed ArcGIS Enterprise using a customized BaseDeployment-SingleMachine.json settings on a Windows Server 2016 Standard VM. We ran into a couple of issues before we were successful that we want to share to help others in case they run into them.

- **Unable to install NuGet and PowerShellGet** - When we attempted to run 

`PS C:\Windows\system31> Install-Module ArcGIS`

 we received the following error:

`NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
provider must be available in 'C:\Program Files PackageManagement Provider Assemblies' or "CUsers gisadmin AppData Local\PackageManagement Provider Assemblies'. You can also install the NuGet provider by running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install and import the NuGet provider now?
[Y] Yes [N] No [S] Suspend [?] Help (default is "Y"): Y
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ".
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement Install-PackageProvider : No match was found for the specified search criteria for the provider "NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags. At C:\Program Files Windows PowerShell Modules PowerShellGet 1.0.0.1\PSModule.psmi:7405 char:21
$null = PackageManagement Install-PackageProvider -Name $script:N ..
CategoryInfo
InvalidArgument: (Microsoft. Power...PackageProvider :InstallPackageProvider) [Install-Pac kageProvider], Exception
FullyQualifiedErrorId : NoMatchFoundFor Provider, Microsoft. PowerShell. PackageManagement. Cmdlets. InstallPackageProvider

PackageManagement Import-PackageProvider : No match was found for the specified search criteria and provider name "NuGet'. Try"Get-PackageProvider -ListAvailable' to see if the provider exists on the system. At C:\Program Files\Windows PowerShell\Modules PowerShell Get\1.0.0.1\PSModule. psmi:7411 char:21 + ... $null = PackageManagement Import-PackageProvider -Name $script:Nu ...
CategoryInfo
: Invalid Data: (NuGet:String) [Import-PackageProvider], Exception + FullyQualifiedErrorId : NoMatchFoundForCriteria, Microsoft. PowerShell. PackageManagement.cmdlets. ImportPackageProvider`

We tracked it down to an issue with PowerShell not being able to communicate over HTTPS. We set the [Net.ServicePointManager]::SecurityProtocol so it could negotiate HTTPS requests using the following command:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

- **Unblock all files in ArcGIS modules folder** - We received errors that indicated ArcGIS couldn't access some of its dependent scripts that are located in the DSCResources folder, such as ArcGIS_Install.psm1, ArcGIS_License.psm1. etc. We had to unblock all of the files recursively in the ArcGIS folder using the following code:

 `Get-ChildItem 'C:\Program Files\WindowsPowerShell\Modules\ArcGIS\1.1.4' -recurse | Unblock-File`

- **Install 7-zip in default location**- We usually install all applications on a non-OS drive. The ArcGIS module requires that 7-zip is installed on the "C:\" drive.

**Comment by shailesh91** [comment]
@joekayaker one way to get around the PowerShell issue is to download Module zip folder from GitHub and push it to target machines using the script below. This script also unblocks all the files in the ArcGIS Module Folder.
https://github.com/Esri/arcgis-powershell-dsc/wiki/Scripts-to-push-the-ArcGIS-Module
As for the 7-zip, it is a known limitation. We will try to tackle that in upcoming releases.

**Comment by joekayaker** [comment]
Thank you @shailesh91! I hadn't noticed the appendices until today....I'll definitely use them on my next installs.

**Comment by nshampur** [comment]
we look for 7zip in program files.
https://github.com/Esri/arcgis-powershell-dsc/blob/821db80873e58051ffe94b27778d3c04d8c00c9d/Modules/ArcGIS/DSCResources/ArcGIS_Install/ArcGIS_Install.psm1#L106 

is this a case where 7zip is not installed in Program Files?

**Comment by joekayaker** [comment]
@nshampur we had 7-Zip installed on a drive other than C:\Program Files, for example X:\Program Files. Once we uninstalled from X: and reinstalled to C:\Program Files everything worked great.

**Comment by nshampur** [comment]
@joekayaker . Gotcha.  Yes the code looks in program files which is typically on the OS disk (wherever that may be  C:\ or D:\)

**Comment by shailesh91** [comment]
@joekayaker Closing this issue. Added support for externalizing 7zip path in release v2.0.0!
