### ISSUE TITLE
Use Azure Files storage for configuration store using DSC?

### ISSUE THREAD

**Issue by dwoollcombe** [Esri/arcgis-powershell-dsc#127]
Hi,

I am deploying a multi machine ArcGIS Enterprise site in Azure and would like to use Azure Files (Cloud Storage) for the configuration store as well as the content store.

I have attempted to do this without success as I get an error related to FileShare.  It works okay when referencing non Azure Files share.  I have tried referencing UNC of Azure Files and also mapping as a drive:
PSDesiredStateConfiguration\Node : One or both of the Config Store Location and Server Directories Root Location is not a file share location
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configuration\ArcGISConfigure.ps1:72 char:5
+     Node $AllNodes.NodeName
+     ~~~~
    + CategoryInfo          : NotSpecified: (:) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException,PSDesiredStateConfiguration\node

I believe this is possible with Cloud Builder - can it be done with arcgis-powershell-dsc?  Can anybody provide an example config?

Thanks for your advice.

**Comment by nshampur** [comment]
@dwoollcombe 

Couple of considerations
1. Performance of Azure Files (Standard SKU) is not good and hence not recommended for (m)any large deployments.  Azure Premium Files will be an option when it reaches GA later in the year.
2. Make sure the Azure Files is mounted by running the net use command as the ArcGIS Service Account

**Comment by shailesh91** [comment]
@dwoollcombe the Fileshare creation error is a reported bug that will be resolved soon.

**Comment by dwoollcombe** [comment]
Thanks for your advice.

I tried mounting via 'net use' and still had an error.  I guess this is related to the bug @shailesh91 referred to.  The bug and advice on Azure Files (Standard SKU) will have me use a file share hosted on a windows server for now.  I am keen to try again when bug address and Azure Premium Files available.
