### ISSUE TITLE
Question: Can DNS alias be used for NodeName?

### ISSUE THREAD

**Issue by prez13** [Esri/arcgis-powershell-dsc#128]
We want to install an general purpose GIS Server and want to make it as independent of machine names as possible, with a later migration to other machines in mind. When using PowerShell DSC for deployment, is it possible to use a DNS alias instead of a machine name or IP for NodeName?

**Comment by shailesh91** [comment]
@prez13 it can possibly be used but in issue #122 we found a bug that prevents its use as of now. A new version will be available in Late March, which will try to address the issue.

**Comment by shailesh91** [comment]
@prez13 Closing this issue. Fixed with release v2.0.0! Please try and reopen if this hasn't been resolved.
