### ISSUE TITLE
ArcGIS Federation fails silently

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#130]
Hello,

After running ArcGIS Install no error was reported so I thought everything went fine.
Testing the portal, I realized that the federated ArcGIS Server was not a "Hosting one" but it should have been. Looking at the verbose log, I noticed the error:

[WARNING]:- Update operation did not succeed. Error:- Failed to update federated server 'FQDN:6443 (id: foobar)'. The ArcGIS Server site has not been licensed as a GIS Server Standard or GIS Server Advanced.

The error occurs because my authorization file contains several authorization numbers (GIS Server Standard and Imagery Role) and I believe only one is authorized.

I think it should raised a proper error to know that something went wrong and the configuration is not in the desired state:
https://github.com/Esri/arcgis-powershell-dsc/blob/0fa1ca8dcadaaa83b791bf48468787458a76dd3c/Modules/ArcGIS/DSCResources/ArcGIS_Federation/ArcGIS_Federation.psm1#L436-L446

Thanks

**Comment by nshampur** [comment]
@Biboba - Thanks for reporting.

The Federation operation can often return false negatives for various reasons and hence we choose to ignore certain errors as warning to avoid deployment/configuration failures. We'll look to see if this is an error condition that is worth catching.

**Comment by Biboba** [comment]
Closing for clean-up as it was solved ;-)
Thanks !
