### ISSUE TITLE
Cannot install SSL certificate because arcgis server machine is registered with its IP

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#132]
Hello,

I don't know why but my machine registered on the ArcGIS server is registered with its IP rather than FQDN
https://FQDN:6443/arcgis/admin/machines/1.2.3.4

And when I try to upload SSL Certificate using "SslCertifcates" property, I received the following error:
"Not able to find machine in site with either hostname $MachineName or fully qualified domain name $FQDN"

Any idea, why was the machine registered with its IP rather than hostname ?

Thanks !

**Comment by Biboba** [comment]
You will find below more details from the VERBOSE log. 
But what I find interesting in this log is the following line:

[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Using File System Based Storage for the config store

I wonder if the file mentionned is the one located in "framework/etc/" named hostname.properties.
Because this file looks like the following:
#Hostname properties set by AgsStartup plugin.
#Fri Mar 08 13:38:22 CET 2019
hostname=1.2.3.4
defaultDirectoriesRoot=D\:\\arcgisserver

So it does have the hostname IP in addition to the wrong defaultDirectoriesRoot path as mentionned by @shailesh91 in https://github.com/Esri/arcgis-powershell-dsc/issues/55

**ArcGISConfigure--Verbose.txt**
---
[HOSTNAME]: LCM:  [ Start  Resource ]  [[ArcGIS_WindowsService]ArcGIS_for_Server_Service]
[HOSTNAME]: LCM:  [ Start  Test     ]  [[ArcGIS_WindowsService]ArcGIS_for_Server_Service]
[HOSTNAME]: LCM:  [ End    Test     ]  [[ArcGIS_WindowsService]ArcGIS_for_Server_Service]  in 0.2600 seconds.
[HOSTNAME]: LCM:  [ Start  Set      ]  [[ArcGIS_WindowsService]ArcGIS_for_Server_Service]
[HOSTNAME]:                            [[ArcGIS_WindowsService]ArcGIS_for_Server_Service] [WARNING] Stopping Server :- Cannot validate argument on parameter 'Message'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
[HOSTNAME]: LCM:  [ End    Set      ]  [[ArcGIS_WindowsService]ArcGIS_for_Server_Service]  in 1.5930 seconds.
[HOSTNAME]: LCM:  [ End    Resource ]  [[ArcGIS_WindowsService]ArcGIS_for_Server_Service]
[HOSTNAME]: LCM:  [ Start  Resource ]  [[ArcGIS_Service_Account]Server_RunAs_Account]
[HOSTNAME]: LCM:  [ Start  Test     ]  [[ArcGIS_Service_Account]Server_RunAs_Account]
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] RunAsAccount Username:- DOMAIN\username
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Install Dir for ArcGIS Server is C:\Program Files\Arcgis\Server\
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Testing Permission for User DOMAIN\username on Directory C:\Program Files\Arcgis\Server\
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Permissions are not set for C:\Program Files\Arcgis\Server\
[HOSTNAME]: LCM:  [ End    Test     ]  [[ArcGIS_Service_Account]Server_RunAs_Account]  in 0.2200 seconds.
[HOSTNAME]: LCM:  [ Start  Set      ]  [[ArcGIS_Service_Account]Server_RunAs_Account]
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] RunAsAccount Username:- DOMAIN\username
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Install Dir for ArcGIS Server is C:\Program Files\Arcgis\Server\
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Testing Permission for User DOMAIN\username on Directory C:\Program Files\Arcgis\Server
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Providing RunAs Account 'DOMAIN\username' has the required permissions to C:\Program Files\Arcgis\Server
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] icacls.exe C:\Program Files\Arcgis\Server /grant DOMAIN\username:(OI)(CI)F
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Restarting Service ArcGIS Server
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Stopping the service
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Stopped the service
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Starting the service
[HOSTNAME]:                            [[ArcGIS_Service_Account]Server_RunAs_Account] Restarted Service ArcGIS Server
[HOSTNAME]: LCM:  [ End    Set      ]  [[ArcGIS_Service_Account]Server_RunAs_Account]  in 21.6220 seconds.
[HOSTNAME]: LCM:  [ End    Resource ]  [[ArcGIS_Service_Account]Server_RunAs_Account]
[HOSTNAME]: LCM:  [ Start  Resource ]  [[ArcGIS_Server]ServerHOSTNAME]
[HOSTNAME]: LCM:  [ Start  Test     ]  [[ArcGIS_Server]ServerHOSTNAME]
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Fully Qualified Domain Name :- FQDN
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Checking for site on 'http://FQDN:6080'
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Unable to detect if Site Exists. Was NOT able to retrieve token for PSA
[HOSTNAME]: LCM:  [ End    Test     ]  [[ArcGIS_Server]ServerHOSTNAME]  in 66.9770 seconds.
[HOSTNAME]: LCM:  [ Start  Set      ]  [[ArcGIS_Server]ServerHOSTNAME]
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Site Administrator UserName:- siteadmin
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Fully Qualified Domain Name :- FQDN
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Waiting for Server 'http://FQDN:6080/arcgis/admin' to initialize
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Configured Host Name  is not equal to FQDN. Setting it
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Version of ArcGIS Server is 10.6.9270
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Version of ArcGIS Server does not require removal of EC2 Listener from NodeAgent xml file
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Restarting Service ArcGIS Server
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Stopping the service
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Stopped the service
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Starting the service
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Restarted Service ArcGIS Server
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Waiting for Server 'http://FQDN:6080/arcgis/admin' to initialize
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Checking for site on 'http://FQDN:6080'
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Creating Site
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Using File System Based Storage for the config store
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Waiting for Server 'http://FQDN:6080/arcgis/admin' to initialize
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] POST http://FQDN:6080/arcgis/admin/createNewSite with -1-byte payload
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] received 20-byte response of content type application/json;charset=UTF-8
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Response from CreateSite:-
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Created Site
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Waiting for Server 'http://FQDN:6080/arcgis/admin' to initialize
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Get Single Cluster Mode Setting
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] POST http://FQDN:6080/arcgis/admin/system/deployment/ with 77-byte payload
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] received 26-byte response of content type application/json;charset=UTF-8
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] {"singleClusterMode":true}
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Current Single Cluster Mode @{singleClusterMode=True}
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Waiting for Server 'http://FQDN:6080/arcgis/admin' to initialize
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Ensuring Log Level WARNING
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] POST http://FQDN:6080/arcgis/admin/logs/settings with 77-byte payload
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] received 280-byte response of content type application/json;charset=UTF-8
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Response from Create Site:- @{settings=}
[HOSTNAME]:                            [[ArcGIS_Server]ServerHOSTNAME] Current Log Level:- WARNING
[HOSTNAME]: LCM:  [ End    Set      ]  [[ArcGIS_Server]ServerHOSTNAME]  in 167.2660 seconds.
[HOSTNAME]: LCM:  [ End    Resource ]  [[ArcGIS_Server]ServerHOSTNAME][](url)

**Comment by shailesh91** [comment]
As a workaround, for now, @Biboba you might want to clear that file (framework/etc/hostname.properties.)  out. And try rerunning the Configure-ArcGIS command. 
PS. These are the default values that are already present in amazon ami that Esri provides that you are encountering.

**Comment by Biboba** [comment]
@shailesh91 Thanks for the reply. Will try that.
Any thought about that one:
[HOSTNAME]: [[ArcGIS_WindowsService]ArcGIS_for_Server_Service] [WARNING] Stopping Server :- Cannot validate argument on parameter 'Message'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

Thanks

**Comment by shailesh91** [comment]
@Biboba I am cannot repro this issue on my environment. Will need more info to repro this.

**Comment by Biboba** [comment]
@shailesh91
Deleting the file "hostname.properties" and rerunning Configure-ArcGIS does not work. It get stuck for ever at testing "ArcGIS_Server".
Indeed, after restarting the ArcGIS Server, I cannot connect to it myself. 

Having a look at the ArcGIS Server log:
<Msg time="2019-05-04T00:03:03,974" type="WARNING" code="7315" source="Admin" process="14484" thread="1" methodName="" machine="100.99.98.97" user="" elapsed="" requestID="">Failed to update the data store with updated list of server machines. {0} Server machine 'https://FQDN:2443/arcgis/datastoreadmin/updateServerMachines' returned an error. 'Invalid Token.'</Msg>
<Msg time="2019-05-04T00:03:09,749" type="WARNING" code="7722" source="Server" process="14484" thread="1" methodName="" machine="100.99.98.97" user="" elapsed="" requestID="">ArcGIS Server has detected that the server machine name '100.99.98.97' has been changed to 'FQDN'. ArcGIS Server will be updated automatically to use the new host name. If you have enabled SSL and your certificate was using the previous machine name, you must generate a new SSL certificate and configure your ArcGIS Server site to use it. If you had configured the ArcGIS Web Adaptor to use your previous machine name, you will need to reconfigure it with a new URL that uses the updated machine name.</Msg>

I tried several times and it is systematic. In fact the issue is more general and problematic and the SSL certificate was only a consequence. Do you have any workaround ? Do you know with hostname.properties is set to the IP instead of the hostname ?

Thanks for your help

**Comment by cameronkroeker** [comment]
@Biboba 

Perhaps the instance has more than one Network Interface Controller card (NIC) or DNS record. This could be why Portal/Server/DS is binding to the IP instead of FQDN.

The hostname.properties file may need to be modified to point to the FQDN for Portal/Server/DS respectively:

[AGS](https://enterprise.arcgis.com/en/server/latest/deploy/windows/multiple-nic-cards-dns-entries.htm)

[Portal](https://enterprise.arcgis.com/en/portal/latest/administer/windows/installing-portal-for-arcgis.htm#ESRI_SECTION1_139D5EECE2EF489C84DA7DD2B57A0FCE)

[DS](https://enterprise.arcgis.com/en/portal/latest/administer/linux/create-data-store.htm#ESRI_SECTION1_4C43EEBE3ABC444082E185FA2B96DA2C)

**Comment by Biboba** [comment]
Hello @cameronkroeker,

Thanks for your reply.
I don't think that there is more that one NIC:
`netsh interface show interface`
returns only one interface for Ethernet.

I tried a deployment of ArcGIS Enterprise on a single host and I don't have this problem with Portal for ArcGIS or with the datastore. The machine name is configured to FQDN for them.
Also, the script is already setting the hostname property to FQDN in "Set-ConfiguredHostName":
https://github.com/Esri/arcgis-powershell-dsc/blob/11e0364c92e3cfdb31270d415accabef4a71ce74/Modules/ArcGIS/DSCResources/ArcGIS_Server/ArcGIS_Server.psm1#L153-L160
But then after restarting the ArcGIS Server service, the file is overwritten to its IP...

Finally, when I install and configure manually the ArcGIS server on this machine, I don't have this problem. After running the setup, the file "hostname.properties" does not exist and after initializing the site with HTML interface, the ArcGIS Site machine is properly configured with its FQDN. 
If I restart it, "hostname.properties" is not created and arcgis server machine is still set to FQDN.

Do you have any idea ? I am under the impression (not tested yet), that if I remove the "Set-ConfiguredHostName" from the configuration, I would not face this issue.

Thanks for your help !

**Comment by Biboba** [comment]
So I confirm that if I comment out the following section:
https://github.com/Esri/arcgis-powershell-dsc/blob/11e0364c92e3cfdb31270d415accabef4a71ce74/Modules/ArcGIS/DSCResources/ArcGIS_Server/ArcGIS_Server.psm1#L156-L159

Everything works as expected and the ArcGIS Server is properly configured with FQDN and does not switch to IP when restarted. Basically "hostname.properties" is never created.

It is funny because both Portal for ArcGIS and dataStore have a similar file ("hostname.properties" for Portal for ArcGIS and "hostidentifier.properties" for dataStore) created by DSC and they are not changed to IP adress when restarting the services. It is only with the ArcGIS Server that this phenoma occurs systematically.

I precise that at the moment it is an ArcGIS Enterprise deployment on one machine.

Any idea why does this issue occur ?

Thanks

**Comment by Biboba** [comment]
To put it in a nutshell, I believe the question is why is the hostname.properties file overwritten by the "AgsStartup plugin" of the ArcGIS Server ?

**Comment by nshampur** [comment]
This is an EC2Observer node agent plugin that tries to account for hostname changes in AWS EC2. 
This may be what is happening here.

**Comment by Biboba** [comment]
Thanks for the reply @nshampur.
FYI, my VM is hosted in Openstack and I don't know if it can help but in the log of ArcGIS Configure there is:
"Version of ArcGIS Server does not require removal of EC2 Listener from NodeAgent xml file"

**Comment by Biboba** [comment]
@cameronkroeker, do you think a bug for the ArcGIS Server product should be opened ? It looks to me more about the ArcGIS Server than arcgis-powershell-dc ?
Thanks

**Comment by cameronkroeker** [comment]
Hello @Biboba,

I recommend opening an Esri Technical Support case, so that they can help investigate the issue further.

Thanks,
Cameron

**Comment by Biboba** [comment]
Hello @cameronkroeker,

 I finally had some time to come back to this issue and try to reproduce it without using 'arcgis-powershell-dsc' library.

  So let say my machine name is "foo" and have the alias "bar": it has thus several DNS entries.
After manually installing ArcGIS Server 10.7.1, I create the hostname.properties file and add the following entry:
```
hostname=bar.company.com
```
I restart the ArcGIS Server service and then the hostname.properties file has been overwritten by ArcGIS Server and looks like this:
```
#Hostname properties set by AgsStartup plugin.
#Wed Aug 21 11:07:22 CEST 2019
hostname=188.200.150.227
```

Just to let you know that I just opened a ticket with the support and I will let you know the outcome.

Thanks

**Comment by nshampur** [comment]
what does a DNS lookup for bar.company.com  look like
using nslookup 
or PowerShell's Resolve-DnsName

**Comment by Biboba** [comment]
`nslookup bar.company.com`

>

```
Server:  ip-dns-2.ipv6.company.com
Address:  1001:1358:101:1100::5

Name:    foo.company.com
Address:  188.200.150.227
Aliases:  bar.company.com
```

**Comment by Biboba** [comment]
But FYI, if I remove the alias "bar" and just create a hostname.properties with the following entry:
`hostname=foo.company.com`
the file is overwritten anyway:
```
#Hostname properties set by AgsStartup plugin.
#Thu Aug 22 10:21:12 CEST 2019
hostname=188.200.150.227
```

DNS lookup returns the following in this case:

`nslookup bar.company.com`

```
Server:  ip-dns-2.ipv6.company.com
Address:  1001:1358:101:1100::5

Name:    foo.company.com
Address:  188.200.150.227
```

**Comment by Biboba** [comment]
Support made me remove NodeAgentExt.xml file and now it does work properly: 
the file is not overwritten.
"Since Openstack is operating as a private cloud, we assume the plugin is treating the machine as it would an EC2 instance in AWS".

**Comment by Biboba** [comment]
FYI, a bug has been logged regarding this issue:
BUG-000124901 - "When deploying ArcGIS Enterprise to a Private Cloud, the AgsStartupPlugin treats the VM as an EC2 instance"

I am closing this issue as it is not related to arcgis-powershell-dsc.

Thanks for your help

**Comment by mkarikari** [comment]
@cameronkroeker I'm hitting similar issue related to IP address being used instead of FQDN on generic EC2 Windows 2016 box with 10.6.1. Is there any flags or configuration to get around this?  I plan to test the work around the commenter mentioned with commenting out code, but was hoping for a cleaner approach if one exists.

**Comment by cameronkroeker** [comment]
> @cameronkroeker I'm hitting similar issue related to IP address being used instead of FQDN on generic EC2 Windows 2016 box with 10.6.1. Is there any flags or configuration to get around this? I plan to test the work around the commenter mentioned with commenting out code, but was hoping for a cleaner approach if one exists.

@mkarikari if this is an Esri/ArcGIS AMI then perhaps try removing the arcgis_cloud_platform environment variable.

**Comment by mkarikari** [comment]
Actually this isnt a ESRI ami, its an instance based on regular windows '16 image

**Comment by cameronkroeker** [comment]
> Actually this isnt a ESRI ami, its an instance based on regular windows '16 image

Thanks for confirming @mkarikari. The only workaround I am aware of is to comment out the AgsStartupPlugin from the NodeAgentExt.xml file.

**Comment by mkarikari** [comment]
Thanks @cameronkroeker, where is the nodeagentext.xml file located at?

**Comment by cameronkroeker** [comment]
> Thanks @cameronkroeker, where is the nodeagentext.xml file located at?

@mkarikari 

By default its in `C:\Program Files\ArcGIS\Server\framework\etc`

**Comment by mkarikari** [comment]
@cameronkroeker 
Ah I see. Based on that though, changing that file only make since to change if run in Install or InstallLicense mode then. If you run InstallLicenseConfigure, updating wouldn't scale when deploying to multiple systems since setting up the site is part of the process. I will move forward with just commenting out that code section within the .ps1 file like Biboba originally mentioned

**Comment by Biboba** [comment]
@mkarikari,
FYI, do not forget to comment out the same part in [ArcGIS_ServerUpgrade](https://github.com/Esri/arcgis-powershell-dsc/blob/master/Modules/ArcGIS/DSCResources/ArcGIS_ServerUpgrade/ArcGIS_ServerUpgrade.psm1#L73-L80) DSC resource otherwise the restore of webgisdr will fail !

cf. https://community.esri.com/t5/high-availability-and-disaster-recovery-questions/arcgis-enterprise-11-0-webgisdr-restore-fails/m-p/1204062#M562
