### ISSUE TITLE
arcGIS/Group Managed Service Account (gMSA) 

### ISSUE THREAD

**Issue by shayrob2** [Esri/arcgis-powershell-dsc#133]
All, do you know what verisons of arcGIS is gMSA compatible?   I have look at several articles and haven't gotten a clear answer for this question.  Any assistance you can provide would greatly be appreciated.

**Comment by shailesh91** [comment]
@shayrob2 ArcGIS Powershell Module doesn't support gMSA. There is an issue (#100) open but I can't give a definite ETA on when this feature will be available.

**Comment by shayrob2** [comment]
@shailesh91 thanks for your response.  Can you please clarify the following things regarding ArcGIS and the Powershell DSC?

- After installation does ArcGIS have to be managed with Powershell DSC?
- Can you clarify that you can or cannot have ArcGIS managed service accounts outside of using Powershell DSC?

Any information you can provide would greatly be appreciated.

**Comment by shailesh91** [comment]
@shayrob2 you can definitely configure MSA accounts and it is not at all necessary to manage ArcGIS using Powershell DSC after deployment.
But you might run into problems when upgrading using Powershell DSC if you do configuration changes outside DSC. Though you can always upgrade manually.
