### ISSUE TITLE
Support non-default 7zip installation paths

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#135]
Hi

I tried to run an ArcGIS GeoEvent Server DSC installation. I installed 7Zip as mentioned, but not in the default path C:\Program Files\7-Zip but in the path D:\APPS\7-Zip. 
With this non default location, the DSC failes with the following error:
[WIN-T01]: LCM:  [ End    Set      ]  [[ArcGIS_Install]ServerInstall]  in 51.5010 seconds.
[WIN-T01]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]GeoEventServerInstall]
[WIN-T01]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]GeoEventServerInstall]
[WIN-T01]: LCM:  [ End    Test     ]  [[ArcGIS_Install]GeoEventServerInstall]  in 0.4060 seconds.
[WIN-T01]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]GeoEventServerInstall]
[]PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: 7-Zip not found at C:\Program Files\7-Zip\7z.exe 
[]Unable to connect to the remote server
[WIN-T01]: LCM:  [ End    Set      ]  [[ArcGIS_Install]GeoEventServerInstall]  in 51.0630 seconds.
[WIN-T01]: LCM:  [ End    Set      ]
[]PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: 7-Zip not found at C:\Program Files\7-Zip\7z.exe 

Why don't you extract the correct installation path for 7Zip?

**Comment by nshampur** [comment]
support for specifying the location of 7 zip is available in the upcoming 2.0 release that will available sometime next week.

**Comment by shailesh91** [comment]
Closing this issue. Support added in release v2.0.0!

**Comment by robal** [comment]
This doesn't seem to be working.
I've supplied SevenZipInstallerDir and SevenZipInstallerPath, and DSC is ignoring it, and trying to download it.
