### ISSUE TITLE
10.7 Upgrade does not configure Server Web Adaptor

### ISSUE THREAD

**Issue by hmelendez** [Esri/arcgis-powershell-dsc#137]
I ran an upgrade from 10.6.1 to 10.7 of a single machine base deployment. The GIS Server was installed but not configured.
[Upgrade_BaseDeployment_20190402_122107.log](https://github.com/Esri/arcgis-powershell-dsc/files/3031760/Upgrade_BaseDeployment_20190402_122107.log)

**Comment by shailesh91** [comment]
@hmelendez looks like your server was not started when you tried to register the web adaptor
```Output of 
execution:- Configuring Web adaptor.

Unable to register the ArcGIS Server with the Web Adaptor. Please make sure that the server machine is running and 
that the account specified has administrative privileges to the site.
```
Any chance you have IWA enabled? If not can you retry running the upgrade again. It is idempotent and should pick where it left.

**Comment by hmelendez** [comment]
The GIS Server WebAdaptor fail to register because the Primary Site Administrator (PSA) of the GIS Server was disabled. Enabling the PSA allowed the upgrade to complete successfully,

Thanks for pointing the error message. I had not seen that.
