### ISSUE TITLE
SendConfigurationApply function did not succeed

### ISSUE THREAD

**Issue by robal** [Esri/arcgis-powershell-dsc#141]
Hi there.  Test driving version 2.0.0.
I'm installing a simple ArcGIS server 10.6 on Windows 2016 WMF 5.1 and always get:

> []PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install Server
> []The SendConfigurationApply function did not succeed.

Despite there are no errors in Verbose log at all. The server got installed fine.
[ArcGISInstall-4-9-2019-1-11-50-PM-Error.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3059161/ArcGISInstall-4-9-2019-1-11-50-PM-Error.txt)
[ArcGISInstall-4-9-2019-1-11-50-PM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3059162/ArcGISInstall-4-9-2019-1-11-50-PM-Verbose.txt)

Any ideas ?

**Comment by robal** [comment]
OK. Turns out the test is failing here:
https://github.com/Esri/arcgis-powershell-dsc/blob/b191e088660eda8516f13bb15fbbc5a35afcfefd/Modules/ArcGIS/DSCResources/ArcGIS_Install/ArcGIS_Install.psm1#L245

I don't know why, but the exception is not reported anywhere (DSC event log, logfiles, console).
Now I need find out why the test is failing. The server seems fine...

**Comment by robal** [comment]
OK. After adding some additional logging to ArcGIS_Install.psm1, I've found that Test-Install is called with:
`Test-Install -Name "Server" -Version "10.6"`
The version I'm installing is 10.6.1, not 10.6.
Test-Install returns $false

**Comment by shailesh91** [comment]
@robal I am closing the issue. Looks like this stands resolved. If you have any other issues please reopen.
