### ISSUE TITLE
ArcGIS Pro Install Configuration 

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-powershell-dsc#144]
Shailesh,

Do you plan to provide ArcGIS Pro installation configuration in the future?

Thanks
Subu

**Comment by shailesh91** [comment]
@pcsswamin yes we do intend to provide installation configurations soon.

**Comment by dird-hyang** [comment]
@shailesh91 
Hi,
Can I use this DSC script to perform desktop & Pro upgrade?
Helen
