### ISSUE TITLE
ArcGIS Server Standalone 10.7 deployment fails

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-powershell-dsc#145]
Started with GISServer-GeneralPurpose.json and modified it to remove all portal info. We want to test only a standalone General purpose ArcGIS Server deployment using ArcGIS PowerShell DSC

Get the following error:

**Error:**
PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: ‪C:\install\ArcGISServer is not found or inaccessible 
The SendConfigurationApply function did not succeed.

**Verbose:**
Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
An LCM method call arrived from computer DENALICLIENT with user sid S-1-5-21-2041598973-134151231-3984567726-56930.
[DENALICLIENT]: LCM:  [ Start  Set      ]
[DENALICLIENT]: LCM:  [ Start  Resource ]  [[User]ArcGIS_RunAsAccount]
[DENALICLIENT]: LCM:  [ Start  Test     ]  [[User]ArcGIS_RunAsAccount]
[DENALICLIENT]:                            [[User]ArcGIS_RunAsAccount] A user with the name arcgis exists.
[DENALICLIENT]:                            [[User]ArcGIS_RunAsAccount] All User arcgis properties match.
[DENALICLIENT]: LCM:  [ End    Test     ]  [[User]ArcGIS_RunAsAccount]  in 2.2780 seconds.
[DENALICLIENT]: LCM:  [ Skip   Set      ]  [[User]ArcGIS_RunAsAccount]
[DENALICLIENT]: LCM:  [ End    Resource ]  [[User]ArcGIS_RunAsAccount]
[DENALICLIENT]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]ServerInstall]
[DENALICLIENT]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]ServerInstall]
[DENALICLIENT]:                            [[ArcGIS_Install]ServerInstall] Installed Version
[DENALICLIENT]: LCM:  [ End    Test     ]  [[ArcGIS_Install]ServerInstall]  in 0.2340 seconds.
[DENALICLIENT]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]ServerInstall]
[DENALICLIENT]: LCM:  [ End    Set      ]  [[ArcGIS_Install]ServerInstall]  in 0.0310 seconds.
[DENALICLIENT]: LCM:  [ End    Set      ]
Operation 'Invoke CimMethod' complete.

**Environment:** 
Windows Server 2016
ArcGIS PowerShell DSC 2.0.0 release

Attached json configdata file as text: 
![ArcGIS_Installer_Folder](https://user-images.githubusercontent.com/11682688/56167655-94069e80-5f8d-11e9-9d8f-af6f3d75d626.PNG)

[GISServer-StandAlone_DenaliClient_ToGITHUB.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3082187/GISServer-StandAlone_DenaliClient_ToGITHUB.txt)

**Comment by shailesh91** [comment]
@pcsswamin Can you please run the Configure-ArcGIS with param -DebugSwitch or provide the logs that were generated?

**Comment by pcsswamin** [comment]
PS C:\install\SampleConfigs> Configure-ArcGIS -ConfigurationParametersFile C:\install\SampleConfigs\GISServer-StandAlone_DenaliClient.json -DebugSwitch
Dot Sourcing the Configuration:- ArcGISInstall
Compiling the Configuration:- ArcGISInstall


    Directory: C:\install\SampleConfigs\ArcGISInstall


Mode                LastWriteTime         Length Name                                                                                                     
----                -------------         ------ ----                                                                                                     
-a----        4/15/2019   2:27 PM           3814 DenaliClient.mof                                                                                         
Starting DSC Job:- ArcGISInstall
VERBOSE: Time taken for configuration job to complete is 0.012 seconds
Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'nam
espaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
An LCM method call arrived from computer DENALICLIENT with user sid S-1-5-21-2041598973-134151231-3984567726-56930.
[DENALICLIENT]: LCM:  [ Start  Set      ]
[DENALICLIENT]: LCM:  [ Start  Resource ]  [[User]ArcGIS_RunAsAccount]
[DENALICLIENT]: LCM:  [ Start  Test     ]  [[User]ArcGIS_RunAsAccount]
[DENALICLIENT]:                            [[User]ArcGIS_RunAsAccount] A user with the name arcgis exists.
[DENALICLIENT]:                            [[User]ArcGIS_RunAsAccount] All User arcgis properties match.
[DENALICLIENT]: LCM:  [ End    Test     ]  [[User]ArcGIS_RunAsAccount]  in 2.2780 seconds.
[DENALICLIENT]: LCM:  [ Skip   Set      ]  [[User]ArcGIS_RunAsAccount]
[DENALICLIENT]: LCM:  [ End    Resource ]  [[User]ArcGIS_RunAsAccount]
[DENALICLIENT]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]ServerInstall]
[DENALICLIENT]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]ServerInstall]
[DENALICLIENT]:                            [[ArcGIS_Install]ServerInstall] Installed Version
[DENALICLIENT]: LCM:  [ End    Test     ]  [[ArcGIS_Install]ServerInstall]  in 0.2340 seconds.
[DENALICLIENT]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]ServerInstall]
[DENALICLIENT]: LCM:  [ End    Set      ]  [[ArcGIS_Install]ServerInstall]  in 0.0310 seconds.
[DENALICLIENT]: LCM:  [ End    Set      ]
Operation 'Invoke CimMethod' complete.
[]PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: â€ªC:\install\ArcGISServer is not found or
 inaccessible 
[]The SendConfigurationApply function did not succeed.
Logs Directory: C:\install\SampleConfigs\Logs
Finished DSC Job:- ArcGISInstall. Time Taken - 00:00:05.0424842
ArcGISInstall - Failed

**Comment by pcsswamin** [comment]
[ArcGISInstall-4-15-2019-2-27-18-PM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3082206/ArcGISInstall-4-15-2019-2-27-18-PM-Verbose.txt)
[ArcGISInstall-4-15-2019-2-27-18-PM-Error.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3082207/ArcGISInstall-4-15-2019-2-27-18-PM-Error.txt)

Shailesh - Please find attached logs. I am happy to take the conversation offline as well. 

Thanks
Subu

**Comment by shailesh91** [comment]
Seems to be a problem with the encoding of your JSON file. Can you make sure it is UTF-8? And can you replace all forward slashed with double backslashes?

**Comment by pcsswamin** [comment]
[GISServer-StandAlone_DenaliClient_ToGITHUB_2.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3082388/GISServer-StandAlone_DenaliClient_ToGITHUB_2.txt)

Shailesh - I am using Visual Studio Code. I resaved the config json file with UTF_8. Please find attached. Same error as before on execution as before.

Log files are also attached below.

[ArcGISInstall-4-15-2019-4-17-40-PM-Error.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3082436/ArcGISInstall-4-15-2019-4-17-40-PM-Error.txt)
[ArcGISInstall-4-15-2019-4-17-40-PM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3082437/ArcGISInstall-4-15-2019-4-17-40-PM-Verbose.txt)

**Comment by shailesh91** [comment]
The Reason I believe there is an error because of the highlighted in your logs.

PowerShell DSC resource ArcGIS_Install failed to execute Set-TargetResource functionality with error message: **_â€ªC_**:\install\ArcGISServer is not found or inaccessible 

Can you send me the JSON Config file to shgoel [at] esri.com

**Comment by pcsswamin** [comment]
Thanks Shailesh for all your help. 

Note to others - For some reason, Visual Studio code was not seeing the characters that powershell was seeing in the json file. I even tried resaving the json file with utf-8 encoding. However,these characters are easily seen in notepad or textpad. They probably came in through copying and pasting the path from windows dialog boxes. I would recommend viewing/editing the config data json file in such text editors. 

and as suggested above - use double backslashes.
