### ISSUE TITLE
Support Multiple Web Adaptors Install and Configurations for a Single ArcGIS Server Installation

### ISSUE THREAD

**Issue by DCHuber** [Esri/arcgis-powershell-dsc#146]
Would like to see support added that would allow for installing multiple web adaptors for a single ArcGIS Server site.  The current configuration only allows for a single web adaptor to be installed for a given server, with the name and admin access set globally.

Our organizations standard AGS Site deployment includes two web adaptors installed on separate machines that support either anonymous access to the public or authenticated access for publishing and site administration.

In the interim, we've overcome this limitation by running two configuration JSON files - one installs the web adaptor and server, and the second contains an identical copy of the server information but has new information for the second web adaptor node name, ServerContext, and AdminAccess.

**Comment by pfoppe** [comment]
Vote up!

**Comment by cameronkroeker** [comment]
Hello @DCHuber and @pfoppe,

We are pleased to announce that this has been added to v3.0.0:

https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Gis%20Servers/GISServer-GeneralPurpose-MultipleWA-MultiContext.json
