### ISSUE TITLE
GeoEvent Server SDK not installed

### ISSUE THREAD

**Issue by prez13** [Esri/arcgis-powershell-dsc#148]
When installing GeoEvent Server 10.7, the GeoEvent SDK is not installed, the folder is missing. The whole GeoEvent Folder is only about 800 MB compared to the normal 1 GB for 10.7. Otherwise, GeoEvent Server seems to work normally.

**Comment by shailesh91** [comment]
@prez13 do you see anything in install logs?

**Comment by prez13** [comment]
The install logs look good to me, nothing suspicious, and it says "GeoEvent installation was successful!". I just uninstalled the PS ArcGIS module and installed it again, then ran Mode Upgrade as suggested by an Esri support analyst; the SDK folder is still missing, the logs look good.

Maybe noteworthy that I had uninstalled the SW after the first install (using Modes Install / Uninstall), because I had thought something was wrong since GeoEvent was neither licenced nor configured. It turned out I had to use the new Mode InstallLicenceConfigure, which I then did.

**Comment by shailesh91** [comment]
@prez13 do you observe the same behavior when installing manually?

**Comment by prez13** [comment]
@shailesh91 When I install manually I get a prompt in the installation wizard to select the components (see attached screenshot). One of the components is GeoEvent Server, which is enabled by default, and the other component is the SDK, which is disabled by default. When I enabled the SDK component, it got installed. 

Does this mean I am not able to use PowerShell DSC to deploy GeoEvent Server if I need the SDK?

![components_to_install](https://user-images.githubusercontent.com/6305723/56648996-93a08e80-6684-11e9-9fa0-485cc831aa26.png)

**Comment by shailesh91** [comment]
@prez13 I think we never checked that SDK was just optional. I will try to provide a fix soon for this.

**Comment by prez13** [comment]
@shailesh91 Thank you for providing a fix. If we already wanted to use the SDK now, is there a way to install it as a workaround while keeping the environment valid for DSC?

**Comment by nshampur** [comment]
@prez13 .. if u happen to know the silent install command for the GeoEvent setup that includes the SDK, then you can try wrapping that with the DSC Package resource 

https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/windows/packageresource

**Comment by rowisequinor** [comment]
@shailesh91 has this been fixed for 10.7.1 ?

**Comment by shailesh91** [comment]
@rowisequinor This has not been fixed yet.

**Comment by cameronkroeker** [comment]
Hello @prez13,

We have added Support for GeoEvent SDK in the latest release, [v3.0.0](https://github.com/Esri/arcgis-powershell-dsc/releases):

**EnableGeoeventSDK** - (Optional - True | False(Default)) - Enables GeoEvent SDK during installation.

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files

We will be fixing the[ sample config](https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Gis%20Servers/GISServer-GeoEvent.json) to include this at a later date, however it should look something like this:

```
"GeoEventServer": {
            "LicenseFilePath": "[License File Path - GeoEvent Server ]",
            "Installer": {
                "Path": "[GeoEvent Server Installer Path]",
                "InstallDir": "[Geoevent Server Install Dir - Ex. C:\\ArcGIS\\GeoEventServer]"
            }
           "EnableGeoeventSDK": true
        },
```
