### ISSUE TITLE
Patches get reinstalled: Not idempotent, potential fix listed

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-powershell-dsc#149]
https://github.com/Esri/arcgis-powershell-dsc/blob/b191e088660eda8516f13bb15fbbc5a35afcfefd/Modules/ArcGIS/DSCResources/ArcGIS_InstallPatch/ArcGIS_InstallPatch.psm1#L155

If same config is reapplied, patches get reinstalled again. 

For ArcGIS Server 10.7 patches, I found that I could fix this by changing the  above line of code to 
$RegPath = "HKLM:\SOFTWARE\ESRI\Server10.7\Updates\*"

@shailesh91  - If you can confirm this, can you provide a more universal fix?

Thanks

**Comment by MAHDTech** [comment]
I also tested this recently and experienced the same issue.

A 10.6.1 install of ArcGIS Enterprise (Portal + Server + Data Store) results in the patches being installed. A second run over the top, such as making a small modification, results in the same patches being re-installed.

I have made a PR with some changes for review #179 

One additional item of note, it seems that some of the supplied MSP files downloaded from the Esri support site are missing the field in the file. This means the patch will always be re-installed. I added this field manually for a test and it seems upon initial testing to be working as expected. Please see the below screenshot.

![MSP Comparison](https://user-images.githubusercontent.com/16071195/58706589-df69f480-83f5-11e9-987a-ed927e881a46.png)

**Comment by pcsswamin** [comment]
Thanks @MAHDTech. I have noticed the same and call it the 'Missing QFE_ID in patch' issue in house. I will incorporate your update and test it out at the next opportunity.
