### ISSUE TITLE
AutoInstallation on Windows Server 2012 failed

### ISSUE THREAD

**Issue by NorbertThoden** [Esri/arcgis-powershell-dsc#150]
I am working on AutoInst based on powershell DSC 

I have done an installation on Windows Server **2016** with ArcGIS Server, DataStore and WebAdapter 10.6. After solving some problems that worked fine.

Now i moved that scripts to a Windows Server **2012R2**. That should be a supported OS Platform also.
(https://github.com/Esri/arcgis-powershell-dsc/wiki/Getting-Started)

Unfortunately i get following error:

> ...
> Finished DSC Job:- ArcGISLicense. Time Taken - 00:00:05.0322976
> ArcGISLicense - Completed
> Dot Sourcing the Configuration:- ArcGISConfigure
> Compiling the Configuration:- ArcGISConfigure
> ArcGIS\xFirewall : 'Domain Private Public' is not a valid value for property 'Profile' on class 'xFirewall'. Please change the value to one of the following strings: Any, Public, Private, Domain.
> At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configuration\ArcGISConfigure.ps1:167 char:25
> +                         xFirewall Server_FirewallRules
> +                         ~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : InvalidValueForProperty,ArcGIS\xFirewall
> 
> ArcGIS\xFirewall : 'Domain Private Public' is not a valid value for property 'Profile' on class 'xFirewall'. Please change the value to one of the following strings: Any, Public, Private, Domain.
> At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configuration\ArcGISConfigure.ps1:815 char:21
> +                     xFirewall DataStore_FirewallRules
> +                     ~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : InvalidValueForProperty,ArcGIS\xFirewall
> 
> ArcGIS\xFirewall : 'Domain Private Public' is not a valid value for property 'Profile' on class 'xFirewall'. Please change the value to one of the following strings: Any, Public, Private, Domain.
> At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configuration\ArcGISConfigure.ps1:834 char:25
> +                         xFirewall DataStore_FirewallRules_OutBound
> +                         ~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : InvalidValueForProperty,ArcGIS\xFirewall
> 
> Errors occurred while processing configuration 'ArcGISConfigure'.
> At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2088 char:5
> +     throw $errorRecord
> +     ~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (ArcGISConfigure:String) [], InvalidOperationException
>     + FullyQualifiedErrorId : FailToProcessConfiguration
> 
> PS C:\AutoInstEsri>

The firewall on both os (2016, 2012R2) is off.

The installation of ArcGIS Server, DataStore and WebAdapter 10.6 and License seems to be successful.
"ArcGISConfigure" seems to be the problematic part.

Any hints?

Thanks in advance.

**Comment by shailesh91** [comment]
@NorbertThoden Any chance you have xNetworking module installed on that machine? Or is there another module with submodule with name 'xfirewall'?

**Comment by NorbertThoden** [comment]
Hi!
Is xNetworking / xFirewall a windows module?
I am not familar with windows. Can you please explain a bit more? 
Thx

**Comment by shailesh91** [comment]
No it is not.
Can you run the following command on your 2012R2 machine and check if the module is indeed installed.
```Get-InstalledModule -Name xNetworking```

**Comment by NorbertThoden** [comment]
Hi!
At the moment i don´t have access to the 2012RS machine and can´t execute the suggested command :-(

But i assume that update Windows Management Framework (WMF) could be a good idea:
https://docs.microsoft.com/en-us/powershell/wmf/overview

I will share my results later

**Comment by NorbertThoden** [comment]
Background:
Typically our server host is a single purpose host -> GIS server and we work in disconnected state. So the system has almost no updates.

On the Server 2012R2 i updated WMF to version 5.1 (https://docs.microsoft.com/en-us/powershell/wmf/overview)
After that the powershell command "Install-Module" was avaiable.
I triggered the auto installation again (Configure-ArcGIS <file.json> and now that was successful :-)

Now i see that this is already added as requirement (https://github.com/Esri/arcgis-powershell-dsc/wiki/Getting-Started)
I wasn´t familar with WMF and i´m still not able not retrieve the installed version :-(

Now it works on 2012R2 and i can confirm that the auto installation works on Windows Server 2012R2 with WMF5.1 :-)
