### ISSUE TITLE
Additional parameter - Server Log Location

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#151]
It would be beneficial if one could specify the server-log-location in the JSON-config, similar to the other server-directories like "ConfigStoreLocation" or "ServerDirectoriesRootLocation".

This would spare us another step to be cared of AFTER the DSC-setup.

**Comment by scma-esrich** [comment]
@jn-bedag

**Comment by cameronkroeker** [comment]
@scma-esrich,

This feature has been added to v3.0.0:
