### ISSUE TITLE
ArcGIS Enterprise service patches installation repeated

### ISSUE THREAD

**Issue by dird-hyang** [Esri/arcgis-powershell-dsc#153]
Hi,
After the first execution of the Configure-ArcGIS with InstallLicenseConfigure, when I rerun the script, all existing successful installations have been skipped. However, The service patches constantly repeated been installed.
Please allow the skip of the service patch installation.
Thanks
Helen

**Comment by shailesh91** [comment]
@dird-hyang this is a duplicate issue. Please reference #149. Closing this.
