### ISSUE TITLE
Unable to publish service due to required parameter

### ISSUE THREAD

**Issue by PleaseStopAsking** [Esri/arcgis-powershell-dsc#155]
When using the ArcGIS_Server_Service, it will fail when the resource attempts to call the Publish-ArcGISService function due to the $PortalToken parameter being set to Mandatory even if its not needed.

This should be optional as not all deployments will use ArcGIS Portal and there is already logic to account for the parameter being passed at all.

```
if($PortalToken){
  $job = Submit-ArcGISPublishJob -ServerHostName $ServerHostName -ServerContext 
  $ServerContext -Token $PortalToken -Referer $Referer -ItemId $item.itemID -Port $Port    
}else{
  $job = Submit-ArcGISPublishJob -ServerHostName $ServerHostName -ServerContext
  $ServerContext -Token $Token -Referer $Referer -ItemId $item.itemID -Port $Port
}
```

https://github.com/Esri/arcgis-powershell-dsc/blob/b191e088660eda8516f13bb15fbbc5a35afcfefd/Modules/ArcGIS/DSCResources/ArcGIS_Server_Service/ArcGIS_Server_Service.psm1#L268

**Comment by shailesh91** [comment]
@PleaseStopAsking I will review this and merge this. 
Just an FYI, Publish-ArcGISService is not supported and feature complete function yet.

**Comment by dird-hyang** [comment]
@shailesh91 
I'm planning to use this function after my server configuration completed.
Is there a planned schedule to support this function?
Helen
