### ISSUE TITLE
Updating certificate with the same alias fails

### ISSUE THREAD

**Issue by MAHDTech** [Esri/arcgis-powershell-dsc#158]
When performing an initial DSC run the certificate is imported successfully.

If you change the path to a NEW certificate, but leave the Alias within the DSC JSON the same, the new certificate is not imported.

If possible can you please add the feature to check if the serial of the existing certificate installed in each role matches the one in the JSON, and if not, overwrite the cert using the same Alias.

**Comment by shailesh91** [comment]
@MAHDTech Can you please tell which component (Server, Portal, Web Adaptor or Load Balancer) were you targetting while trying to import the new certificate?

**Comment by MAHDTech** [comment]
I was testing with Portal and Server, both experience the same issue.
