### ISSUE TITLE
Cannot Federate Server : stuck at testing 

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#160]
Hello,

I am trying to test an ArcGIS Enterprise 10.7 deployment on one machine and the federate operation get stucks at testing.

Debugging the configuration, I understood that it keeps trying to generate a token to the Portal forever:
https://github.com/Esri/arcgis-powershell-dsc/blob/11e0364c92e3cfdb31270d415accabef4a71ce74/Modules/ArcGIS/DSCResources/ArcGIS_Federation/ArcGIS_Federation.psm1#L137-L148

And the reason why it does not manage to retrieve a token is because the function "Get-PortalToken" uses portal hostname instead of the FQDN:
https://github.com/Esri/arcgis-powershell-dsc/blob/11e0364c92e3cfdb31270d415accabef4a71ce74/Modules/ArcGIS/ArcGISUtility.psm1#L94

If the request was made to 
`https://$($FQDN):$($Port)/$SiteName/sharing/rest/generateToken`
then it would work.

Did I misconfigure anything or is it a bug ?

I think it is pretty similar to #159 : "Portal configuration requires fully qualified domain name in the WebAdaptor URL"

Thanks

**Comment by shailesh91** [comment]
@Biboba the call is being made to the FQDN. The calling ArcGISFederation resource always try to get the FQDN of the portal machine.
https://github.com/Esri/arcgis-powershell-dsc/blob/11e0364c92e3cfdb31270d415accabef4a71ce74/Modules/ArcGIS/Configurations-OnPrem/ArcGISFederation.ps1#L72

As a simple test can you try running the (Get-FQDN $PortalNodeName) on your orchestrating machine and check if that matches the Portal FQDN.

**Comment by Biboba** [comment]
Thanks for your reply @shailesh91 !
If I check the generated mof file for ArcGIS Federation, I have  : 
`"PortalHostName" = "myhostname";`

So it is not set to FQDN. 
Does that mean that something went wrong with the configuration ?

Thanks

**Comment by shailesh91** [comment]
@Biboba can you please attach your json config file and can you please tell about the deployment setup you have.

**Comment by Biboba** [comment]
Yes.
So it's an ArcGIS Enterprise 10.7 deployment on one machine:
[Deployment.json.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3149283/Deployment.json.txt)

Thanks !

**Comment by shailesh91** [comment]
[Deployment.json.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3149295/Deployment.json.txt)
I made a change to ssl section. And you need to give an FQDN for the alias of the certificate.

**Comment by spitzerr** [comment]
I thought "Alias" is a little bit vague in this case. As it could be understood as an alias for the certificate which is used in ArcGIS Backend to identify the Certificate and not the CN/SAN of the certificate. Maybe it is possible to rename the parameter in a future release?
@scma-esrich FYI

**Comment by Biboba** [comment]
Many thanks @shailesh91 !
It does solve the issue. 

On a side note, I agree with @spitzerr: I was misguided by the "alias" which I supposed was as the same as the parameter of the Admin REST API operation "importExistingServerCertificat" that is to say just a name:
https://developers.arcgis.com/rest/enterprise-administration/portal/import-existing-server-certificate.htm

Also the Wiki is not very clear about its property:
"The alias with which the certificate will be used.":
https://github.com/Esri/arcgis-powershell-dsc/wiki/Variables-reference-page-for-JSON-configuration-files.

Though config sample is a little bit clearer but could maybe be illustrated by an example ?:
https://github.com/Esri/arcgis-powershell-dsc/blob/11e0364c92e3cfdb31270d415accabef4a71ce74/SampleConfigs/Base%20Deployment/BaseDeployment-ThreeMachine-ssl-per-Node-Example1.json#L24

**Comment by spitzerr** [comment]
@Biboba Do you mind to open a new Issue for the Alias part? I like your summary in the last post about this topic.
