### ISSUE TITLE
Confusing certificate "alias" property

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#161]
Following #160 (and #159), I was misguided by the "alias" certificate property which I supposed was as the same as the parameter of the Admin REST API operation "importExistingServerCertificat" that is to say just a name:
https://developers.arcgis.com/rest/enterprise-administration/portal/import-existing-server-certificate.htm

Also the Wiki is not very clear about its property:
"The alias with which the certificate will be used.":
https://github.com/Esri/arcgis-powershell-dsc/wiki/Variables-reference-page-for-JSON-configuration-files.

Though config sample is a little bit clearer but could maybe be illustrated by an example ?:
https://github.com/Esri/arcgis-powershell-dsc/blob/11e0364c92e3cfdb31270d415accabef4a71ce74/SampleConfigs/Base%20Deployment/BaseDeployment-ThreeMachine-ssl-per-Node-Example1.json#L24

 /cc @spitzerr

**Comment by MAHDTech** [comment]
I had the same issue.

I had assumed the alias was only used as the entry for storing the cert inside the tomcat keystore however it's also used for the connectivity between the hosts.

ie, if you are using webadaptor you should use the WebAdaptor FQDN for the alias for communication to succeed.

**Comment by shailesh91** [comment]
@Biboba @MAHDTech @spitzerr The wiki has been updated to clarify the alias param. We will consider refactoring this parameter name in a future release.

**Comment by Biboba** [comment]
@shailesh91 Much clearer : thanks !

**Comment by cameronkroeker** [comment]
@Biboba,

In the latest release, v3.0.0, We have changed the "Alias" certificate property to "CNameFQDN":

**CNameFQDN** - Refers to a fully qualified domain name (CN/SAN) associated with the certificate.

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files
