### ISSUE TITLE
Clarify valid values for PortalLicenseUserType parameter

### ISSUE THREAD

**Issue by joekayaker** [Esri/arcgis-powershell-dsc#162]
Trying to confirm that the 10.7 JSON configuration file (**BaseDeployment-SingleMachine.json**) should have the following variable set as: **"PortalLicenseUserType": "Creator"**? That is the user I have listed as options, besides Viewer, in my Portal license file (*.json). But "GIS Professional" appears to be a more robust user in the new 5 tier user types, but isn't an option in the license file.

**Comment by cameronkroeker** [comment]
@joekayaker 

The Creator user type ID is creatorUT:

"PortalLicenseUserType": "creatorUT"

If you would like to use GIS Professional there are the following options:

GISProfessionalAdvUT
GISProfessionalStdUT
GISProfessionalBasicUT

However, you can only use what is available within your portal license json file. If these options are missing from the license file then you will need to recreate it through the My Esri site.

**Comment by cameronkroeker** [comment]
@joekayaker 

The Portal site initial administrator account can be created with the level 2 user types. The "PortalLicenseUserType": "" references the user type by name. So for example, the following options can be used as long as your portal json license file accommodates:

"PortalLicenseUserType": "Creator"
"PortalLicenseUserType": "GIS Professional Basic"
"PortalLicenseUserType": "GIS Professional Standard"
"PortalLicenseUserType": "GIS Professional Advanced"

**Comment by joekayaker** [comment]
@cameronkroeker 

Thanks for the clarification!

**Comment by amarilatitude** [comment]
Hi there! I'm doing a 10.6 installation. What would be the possible values in this case? Would it be "Level2" for example? Thanks!

**Comment by cameronkroeker** [comment]
@amarilatitude 

The "PortalLicenseUserType" parameter is only applicable to 10.7 and above. This is not needed/utilized for 10.6.1 and below.

Thanks,
Cameron K.

**Comment by amarilatitude** [comment]
Thanks Cameron!

**Comment by RubenGeo** [comment]
I would be nice if this explanation could be added to the variable reference page wiki. It took me a while to find this issue so I could input the correctt value for PortalLicenseUserType.

> @joekayaker
> 
> The Portal site initial administrator account can be created with the level 2 user types. The "PortalLicenseUserType": "" references the user type by name. So for example, any one of the following options can be used as long as your portal json license file accommodates:
> 
> "PortalLicenseUserType": "Creator"
> "PortalLicenseUserType": "GIS Professional Basic"
> "PortalLicenseUserType": "GIS Professional Standard"
> "PortalLicenseUserType": "GIS Professional Advanced"
