### ISSUE TITLE
InstallLicenseConfigure fails with ArcGISConfigure 

### ISSUE THREAD

**Issue by grumor** [Esri/arcgis-powershell-dsc#165]
@shailesh91 
Im installing Portal and webadaptor on a server each. Started with InstallLicensenConfigure and met an error. I tested Install and InstallLicenses. They work fine. But when using InstallLicensenConfigure I first get a warning then invalid MOF definition 

Any idea to resolve this?
This is the error in Powershell window:

WARNING: It is not recommended to use domain credential for node 'portalserver'. In order to suppress the warning, you can add a property named
'PSDscAllowDomainUser' with a value of $true to your DSC configuration data for node 'portalserver'.

Write-NodeMOFFile : Invalid MOF definition for node 'portalserver': Exception calling "ValidateInstanceText" with "1" argument(s): "Undefined propety State
At line:32, char:2
Buffer:
"ArcGISConfigure";
;^
Insta
"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2369 char:21
 ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
   + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile
   
 Directory: E:\ArcGIS_Automation\ArcGISConfigure


Mode                LastWriteTime         Length Name
---                -------------         ------ ----
a----       10.05.2019     15:42           7116 portalserver.mof.error


Write-NodeMOFFile : Invalid MOF definition for node 'webadapterserver': Exception calling "ValidateInstanceText" with "1" argument(s): "Undefined property Sate
At line:29, char:2
Buffer:
"ArcGISConfigure";
;^
Insta
"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2369 char:21
 ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
   + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile

a----       10.05.2019     15:42          15296 webadatorserver.mof.error  

Compilation errors occurred while processing configuration 'ArcGISConfigure'. Please review the errors reported in error stream and modify your confiuration code appropriately.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+    throw $ErrorRecord
+   ~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : InvalidOperation: (ArcGISConfigure:String) [], InvalidOperationException
   + FullyQualifiedErrorId : FailToProcessConfiguration

**Comment by shailesh91** [comment]
@grumor can you confirm that you don't have the xNetworking module installed? This error sounds very similar to some of the users have encountered due to submodule naming conflicts.

**Comment by grumor** [comment]
@shailesh91 i will check during the weekend. Do have a brief explanation how to check if it is install. (I could probably google it to find how, but if you have it by your fingers, i will preseate a quick solution)

**Comment by grumor** [comment]
@shailesh91  I **have identified the reason why this error occur**s!  Our servers is created by Powershell DSC by our partner, and are using a newer version of the xFirewall resources that is embedded in the ArcGIS module. In the ArcGIS module version 2.0 is used and my partner use 5.4. The reason is a naming conflict when running the ArcGIS module. 
The lead specialist that looked into this suggested, you should rename the xFirewall resource in the code or check if it exists.  It was enough to delete del 'C:\Program Files\WindowsPowerShell\Modules\xNetworking' -Force then it worked fine.  How to proceed to fix this?

**Comment by shailesh91** [comment]
@grumor this is being renamed in the upcoming release.

**Comment by grumor** [comment]
@shailesh91  thx!

**Comment by grumor** [comment]
Looking forward to test. THX
