### ISSUE TITLE
Additional parameters - AdminSecurityQuestionIndex and AdminSecurityAnswer

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#168]
Hello,

Currently, values for "AdminSecurityQuestionIndex" and "AdminSecurityAnswer" are hardcoded.
I think it would nice to be able to specify them in the config:

```
"PrimarySiteAdmin": {
	"UserName": "siteadmin",
	"Email": "foo@bar.com",
	"Password": "secret",
	"SecurityQuestionIndex": 1,
	"SecurityAnswer" : "vanilla"
}
```

Thanks !

**Comment by spitzerr** [comment]
@shailesh91 Could you please update the Wiki according to these new config parameters?
https://github.com/Esri/arcgis-powershell-dsc/wiki/Variables-reference-page-for-JSON-configuration-files
Thx
