### ISSUE TITLE
Update documentation for invalid config variable "DataStoreType"

### ISSUE THREAD

**Issue by pfoppe** [Esri/arcgis-powershell-dsc#171]
The WIKI indicates the AllNodes.DataStoreType parameter while the samples are AllNodes.DataStoreTypes (included an 's').  Documentation should also indicate this is an array (multiple choices).  

Docs - https://github.com/Esri/arcgis-powershell-dsc/wiki/Variables-reference-page-for-JSON-configuration-files

> DataStoreType - This is a valid parameter when the node role is 'DataStore'. Valid values are 'Relational | SpatioTemporal | TileCache'.

Example - https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/Base%20Deployment/BaseDeployment-SingleMachine.json

>                          "DataStoreTypes":  [ 
>                                               "Relational"
>                                             ],

**Comment by shailesh91** [comment]
@pfoppe The typo in documentation is fixed now.
