### ISSUE TITLE
Deployment stops after ArcGISInstall Job finish

### ISSUE THREAD

**Issue by hmelendez** [Esri/arcgis-powershell-dsc#172]
I'm deploying a new site using ArcGIS Module 2.0.0, after the installation step _Finished DSC Job:- ArcGISInstall_ is compleated the execution ends without any error. It does not continue to the configuration.
[Install_BaseDeployment_END.log](https://github.com/Esri/arcgis-powershell-dsc/files/3196336/Install_BaseDeployment_END.log)

**Comment by shailesh91** [comment]
@hmelendez I am assuming you are setting the mode to "Install". To configure the whole enterprise stack you need to use mode "InstallLicenseConfigure" starting version 2

**Comment by hmelendez** [comment]
Small change that I was not aware. Thanks for the quick reply.
