### ISSUE TITLE
Clarify the "FileShare" role for multi-machine GEneral Purpose ArcGIS Setup

### ISSUE THREAD

**Issue by amarilatitude** [Esri/arcgis-powershell-dsc#174]
Hi there! We are trying to install a two-server ArcGIS GEneral purpose (and federate that with an existing Portal). We are confused by a few things:

1) On the example file "GISServer-GeneralPurpose-MultiMachine.json", the "roles" for the first machine includes a role called "FileShare"? What is this for? We have a file share on a nas, separete from the two ArcGIS Machines. Also, the Wiki doesn't list that as a valid option for the roles

2) Can you clarify what the "FileShareLocalPath" and "FileShareName" exactly are? It would be helpful to have examples on the Wiki page, as it's not clear exactly how those are used.

Right now, this is what I'm going to try:

"FileShareLocalPath":  "\\\\nas\\arcgisdata",
"FileShareName":  "arcgisdata",

(\\nas\arcgisdata is where we plan to put ArcGIS server's shared data)

Thanks!

**Comment by shailesh91** [comment]
@amarilatitude FileShare role is when you want the DSC script to provision an smb file share for you on the machine which you have specified the role on. "FileShareLocalPath" and "FileShareName" are required only when you FileShare Role on one of your machines.
We do support external file shares. Just give the relative paths for server and portal parameters in Config Data Block. Example - Replace ```\\\\[Fileshare Machine Name 1]\\[Fileshare Name]\\ ``` with ```\\nas\arcgisdata```

**Comment by amarilatitude** [comment]
Thanks for the clarification! Would be very useful if the wiki can be updated to include this information.

**Comment by shailesh91** [comment]
@amarilatitude Wiki will be updated in a coming release.
