### ISSUE TITLE
Trace-DSCJob error handling

### ISSUE THREAD

**Issue by robal** [Esri/arcgis-powershell-dsc#175]
I'm having a hard time trying to catch the error when I run Configure-ArcGIS from my parent script.
Even when DSC job fails, the function does not return error code and does not output to stderr.

It does print the error message as red text to stdout. Why is it designed (to hide error) like this ?
https://github.com/Esri/arcgis-powershell-dsc/blob/72c8a26007170cbdf231ab024501e99d2d82274b/Modules/ArcGIS/ArcGIS.psm1#L180

**Comment by shailesh91** [comment]
Fixed with v2.1.1!
