### ISSUE TITLE
The current license file for this portal is from previous version. please use the software authorization wizard to provide a valid license for Portal for ArcGIS

### ISSUE THREAD

**Issue by dird-hyang** [Esri/arcgis-powershell-dsc#177]
When I run the upgrading for 10.5.1 to 10.6.1 on a single machine (base deployment), I got the following error message, the same message appear to all my servers in the department during new installation or upgrading process.

The same file can be used through manual configuration for both portal and server.

Could you advise why the issue constantly appear?

The message is:
[]PowerShell DSC resource ArcGIS_PortalUpgrade  failed to execute Set-TargetResource functionality with error message: [ERROR]:- {"error":{"code":500,"message":"The current license file for t
his portal is from a previous version. Please use the Software Authorization Wizard to provide a valid license for Portal for ArcGIS.","details":null}} 
[]The SendConfigurationApply function did not succeed.

Thanks

I have attached the json file for your reference.

Helen
[BCBR2GIS1_Upgrade1051to1061.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3239212/BCBR2GIS1_Upgrade1051to1061.txt)

**Comment by cameronkroeker** [comment]
Hi @dird-hyang,

Could you check the license keycodes file from the Portal machine in the following two locations:

C:\Program Files (x86)\Esri\License10.5\sysgen\keycodes
C:\Program Files\ESRI\License10.5\sysgen\keycodes

This file can be opened with a text editor (nodepad ++ is my recommendation but really any text editor should suffice).

Does either file contain previous versions of licenses?
Also, in C:\Program Files\ESRI and C:\Program Files (x86)\Esri does it contain other folders besides License10.5?

**Comment by dird-hyang** [comment]
@cameronkroeker
Hi,
the Server is brand new and never installed the previous version.
Thus, there is only License10.6 folder exists in both directories. The license files are both states that the version is 106

**Comment by cameronkroeker** [comment]
@dird-hyang 

When manually authorizing the portal license file (which worked?), was the Software Authorization GUI used or was it authorized silently?

Perhaps you could attach the PowerShell DSC log file that contains the error?

**Comment by dird-hyang** [comment]
@cameronkroeker
It was through the GUI with internet method.

**Comment by dird-hyang** [comment]
@cameronkroeker
The log file attached. This is a brand new server running the full installation, license and configuration.
[BCBR1GIS6.zip](https://github.com/Esri/arcgis-powershell-dsc/files/3274077/BCBR1GIS6.zip)

**Comment by cameronkroeker** [comment]
Thanks @dird-hyang. Does the "D:\InstallationPackages\Level1n2NamedUsersPortalforArcGIS_610961.prvc" file contain both Portal and ArcGIS Server licenses, or only Portal?

**Comment by dird-hyang** [comment]
Only portal

**Comment by cameronkroeker** [comment]
Thanks @dird-hyang. The PowerShell DSC ArcGISLicense log is indicating that the authorization of Portal 10.6 went through successfully:

```
[[ArcGIS_License]PortalLicenseBCBR1GIS6] [Running Command] C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe -s -ver 10.6 -lif "D:\InstallationPackages\Level1n2NamedUsersPortalforArcGIS_610961.prvc"
[[ArcGIS_License]PortalLicenseBCBR1GIS6] Finished Licensing Product [Portal]
```

However, it looks like the error is occurring when Portal attempts to configure, its not liking the contents of the file from C:\Program Files\ESRI\License10.6\sysgen\keycodes.

`PowerShell DSC resource ArcGIS_Portal  failed to execute Set-TargetResource functionality with error message: The current license file for this portal is from a previous version. Please use the Software Authorization Wizard to provide a valid license for Portal for ArcGIS. `

I recommend contacting Esri Customer Service and/or Esri Technical Support as they will be able to look at the Portal license and/or keycodes file.
