### ISSUE TITLE
primarysiteadmin is different for portal and server

### ISSUE THREAD

**Issue by dird-hyang** [Esri/arcgis-powershell-dsc#178]
Hi,
I'm in the middle of upgrading from 10.5.1 to 10.6.1.
I have encountered a problem where admin for portal and admin for arcgis server has different user names.
In the configure file, there is one PrimarySiteAdmin parameter. Which admin account I should assign for this, portal or server?
Helen

**Comment by dird-hyang** [comment]
it would be good to have server and portal primary site variables separately.

**Comment by shailesh91** [comment]
@dird-hyang As of now, we don't support separate primary site admin user variables for server and portal. To support this will require significant refactoring. Though we will consider this enhancement for a future release.

**Comment by cameronkroeker** [comment]
@dird-hyang 

We now support separate primary site admin user variables for ArcGIS Server and Portal for ArcGIS in v3.0.1.

https://github.com/Esri/arcgis-powershell-dsc/wiki/v3.0.1-ArcGIS-Server-Primary-Administrator-Account-and-Portal-for-ArcGIS-Initial-Administrator-Account-variables
