### ISSUE TITLE
Datastore upgrade 10.5.1 to 10.6.1 Relative Path is not supported

### ISSUE THREAD

**Issue by dird-hyang** [Esri/arcgis-powershell-dsc#180]
Hi,
I encountered the error while upgrading the base enterprise from 10.5.1 to 10.6.1.
I have managed to go through the portal and server upgrade, now it stopped at data store upgrade.
I got two errors:
1. "Relative Path is not supported. The related file/directory is: \etc\upgrade.txt".
2. "Unable to connect to the remote server".
I have attached the verbose and error files and the configuration json file for your reference.
Please help.
Thanks
Helen
[DataStoreUpgradeInstall-31-05-2019-6-02-40-PM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3245367/DataStoreUpgradeInstall-31-05-2019-6-02-40-PM-Verbose.txt)
[DataStoreUpgradeInstall-31-05-2019-6-02-40-PM-Error.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3245368/DataStoreUpgradeInstall-31-05-2019-6-02-40-PM-Error.txt)
[DataStoreUpgradeConfigure-31-05-2019-6-02-50-PM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3245369/DataStoreUpgradeConfigure-31-05-2019-6-02-50-PM-Verbose.txt)
[DataStoreUpgradeConfigure-31-05-2019-6-02-50-PM-Error.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3245370/DataStoreUpgradeConfigure-31-05-2019-6-02-50-PM-Error.txt)
[BCBR2GIS1_Upgrade1051to1061.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3245390/BCBR2GIS1_Upgrade1051to1061.txt)

**Comment by shailesh91** [comment]
@dird-hyang you are missing parameters. Please use the original JSON Config and modify it for upgrades. Specifically for datastore, you are missing param "InstallDir" in the attached config. 
PS. Another issue I noticed is we don't support patching during upgrades.

**Comment by dird-hyang** [comment]
Thanks. The issue resolved. 
I have to manually update the arcgis server datastore connection list.
The link to solve the issue is at:

https://support.esri.com/en/technical-article/000017079
Thanks for the help.
Helen
