### ISSUE TITLE
Local ArcGIS Data Store rule being created by WmiPrvSE.exe

### ISSUE THREAD

**Issue by cdbarker** [Esri/arcgis-powershell-dsc#183]
We have deployed a 10.5.1 SpatioTemporal Data Store on a single machine, registered with a server on another machine.

We have noticed that a local ArcGIS Data Store rule is being created during the process (which makes sense). However when this is removed, it is immediately recreated by a local WMI Provider process (WmiPrvSE.exe).
The rule contains rules for ports 2443, 9876, 29080, 29081, which are rules for the Relational and Tile Cache Data Stores, not the SpatioTemporal Data Store.

Is this rule correct? Should it not also include ports 9220 and 9320?
How can we stop this rule being automatically generated once manually removed?

**Comment by cameronkroeker** [comment]
Hi @cdbarker,

I believe there should be two separate rules created. One will contain ports 2443, 9876, 29080, 29081 for the Relational/TileCache stores and another one for the SpatioTemporal.

In the Windows Defender Firewall with Advanced Security console, in the Inbound Rules section do you see both rules or only one?

https://github.com/Esri/arcgis-powershell-dsc/blob/master/Modules/ArcGIS/Configurations-OnPrem/ArcGISConfigure.ps1#L858

and 

https://github.com/Esri/arcgis-powershell-dsc/blob/master/Modules/ArcGIS/Configurations-OnPrem/ArcGISConfigure.ps1#L822

**Comment by cdbarker** [comment]
Hi @cameronkroeker 
Likely both were created but we have since got rid of local firewall rules in favor of group policy.
However the Relational/TileCache rule continues to be recreated after it is deleted.

**Comment by cameronkroeker** [comment]
When is it regenerated, at reboot? What happens if the rule is disabled instead of deleted?

**Comment by cameronkroeker** [comment]
@cdbarker 

I recommend checking to see what the ConfigurationMode is set to in the DscLocalConfigurationManager. If its set to something like "ApplyAndAutoCorrect" then it is likely the reason the rule comes back after deletion.

Launch PowerShell cmdlet and run the following command:

`Get-DscLocalConfigurationManager`

For example:
```
PS C:\windows\system32> Get-DscLocalConfigurationManager


ActionAfterReboot              : ContinueConfiguration
AgentId                        : 27456FCA-8C99-11E9-8212-005056AC679C
AllowModuleOverWrite           : False
CertificateID                  :
ConfigurationDownloadManagers  : {}
ConfigurationID                :
ConfigurationMode              : ApplyAndMonitor
ConfigurationModeFrequencyMins : 15
Credential                     :
DebugMode                      : {NONE}
DownloadManagerCustomData      :
DownloadManagerName            :
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : Busy
LCMStateDetail                 : LCM is performing a consistency check.
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
SignatureValidationPolicy      : NONE
SignatureValidations           : {}
MaximumDownloadSizeMB          : 500
PartialConfigurations          :
RebootNodeIfNeeded             : False
RefreshFrequencyMins           : 30
RefreshMode                    : PUSH
ReportManagers                 : {}
ResourceModuleManagers         : {}
PSComputerName                 :
```

**Comment by cameronkroeker** [comment]
Hi @cdbarker,

I wanted to follow up to see if my previous post helped resolve the issue?

**Comment by cdbarker** [comment]
Hi @cameronkroeker Thanks for the above. I checked the ConfigurationMode which was set to ApplyAndMonitor. We have just started deploying on a new environment and this issue is not reproducible with the same machine config.

**Comment by cameronkroeker** [comment]
Thanks @cdbarker. Since it's no longer reproducible in the new env I'll go ahead and close out the issue.
