### ISSUE TITLE
Offline Licensing

### ISSUE THREAD

**Issue by pfoppe** [Esri/arcgis-powershell-dsc#184]
Some of our environments are in an isolated network where the servers have no outbound internet access.  Our client machines generally do.  

This is causing issues with licensing the products (issues detailed below). I'm assuming the ArcGIS psdsc module does not support this situation.  Is there a reccomended workflow to install the software, manually license, then complete the final configurations?

I just ran the InstallLicenseConfigure (until it hung), then manually licensed the products, then re-ran the InstallLicenseConfigure commands.  So far it seems to have work as expected.  Thoughts?  Thanks!

**-- Issues Detailed Below ---**

We received the following error indicating this: 

> [MACHINE1]: LCM:  [ End    Set      ]  [[ArcGIS_License]PortalLicenseMACHINE1]  in 707.3010 seconds.
> [MACHINE1]: LCM:  [ End    Set      ]
> []PowerShell DSC resource ArcGIS_License  failed to execute Set-TargetResource functionality with error message: [ERROR] - Attempt 10 - Licensing for Product [Portal] failed. Software Authorization Utility returned Error authorizing with the following file  \\MACHINE1\share$\Licenses\lic_file.prvc
> []The SendConfigurationApply function did not succeed.
> [MACHINE2]: LCM:  [ End    Set      ]  [[ArcGIS_License]ServerLicenseMACHINE2]  in 714.2440 seconds.
> [MACHINE2]: LCM:  [ End    Set      ]
> []PowerShell DSC resource ArcGIS_License  failed to execute Set-TargetResource functionality with error message: [ERROR] - Attempt 10 - Licensing for Product [Server] failed. Software Authorization Utility returned Error authorizing with the following file  \\MACHINE1\share$\Licenses\lic_file.prvc
> []The SendConfigurationApply function did not succeed.

That is causing issues further down the execution: 

> [MACHINE1]: LCM:  [ Start  Test     ]  [[xFirewall]WebAdaptorFirewallRulesMACHINE1]
> []PowerShell DSC resource ArcGIS_Portal  failed to execute Set-TargetResource functionality with error message: This portal does not have a valid license. Please use the Software Authorization Wizard to authorize Portal for ArcGIS.
> [MACHINE1]: LCM:  [ End    Test     ]  [[xFirewall]WebAdaptorFirewallRulesMACHINE1]  in 2.2640 seconds.
> ...
> [MACHINE2]: LCM:  [ Start  Set      ]  [[xFirewall]DataStore_FirewallRules_OutBound]
> []PowerShell DSC resource ArcGIS_Server  failed to execute Set-TargetResource functionality with error message: CreateSite Failed. Error:- Failed to create the site. The machine does not have a valid license. Please authorize using the Software Authorization for ArcGIS Server wizard.
> [MACHINE2]: LCM:  [ End    Set      ]  [[xFirewall]DataStore_FirewallRules_OutBound]  in 0.5330 seconds.

Until it ultimately hung here: 

> [MACHINE2]: LCM:  [ End    Set      ]  [[ArcGIS_DataStore]DataStoreMACHINE2]  in 551.9020 seconds.
> [MACHINE2]: LCM:  [ End    Set      ]
> []PowerShell DSC resource ArcGIS_DataStore  failed to execute Set-TargetResource functionality with error message: Register Data Store Failed after multiple attempts.
> []The SendConfigurationApply function did not succeed.

Once it hung, we had to Ctrl+z to kill the execution.  We manually licensed the products using an offline method - https://enterprise.arcgis.com/en/server/latest/install/windows/authorize-arcgis-server.htm#GUID-D8B5B450-A485-42EA-9BF5-AF4522C07AA3
**

> Authorize at Esri's website or by email to receive your authorization file.

**

**Comment by nshampur** [comment]
@pfoppe .. you can acquire a license file with already activated keycodes from your account/licensing team. 
This will avoid the phone back home to activate licenses.

**Comment by pfoppe** [comment]
Hi @nshampur - Thanks for the response!  I'll look into this on the next execution.

**Comment by pfoppe** [comment]
Update - I worked with our Esri account rep to enable our organization to generate an "Esri Secure License File" and was able to generate an ".eslf" license file.  I've used this file for 2 'offline' deployments with success.  Closing out this issue.  Thanks!
