### ISSUE TITLE
Federate highly available ArcGIS Server

### ISSUE THREAD

**Issue by cdbarker** [Esri/arcgis-powershell-dsc#189]
Is it possible to federate a highly available ArcGIS Server? We currently use a single config to install a multi-machine ArcGIS Server site. This is load balanced by an existing load balancer. We then have to manually federate using the load balanced ArcGIS Server URL. I can't see any option to set the server URL during federation.

**Comment by shailesh91** [comment]
@cdbarker please try using the parameter - "ExternalLoadBalancer" along with the federation block.

**Comment by shailesh91** [comment]
@cdbarker Closing this issue. Please reopen if you have any further queries.
