### ISSUE TITLE
Creating RasterDataStoreItem not idempotent (enough)

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#191]
When **re**running a configuration, where the Role "RasterDataStoreItem" with its corresponding parameters
```
"DataStoreItems": {
            "RasterStore": {
                "FileShareLocalPath": "D:\\RasterFileShare",
                "FileShareName": "RasterFileShare"
            }
```
is specified, it fails with the error-message:
_Die PowerShell DSC-Ressource "ArcGIS_FileShare" konnte die Funktion "Test-TargetResource" nicht ausführen. Fehlermeldung: "FileShareLocalPath already exist. Please Choose Another One!" 
Die Funktion 'SendConfigurationApply' war nicht erfolgreich._

As far as I understood, the reason can be found in "ArcGIS_FileShare.psm1", row 168. In there it "throws" an error, if the file share-path already exists. But why not only check, if a file share is also present on that folder and continue?

This behavior could be reproduced with arcgis-powershell-dsc in version 2.0, ArcGIS Enterprise 10.6.1 on Windows Server 2016 Datacenter (German).

**Comment by shailesh91** [comment]
Introduced a new variable "ExternalFileShare" for Raster Datastore Items. Fixed with v2.1.1!
