### ISSUE TITLE
upgrade base deployment from 10.6.1 to 10.7.1 fail after server reboot

### ISSUE THREAD

**Issue by dird-hyang** [Esri/arcgis-powershell-dsc#192]
Hi,
I run the script to upgrade our base deployment from 10.6.1 to 10.7.1. The process runs successfully without error message. The portal can be accessed directly. 
However, after the server reboot, I got the error message ArcGIS Web Adaptor: "Could you not access any Portal machines. Please contact your system administrator."
It seems something not set properly after upgrade.
Can you help to identify the issues?
thanks
Helen

**Comment by shailesh91** [comment]
Hey Helen,
Looks like portal service didn't come up correctly after a machine reboot. Please try starting your portal service and try again. 
Thanks,
Shailesh

**Comment by dird-hyang** [comment]
Thanks for the feedback. After I set the service into delayed start, it works.
@shailesh91 
Helen

**Comment by spitzerr** [comment]
If you install manually I'm pretty sure the service is set on "delayed start" by default. Is it a legacy issue from your upgraded environment or is the DSC not setting the service to "delayed start"?
@shailesh91 could you double check on setting the service to "delayed start" on a fresh installation?

**Comment by shailesh91** [comment]
@spitzerr we set the service to an automatic start and not delayed start.
