### ISSUE TITLE
install ODBC Driver as part of the installation package

### ISSUE THREAD

**Issue by dird-hyang** [Esri/arcgis-powershell-dsc#193]
Hi,
It would be very handy to include the installation or update the ODBC driver as part of the configurable installation items.
We use SQL Server to store and manage most of our spatial data. I have to manually install the ODBC driver in order for the portal/server to register the connection file to the SQL DB.
This is just a wish list. Thanks for the consideration.
Helen

**Comment by pfoppe** [comment]
Vote Up!  This hit us today on testing out a PSDSC install of ArcGIS Enterprise.  We will be looking for alternative automated install options for the SQL Server Driver as well so that we dont have to manually complete this work.  

Thanks for the consideration.

**Comment by DCHuber** [comment]
Vote Up!

**Comment by cameronkroeker** [comment]
Hello @dird-hyang @pfoppe and @DCHuber,

This has been added to the latest release, v3.0.0:

https://github.com/Esri/arcgis-powershell-dsc/releases

**Tutorial Wiki:**
https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Register-an-Enterprise-Geodatabase-with-ArcGIS-Server-site

**Sample Config:**
https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Gis%20Servers/GISServer-Database.json

**Comment by pfoppe** [comment]
Great news!!! Thank you!
