### ISSUE TITLE
Pro 2.4 Install issue and possible fix

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-powershell-dsc#194]
I had to add '2.4.19948' as a Pro version on this line

https://github.com/Esri/arcgis-powershell-dsc/blob/037b14af2d058f54c96a0f46f4facd9baf77579f/Modules/ArcGIS/ArcGISUtility.psm1#L1466

and the corresponding component code after the next line

'2.4.19948' = 'E3B1CE52-A1E6-4386-95C4-5AB450EF57BD'

https://github.com/Esri/arcgis-powershell-dsc/blob/037b14af2d058f54c96a0f46f4facd9baf77579f/Modules/ArcGIS/ArcGISUtility.psm1#L1543

The above two changes allowed Pro install DSC configuration to validate and log messages correctly that it completed successfully. It also prevents Pro from being reinstalled if you run the same DSC configuration again.

**Comment by shailesh91** [comment]
@pcsswamin product code is wrong for Pro 2.4. We will make the necessary change in an upcoming minor release.

**Comment by dird-hyang** [comment]
Hi,
Does this means we can use this ArcGIS version 2.1 to upgrade the Pro and desktop set?

**Comment by shailesh91** [comment]
@dird-hyang as of now upgrades of Pro and Desktop is not supported by the DSC Module.

**Comment by shailesh91** [comment]
Fixed with v2.1.1!
