### ISSUE TITLE
Installing Insights on arcgis enterprise environments

### ISSUE THREAD

**Issue by lachlanwainwright** [Esri/arcgis-powershell-dsc#196]
Hi
We have been using powershell to setup arcgis enterprise 10.7.1 in a DEV environment and need to install Insights.  I have taken a peek but cannot find any reference to this with the scripts, is insights included in the enterprise installation capability?

If it isn't included, is it possible to manually install and not affect the automation/script capability going forward (upgrades etc)

I look forward to the help.
Lachlan

**Comment by shailesh91** [comment]
Hi Lachlan,
We don't yet support installing insights along with deploying ArcGIS Enterprise stack. This is in the roadmap but no definite ETA.
Impact on upgrades when doing a Manual installation of insight is unknown as of now. 
Regards,
Shailesh

**Comment by lachlanwainwright** [comment]
Hey Shailesh
Thanks for the info. I did install and out of interest ran the script again and no errors returned.

Can't wait for it to be included and if you do get the opportunity to test an u/g prior to inclusion I'd like to know the outcome.

thanks again
Lachlan

**Comment by lachlanwainwright** [comment]
thanks again
