### ISSUE TITLE
ArcGIS_Portal defaults to creatorUT for UserLicenseType parameter 

### ISSUE THREAD

**Issue by PleaseStopAsking** [Esri/arcgis-powershell-dsc#198]
With the release of support for 10.7 and 10.7.1, ArcGIS Portal requires the selection of a UT/Role when creating the IAA. The ArcGIS_Portal resource is currently defaulting to the Creator role (creatorUT) regardless of what value is provided in the UserLicenseType parameter due to the way the below ``if`` statement is constructed.

If the resource should always use the creatorUT, the UserLicenseType should be removed but I assume that we want to leave the option of actually selecting a UT.

Furthermore, if you leave the UserLicenseType out completely, it will still succeed but assigns the IAA as a Temporary Standard UT.

https://github.com/Esri/arcgis-powershell-dsc/blob/037b14af2d058f54c96a0f46f4facd9baf77579f/Modules/ArcGIS/DSCResources/ArcGIS_Portal/ArcGIS_Portal.psm1#L167-L171

**Comment by shailesh91** [comment]
Fixed with v2.1.1!
