### ISSUE TITLE
 Deploy ArcGIS 10.7.1 Portal - ArcGIS License Fail 

### ISSUE THREAD

**Issue by Lobstersack** [Esri/arcgis-powershell-dsc#199]
Hey Guys

Im attempting a multi machine deployment in a DEV environment and had recently had everything working for 10.6.1 Enterprise. with the project still not out of DEV i decided go with 10.7.1. 

doing this i only changed the install, patches, licences path and version to the new 10.7.1 install
its now failing to create the MOF for ArcGISlicences  and i get this error below 
 
attached is my DSC .json for portal

[TEST_10-7-1_san.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3465567/TEST_10-7-1_san.txt)

ArcGISInstall - Completed
Dot Sourcing the Configuration:- ArcGISLicense
Compiling the Configuration:- ArcGISLicense
Starting DSC Job:- ArcGISLicense
Start-DscConfiguration : The computer name was not specified and the configuration directory does not have any configuration files.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\ArcGIS\ArcGIS.psm1:214 char:16
+ ...      $Job = Start-DscConfiguration -Path ".\$($ConfigurationName)" -F ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-DscConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDscConfigurationCommand
 
Logs Directory: C:\ArcGIS\Logs
Finished DSC Job:- ArcGISLicense. Time Taken - 00:00:00.0174342
ArcGISLicense - 
2019-08-05 10:47:24 - DSC Run finished for E:\DSC\TEST.json
2019-08-05 10:47:24 - Script Finished

Any ideas??

**Comment by spitzerr** [comment]
Hi,

at 10.7 and above you need to specify the `PortalLicenseUserType` for the Primary Site Admin. As I can see you didn't specify this setting in your json... Put something like Creator in there to get things running.

**Comment by Lobstersack** [comment]
i did try this and it didn't work. but maybe I'm missing something (see below)

also found out it doesn't matter as there was a bug listed for the 10.7.1 [](https://github.com/Esri/arcgis-powershell-dsc/issues/198) 

To insure I'm doing this properly. please see example below. 

  "Portal" : {

            "LicenseFilePath" : "C:\\ArcGIS\\Licenses\\ArcGIS_Enterprise_Portal_107_283244_20190804.json" ,
            "LicensePassword" : "" ,
            "PortalLicenseUserType" : "Creator" ,
            "ContentDirectoryLocation" : "\\\\devapp265vs.dev.act.gov.au\\WorkDir\\PortalContent" ,
            "EnableAutomaticAccountCreation" : "False" ,

thanks for your input, i'm hopping for an easy fix, but starting to think it might not be.

**Comment by shailesh91** [comment]
@Lobstersack Try without the LicensePassword field once. The snippet below has a bug, which might be causing the License File Path to be set to NULL in your case. 

https://github.com/Esri/arcgis-powershell-dsc/blob/037b14af2d058f54c96a0f46f4facd9baf77579f/Modules/ArcGIS/Configurations-OnPrem/ArcGISLicense.ps1#L65-L69

**Comment by Lobstersack** [comment]
Hi @shailesh91 

i had a go, but it didn't it work. (see below)
"Portal" : {

            "LicenseFilePath" : "C:\\ArcGIS\\Licenses\\ArcGIS_Enterprise_Portal_107_283244_20190804.json" ,
            "PortalLicenseUserType" : "creator" ,
            "ContentDirectoryLocation" : "\\\\devapp265vs.dev.act.gov.au\\WorkDir\\PortalContent" ,
            "EnableAutomaticAccountCreation" : "False" ,

with the Error, i don't feel like the its getting to the stage of even looking at some of the details, because it's not creating a .MOF file. 

its being deployed from AZURE DevOps, so i might delete everything it run it from it form scratch. maybe its just hasn't unpacked/installed all the DSC stuff properly.

I'll keep everyone posted.

Cheers.
LB

**Comment by Lobstersack** [comment]
Update: still getting them same error with fresh deploy. 
I'm open to any ideas : )

**Comment by shailesh91** [comment]
@Lobstersack try deploying without "PortalLicenseUserType" parameter. It might default to temp user type that you can later modify.

**Comment by Lobstersack** [comment]
@shailesh91 Tried this, didn't work (see example below )

I'm still getting the same error and it doesn't compile the config to a MOF file
    "Portal" : {

            "LicenseFilePath" : "C:\\ArcGIS\\Licenses\\ArcGIS_Enterprise_Portal_107_283244_20190804.json" ,
            "ContentDirectoryLocation" : "\\\\devapp265vs.dev.act.gov.au\\WorkDir\\PortalContent" ,
            "EnableAutomaticAccountCreation" : "False" ,

            "Installer" : {
                "Path" : "C:\\ArcGIS\\InstallFiles\\Portal_for_ArcGIS_Windows_1071_169688.exe",
                "PatchesDir" : "C:\\ArcGIS\\InstallFiles\\Patches\\Portal\\v10-7-1" ,
                "InstallDir" : "C:\\Program Files\\Esri\\ArcGIS\\Portal" ,
                "ContentDir" : "C:\\Program Files\\Esri\\ArcGIS\\Portal\\Content"
            }
        }
    }
}

thanks for everyone's input thus far : )

Cheers,
Jono

**Comment by spitzerr** [comment]
Hi,

here are some Debug-Hints maybe we find some more clues on this.
What does `Get-DSCConfigurationStatus -All` say?
Could you run your Configuration with `-DebugSwitch` and show the Debug-Log here?

You could also try to enable DSC-Debugging if you think its related to the creation of the mof-file itself: https://docs.microsoft.com/en-us/powershell/dsc/troubleshooting/debugresource

Best,
-R

**Comment by cameronkroeker** [comment]
Hello @Lobstersack, has there been any progress on this issue?

**Comment by Lobstersack** [comment]
Sorry guys, long time between drinks.

No, I haven't solved this issue. I have progressed with the 10.6.1. The extra debug switch didn't give me anything extra to work with. 

I will however go back to development with a smaller stack of 4 VM's and try 10.7.1 again. ill keep everyone posted 

Cheers,
Jono

**Comment by cameronkroeker** [comment]
@Lobstersack 

Sorry to hear that it is still an issue. Perhaps try with a single portal instance rather than two, to see if helps.

**Comment by cameronkroeker** [comment]
If this issue still persists please feel free to re-open with updated details and logs.
