### ISSUE TITLE
Datastore no longer registered with server after 10.6.1 to 10.7.1 upgrade

### ISSUE THREAD

**Issue by pfoppe** [Esri/arcgis-powershell-dsc#200]
I recently upgrade an enterprise deployment from v10.6.1 to v10.7.1.  All output messaging and PSDSC logs indicated it was successful (no apparent errors), however accessing the portal settings page returned: 
![image](https://user-images.githubusercontent.com/8226358/63061740-7aca1c00-beb3-11e9-9f04-49a2d7dccfa6.png)

and the hosting server failed to validate.  **The hosting server indicated it no longer had a data store registered with the server.**  I was able to manually complete an "ArcGIS Data Store Upgrade"  by navigating to https://data_store_machine:2443/arcgis/datastore/

The upgrade indicated it was successful, but I was unable to see the registered data store in arcgis manager.  I did have to run it a second time which looked like a brand new registration.  After the second attempt, the hosted services still function (content was returned in a web-map). So I'm hopeful there are no systemic/lasting effects from the upgrade. 

I have a 4 machine site with the following configuration: 
  - Machine 1 - IIS, Portal Web-adaptor, Hosted Server web-adaptor, Federated Server web-adaptor
  - Machine 2 - Portal Data Store
  - Machine 3 - ArcGIS Server set as a federated + Hosting Server
  - Machine 4 - Federated ArcGIS Server (no hosting)

Attached is the redacted original v10.6.1 JSON file and the updated v10.7.1 JSON file for the base deployment (machine 1-3).  I did not provide the JSON files for machine 4 since I dont think it has anything to do with this situation.

[1061_install.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3503718/1061_install.txt)
[1071_upgrade.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3503720/1071_upgrade.txt)

Thanks

**Comment by shailesh91** [comment]
@pfoppe would it be possible for you to send over the logs files for the datastore upgrade part?

**Comment by pfoppe** [comment]
Hi @shailesh91 

Yes, see attached redacted log files.  
[DataStoreUpgradeInstall-8-14-2019-11-02-45-AM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3506921/DataStoreUpgradeInstall-8-14-2019-11-02-45-AM-Verbose.txt)
[DataStoreUpgradeConfigure-8-14-2019-11-06-32-AM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3506922/DataStoreUpgradeConfigure-8-14-2019-11-06-32-AM-Verbose.txt)

Yes, the UpgradeConfigure log file seems very sparse.  

Thanks!

**Comment by shailesh91** [comment]
@pfoppe I haven't been able to reproduce this issue or #188 which are appearing to be the same. Will keep you updated.

**Comment by pfoppe** [comment]
I see this issue was referenced with the 2.1.1 release - https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v2.1.1

I've completed 2 upgrades (from 10.6.1 to 10.7.1) with v2.1.1 and both of them have succeeded!

So its possible this issue is resolved with the "stability fixes for Datastore Upgrades".  I'm going to go ahead and close this issue for now.

Thanks!
