### ISSUE TITLE
ArcGIS Enterprise 10.7 - Support for "Portal for ArcGIS Web Styles"

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#201]
Hello,

From 10.7.1, "Portal for ArcGIS Web Styles" have been separated from the main setup:
[ArcGIS Enterprise 10.7.1 quick start guide—Quick Start Guides | ArcGIS Desktop](https://community.esri.com/external-link.jspa?url=https%3A%2F%2Fdesktop.arcgis.com%2Fen%2Fquick-start-guides%2Flatest%2Farcgis-enterprise-quick-start-guide.htm)

Would be nice if the library could allow to install it as well.

Thanks !

**Comment by dird-hyang** [comment]
support this idea.

**Comment by shailesh91** [comment]
@Biboba @dird-hyang this is supported. The sample config files and wiki (Variables-reference-page-for-JSON-configuration-files) are already updated to reflect this.
https://github.com/Esri/arcgis-powershell-dsc/blob/037b14af2d058f54c96a0f46f4facd9baf77579f/SampleConfigs/Base%20Deployment/BaseDeployment-SingleMachine.json#L70

**Comment by Biboba** [comment]
Awesome @shailesh91 !
My bad thanks.
Closing the issue then !
