### ISSUE TITLE
Getting started page does not mention 10.7.1

### ISSUE THREAD

**Issue by AdamBranscomb** [Esri/arcgis-powershell-dsc#203]
As title. The getting started page says 10.7 is supported by does not explicitly mention 10.7.1.
The wiki says 10.4.1 and later is supported.

**Comment by shailesh91** [comment]
@AdamBranscomb we do support 10.7.1. Documentation will be updated to reflect the same. Thanks for pointing out the omission.

**Comment by shailesh91** [comment]
Fixed with v2.1.1!
