### ISSUE TITLE
NuGet installation issue

### ISSUE THREAD

**Issue by CliveSW-online** [Esri/arcgis-powershell-dsc#205]
Greetings,

Due to security constraints we cannot download software from external or websites.

I placed the nugget.exe on the PC and installed by opening the file.  
When I run Install-Module ArcGIS command in PowerShell, it still tries to download the NuGet file from 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409'????
It returns a "Not found" error??

Any suggestions.

Thanks,

Clive

**Comment by CliveSW-online** [comment]
I also tried running:
Install-PackageProvider –Name “P:\My Documents\DEV\Portal\nuget.exe”

Still get an error: NoMatchFoundForProvider ???

**Comment by CliveSW-online** [comment]
After about 4 hours!! I found a posting to download the NuGet module from a networked machine to an offline machine..

Pity there is not a help page for secure systems, that don't have internet access.

**Comment by nshampur** [comment]
@CliveSW-online  - glad you got this resolved.

I didn't have a chance to post y'day, but installing PowerSHell modules can also be achieved via a Simple X-copy of the module into the PowerShell Modules directory (typically Program Files / PowerShell / Modules

The nuget update is needed for Install-MOdule to function.
