### ISSUE TITLE
Use CloudStorage for portal content and server configuration store and directories

### ISSUE THREAD

**Issue by hmelendez** [Esri/arcgis-powershell-dsc#206]
Is there a way to specify cloud storage for the portal content, server configuration store, and server directories? I would like to be able to define the AWS S3 bucket, Azure File (SBS) or Blob storage when deploying on those environments.

**Comment by shailesh91** [comment]
@hmelendez As of now we haven't exposed the support for cloud storage. This is on the road map, but we don't have a definite timeline it will be available.

**Comment by cameronkroeker** [comment]
@hmelendez,

We have added this to the latest release, v3.0.0:
https://github.com/Esri/arcgis-powershell-dsc/releases

**Sample Config:**
https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Base%20Deployment/BaseDeployment-SingleMachine-CloudStore.json

**Comment by Biboba** [comment]
Hello @cameronkroeker,

I would like to configure an S3 cloud storage as a cache directory and I believe it is currently not possible.

I seems to me that it is the same request as @hmelendez so why did you close it ? Do you want me to open another issue to track this request ?

You seem to be aware of this [limitation:](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files)

```
DataStoreItems - Only RasterStore is being tested and supported as of now. We will support Folder, CloudStore and BigDataFileShare in future releases.
```

Thanks !

**Comment by cameronkroeker** [comment]
> Hello @cameronkroeker,
> 
> I would like to configure an S3 cloud storage as a cache directory and I believe it is currently not possible.
> 
> It seems to me that it is the same request as @hmelendez so why did you close it ? Do you want me to open another issue to track this request ?
> 
> You seem to be aware of this [limitation:](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files)
> 
> ```
> DataStoreItems - Only RasterStore is being tested and supported as of now. We will support Folder, CloudStore and BigDataFileShare in future releases.
> ```
> 
> Thanks !

Hello @Biboba ,

I recommend opening a different issue for this feature request. The reason this one is closed is because we added support for deploying portal content and ArcGIS Server config-store within Azure Blob Storage and Azure Files. Registering DataStoreItems is a different workflow/different set of resources.

Thanks,
Cameron K.
