### ISSUE TITLE
Updating Portal and AGS licensing on existing deployments

### ISSUE THREAD

**Issue by KC-JJ** [Esri/arcgis-powershell-dsc#209]
It would be great to be able to update the licensing on existing deployments by using the config file that was used to license the software in the first place.  I tried just running "InstallLicense" to update new licenses but the script looks like it's looking for anything with "svr" in the keycode file before it will update the license for AGS and I'm not sure how it's checking Portal's licensing.  if I renamed the nearly-expiring AGS keycode file on the existing deployment, it would actually update the licensing for AGS when I ran the Mode as "InstallLicense". This would be super handy in maintaining new licenses for large scale deployments instead of needing to visit each machine individually.

**Comment by cameronkroeker** [comment]
Hi @KC-JJ,

Thanks for the feedback. One challenge with this is authorization keys have a finite amount of available authorizations. The PowerShell DSC arcgis module is idempotent, so if we made this change and the deployment fails then the same authorization key would be re-authorized each time. This wouldn't be ideal because then potentially the available authorizations would eventually be all used up.

**Comment by KC-JJ** [comment]
Thanks for the reply @cameronkroeker 
Maybe there just needs to be a switch like -UpdateLicense that would override the check and re-authorize that way it's not changing the way the check happens now, but the user would have the option to update that licensing per the deployment.  I do know that license management for administrators can be a challenge when you start looking at large scale HA deployments - this would greatly help them managing that.

**Comment by cameronkroeker** [comment]
@KC-JJ,

We have added the following feature to the latest release, [v3.0.0](https://github.com/Esri/arcgis-powershell-dsc/releases):

**ForceLicenseUpdate** - (Optional - true | false) - Will force update license on all components in the AllNodes block.

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files
