### ISSUE TITLE
7zip download failures

### ISSUE THREAD

**Issue by PleaseStopAsking** [Esri/arcgis-powershell-dsc#211]
The url being used to download 7zip within the ArcGIS_Install resource is now failing due to tls. With PowerShell 5 and earlier, the response is...

```
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.
At line:1 char:1
+ Invoke-WebRequest -Uri 'https://osdn.net/frs/redir.php?m=pumath&f=sev ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebEx
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

with PowerShell 6 and newer, the response is...

```
Invoke-WebRequest : Response status code does not indicate success: 302 (Found).
At line:1 char:1
+ Invoke-WebRequest -Uri 'https://osdn.net/frs/redir.php?m=pumath&f=sev ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Reques\u2026PowerShell/6.2.3
}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

The fix is to either revert to using the http url or to add the following string before using Invoke-WebRequest. I wont submit a PR for this as it is likely easier to make the change yourself instead of dealing with a PR.

```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
```

**Comment by shailesh91** [comment]
@PleaseStopAsking You can also specify a local installer as a stop-gap. You need to specify the following two params in your config - SevenZipInstallerDir and SevenZipInstallerPath. More info in Variable reference (https://github.com/Esri/arcgis-powershell-dsc/wiki/Variables-reference-page-for-JSON-configuration-files)

**Comment by nshampur** [comment]
@pcsswamin  - concern acknowledged. 
In the past 7-zip changed the download links to require user interaction, hence the switch was made.

The ArcGIS installers don't support extraction at command line. If that's what you meant by built in extractors.

**Comment by pcsswamin** [comment]
@nshampur - Thanks for the explanation. Documenting that reason and hence the need for 7zip for extracting ArcGIS installers somewhere in the wiki  would help many of us out.

**Comment by nshampur** [comment]
@cameronkroeker  brought to my attention some silent options for extraction. I stand corrected.

We'll look into removing the requirement for 7 zip

**Comment by pcsswamin** [comment]
Thanks @nshampur and @cameronkroeker

**Comment by spitzerr** [comment]
In Powershell V5 there is also
`Expand-Archive "PATH TO ARCHIVE" -DestinationPath "DESTINATION PATH"`
available. Maybe this could be used instead of 7zip?

**Comment by PleaseStopAsking** [comment]
@shailesh91 That is using the assumption that everyone uses the ArcGIS Module by using the included configurations. In our case, we build our own custom configurations and leverage the DSC resources directly.

I am onboard with moving away from 7zip if the installers supported through the ArcGIS_Install resource have the necessary extraction support already there but in the meantime, could we not add the tls workaround?

**Comment by cameronkroeker** [comment]
Hello @PleaseStopAsking, @pcsswamin, @spitzerr,

We are excited to share that we have removed the dependency of 7Zip in the latest release, v3.0.0. 

7Zip is no longer required or used to extract the setup archives. 

https://github.com/Esri/arcgis-powershell-dsc/releases
