### ISSUE TITLE
ArcGIS Pro Patches get reinstalled: Not idempotent

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-powershell-dsc#212]
The QFE ID returned by DSC code from "HKLM:\SOFTWARE\ESRI\ArcGISPro\Updates\*"  does not match the one retreived from the msp file and so the Pro patches get reinstalled every time.

Snippets from my log file:
[[ArcGIS_InstallPatch]ProInstallPatch] Comparing QFE ID ArcGIS_Pro_241_170796 against ID QFE-24-PRO-Update241
 [[ArcGIS_InstallPatch]ProInstallPatch] Comparing QFE ID ArcGIS_Pro_241_170796 against ID QFE-24-PRO-Update242
 [[ArcGIS_InstallPatch]ProInstallPatch]  > Patch not installed - installing
....
 [[ArcGIS_InstallPatch]ProInstallPatch] Comparing QFE ID ArcGIS_Pro_242_170797 against ID QFE-24-PRO-Update241
 [[ArcGIS_InstallPatch]ProInstallPatch] Comparing QFE ID ArcGIS_Pro_242_170797 against ID QFE-24-PRO-Update242
[[ArcGIS_InstallPatch]ProInstallPatch]  > Patch not installed - installing

**Comment by cameronkroeker** [comment]
@pcsswamin 

The PowerShell DSC ArcGIS Module will attempt to extract a QFE ID from the .msp file and check to see if it exists in the Windows registry, if it finds a match then the patch is skipped. If no match found, then the patch is installed. If the QFE ID isn't found in the .msp or there is a mismatch then this problem you are reporting occurs.

I recommend calling Esri Technical Support to report this issue.

**Comment by pcsswamin** [comment]
@cameronkroeker - I disagree. This is not specific to my environment or organization. So shouldn't calling esri tech support directly be the last option here for an esri customer here? I am not trying to subvert due process here. 

The esri automation team should be to reproduce this issue very quickly and route it internally to the team that does patch releases across the arcgis platform. In addition to Pro, This QFE ID mismatch issue also manifests in 10.6.1 ArcGIS Server patches (blank or empty QFE IDs) and so this is more systemic problem which one of you should be able to route through internally in Redlands much more efficiently than me calling tech support and explaining everything from scratch.

**Comment by cameronkroeker** [comment]
@pcsswamin 

The challenge here is that the issue isn’t with the PowerShell DSC ArcGIS Module, but rather the patches (.msp). It would be ideal to be able to find all existing patches that are missing the QFE ID’s (or incorrect QFE ID’s), that have already been released and replace them with an msp that contains the correct QFE ID. However, this will still remain an issue for customers who have already downloaded and installed a patch that didn’t contain a QFE ID. 

With that said we will follow up internally with the patch release team, but still encourage all customers to reach out to Esri Technical Support as this is the best avenue.  Additionally, GitHub isn’t really the proper channel or forum to report patches missing QFE ID’s, but rather these should be reported to Esri Technical Support. This way Esri Technical Support can reproduce the issue and submit an official bug report that contains a bug ID that will allow the status to be tracked via the Support site. 

If you would like to discuss further, please feel free to contact me directly via email, ckroeker@esri.com.

Thanks,
Cameron K.

**Comment by pcsswamin** [comment]
@cameronkroeker 

I am willing to start a tech support case to start tackling this. Taking it all the way to register a bug requires considerable investment of time and that is what I was balking at. Happy to take this offline. I will drop you an email on this soon.

Thanks
