### ISSUE TITLE
Issue installing HA Portal

### ISSUE THREAD

**Issue by cdbarker** [Esri/arcgis-powershell-dsc#219]
I am trying to install a highly available portal. I have attached the config file.

[HA_Portal.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3847771/HA_Portal.txt)

We are setting the web context url using the DNS as the Portal web adaptor alias.

We have two VMs hosted in Azure sitting behind a load balancer. The portal content store is being hosted on an Azure file share. 
On the VMs themselves we have a host file entry for the load balancer URL, but rather than pointing to the load balancer they are configured to their own IP addresses.

Portal and the web adaptors successfully install on both machines and both primary and standby machines are showing in Portal Admin. However the web adaptors fail to register without any error - they just don't ever configure and the process hangs. 
There are no errors in the PS logs.
Portal admin shows a single web adaptor registered, which is registered under the portal DNS with no machine IP. The web adaptors on both portal machines are showing as not having been configured.

There's nothing immediately obvious in the Portal logs themselves.

**Comment by cameronkroeker** [comment]
@cdbarker 

At 10.7.1, the Portal WebAdaptor registration kicks off a full reindex of portal content. Perhaps since the portal content is in Azure file share it could be taking awhile (15+ minutes) for the reindex to fully complete and the Web Adaptors registration page wont reflect that it is configured until the reindex has fully completed.

When the WA registration is started, open a task manager window on the primary portal machine and there should be an additional java.exe process (enable command line column in the task manager details tab). Check the class path to verify the additional java.exe is the indexer tool. This indicates that a full reindex is taking place. Can also enable portal debug logging and it should show the reindex taking place as well. Once this java.exe process disappears then the index is complete, then check the WebAdaptor page (https://webadaptor.domain.com/portal/webadaptor) to see if the registration completed.

**Comment by cdbarker** [comment]
@cameronkroeker 

Thanks for your swift response.
After waiting slightly longer I received the following two errors in the Portal logs:

PortalTrustManager initialization failed. java.lang.Exception: Cannot connect to the database jdbc:postgresql://localhost:7654/gwdb FATAL: the database system is shutting down.

Failed to register ArcGIS Web Adaptor '<portal DNS>' with the portal.java.lang.Exception: Cannot connect to the database jdbc:postgresql://localhost:7654/gwdb FATAL: the database system is shutting down.

This is then followed by repeated 'The web server was found to be stopped. Re-starting it'. 

This suggests an issue communicating over port 7654 -  is this port included in the firewall rules created during install?

**Comment by cameronkroeker** [comment]
Hi @cdbarker,

We do include 7654 in the firewall rules:
https://github.com/Esri/arcgis-powershell-dsc/blob/master/Modules/ArcGIS/Configurations-OnPrem/ArcGISConfigure.ps1#L547

For multi-node portal though the portals wont communicate with each other over 7654. Instead these other ports are used:

https://github.com/Esri/arcgis-powershell-dsc/blob/master/Modules/ArcGIS/Configurations-OnPrem/ArcGISConfigure.ps1#L595

Are you seeing those errors on primary portal, secondary portal, or both?

**Comment by cdbarker** [comment]
Hi @cameronkroeker

The errors were on the primary portal.

One thing I have noticed is a massive issue throughout this deployment is the incomplete writing of the portal content. On multiple occasions, not all files are created in the portal content/items directory but DSC continues. This results in the following error:

PowerShell DSC resource ArcGIS_Portal  failed to execute Set-TargetResource functionality with error
message: Unable to unzip portal content.

This happens whether the content store is on Azure files or a share on another Azure VM.

Re-running the configuration doesn't create the missing files.

Are there any suggestions/requirements for deploying in Azure e.g. minimum IOPS or machine specifications over and above the standard Esri requirements?

**Comment by cdbarker** [comment]
Hi @cameronkroeker 

I have got around the incomplete content creation by using a file server rather than azure files.

The main issue is with the web adaptors. Using DSC, only one web adaptor will configure and the second always fails:

'[ArcGIS_WebAdaptor]ConfigurePortalgis-machine.xxxxx.internal.cloudapp.net' on machine(s)
'gis-portal-az2' is not ready after '100' retries with retry interval of '60' second(s).

To test this further I removed the web adaptors from the DSC configuration and installed them manually after the two portals had configured.
I can register the first web adaptor, but when I register the second web adaptor it overwrites the first in portal admin. However, the first web adaptor still thinks it is configured (when browsing to the configuration page). This is the same behavior seen when trying to configure via DSC.

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker
> 
> I have got around the incomplete content creation by using a file server rather than azure files.
> 
> The main issue is with the web adaptors. Using DSC, only one web adaptor will configure and the second always fails:
> 
> '[ArcGIS_WebAdaptor]ConfigurePortalgis-machine.xxxxx.internal.cloudapp.net' on machine(s)
> 'gis-portal-az2' is not ready after '100' retries with retry interval of '60' second(s).
> 
> To test this further I removed the web adaptors from the DSC configuration and installed them manually after the two portals had configured.
> I can register the first web adaptor, but when I register the second web adaptor it overwrites the first in portal admin. However, the first web adaptor still thinks it is configured (when browsing to the configuration page). This is the same behavior seen when trying to configure via DSC.

@cdbarker glad to hear the portal content created. As for the Portal WA issue, this will be addressed in the next release.

Thanks,
Cameron
