### ISSUE TITLE
HA install quirk

### ISSUE THREAD

**Issue by jhevenor** [Esri/arcgis-powershell-dsc#222]
Our setup: 10.6.1 install with paired VMs for web adapter, portal, server.  Following the standard multi-machine template.  Using 'ExternalLoadBalancer' to define the pubic URL that points to our Azure Network Load Balancer. Things go pretty smoothly and everything looks good at the surface. 

My team was doing some testing along the lines of 'shut off one side, what happens'.  When shutting off one of the portal VMs (POR0),  the public URL survives, we log into portal, etc.  When we go to the org settings and validate the server it fails. The mouseover/tooltip says it can't authenticate to POR0 (which is off).  Uh oh. 

Digging into the portal settings I see the following under /server/admin/security/config:

```
{
  "portalUrl": "https://something.domain.ca/portal",
  "privatePortalUrl": "https://env-por0.internal.domain.ca:7443/arcgis",
  "portalSecretKey": "xyz",
  "portalMode": "ARCGIS_PORTAL_FEDERATION",
  "serverId": "abc",
  "serverUrl": "https://something.domain.ca/server",
  "privateHostingServerUrl": "https://something.domain.ca/server"
}
```

Ah ha! So it's using a single URL internally. 

So my questions...is there a DSC config variable that I need to be setting more specifically, or, is this a bug with DSC?   Other thoughts?   I do have internal load balancers for the portal and server VMs that I've yet to make use of since I'm not sure how to wire them into my DSC templates.  

Thanks for the advice,   Josh

**Comment by shailesh91** [comment]
Hi Josh, 
This has been an issue with DSC since the first release and the following comment kind of touches on the same. https://github.com/Esri/arcgis-powershell-dsc/issues/113#issuecomment-449614816
We will be supporting an additional parameter in the coming release for "InternalLoadBalancer". 
As of now, there is no way to define or modify DSC to support this other than modifying the "privateportaladminurl" explicitly through portal admin rest endpoint.
Thanks,
Shailesh

**Comment by cameronkroeker** [comment]
@jhevenor,

We have added the following parameters for both Portal and Server to the latest release, [v3.0.0](https://github.com/Esri/arcgis-powershell-dsc/releases) to address this.

**InternalLoadBalancer** - Internal Load Balancer Endpoint fronting 6443 ports on Server Machines. This parameter can be used to use Load Balancer like (HAProxy, Nginx, F5, etc.).

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files
