### ISSUE TITLE
ArcGIS GeoEvent Server Upgrade fails

### ISSUE THREAD

**Issue by jesa-esrich** [Esri/arcgis-powershell-dsc#223]
The ArcGIS PowerShell DSC Mode- Upgrade fails for GeoEvent Server.

Behavior:

- Unable to upgrade the ArcGIS Server
- The GeoEvent Service has to be stopped manually, so that the ArcGIS Server can be upgraded using the Powershell DSC Modules.
- After stopping the GeoEvent Services the ArcGIS Server is upgraded using PowerShell DSC. However, the GeoEvent Server is not upgraded.

Possible Solution:
Change Modules to
- stop GeoEvent Server Service before Upgrading ArcGIS Server
- restart GeoEvent Services after Upgrade
- initiate GeoEvent Upgrade or add Module to Upgrade the GeoEvent Server

**Comment by jesa-esrich** [comment]
@scma-esrich

**Comment by shailesh91** [comment]
@jesa-esrich this is a bug. We already do that for our azure deployments. We will fix this in the upcoming release.

**Comment by scma-esrich** [comment]
Thanks for your quick response @shailesh91!

**Comment by jesa-esrich** [comment]
> @jesa-esrich this is a bug. We already do that for our azure deployments. We will fix this in the upcoming release.

Great to hear this will be fixed. And thanks for the quick reply.

**Comment by cameronkroeker** [comment]
@jesa-esrich,

This issue has been addressed in the latest release, [v3.0.0](https://github.com/Esri/arcgis-powershell-dsc/releases).
