### ISSUE TITLE
404-deadlink on DSC-landing-page

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#225]
The link on the github-DSC-landing page is pointing to a URL no longer available:
![image](https://user-images.githubusercontent.com/45851791/70996567-57b6af80-20d3-11ea-80b8-c2bdd92d9280.png)

The URL it is trying to reach: https://docs.microsoft.com/en-us/powershell/dsc/overview

**Comment by cameronkroeker** [comment]
Thanks @scma-esrich for bringing this to our attention. It has been updated.
