### ISSUE TITLE
Datastore 

### ISSUE THREAD

**Issue by jhevenor** [Esri/arcgis-powershell-dsc#226]
My team has been failure testing our HA environment and noticed out standby datastore wasn't being promoted when the primary failed.  Working with ESRI support we were presented with a manual solution: 

- Remote desktop to the DS machines
- Edit C:\ArcGIS\DataStore\framework\etc\datastore.properties
- Set failover_on_primary_stop=true

Is this something that can be the default with 2+ data store machines through DSC? Or configurable via some new variable?

I'm hoping in the new year to get into fixing some of these myself and sending pull requests. Thanks for all the support, this project is very helpful.

**Comment by PleaseStopAsking** [comment]
@jhevenor The Datastore resource currently has a parameter called $IsEnvAzure which does change that property to true. I dont recall off the top of my head what else the parameter does unfortunately so it might be wise to review before implementing it if you are not deploying in Azure.

**Comment by nshampur** [comment]
that's correct - the parameter was intended to control whether failover should occur on cloud environments where a system maintenance events used to be applied (in the past) and we didn't want to trigger a failover when the VM restarts during the update event. 
If this is an environment that you are in control of machine maintenance, then you can set data store to failover automatically when the windows service is stopped (e.g:- a machine restart)

**Comment by jhevenor** [comment]
Thanks for information @PleaseStopAsking  and @nshampur .  

I am deploying to Azure.  My data store VMs are deployed to availability sets, so they shouldn't be updated at the same time.  I don't understand if this means that $IsEnvAzure=$true would be appropriate or not, but I'm interested in everyone's position on this. 

Also, how would I go about attempting to change the $IsEnvAzure property.  I don't see it listed in the variables wiki.

**Comment by nshampur** [comment]
@jhevenor - you are correct. we haven't exposed it via the Configuration file JSON

Independent of availability sets, you should consider how system maintenance events are managed.  How do you roll out windows updates? Do you use something like Azure OMS patch management?

Azure has gotten better with host level updates and will do memory freezing updates when they need to update VMs.  
https://docs.microsoft.com/en-us/azure/virtual-machines/maintenance-and-updates 

However you are still responsible for updating the Guest OS?

**Comment by jhevenor** [comment]
In the end my orgs IT department will be responsible for the VMs. If there are settings/workflows that ArcGIS Enterprise performs best under then I can send us down that path. I haven't been worrying about Guest OS updates so far. 

I guess another question is, with 2 datastore VMs,  with failover_on_primary_stop=true, is there any point to the second VM?   I've been generally following the HA deployment architecture that ESRI describes but I'm not sure I understand what's happening in practice.

**Comment by cameronkroeker** [comment]
Hello @jhevenor,

We have introduced the following parameter in the latest release v3.0.0:

**EnableFailoverOnPrimaryStop** - Enables Failover to secondary when primary datastore is stopped.

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files

An example can be found here as well:

https://github.com/Esri/arcgis-powershell-dsc/blob/7d365cb94b9ae351797af2cce582dd8b811f1a49/SampleConfigs/v3/Base%20Deployment/BaseDeployment-SingleMachine.json#L117
