### ISSUE TITLE
Upgrade Doesn't Install WA

### ISSUE THREAD

**Issue by kphaneuf** [Esri/arcgis-powershell-dsc#228]
We have a dual machine deployment, WA is on the same server as Portal and Server, DataStore on it's own server.  We are testing upgrading (we did not use powershell for initial install) and we found the web adaptor does not install.  Wondering if this is because there are bindings on the IIS.

**Comment by cameronkroeker** [comment]
@kphaneuf 

If you try to manually install the WA silently does it give any errors?

Also, are there any PowerShell logs or messages that you could share from the deployment?

**Comment by kphaneuf** [comment]
@cameronkroeker We rolled our server back and installed everything manually to see if we ran into any issues.  We plan on rolling back again on Friday and trying the Powershell install again.  I will share the results and logs then.  Thanks!

**Comment by kphaneuf** [comment]
So this happened again. The log is below.  The WA installed but was not configured.  
[WebAdaptorInstall-1-10-2020-2-23-28-PM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/4048598/WebAdaptorInstall-1-10-2020-2-23-28-PM-Verbose.txt)

**Comment by kphaneuf** [comment]
Any ideas if this is a bug or something we can fix?

**Comment by cameronkroeker** [comment]
@kphaneuf 

Looks like an "Unauthorized" 401 error was returned when attempting to configure the WA.

```
[DWGISAP01]:                            [[ArcGIS_WebAdaptor]ConfigurePortal-DWGISAP01.cityofsacramento.org] https://dwgisap01.cityofsacramento.org/portal/webadaptor
[DWGISAP01]:                            [[ArcGIS_WebAdaptor]ConfigurePortal-DWGISAP01.cityofsacramento.org] Output of execution:- Unable to register with Portal. The remote server returned an error: (401) Unauthorized.
```
On the machine hosting the Portal WA, are you able to successfully browse to https://dwgisap01.cityofsacramento.org/portal/webadaptor?

Also, on the machine hosting the Portal WA can you successfully sign into the Portal Administrator Directory? For example, https://<portal.domain.com>:7443/arcgis/portaladmin.

Is the same "Unauthorized" error returned when trying to manually configure using the WA tool?
https://enterprise.arcgis.com/en/server/latest/install/windows/configure-arcgis-web-adaptor-after-installation.htm#ESRI_SECTION1_2137BAF24B7F4AAAA8C21DEE5FEC8059

**Comment by kphaneuf** [comment]
Hi @cameronkroeker 
Yes I can reach both of those urls.  I was able to manually configure the WA using the tool without any errors.  Was wondering if it could be a bindings issue?  When doing a full install manually (without Powershell) I've had to remove the bindings when installing the WA then re-add them when configuring.  See images below.
![GetImage (1)](https://user-images.githubusercontent.com/13141791/72557275-46d59700-3855-11ea-8816-8d602e8717fa.png)
![GetImage (2)](https://user-images.githubusercontent.com/13141791/72557287-4dfca500-3855-11ea-935d-6dd4a7c162a1.png)

**Comment by cameronkroeker** [comment]
Hi @kphaneuf,

The silent WA setup by passes the binding error 2878 because it passes in the WEBSITE_ID:

`Executing C:\Windows\TEMP\WebAdaptor\portal\WebAdaptorIIS\Setup.exe with arguments /qb VDIRNAME=portal WEBSITE_ID=1`

Whereas the WA GUI Setup Wizard is not able to:
https://support.esri.com/en/technical-article/000012091

Additionally, the WA did install successfully and is accessible so I don't think the binding issue is the cause.

Which parameters did you use to silently configure the WA that succeeded? Perhaps, these differ from what PowerShell attempted to use. (Although unfortunately the Powershell log doesn't show us).

Try re-running PowerShell with the `-DebugSwitch` parameter, it may give us some additional insight.

**Comment by kphaneuf** [comment]
When I manually configured the WA I used the same credentials that are in the PowerShell.  I'm assuming the credentials that both Server and Portal WA's use is the "PrimarySiteAdmin" under 
Credentials" information in the Powershell?  We were wondering what happens when the Portal and Server WA username and pw's are different.  They were before I ran Powershell this last time but I changed them to the match thinking that may have been the issue.  We will probably roll back again and when we rerun Powershell I include the -DebugSwitch parameter.

**Comment by kphaneuf** [comment]
@cameronkroeker 
Another thing is our Portal is setup to use SAML and we had the security sign-in settings set to only use City of Sacramento Logins, not the builtin logins.  This is only for the sign in page, but could this have been an issue?  It's just odd that the WA for Server installed and configured, but the Portal got the error.

**Comment by kphaneuf** [comment]
Today we rolled back and reran this process with -debugswitch after setting up the security questions of the portal admin user.  See [issue 229](https://github.com/Esri/arcgis-powershell-dsc/issues/229) for that full description.
The web adaptor installed but still gave the error 
"[DWGISAP01]:                            [[ArcGIS_WebAdaptor]ConfigurePortal-DWGISAP01.cityofsacramento.org] Output of execution:- Unable to register with Portal. The remote server returned an error: (401) Unauthorized."

As soon as this error showed in Powershell I went to the url https://dwgisap01.cityofsacramento.org/portal/webadaptor successfully.  I then successfully configured the Portal WA.  What I'm wondering is why is it not even able to access the website? Is it trying as my user sid to access the page or trying as gisadmin?  Here is a screenshot.
![image](https://user-images.githubusercontent.com/13141791/72654230-8084cb80-3943-11ea-8426-ab5cc831e366.png)

**Comment by cameronkroeker** [comment]
Thanks @kphaneuf for the additional information. I recommend checking the authentication at each level within IIS Manager. For example, the authentication at the 'Root', 'Default Web Site' level as well as at the 'portal' level, and even at the 'WebAdaptor' level:

![DefaultSite_IIS_auth](https://user-images.githubusercontent.com/48299621/72837836-048ccb00-3c44-11ea-9b0a-44a67d01e607.png)


![portal_IIS_auth](https://user-images.githubusercontent.com/48299621/72837867-12425080-3c44-11ea-9b24-49d3685b5c79.png)

![WebAdaptor_IIS_Auth](https://user-images.githubusercontent.com/48299621/72838237-c6dc7200-3c44-11ea-859f-3ee343ee4305.png)


Perhaps, Basic or Windows Auth is enabled at the 'Root', 'portal' or 'WebAdaptor' level?

**Comment by kphaneuf** [comment]
@cameronkroeker Ahhh! That was it at the WebAdaptor level! Anonymous was disabled and Windows was enabled.  Thank you!!

**Comment by cameronkroeker** [comment]
> @cameronkroeker Ahhh! That was it at the WebAdaptor level! Anonymous was disabled and Windows was enabled. Thank you!!

@kphaneuf,  glad to hear that resolved the issue!
