### ISSUE TITLE
External Load balancer examples 

### ISSUE THREAD

**Issue by Lobstersack** [Esri/arcgis-powershell-dsc#230]
Hey ESRI DSC friends,

has anyone got JSON examples of a multimachine deployment with external load balancers or Application Gateway's? 
I tried using the load balancer node block with an IP instead of a fully qualified domain name  and I'm getting errors. 

Cheers,
Jono

**Comment by cameronkroeker** [comment]
Hello @Lobstersack,

Perhaps the following two resources may help:

https://github.com/Esri/arcgis-powershell-dsc/wiki/Using-Internet-Protocol-(IP)-address-instead-of-Fully-Qualified-Domain-Names-(FQDN)

and

https://github.com/Esri/arcgis-powershell-dsc/blob/66e421338bee7ee40cb5ec43d1df06e0d430771d/SampleConfigs/v3/Base%20Deployment/BaseDeployment-MultiMachine.json#L97

**Comment by cameronkroeker** [comment]
Additional samples can be found here:

https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/v3.2.0/Base%20Deployment/BaseDeployment-MultiMachine.json
