### ISSUE TITLE
Patches Don't Install on Upgrade 10.6.1 to 10.7.1

### ISSUE THREAD

**Issue by kphaneuf** [Esri/arcgis-powershell-dsc#232]
We ran our config setup as below and the Portal and Server patches that were in the specified directories were not installed.  There are no log errors, they just weren't attempted.  I've attached the Portal and Server log files.
[ServerUpgrade-1-24-2020-1-35-27-PM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/4111016/ServerUpgrade-1-24-2020-1-35-27-PM-Verbose.txt)
[PortalUpgrade-1-24-2020-10-51-29-AM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/4111017/PortalUpgrade-1-24-2020-10-51-29-AM-Verbose.txt)
[FileDir](https://user-images.githubusercontent.com/13141791/73109178-4d988580-3eb7-11ea-82c3-f2244d082ab0.png)

"Server": {
            "LicenseFilePath": "D:\\InstallationFiles\\1071\\ArcGISGISServerStandard_StagingArcGISServer_833252.prvc",
            "Installer": {
                "Path": "D:\\InstallationFiles\\1071\\ArcGIS_Server_Windows_1071_169677.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27",
                "PatchesDir": "D:\\InstallationFiles\\1071\\ServerPatches"
            },
            "ServerDirectoriesRootLocation": "D:\\arcgisserver\\directories",
            "ConfigStoreLocation": "D:\\arcgisserver\\config-store"
        },
        "Portal": {
            "LicenseFilePath": "D:\\InstallationFiles\\1071\\ArcGIS_Enterprise_Portal_107_289384_20191127.json",
            "Installer": {
                "Path": "D:\\InstallationFiles\\1071\\Portal_for_ArcGIS_Windows_1071_169688.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\Portal",
                "ContentDir": "D:\\",
                "PatchesDir": "D:\\InstallationFiles\\1071\\PortalPatches"
            },
            "ContentDirectoryLocation": "D:\\arcgisportal\\content"
        },

**Comment by cameronkroeker** [comment]
@kphaneuf 

Can you re-run it but this time instead of `-Mode Upgrade` try `-Mode Install`? Also, try adding the
` -DebugSwitch` parameter as well.

**Comment by pcsswamin** [comment]
@kphaneuf, @cameronkroeker ,
I am not seeing the patch install dsc resource being called in the server upgrade configuration. Would expect it around here - https://github.com/Esri/arcgis-powershell-dsc/blob/e06c6e3ba5f31707cce916a693c825bd616ec3f3/Modules/ArcGIS/Configurations-OnPrem/Upgrades/ServerUpgrade.ps1#L62

This would be good enhancement request or custom edit. Users would want patches to be applied as soon as upgrade is completed.

**Comment by kphaneuf** [comment]
Running the -Mode Install and it appears to be installing the patches.

**Comment by kphaneuf** [comment]
All patches were installed when run with -mode Install.

**Comment by cameronkroeker** [comment]
Thanks @kphaneuf for confirming that `-mode install` did the trick.
