### ISSUE TITLE
Powershell does not support 10.8

### ISSUE THREAD

**Issue by dimesv** [Esri/arcgis-powershell-dsc#235]
Hi guys,

When will be included support for 10.8? I get an error that the version code is invalid.

Cheers,
Jose

**Comment by nshampur** [comment]
should be there later this week.

**Comment by dimesv** [comment]
Thanks Nikhil

**Comment by cameronkroeker** [comment]
@dimesv 

We are excited to announce that ArcGIS Module v3.0.0 has been officially released and supports 10.8:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.0.0

https://www.powershellgallery.com/packages/ArcGIS/3.0.0
