### ISSUE TITLE
Error Dot Sourcing the Configuration - ArcGISServer

### ISSUE THREAD

**Issue by dimesv** [Esri/arcgis-powershell-dsc#238]
Hi guys,

I am running into an issue when installing either base enterprise or a single arcgis server just at the end, after the licensing is done, when dot sourcing the ArcGIS Server configuration. See the attached log file for further details.

This error happens in file "C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.0.0\Configurations-OnPrem\ArcGISServer.ps1" line 115, but I think this is just because the .mof file is never created in the ArcGISServer folder when running the Invoke-DSCJob. Perhaps the reason for this is that it does not support domain accounts as the warnings included in the log indicate. I have tried to put the flag "PSDscAllowDomainUser" to suppress the warning and it did suppress it but the issue persisted. I haven't tried installing the software with a local account.

I appreciate that this version seems to be a major re-design of the old API but the older one seemed to work fine while this one is giving me a lot more trouble running it on the same environment.
[GISServer-General-Purpose-05-03-2020-14-53-57-PM.log](https://github.com/Esri/arcgis-powershell-dsc/files/4292344/GISServer-General-Purpose-05-03-2020-14-53-57-PM.log)

Can someone have a look into this?

**Comment by cameronkroeker** [comment]
@dimesv would you be able to provide the json file used? Feel free to scrub out all the sensitive information.

**Comment by dimesv** [comment]
@cameronkroeker ,

I've hidden some of the sensitive information and zipped the file. 
[GISServer-General-Purpose.zip](https://github.com/Esri/arcgis-powershell-dsc/files/4295228/GISServer-General-Purpose.zip)

Let me know what you think.

**Comment by dimesv** [comment]
Thanks @cameronkroeker , that was the issue. Without the server directories it fails.
It still throws the warning below so perhaps you could just add the flag PSDscAllowDomainUser to $true above every PSDscAllowPlainTextPassword that you already have in place? This would remove this warning.
 
"WARNING: It is not recommended to use domain credential for node '2108-jvs.etgnz.eagle.co.nz'. In order to suppress the warning, you can add a property named 'PSDscAllowDomainUser' with a value of $true to your 
DSC configuration data for node '2108-jvs.etgnz.eagle.co.nz'."

**Comment by cameronkroeker** [comment]
@dimesv 

**"ServerDirectories"** is now optional and will no longer throw an error if not included in the json file. Fixed in v3.0.1.
