### ISSUE TITLE
Error:  Unrecognized user license type id

### ISSUE THREAD

**Issue by aaron1uk** [Esri/arcgis-powershell-dsc#239]
I'm not sure if this is a bug or my inexperience is the issue.

I seem to be having an issue PortalLicenseUserTypeId field.

I've tried "Creator", "CreatorUT" and "Administrator. All throw the above error. Am I being an idiot or is something wrong here?

Should point out trying to install 10.7.1 on a single machine build over VMs

**Comment by cameronkroeker** [comment]
@aaron1uk I believe it's case sensitive. Try "creatorUT". 

If you open the Portal Authorization json file with a text editor you will see all the available options.

**Comment by aaron1uk** [comment]
Ah what a classic, moved on to another error now regarding a default user to enable automatic account creation, didn't think that was required if "EnableAutomaticAccountCreation" was set to flase?

` Set-PortalSecurityConfig Response:- A default user type id must be specified to enable automatic account creation for your Enterprise portal. 
The SendConfigurationApply function did not succeed.
`

**Comment by cameronkroeker** [comment]
@aaron1uk 

Glad to hear the original issue is resolved. Could you open a new issue for the default user type error? That way this one can be closed since they are two separate issues. In the new thread could sgare your json file (scrub out sensitive info)?

Thanks,
Cameron K.
