### ISSUE TITLE
Please document the parameter "MappedDriveOverrideFlag"

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#240]
Hi guys

The new parameter "MappedDriveOverrideFlag" is nowhere documented, at least that's what a github-repo-search brought up.

I had a look at the underlying code and have an idea, what this parameter is about.
But rather than guessing, I would prefer to get this info legitimized from you.

Thanks a lot in advance! Your work is much appreciated!

P.S.: BTW, a variable in the variable reference that would greatly benefit from an example-value in the documentation is "PortalLicenseUserTypeId". As of right now, it is not clear, if the form aligns with those from the variable "DefaultUserLicenseTypeIdForUser" (it is not, to my knowledge), which additionally is confusing.

P.P.S.: There is a (small) typo in a lot but not all of the Scenario-descriptions in the documentation. It says "Debu**d**Switch" instead of "Debu**g**Switch", which could lead to copy/paste-errors.

**Comment by scma-esrich** [comment]
@spitzerr, FYI.

**Comment by scma-esrich** [comment]
One other addition:
On the landing-page (see https://esri.github.io/arcgis-powershell-dsc/) the version-hint "What's new" still references to the 10.7.1 version:
![image](https://user-images.githubusercontent.com/45851791/76220534-ee4cc580-6217-11ea-96ab-b0f1df216649.png)

**Comment by cameronkroeker** [comment]
Thanks @scma-esrich for the feedback! 

We've updated the following items:

-  [Welcome to Windows PowerShell DSC](https://esri.github.io/arcgis-powershell-dsc/) page.

- `DebugSwitch` typo in Scenario descriptions.

- `PortalLicenseUserTypeId` definition to include examples in the [Variables Reference](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files) page.

As for the `MappedDriveOverrideFlag` this is for referencing Network Mapped drive paths within the json file for setups/authorization/certificate files. We will look to improve this.

**Comment by scma-esrich** [comment]
Thanks a lot for your quick response!

**Comment by Biboba** [comment]
Also, on the mentioned above [landing-page](https://esri.github.io/arcgis-powershell-dsc/)), the link 'What is Windows PowerShell DSC?' is broken (404 error).
Thanks

**Comment by cameronkroeker** [comment]
> Also, on the mentioned above [landing-page](https://esri.github.io/arcgis-powershell-dsc/), the link 'What is Windows PowerShell DSC?' is broken (404 error).
> Thanks

Great catch @Biboba! Thanks for letting us know, we will get this updated and I'll let you know when its fixed.

**Comment by cameronkroeker** [comment]
@scma-esrich 

A  new wiki page has been created defining `-MappedDriveOverrideFlag` as well as all the other available parameters.

https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters

**Comment by scma-esrich** [comment]
@cameronkroeker, that's way better! Thank you!

One little detail is remaining for me:
Could you explain a little further, what the Credential-parameter is for? I always get questions from customers, which steps in the DSC-process the "Credential"-parameter is used for.

**Comment by cameronkroeker** [comment]
> @cameronkroeker, that's way better! Thank you!
> 
> One little detail is remaining for me:
> Could you explain a little further, what the Credential-parameter is for? I always get questions from customers, which steps in the DSC-process the "Credential"-parameter is used for.

@scma-esrich apologies for the delayed response. Hope this helps:

When the `-Credential` parameter is used the module will start the job as the account specified in the `-Credential` parameter on the target machine to gather information from the other target machines, but the actual DSC resources will still run as local user account on the machine. An example of when to use the `-Credential` parameter is if we start the PowerShell cmdlet as user A and User A doesn't have permissions on the target machine then we can pass the `-Credential` parameter with User B that does have the correct permissions.

**Comment by scma-esrich** [comment]
@cameronkroeker: Yes, that would be a very helpful explanation to our customers!
Do you plan on integrating it in the documentation?
