### ISSUE TITLE
Web Adaptor fails configuring

### ISSUE THREAD

**Issue by dimesv** [Esri/arcgis-powershell-dsc#241]
Hi guys,

I've tried installing Base Enterprise using V3 in two machines: one with the core components (portal, hosting and data store) and another machine with the web adaptor. 

The powershell module installs base enterprise without any issues (after putting the flag -NoNewWindow when running the installers) but when it tries to configure the web adaptor with ArcGIS Enterprise it fails. I have attached the log file.

What is interesting here, is that when I checked the web adaptors in IIS and in the install folders, almost nothing was there pretty much just the web.config file. So in fact, the installation of the web adaptors were not successful. But this is not what the log says. 

I've then installed the web adaptors on this same machine using the same Esri V3 powershell modules and it worked fine. The log produced was exactly the same.

This means that when the web adaptor fails to install, the Esri powershell module continues forward without validating whether the web adaptor is working OK or not.

I have also noticed that the wa install sometimes works and sometimes doesn't. Weird.

Not sure if you have experienced the same issue.

Log:
[BaseDeployment-12-03-2020-15-36-24-PM.log](https://github.com/Esri/arcgis-powershell-dsc/files/4326717/BaseDeployment-12-03-2020-15-36-24-PM.log)
.

**Comment by jhevenor** [comment]
I've just started updating to DSC v3 myself and am attempting a 2 VM server setup with the WA on each server.  I get to the end of the WA install and it hangs.  

```
[GEO-SBX-IMG1]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer] Operation 'Enumerate CimInstances' complete.
[GEO-SBX-IMG1]: LCM:  [ End    Test     ]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer]  in 0.3010 seconds.
[GEO-SBX-IMG1]: LCM:  [ Skip   Set      ]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer]
[GEO-SBX-IMG1]: LCM:  [ End    Resource ]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer]
[GEO-SBX-IMG1]: LCM:  [ End    Set      ]
[GEO-SBX-IMG1]: LCM:  [ End    Set      ]    in  1.1250 seconds.
Operation 'Invoke CimMethod' complete.
```

My template looks like:

```
 {
            "NodeName": "geo-sbx-img0.internal.com",
            "Role": [
                "Server",
                "ServerWebAdaptor"
            ],
            "PSDscAllowDomainUser": true,
            "SslCertificates":  [
                {
                    "Path":  "C:\\gis-deploy\\__cert.pfx",
                    "Password":  "********",
                    "Alias":  "sbxgis.domain.com",
                    "Target" :["WebAdaptor"]
                }
            ]
        },
```

**Comment by cameronkroeker** [comment]
> Hi guys,
> 
> I've tried installing Base Enterprise using V3 in two machines: one with the core components (portal, hosting and data store) and another machine with the web adaptor.
> 
> The powershell module installs base enterprise without any issues (after putting the flag -NoNewWindow when running the installers) but when it tries to configure the web adaptor with ArcGIS Enterprise it fails. I have attached the log file.
> 
> What is interesting here, is that when I checked the web adaptors in IIS and in the install folders, almost nothing was there pretty much just the web.config file. So in fact, the installation of the web adaptors were not successful. But this is not what the log says.
> 
> I've then installed the web adaptors on this same machine using the same Esri V3 powershell modules and it worked fine. The log produced was exactly the same.
> 
> This means that when the web adaptor fails to install, the Esri powershell module continues forward without validating whether the web adaptor is working OK or not.
> 
> I have also noticed that the wa install sometimes works and sometimes doesn't. Weird.
> 
> Not sure if you have experienced the same issue.
> 
> Log:
> [BaseDeployment-12-03-2020-15-36-24-PM.log](https://github.com/Esri/arcgis-powershell-dsc/files/4326717/BaseDeployment-12-03-2020-15-36-24-PM.log)
> .

@dimesv Very interesting. We have not come across this issue before. The time when the Web Adaptor didn't install correctly (or fully) were there any messages within the Windows Event Viewer?

**Comment by cameronkroeker** [comment]
> I've just started updating to DSC v3 myself and am attempting a 2 VM server setup with the WA on each server. I get to the end of the WA install and it hangs.
> 
> ```
> [GEO-SBX-IMG1]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer] Operation 'Enumerate CimInstances' complete.
> [GEO-SBX-IMG1]: LCM:  [ End    Test     ]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer]  in 0.3010 seconds.
> [GEO-SBX-IMG1]: LCM:  [ Skip   Set      ]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer]
> [GEO-SBX-IMG1]: LCM:  [ End    Resource ]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer]
> [GEO-SBX-IMG1]: LCM:  [ End    Set      ]
> [GEO-SBX-IMG1]: LCM:  [ End    Set      ]    in  1.1250 seconds.
> Operation 'Invoke CimMethod' complete.
> ```
> 
> My template looks like:
> 
> ```
>  {
>             "NodeName": "geo-sbx-img0.internal.com",
>             "Role": [
>                 "Server",
>                 "ServerWebAdaptor"
>             ],
>             "PSDscAllowDomainUser": true,
>             "SslCertificates":  [
>                 {
>                     "Path":  "C:\\gis-deploy\\__cert.pfx",
>                     "Password":  "********",
>                     "Alias":  "sbxgis.domain.com",
>                     "Target" :["WebAdaptor"]
>                 }
>             ]
>         },
> ```

Hi @jhevenor I think this should go in its own thread as it sounds like a separate issue. In the SSLCertificates block try updating `"Alias":  "sbxgis.domain.com",` to `"CNameFQDN":  "sbxgis.domain.com",`

If this doesn't resolve the issue please feel free to log this as a new issue. Thanks!

**Comment by jhevenor** [comment]
Thanks @cameronkroeker ,  I've had a few oddities and I'm not sure what's what.  Restarting the process. At first I thought that my use of `update-module` may have been the culprit, as it left 2 versions of esri dsc installed.  I've removed my WA components and I'm still freezing. Deleting and starting over at this point. 

So, ignore my stuff and I'll post something new once I narrow it down. Cheers,

**Comment by dimesv** [comment]
> Hi guys,
> I've tried installing Base Enterprise using V3 in two machines: one with the core components (portal, hosting and data store) and another machine with the web adaptor.
> The powershell module installs base enterprise without any issues (after putting the flag -NoNewWindow when running the installers) but when it tries to configure the web adaptor with ArcGIS Enterprise it fails. I have attached the log file.
> What is interesting here, is that when I checked the web adaptors in IIS and in the install folders, almost nothing was there pretty much just the web.config file. So in fact, the installation of the web adaptors were not successful. But this is not what the log says.
> I've then installed the web adaptors on this same machine using the same Esri V3 powershell modules and it worked fine. The log produced was exactly the same.
> This means that when the web adaptor fails to install, the Esri powershell module continues forward without validating whether the web adaptor is working OK or not.
> I have also noticed that the wa install sometimes works and sometimes doesn't. Weird.
> Not sure if you have experienced the same issue.
> Log:
> BaseDeployment-12-03-2020-15-36-24-PM.log
> .
> 
> @dimesv Very interesting. We have not come across this issue before. The time when the Web Adaptor didn't install correctly (or fully) were there any messages within the Windows Event Viewer?

Hi @cameronkroeker, I don't think there was any relevant messages in the WEM. I haven't been having this issue for a while now so I will ignore it for now. If it happens again, I will try to get more details, have a look into the Event Viewer and post it here.

Thanks for coming back to me.

**Comment by cameronkroeker** [comment]
Thanks @dimesv. I will close this for now but if the issue happens again feel free to reopen with additional details of the occurrence.
