### ISSUE TITLE
Server Bug

### ISSUE THREAD

**Issue by dimesv** [Esri/arcgis-powershell-dsc#242]
Hi guys,

There seems to be a bug in file "ArcGIS.psm1" line 995.
**Instead of:**
$IsServerWAOnSeparateMachine = ((**$AllNodes** | Where-Object { $_.NodeName -ine $WANode.NodeName } | Measure-Object).Count -gt 0)

**Should be:**
$IsServerWAOnSeparateMachine = ((**$ConfigurationParamsHashtable.AllNodes** | Where-Object { $_.NodeName -ine $WANode.NodeName } | Measure-Object).Count -gt 0)

This bug causes the variable $IsServerWAOnSeparateMachine to never evaluate to true even when the WA is effectively on a separate server.

This then causes line 1074 to get the wrong value assigned when installing only Server.
$ServerArgs["OpenFirewallPorts"] = ($PortalCheck -or $DataStoreCheck -or $IsServerWAOnSeparateMachine)

As a consequence of this, a firewall inbound rule is not added to the server to allow communications via 6443. For Base Enterprise everything works fine because the additional checks above make sure that the flag is set to true regardless of the bug.

Can you guys have a look?

See the attached log file with the error introduced by the code as it stands:
[GISServer-General-Purpose-13-03-2020-12-03-41-PM.log](https://github.com/Esri/arcgis-powershell-dsc/files/4327084/GISServer-General-Purpose-13-03-2020-12-03-41-PM.log)

Here is my current json template (i've hidden sensitive information):
[GISServer-General-Purpose - Copy.zip](https://github.com/Esri/arcgis-powershell-dsc/files/4327087/GISServer-General-Purpose.-.Copy.zip)

**Comment by cameronkroeker** [comment]
@dimesv this issue has been addressed in v3.0.1.

**Comment by dmjanssen** [comment]
I am seeing a similar problem when I use the GISServer-RasterAnalytics-fileshare.json sample config. The firewall rule is not getting created. Is this an issue again?
