### ISSUE TITLE
Question: Regarding DSC for existing deployment

### ISSUE THREAD

**Issue by mkarikari** [Esri/arcgis-powershell-dsc#244]
Hi I was hoping to get a little clarity. Can ArcGIS for DSC be used already existing deployment, under the assumption that he current state of our deployment already lines up with what is placed in configuration file. I'm trying to determine if if this type of solution can be introduced to an already existing system for handling upgrades and deploying new machines.

Appreciate any insight you can give.

**Comment by nshampur** [comment]
In theory Yes.  But the state of the deployment needs to **exactly** match what DSC would configure it as.

DSC is idempotent in that it will skip steps that it considers are already configured to what it expects.
I would only recommend trying this first on a test system.

**Comment by mkarikari** [comment]
Thanks for that answer, its much appreciated
