### ISSUE TITLE
ServiceAccount password not updated

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal
* DataStore

### Configuration Files

```
"ServiceAccount": {
	"Password": "foo",
	"UserName": "COMPANY\\serviceaccount",
	"IsDomainAccount": true
}
```
### Expected Behavior

I would expect the service account password to be updated with "foo" value.

### Actual Behavior

Password is not updated.

### Steps to Reproduce

1. Initialize your ArcGIS Enterprise with a company service account to run services
2. Change your company service account password
3. Update the password in the config and apply the config

=> Password is not updated

Is that doable ?  I understand that it should not be applied every time as it requires a reboot of the service but can somehow a password hash be compared so as to detect that password has changed ? 

It would be nice improvement =)

Thanks !

**Comment by cameronkroeker** [comment]
Thanks for the suggestion @Biboba. I have marked this as an enhancement and we will evaluate the request!

**Comment by Biboba** [comment]
Thanks for listening @cameronkroeker.
I just did a test with portal licence file and it did not update it as well. Is is an unsupported feature as well ?
Thanks

**Comment by cameronkroeker** [comment]
> Thanks for listening @cameronkroeker.
> I just did a test with portal licence file and it did not update it as well. Is is an unsupported feature as well ?
> Thanks

Hi @Biboba,

Updating the license is supported:

https://github.com/Esri/arcgis-powershell-dsc/issues/209#issuecomment-592646172

If this is not working please open a new issue, and if you could share the logs and json file (scrub out any sensitive info like passwords, etc) I'd be glad to help investigate.

Thanks!

**Comment by Biboba** [comment]
Thanks for the reply @cameronkroeker !
Did not know you you had to opt-in for that but reading your comment on now understand.
Once the parameter was added it worked. 
I am going to hide this discussion as it is not related to this issue. Sorry for that.

**Comment by Biboba** [comment]
Following #279, it would be nice support as well the update of service account and not only the password.

**Comment by cameronkroeker** [comment]
Hello @Biboba,

I'm excited to announce that this feature request has been added to v3.2.0!

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0

To use just add **ConfigData.Credentials.ServiceAccount.ForceUpdate** = true to your json config file.

Thanks,
Cameron K.
