### ISSUE TITLE
Wiki update following #178

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* Wiki

[V3 Wiki](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files) is still mentioning V3.0.0 parameter "PrimarySiteAdmin" instead of "PortalAdministrator" in "Federation" part and it does not mention also the "PortalAdministrator" part in Portal node.
Maybe a distinction between v3.0.0 and v3.0.1 should be made ? 

Thanks

**Comment by cameronkroeker** [comment]
Thanks @Biboba. The wiki has been updated to reflect the new variable changes.
