### ISSUE TITLE
Register datastore on D drive fails

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* ArcGIS_DataStore

### Configuration Files

```
"DataStore": {
            "ContentDirectoryLocation": "D:\\arcgis\\arcgisdatastore",
            "Installer": {
                "Path": "\\\\pathtoSetup\\ArcGIS_DataStore_Windows_1071_169689.exe",
                "InstallDir": "C:\\Program Files\\Arcgis\\DataStore"
            }
        }
```

### Expected Behavior

Datastore should be successfully registered with hosted ArcGIS Server

### Actual Behavior

It fails with the following error:
```
PowerShell DSC resource ArcGIS_DataStore  failed to execute Set-TargetResource functionality with error message: Register Data Store Failed after multiple attempts. @{code=500; message=Configuration store is not configured correctly, or a bad configuration is being used.. Could not find file nulletc\arcgis-data-store-config.json.; details=}
```
More details from verbose:
```
Restarted Service 'ArcGIS Data Store'
Waiting for Url https://datastore01.company.com:2443/arcgis/datastoreadmin/configure?f=json
[Warning]:- Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
Url is OK
Waiting for Url https://agshosted01.company.com:6443/arcgis/admin
Url is OK
Ensure the Publishing GP Service (Tool) is started on Server
Service Status :- @{configuredState=STARTED; realTimeState=STARTED}
POST https://localhost:2443/arcgis/datastoreadmin/configure with 253-byte payload
received -1-byte response of content type application/json;charset=UTF-8
Response:- {"currentVersion":"10.7.1","relational":{"configureRole":"PRIMARY"},"tileCache":{"configureRole":"PRIMARY"},"spatioTemporal":{"configureRole":"BIGDATA_ONLY"},"defaultContentDirectory":"C:\\arcgisdatastore"}
Checking if Relational Datastore is registered
The machine with FQDN 'datastore01.company.com' does NOT participates in a registered 'Relational' data store
Registering datastores Relational
Adding Relational as a data store type
Register DataStore at https://localhost:2443/arcgis/datastoreadmin with DataStore Content directory at D:\arcgis\arcgisdatastore for server https://agshosted01.company.com:6443/arcgis
Register DataStore Attempt 1
Register DataStore on Machine datastore01.company.com
POST https://localhost:2443/arcgis/datastoreadmin/configure with 233-byte payload
received -1-byte response of content type application/json;charset=UTF-8
Response:- {"error":{"code":500,"message":"Configuration store is not configured correctly, or a bad configuration is being used.. Could not find file nulletc\\arcgis-data-store-config.json.","details":null}}
Error Response - @{code=500; message=Configuration store is not configured correctly, or a bad configuration is being used.. Could not find file nulletc\arcgis-data-store-config.json.; details=}
[WARNING]:- ERROR: failed. Configuration store is not configured correctly, or a bad configuration is being used.. Could not find file nulletc\arcgis-data-store-config.json.
Attempt [1] Failed. Retrying after 30 seconds

[...] It retries 5 times with the same results

[WARNING]:- ERROR: failed. Configuration store is not configured correctly, or a bad configuration is being used.. Could not find file nulletc\arcgis-data-store-config.json.
```

Additional information:
- In the configuration, there are 2 servers for 2 datastores (relational and tileCache): same happens for both.

- An interesting fact is that, after DSC failure, if I log on the VM and open the 'Data Store Configuration Wizard' in IE, I specify 'GIS Server URL', 'username', 'password' then next, and in 'Specify Content Directory' step, I enter 'D:\arcgis\arcgisdatastore' and next, it works: the POST operation to:
'https://localhost:2443/arcgis/datastoreadmin/configure'
is successfull.
Then I exit the wizard without specifying the datastore type, run DSC configuration, and it works.

- Registering the datastore on 'C:\arcgis\arcgisdatastore' works

### Steps to Reproduce

Try to deploy a configuration with a datastore content directory on D drive (cf. configuration above)

### Important Factoids

VMs are running in Openstack private cloud

Thanks for your help !

**Comment by Biboba** [comment]
Hi @cameronkroeker,

Thanks for having a look at this issue.
Here is the config file:
[AnonymousDeployment_3_1.txt](https://github.com/Esri/arcgis-powershell-dsc/files/4446234/AnonymousDeployment_3_1.txt)

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker,
> 
> Thanks for having a look at this issue.
> Here is the config file:
> [AnonymousDeployment_3_1.txt](https://github.com/Esri/arcgis-powershell-dsc/files/4446234/AnonymousDeployment_3_1.txt)

Thanks @Biboba. The json file looks valid, I only see two potential issues but both are in the portal block and shouldn't impact datastore. I recommend updating the following two parameter's:

`"PortalLicenseUserType": "GIS Professional Advanced",`

```
"PortalAdministrator": {
				"UserName": "user",
				"Email": "user@company.com",
				"Password": "password"
			},
```

**to**

`"PortalLicenseUserTypeId": "GISProfessionalAdvUT",`
```
"PortalAdministrator": {
				"UserName": "user",
				"Email": "user@company.com",
				"Password": "password",
                                "SecurityQuestionIndex": 1,
                                "SecurityAnswer": "vanilla"
			},
```

As for the Data Store issue I'm still not quite sure what could have caused it. Perhaps this is a one off or has this issue occurred more than once? Is there any additional information provided in the DSC logs?

**Comment by Biboba** [comment]
Thanks for investigating.
I was not able to reproduce it as well so it might have been a temporary issue on my side.
Apologize for the noise then.

**Comment by cameronkroeker** [comment]
> Thanks for investigating.
> I was not able to reproduce it as well so it might have been a temporary issue on my side.
> Apologize for the noise then.

Thanks @Biboba glad to hear it was a temporary issue!
