### ISSUE TITLE
Wiki update: PortalAdministrator SecurityQuestionIndex

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* Wiki: would be nice to have a link from the [wiki](https://github.com/Esri/arcgis-powershell-dsc/wiki/v3.0.1-ArcGIS-Server-Primary-Administrator-Account-and-Portal-for-ArcGIS-Initial-Administrator-Account-variables) to the mapping of the security question. I found it there:
https://developers.arcgis.com/rest/enterprise-administration/portal/create-site.htm

Thanks !

**Comment by cameronkroeker** [comment]
Thanks @Biboba for the recommendation. It has been added to the wiki:

https://github.com/Esri/arcgis-powershell-dsc/wiki/ArcGIS-Server-Primary-Administrator-Account-and-Portal-for-ArcGIS-Initial-Administrator-Account-variables#security-question-index-list

**Comment by joekayaker** [comment]
The V3 documentation, [Variables Reference Page](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files) - Portal section, is missing information about the Portal Administrator "SecurityQuestionIndex" values that are acceptable. They are available on the [ArcGIS Server Primary Administrator Account and Portal for ArcGIS Initial Administrator Account variables](https://github.com/Esri/arcgis-powershell-dsc/wiki/ArcGIS-Server-Primary-Administrator-Account-and-Portal-for-ArcGIS-Initial-Administrator-Account-variables#security-question-index-list) page, which links off to the [Secret questions & indexes](https://developers.arcgis.com/rest/enterprise-administration/portal/create-site.htm) page, but should be included in the [Variables Reference Page](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files) documentation.
