### ISSUE TITLE
Upgrading ArcGIS Enterprise to 10.8 finishes with an error with version 3.0.1

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* ArcGIS_DataStore ?

### Configuration Files

[AnonymousDeployment.txt](https://github.com/Esri/arcgis-powershell-dsc/files/4535448/AnonymousDeployment.txt)

### Expected Behavior

I would expect the upgrade from 10.7.1 to 10.8 to complete successfully without any error at the end.

### Actual Behavior

I believe upgrade completed successfully but it returned an error after having successfully upgrade the 2 datastores as if it wanted to process a third datastore which does not exist. Everything seems to be working fine on the upgraded ArcGIS Enterprise and I think 'DataStoreUpgradeConfigure' is the last step so it's OK but it's not very nice not being sure that everything went as expected. 

I don't think it comes from my config but maybe ?

Here are the last outputs from upgrade process:

```
Dot Sourcing the Configuration:- DataStoreUpgradeConfigure
VERBOSE: ags01
Starting DSC Job:- DataStoreUpgradeConfigure
VERBOSE: Time taken for configuration job to complete is 0.003 seconds
[STORE01]: LCM:  [ Start  Set      ]
[STORE01]: LCM:  [ Start  Resource ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]
[STORE01]: LCM:  [ Start  Test     ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]
[STORE01]: LCM:  [ End    Test     ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]  in 6.0940 seconds.
[STORE01]: LCM:  [ Start  Set      ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]
[STORE01]: LCM:  [ End    Set      ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]  in 172.2030 seconds.
[STORE01]: LCM:  [ End    Resource ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]
[STORE01]: LCM:  [ End    Set      ]
[STORE01]: LCM:  [ End    Set      ]    in  178.5310 seconds.
Logs Directory: C:\Users\foo\Logs
Finished DSC Job:- DataStoreUpgradeConfigure. Time Taken - 00:03:00.0494907
DataStoreUpgradeConfigure - Completed
Dot Sourcing the Configuration:- DataStoreUpgradeConfigure
VERBOSE: ags01
Starting DSC Job:- DataStoreUpgradeConfigure
VERBOSE: Time taken for configuration job to complete is 0.003 seconds
[STORE02]: LCM:  [ Start  Set      ]
[STORE02]: LCM:  [ Start  Resource ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]
[STORE02]: LCM:  [ Start  Test     ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]
[STORE02]: LCM:  [ End    Test     ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]  in 21.6250 seconds.
[STORE02]: LCM:  [ Start  Set      ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]
[STORE02]: LCM:  [ End    Set      ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]  in 69.4500 seconds.
[STORE02]: LCM:  [ End    Resource ]  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade]
[STORE02]: LCM:  [ End    Set      ]
[STORE02]: LCM:  [ End    Set      ]    in  91.5600 seconds.
Logs Directory: C:\Users\foo\Logs
Finished DSC Job:- DataStoreUpgradeConfigure. Time Taken - 00:01:35.0342015
DataStoreUpgradeConfigure - Completed
Dot Sourcing the Configuration:- DataStoreUpgradeConfigure
Starting DSC Job:- DataStoreUpgradeConfigure
Start-DscConfiguration : The computer name was not specified and the configuration directory does not have any configuration files.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:232 char:29
+ ... redential){ Start-DscConfiguration -Path ".\$($ConfigurationName)" -F ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-DscConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDscConfigurationCommand
 
Logs Directory: C:\Users\foo\Logs
Finished DSC Job:- DataStoreUpgradeConfigure. Time Taken - 00:00:00.1043231
DataStoreUpgradeConfigure - 
```
### Steps to Reproduce

Using the attached config file, run the following command:
```
Invoke-ArcGISConfiguration -ConfigurationParametersFile pathTo\DeploymentUpgrade.json -Credential (Get-Credential) -Mode Upgrade 
```

Upgrade should be working fine finishing with the 2 datastores job "DataStoreUpgradeConfigure" completed successfully and then this error appears. I believe there is no other job to be run after that but we may wonder if it did not prevent the upgrade from additionnal steps

I faced this issue twice on two differerent environnement.

Thanks

**Comment by cameronkroeker** [comment]
@Biboba this has been fixed in v3.0.2. Please feel free to give that a try =)

**Comment by Biboba** [comment]
@cameronkroeker, I just successfully upgraded from 10.8 to 10.8.1 using 3.1.0 but this issue occurred again at the end.
Thanks

**Comment by cameronkroeker** [comment]
> @cameronkroeker, I just successfully upgraded from 10.8 to 10.8.1 using 3.1.0 but this issue occurred again at the end.
> Thanks

Hi @Biboba ,

Sorry to hear the issue happened again. May I ask which machine was the orchestrating machine?

Thanks,
Cameron K.

**Comment by Biboba** [comment]
Thanks for your reply @cameronkroeker.
It's my computer running Windows 10 Enterprise. What other information would you need ?
Thanks

**Comment by cameronkroeker** [comment]
> Thanks for your reply @cameronkroeker.
> It's my computer running Windows 10 Enterprise. What other information would you need ?
> Thanks

Thanks @Biboba The reason I asked is, I was not able to reproduce this when using one of the target nodes as the orchestrating machine. However, I will see if I can reproduce this when using my workstation as the orchestrating machine.

**Comment by cameronkroeker** [comment]
> > Thanks for your reply @cameronkroeker.
> > It's my computer running Windows 10 Enterprise. What other information would you need ?
> > Thanks
> 
> Thanks @Biboba The reason I asked is, I was not able to reproduce this when using one of the target nodes as the orchestrating machine. However, I will see if I can reproduce this when using my workstation as the orchestrating machine.

Hi @Biboba,

I am not quite sure what could be causing this issue. I was not able to reproduce it when using my workstation as the orchestrating machine. If you wish to investigate this issue further I recommend contacting Esri Technical Support as they would have the ability to screen share and take a look at the environment.

Thanks,
Cameron K.
