### ISSUE TITLE
ArcGIS_WebAdaptorInstall failed to execute

### ISSUE THREAD

**Issue by hmelendez** [Esri/arcgis-powershell-dsc#259]
I'm getting a fail to install for most components although they actually install. In the case of the WebAdaptor after the error, the deployment stops and does not configure the site.

> "Operation 'Invoke CimMethod' complete.
Trace-DSCJob : The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.0.1\ArcGIS.psm1:236 char:5
   Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
 CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
 FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob"
 

> 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* ArcGIS_WebAdaptorInstall
* ArcGIS_InstallPatch
* ArcGIS_Install

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```
[deployment.log](https://github.com/Esri/arcgis-powershell-dsc/files/4549834/deployment.log)
[BaseDeployment_AM.json.txt](https://github.com/Esri/arcgis-powershell-dsc/files/4549897/BaseDeployment_AM.json.txt)

**Comment by Biboba** [comment]
Is the "version" parameter correct ?

**Comment by hmelendez** [comment]
"Version":  "10.7.1" is what I'm deploying. I'm using the latest ArcGIS module available in the powershell galery.

**Comment by cameronkroeker** [comment]
Hi @hmelendez ,

Looks like the module is detecting that there are already multiple instances of the Web Adaptor installed:

```
[machine-name]: [[ArcGIS_WebAdaptorInstall]WebAdaptorInstallServer] Multiple Instances 
of Web Adaptor are already installed
```
I would check the Windows Programs and Features list and examine which Web Adaptors (versions and context names) are present. Were any of these ever previous manually installed/configured? They may need to be uninstalled, then see if the module is successful in reinstalling them.

Also, I notice that in your BaseDeployment_AM.json it has **"PrimarySiteAdmin"** parameter within the **"Credentials"** block. At v3.0.1 this has been separated into two parameters, one for ArcGIS Server (**PrimarySiteAdmin**), and one for Portal (**PortalAdministrator**):

https://github.com/Esri/arcgis-powershell-dsc/wiki/ArcGIS-Server-Primary-Administrator-Account-and-Portal-for-ArcGIS-Initial-Administrator-Account-variables#arcgis-module-v301-and-above

**Comment by hmelendez** [comment]
@cameronkroeker I have corrected the credentials block. I have run the setup more than once which is the reason for the Multiple Instances of Web Adaptor. The issue appears to be when getting confirmation that the item is installed. For example, the portal and server Web Adaptors do install and I can get to them in the browser to configure manually but the script fails to detect that they have been install and does not continue to set up the site. I have also uninstalled the Web Adaptors and re-run the script with the same outcome.

**Comment by cameronkroeker** [comment]
Thanks @hmelendez . This is odd indeed. A couple other items to note, I notice that there are the following parameters specified:

**"PatchesDir_DONT"**
**"WebStylesPath_DONT"**

Not sure if this is related to the issue but perhaps try removing these if not in use.

Also, the module no longer uses the third party 7Zip tool to extract the setup archive files, therefore **"SevenZipInstallerPath"** can also be removed.

With these updated changes could you submit fresh DSC logs along with the newly updated json file?

Thanks!

**Comment by cameronkroeker** [comment]
Hello @hmelendez ,

Are you still running into this issue? If so, perhaps try with the latest release v3.1.0. If issue is still occurring please feel free to re-open and we can re-investigate it.

Thanks,
Cameron K
