### ISSUE TITLE
Clarify wiki for EnableFailoverOnPrimaryStop DataStore parameter

### ISSUE THREAD

**Issue by joekayaker** [Esri/arcgis-powershell-dsc#261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* ArcGIS_DataStore EnableFailoverOnPrimaryStop Documentation

### Wiki Documentation

The V3 documentation, [Variables Reference Page - DataStore](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files) section, "EnableFailoverOnPrimaryStop" parameter could be clarified to state "Use blank if you do not have a failover system. Use False if you have a system and do not want to automatically failover." The documentation currently doesn't provide clear instructions for someone who doesn't have a failover system in place.

**Comment by cameronkroeker** [comment]
Modified the definition of EnableFailoverOnPrimaryStop in the variable wiki page.

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files

**EnableFailoverOnPrimaryStop** - (Optional) Boolean (true|false). Set to true to enable failover to secondary when primary datastore is stopped. The default is false.

**Comment by Biboba** [comment]
@cameronkroeker, could you please point me to the relevant official datastore documentation about what is this parameter is doing ?
I was not able to find anything and to me this option should be set to true by default. I don't see the point of having HA deployment with this parameter is false ? Am I missing anything ? Thanks !

**Comment by cameronkroeker** [comment]
> @cameronkroeker, could you please point me to the relevant official datastore documentation about what is this parameter is doing ?
> I was not able to find anything and to me this option should be set to true by default. I don't see the point of having HA deployment with this parameter is false ? Am I missing anything ? Thanks !

Hi @Biboba ,

The explanation for your second point is described as:

"By default, stopping the primary relational data store machine does not cause the data store to fail over in an on-premises deployment, as you may not want to fail over if you are performing a maintenance task, such as temporarily taking the data store offline":

https://enterprise.arcgis.com/en/portal/latest/administer/windows/data-store-function-reference.htm#ESRI_SECTION1_C02AFE5FB9564837ACB9662D59DF33F2

And in the "Failover scenarios for relational data stores" section of the following doc it describes a bit more about the default behavior (human initiated versus hardware/software failures):

https://enterprise.arcgis.com/en/portal/latest/administer/windows/add-standby-machine.htm#ESRI_SECTION1_39B889D99635448CB901792F0DF80EE3

The EnableFailoverOnPrimaryStop parameter changes the setting within C:\\Program Files\\ArcGIS\\DataStore\\framework\\etc\\datastore.properties:
```
# When failover_on_primary_stop is set true, failover will take place when the primary
# machine is stopped. Default is false.
failover_on_primary_stop=false
```

**Comment by Biboba** [comment]
@cameronkroeker  Many thanks for these explanations !
