### ISSUE TITLE
Clarify wiki for DefaultUserLicenseTypeIdForUser Portal parameter

### ISSUE THREAD

**Issue by joekayaker** [Esri/arcgis-powershell-dsc#262]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* ArcGIS_Portal "DefaultUserLicenseTypeIdForUser"
* BaseDeployment-SingleMachine.json
* BaseDeployment-SingleMachine-CloudStore.json

### Wiki Documentation

The documentation and the sample json files for "singleMachine" do not include "viewerUT" as an option for "DefaultUserLicenseTypeIdForUser" within the Portal parameters. According to this [User types, roles, and privileges](https://enterprise.arcgis.com/en/portal/latest/administer/windows/roles.htm) page it should be.

**Is "viewerUT" a valid option?**

If yes, it should be included in the wiki page and the sample json files.

**Comment by cameronkroeker** [comment]
@joekayaker. Yes, good catch. Acceptable values are:

The ID of a user type licensed with your organization. To see which user types are included with your organization's licensing, see the [License](https://developers.arcgis.com/rest/enterprise-administration/portal/license.htm) resource in the Portal Admin API.

Values: creatorUT | editorUT | GISProfessionalAdvUT | GISProfessionalBasicUT | GISProfessionalStdUT | viewerUT | fieldWorkerUT |

https://developers.arcgis.com/rest/users-groups-and-items/set-user-default-settings.htm

**Comment by joekayaker** [comment]
@cameronkroeker thanks for the quick answer! Can you label this as an 'Enhancement'?

**Comment by cameronkroeker** [comment]
addressed in v3.0.2
