### ISSUE TITLE
Invalid GISServer-GenerlPurpose config with 3.01

### ISSUE THREAD

**Issue by mkarikari** [Esri/arcgis-powershell-dsc#264]
Im attempting to run upgrade on existing install using the GISServer-GeneralPurpose.json,, but it returns the following error. Not sure why I would have to specify a Portal config if this is suppose to be for standalone instance of ArcGIS Server, or am I incorrect?
![image](https://user-images.githubusercontent.com/19801488/81321518-ac49cf80-9060-11ea-9a7a-b2f3c60c433d.png)

**Comment by mkarikari** [comment]
Also, when I do add some dummy values for the Portal cred variable, im able get pass the error but hangs at the following step. I dont see any logs to provide context to why it is hanging at this point.

![image](https://user-images.githubusercontent.com/19801488/81324699-562b5b00-9065-11ea-9648-f523c8882f33.png)

**Comment by Biboba** [comment]
I believe it is a duplicate of #255

**Comment by mkarikari** [comment]
Ah gotcha thanks, I will close this out and add my agreement that the one that is already open, thanks
