### ISSUE TITLE
Installing Multiple ArcGIS Server Sites with one config file

### ISSUE THREAD

**Issue by mkarikari** [Esri/arcgis-powershell-dsc#265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.0

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "tstserver.test",
            "Role": [
                "Server"
            ]
        },
		{
            "NodeName": "monserver.test",
            "Role": [
                "Server"
            ]
        }
    ],
```

### Expected Behavior

I was expecting that if I want to install multiple arcgis server sites on multipe machines I could just provide the FQDNs of the servers and would install them independently.

### Actual Behavior

It returns following error:
```
One or both of Config Store Location and Server Directories Root Location is not a fileshare path
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:640 char:21
+ ...             throw "One or both of Config Store Location and Server Di ...
```
In my case I dont wish to configure a multimachine site, so the need for UNC path isn't needed. Is there a way to work around this?

**Comment by pcsswamin** [comment]
I ran into the same in 2.x module. I need the same enhancement. I say 'enhancement' because at least in the 2.x version, the logic is working as the code is written. It is an overlooked use case which is very common - for example Installing patches across multiple ArcGIS Servers.

**Comment by mkarikari** [comment]
@cameronkroeker or @shailesh91  are there any work arounds that may allow me to run a single config for multiple arcgis server site installs? Just trying to figure out if I should look at other methods for handling that specific workflow.

Thanks

**Comment by cameronkroeker** [comment]
Hello @mkarikari,

In the next release we are looking at providing partial support for this. By this I mean the module will allow `-Mode Install` or `-Mode InstallLicense` which can be used to install and authorize ArcGIS Server on more than one node. 

@pcsswamin This should also help with installing patches across multiple ArcGIS Servers.

https://github.com/Esri/arcgis-powershell-dsc/issues/233

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Partial support has been added in v3.0.2.

`-Mode Install` and `-Mode InstallLicense` can be used to install/authorize/patch multiple ArcGIS Server nodes.
