### ISSUE TITLE
Installed ArcGIS Pro but not appearing in Programs and Features/Start menu

### ISSUE THREAD

**Issue by eanderson2030** [Esri/arcgis-powershell-dsc#266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.0

### Affected Resource(s)

* ArcGIS_Pro

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "MACHINENAME",
            "Role": [
                "Pro"
            ]
        }
    ],
    "ConfigData": {
        "ProVersion": "2.5",
        "Pro": {
            "AuthorizationType": "NAMED_USER",
            "BlockAddIns": "",
            "SoftwareClass": "",
            "AllUsers": "",
            "EnableEUEI": "True",
            "CheckForUpdatesAtStartup": "True",
            "Installer": {
                "Path": "\\\\SHARE\\gis\\software\\pro\\ArcGISPro_25_172639.exe",
                "InstallDir": "E:\\Programs\\ArcGIS\\Pro",
                "PatchesDir": ""
            }
        }
    }
}
```

### Expected Behavior

Install ArcGIS Pro, and be visible in Start menu and Window's Programs and Features menu. 

### Actual Behavior

Directory in E:/Programs/ArcGIS/Pro was created, and I can successfully navigate to the bin folder and find the exe. Software successfully launches as well. However, as noted, ArcGIS Pro does not appear in the Start menu nor in the Programs and Features.

Tested both Named User and Single Use with the same result, and also tested on two different server machines (both running Windows Server 2016 English) with the same result. 

Running the installation manually outside of PowerShell does not have this issue. 

### Steps to Reproduce

In Powershell ISE:

Invoke-ArcGISConfiguration "\\\SHARE\gis\powershell\gii\configs\Pro-Named.json" -Mode Install

**Comment by cameronkroeker** [comment]
Hello @eanderson2030 ,

I suspect the issue is related to missing or blank parameters during the installation. What values were used for `"BlockAddIns": "", "SoftwareClass": "", "AllUsers": "",`? If these are present in the json but left blank they still get passed during the silent install command which could cause this behavoir. 

We will be updating the Sample Json files in the next release. Here is a better sample:
```
{
    "AllNodes": [
        {
            "NodeName": "[Machine Name 1]",
            "Role": [
                "Pro"
            ]
        }
    ],
    "ConfigData": {
        "ProVersion": "[Version of ArcGIS Pro ]",
        "Pro": {
            "LicenseFilePath": "[License File Path - Pro ]",
            "AuthorizationType": "SINGLE_USE",
            "LockAuthSettings": "[ True(Default) | False ]",
            "BlockAddIns": "[0 (Default All Addins Allowed), 1 (Signed by CA), 2 (Esri Addins Only), 3 (Esri Addins Only from Admin Folder), 4 (No Addins Allowed), 5 (Only Addins from Addmin Folder)]",
            "SoftwareClass": "[Viewer | Editor | Professional]",
            "PortalList": "[List of Portals for Pro]",
            "AllUsers": "[1 (Per Machine Install), 2 (Default Per User Install]",
            "EnableEUEI": "[ True (Default enables participation of Esri User Experience Improvement Program) | False]",
            "CheckForUpdatesAtStartup": "[ True (Default enables automatic update notifications of ArcGIS Pro) | False ]",
            "Installer": {
                "Path": "[Pro Installer Path]",
                "InstallDir": "[Pro Install Dir - Ex. C:\\ArcGIS\\Pro]",
                "PatchesDir": ""
            }
        }
    }
}
```

**Comment by eanderson2030** [comment]
Hi @cameronkroeker ,

Thanks for the response. I tested what you suggested with the Single Use config, however, it has the same issue. I'm open to any other suggestions you may have. Thank you!

`{
    "AllNodes": [
        {
            "NodeName": "MACHINENAME",
            "Role": [
                "Pro"
            ]
        }
    ],
    "ConfigData": {
        "ProVersion": "2.5",
        "Pro": {
            "LicenseFilePath": "\\\\SHARE\\gis\\software\\_licenses\\ArcGISProAdvanced_SingleUse_570626",
            "AuthorizationType": "SINGLE_USE",
            "LockAuthSettings": "True",
            "BlockAddIns": "0",
            "SoftwareClass": "Professional",
            "PortalList": "https://www.arcgis.com",
            "AllUsers": "2",
            "EnableEUEI": "True",
            "CheckForUpdatesAtStartup": "True",
            "Installer": {
                "Path": "\\\\SHARE\\gis\\software\\pro\\ArcGISPro_25_172639.exe",
                "InstallDir": "E:\\Programs\\ArcGIS\\Pro",
                "PatchesDir": ""
            }
        }
    }
}`

**Comment by cameronkroeker** [comment]
Hi @eanderson2030 ,

For the parameters that are boolean, true|false, let's remove the double quotes. For example:
```
"LockAuthSettings": True,
"EnableEUEI": True,
"CheckForUpdatesAtStartup": True,
```

Also, if not passing in a directory for `"PatchesDir": "",` let's remove that as well.

**Comment by eanderson2030** [comment]
Hey @cameronkroeker ,

Good catch on the license file extension, I tested adding the extension first without making the other changes you suggested, however, it had the same issue. Guess that makes sense since I'm seeing the issue using either the Pro-Named or Pro-SingleUse config. 

When I make the suggestion to remove the double-quotes around the boolean parameters, I get the following:

```
ConvertFrom-Json : Invalid JSON primitive: True.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:589 char:45
+ ...  $ConfigurationParamsJSON = (ConvertFrom-Json (Get-Content $cf -Raw))
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

**Comment by cameronkroeker** [comment]
> Hey @cameronkroeker ,
> 
> Good catch on the license file extension, I tested adding the extension first without making the other changes you suggested, however, it had the same issue. Guess that makes sense since I'm seeing the issue using either the Pro-Named or Pro-SingleUse config.
> 
> When I make the suggestion to remove the double-quotes around the boolean parameters, I get the following:
> 
> ```
> ConvertFrom-Json : Invalid JSON primitive: True.
> At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:589 char:45
> + ...  $ConfigurationParamsJSON = (ConvertFrom-Json (Get-Content $cf -Raw))
> +                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
>     + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
> ```

My apologies @eanderson2030, I forgot json is case sensitive. The boolean values need to be all lowercase and without quotes.

Try:
```
"LockAuthSettings": true,
"EnableEUEI": true,
"CheckForUpdatesAtStartup": true,
```

**Comment by eanderson2030** [comment]
Hey @cameronkroeker 

Thanks again for your help. I actually just had some success and was able to resolve this by setting AllUsers to "1", instead of the default of "2".

**Comment by cameronkroeker** [comment]
> Hey @cameronkroeker
> 
> Thanks again for your help. I actually just had some success and was able to resolve this by setting AllUsers to "1", instead of the default of "2".

Thanks @eanderson2030 for this clue. We found when using per user installation option (AllUsers=2), the module is installing Pro as NT Authority\System account rather than the Current User. This is why the installation appears to be incomplete because its getting installed into the LocalSystem registry/profile rather than the Current User (therefore current user wont be able to see the start menu shortcuts or listed in Programs List of Control Panel). So for now it is best to use per machine installation option (AllUsers=1). 

In the next release we will push a change that will only allow per machine installations to prevent this confusion of the installation being incomplete. And for future releases We will also evaluate adding a parameter to each individual dsc resources to allow for installation to be by a specific user rather than NT Authority\System:

https://powershell.org/forums/topic/running-an-entire-dsc-configuration-as-a-user-with-admin-rights/

**Comment by eanderson2030** [comment]
Excellent, thanks for the explanation @cameronkroeker and glad to hear you and the team will be making changes in the future to prevent this confusing issue. Thanks again for the responsive and helpful support.
