### ISSUE TITLE
Hostname.properties issue with 10.6.1 ArcGIS Server Configure

### ISSUE THREAD

**Issue by mkarikari** [Esri/arcgis-powershell-dsc#271]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.2

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

```
      "ServerDirectoriesRootLocation": "\\\\networkshare\\test\\arcgis\\ags\\arcgisserver\\directories",
       "ConfigStoreLocation": "\\\\networkshare\\test\\arcgis\\ags\\arcgisserver\\config-store"
```

### Expected Behavior

Expect the configuration **not** to try to create folders on a non-existent volume.  

### Actual Behavior

PowerShell DSC resource ArcGIS_Server  failed to execute Set-TargetResource functionality with error message: CreateSite Failed. Error:- Failed 
to create the site. Configuration store error. File system 'D:\arcgisserver\local\config-store' connection failed. The specified location is not accessible. 
Ensure that the ArcGIS Server account has read and write access to the location.  
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:239 char:5

### Important Factoids
Running in AWS gov-cloud, D volume was replaced with E volume prior to running install. I saw similar reference to this issue in other post, but it wasnt clear to me if this was address within tool or documented workaround

**Comment by cameronkroeker** [comment]
@mkarikari 

Try specifying the following parameter in the json file:

**LocalRepositoryPath** - (Optional) Directory where the local config-store is stored when site is in read-only mode.

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files

Here is an example:
```
"Server":  {
            "ServerDirectoriesRootLocation":  "C:\\arcgisserver\\directories",
            "ConfigStoreLocation":  "C:\\arcgisserver\\config-store",
	    "LocalRepositoryPath": "C:\\arcgisserver\\local",
	    "ServerLogsLocation":"C:\\arcgisserver\\logs"
           },
```

**Comment by mkarikari** [comment]
That was it, much appreciated on the quick response!
