### ISSUE TITLE
powershell v3 prompting for credentials

### ISSUE THREAD

**Issue by lachlanwainwright** [Esri/arcgis-powershell-dsc#274]
Hi
We are using v3 to perform a 10.7.1 multi machine install and it's failing on the Configuration by:
1. asking for credentials via a powershell credential request, am unsure what credentials it's asking for.
2. entering nothing the following below is returned. You can see the request for siteadmin creds.

I ran again and entered the siteadmin username and password and so far so good, It prompted again when it needed the creds for portal.

Keep you posted.  

Note, the config worked perfectly using the older version of powershell as it rolled through on many many multimachine installs. 

-----------
Logs Directory: C:\Users\wainwrla_a\Logs
Finished DSC Job:- ArcGISLicense. Time Taken - 00:00:05.0598878
ArcGISLicense - Completed
Dot Sourcing the Configuration:- ArcGISServer
ArcGISServer : C**annot validate argument on parameter 'ServerPrimarySiteAdminCredential'. The argument** is null or empty. Provide an argument that is not null or empty, and 
then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.0.2\ArcGIS.psm1:226 char:25
+     &$ConfigurationName @Arguments -Verbose
+                         ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ArcGISServer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,ArcGISServer
 
Starting DSC Job:- ArcGISServer
Start-DscConfiguration : .\ArcGISServer is not a valid directory.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.0.2\ArcGIS.psm1:235 char:131
+ ... tial }else{ Start-DscConfiguration -Path ".\$($ConfigurationName)" -F ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-DscConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDscConfigurationCommand
 
Logs Directory: C:\Users\wainwrla_a\Logs
Finished DSC Job:- ArcGISServer. Time Taken - 00:00:00.0237520
ArcGISServer - 

==================================================
==================================================

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

**Comment by cameronkroeker** [comment]
@lachlanwainwright 

I recommend checking that the portal site administrator and arcgis server primary site administrator parameter(s) are defined correctly in your json file. They used to be defined as one parameter in the **ConfigData** **Credentials** block (v3.0.0 and below), but at v3.0.1 and above have been moved to separate parameters.

Here is a wiki that describes what to use for the different versions of the module:

https://github.com/Esri/arcgis-powershell-dsc/wiki/ArcGIS-Server-Primary-Administrator-Account-and-Portal-for-ArcGIS-Initial-Administrator-Account-variables

Hope this helps.

Thanks,
Cameron K.

**Comment by lachlanwainwright** [comment]
Hi Cameron

Thank you yet again.  Egg on my face big time!  I was told there were changes from v2 to v3 and I neglected to take that comment from JJ at ESRI on board.

I have updated the admin details and added a few of the new little extras and it's punching away perfectly.

Have a great weekend. 
Lachlan

**Comment by cameronkroeker** [comment]
@lachlanwainwright glad to hear that resolved your issue! Thanks, and have a great weekend as well.
