### ISSUE TITLE
Dead Link for 'PortalAdministrator'-documentation

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#281]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.0

### Affected Resource(s)

* Documentation

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

Documentation-links should work.

### Actual Behavior

Documentation-links for 'PortalAdministrator'-parameter don't work.

### Steps to Reproduce

* Go to https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files.
* Click on any of the two links in the 'PortalAdministrator'-parameter description, they both do not work outside of Esri ;-)

### Important Factoids

-

**Comment by cameronkroeker** [comment]
Good catch @scma-esrich. The links have been updated.

Thanks!
