### ISSUE TITLE
DSC resource ArcGIS_WebAdaptorInstall not found

### ISSUE THREAD

**Issue by marcolio** [Esri/arcgis-powershell-dsc#282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.0

### Affected Resource(s)

* ArcGIS_WebAdaptorInstall

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "<datastore host>",
            "DataStoreTypes": [
                "Relational",
                "SpatioTemporal"
            ],
            "Role": [
                "DataStore"
            ]
        },
        {
            "NodeName": "<portal host>",
            "Role": [
                "Portal",
                "PortalWebAdaptor"
            ]
        },
        {
            "NodeName": "<server host>",
            "Role": [
                "Server",
                "ServerWebAdaptor"
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.8.1",
	"OldVersion": "10.7.1",
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "Password": "######",
                "UserName": "DOMAIN\\arcsvr",
                "IsDomainAccount": true
            }
        },
        "Server": {
            "LicenseFilePath": "\\\\TESTCLIENT2\\Path\\to\\Downloads\\ArcGISEnterpriseInstall\\ArcGISGISServerStandard_StagingArcGISServer.pvrc",
            "Installer": {
                "Path": "\\\\TESTCLIENT2\\Path\\to\\Downloads\\ArcGISEnterpriseInstall\\ArcGIS_Server_Windows_1081_175203.exe",
                "InstallDir": "C:\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27"
            },
            "ServerDirectoriesRootLocation": "E:\\arcgisserver",
            "ConfigStoreLocation": "E:\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": "PRIMARY SITE ADMIN ACCOUNT",
                "Password": "########"
            }
        },
        "Portal": {
            "LicenseFilePath": "\\\\TESTCLIENT2\\Path\\to\\Downloads\\ArcGISEnterpriseInstall\\ArcGIS_Enterprise_Portal_1081_328857_20200825.json",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "\\\\TESTCLIENT2\\Path\\to\\Downloads\\ArcGISEnterpriseInstall\\Portal_for_ArcGIS_Windows_1081_175214.exe",
                "WebStylesPath": "\\\\TESTCLIENT2\\Path\\to\\Downloads\\ArcGISEnterpriseInstall\\Portal_for_ArcGIS_Web_Styles_Windows_1081_175215.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\Portal",
                "ContentDir": "E:\\arcgisportal"
            },
            "ContentDirectoryLocation": "E:\\arcgisportal\\content",
            "PortalAdministrator": {
                "UserName": "BUILT IN ADMIN ACCOUNT",
                "Email": "#####",
                "Password": "#####",
                "SecurityQuestionIndex": N,
                "SecurityAnswer": "#####"
            },
            "ExternalLoadBalancer": "gis2.TESTDOMAIN.com"
        },
        "DataStore": {
            "ContentDirectoryLocation": "E:\\arcgisdatastore",
            "EnableFailoverOnPrimaryStop": "False",
            "Installer": {
                "Path": "\\\\TESTCLIENT2\\Path\\to\\Downloads\\ArcGISEnterpriseInstall\\ArcGIS_DataStore_Windows_1081_175216.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\DataStore"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "\\\\TESTCLIENT2\\Path\\to\\Downloads\\ArcGISEnterpriseInstall\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_1081_175217.exe"
            }
        }
    }
}
```

### Expected Behavior

ArcGIS Enterprise was upgraded from 10.7.1. to 10.8.1. on a three machine base deployment.

### Actual Behavior

I got this error:
```
Trace-DSCJob : The PowerShell DSC resource ArcGIS_WebAdaptorInstall from module <ArcGIS,3.1.0> does not exist at the
PowerShell module path nor is it registered as a WMI DSC resource.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:241 char:5
```
### Steps to Reproduce

I ran this command:
```Invoke-ArcGISConfiguration -ConfigurationParametersFile .\TEST_BaseDeployment-ThreeMachine.json -Mode Upgrade```

### Important Factoids

- I originally installed with this JSON file using version 3.0.1 of the ArcGIS DSC module. 
- I upgraded to 3.1.0 since it seems that is necessary to install versions of Enterprise newer than 10.7.1.
- I modified the original "ConfigData" block to include the OldVersion element as directed in the upgrade instructions.
- I am setting the ExternalLoadBalancer variable. I was advised by ESRI support this was the only way to set a friendly name for my portal host. 
- I have a DNS A record that resolves gis2.testdomain.com to the IP of the actual host name.

### References
- I can see the web adaptor install file here: (as expected)
```C:\Program Files\WindowsPowerShell\Modules\ArcGIS\DSCResources\ArcGIS_WebAdaptorInstall\ArcGIS_WebAdaptorInstall.psm1```
- My PSModulePath includes this folder: %ProgramFiles%\WindowsPowerShell\Modules
- Instructions I followed indicating changes needed to config file.
https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Upgrade-an-ArcGIS-Enterprise-deployment

- Direction from ESRI regarding friendly name
"To set a DNS friendly name for Portal and Server you have to modify the arcgis-powershell-dsc script.
In the script, modify the ExternalLoadBalancer setting to the DNS Friendly name
With this workflow the user was able to run the powershell script to set the friendly name and successfully federate"

**Comment by shailesh91** [comment]
@marcolio Did you delete the v3.0.1 version of ArcGIS DSC module?

**Comment by marcolio** [comment]
Hi, thanks for the response. I saved a backup copy in a zip archive before I upgraded. I tried restoring the v.3.0.1 version of the module and re-running but it gave an error that the value "10.8.1" was not in a set of values which corresponded to available versions when 3.0.1 was released.

**Comment by shailesh91** [comment]
@marcolio you do need to delete the v3.0.1 version of the module. Replace the contents with V3.1.0. 
Your contents of the ArcGIS module should look like what's in the image below.
![image](https://user-images.githubusercontent.com/3657525/92025460-694cef80-ed14-11ea-96a6-68d486ebcc4d.png)

**Comment by marcolio** [comment]
Hi, sorry if my response was unclear. I archived the 3.0.1 version and deleted the ArcGIS module folder before installing the latest version 3.1.0. Here's a screen capture.
![image](https://user-images.githubusercontent.com/2885984/92028465-b7202280-ed29-11ea-9179-d19e377996fd.png)

**Comment by eanderson2030** [comment]
Hi @marcolio  @shailesh91  , I am also getting this exact error when trying to upgrade an unfederated Server with its Web Adaptor from 10.6.1 to 10.8.1 using the ArcGIS DSC 3.1.0:

Trace-DSCJob : The PowerShell DSC resource ArcGIS_WebAdaptorInstall from module <ArcGIS,3.1.0> does not exist at the PowerShell module path nor is it registered as a WMI DSC 
resource.

**Comment by shailesh91** [comment]
@marcolio  in a few days we are releasing a minor version where we will be removing the ArcGIS_WebAdaptorInstall resource and merging it with ArcGIS_Install Resource. Hopefully, that should remedy the issue you are facing currently.

**Comment by cameronkroeker** [comment]
Hello @marcolio we have released v3.1.1 where ArcGIS_WebAdaptorInstall resource has been merged with ArcGIS_Install Resource. Please give this a try to see if it resolves the issue.

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.1.1

**Comment by ErikHiCoGIS** [comment]
I may be seeing the same error. Encountering a couple distinct issues - still separating them out. But unable to get Webadaptor to install at all in 3.1.1.

**Comment by ErikHiCoGIS** [comment]
Rerun is no go. Win Server 2016. Everything current. Installer for 10.7.1.
<img width="904" alt="Capture" src="https://user-images.githubusercontent.com/48337194/99603213-f2380680-29a6-11eb-990c-a99388a1948d.PNG">

**Comment by cameronkroeker** [comment]
@ErikHiCoGIS 

Could you provide the config json file, along with the DSC logs from `C:\WINDOWS\system32\Logs`? Feel free to scrub out any sensitive information. From what I gather:

- Using PowerShell ArcGIS Module v3.1.1
- Installing standalone GIS Server 10.7.1 with GIS Server Web Adaptor all on the same machine (Fresh deployment not an upgrade)
- Windows Server 2016

**Comment by ErikHiCoGIS** [comment]
Aloha,

I’ve manually configured around the issue that was presenting.

Will see if I can find some time to run it again on a different machine and provide the logs from that run.

Note that we just needed that one installation in 10.7.1. With 10.8.1 the web adaptor installs fine for us.

Thanks,
Erik

**Comment by ErikHiCoGIS** [comment]
Aloha.  Ran through another test of failed 10.7.1 configuration on different machine. No issues encountered. Probably was some misfunction in the first server. No other errors encountered.

**Comment by cameronkroeker** [comment]
Due to this issue going a bit stale, I am going to close it for now. However, if issue persists, if possible try with v3.2.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0

Attach fresh logs, json config file, and description of the issue and we can reopen.

Thanks,
Cameron K.
