### ISSUE TITLE
Running Install Doesn't Seem To Actually Run

### ISSUE THREAD

**Issue by crosss3** [Esri/arcgis-powershell-dsc#284]
I am trying to install both Desktop and Single Machine site on a server. I run the Invoke-ArcGISConfiguration and it looks to be working but then finishes in less than a second so I know something is not getting installed. Any advice is really appreciated.

Thanks

![image](https://user-images.githubusercontent.com/8710425/92612227-aae71880-f287-11ea-9538-19cd7f6108bd.png)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

**Comment by cameronkroeker** [comment]
Hello @crosss3 ,

Could you provide the json file used in your deployment (feel free to remove sensitive information such as machine names, passwords, etc)? Also, if you could provide the DSC logs within C:\Users\$cross3\logs.

Thanks,
Cameron

**Comment by crosss3** [comment]
{
    "AllNodes": [
        {
            "NodeName": "IP",
            "DataStoreTypes": [
                "Relational"
            ],
            "Role": [
                "Server",
                "Portal",
                "DataStore"
            ]
        }
    ],
    "ConfigData": {
        "Version": "[10.7.1]",
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "UserName": "[username]",
                "Password": "[password]",
                "IsDomainAccount": true
            },
            "ADServiceUser": {
                "UserName": "[ADServiceUser Username - Active Directory Service user for enabling use of Integrated Windows Authentication with your portal.]",
                "Password": "[ADServiceUser Password]"
            }
        },
        "Server": {
            "LicenseFilePath": "[D:\\ArcGIS\\Licenses]",
            "Installer": {
                "Path": "[D:\\ArcGIS\\ArcGISServer]",
                "InstallDir": "[D:\\Program Files\\ArcGIS\\Server]",
                "InstallDirPython": "[D:\\Python27] ",
                "PatchesDir": "[Path to Directory with Patches for Server]"
            },
            "ServerDirectoriesRootLocation": "D:\\arcgisserver\\directories",
            "ConfigStoreLocation": "D:\\arcgisserver\\config-store",
            "LocalRepositoryPath": "D:\\arcgisserver\\local",
            "ServerLogsLocation": "D:\\arcgisserver\\logs",
            "ServerDirectories": [
                {
                    "name": "arcgiscache",
                    "physicalPath": "D:\\arcgisserver\\directories\\arcgiscache",
                    "directoryType": "CACHE",
                    "cleanupMode": "NONE",
                    "maxFileAge": 0
                },
                {
                    "name": "arcgisjobs",
                    "physicalPath": "D:\\arcgisserver\\directories\\arcgisjobs",
                    "directoryType": "JOBS",
                    "cleanupMode": "TIME_ELAPSED_SINCE_LAST_MODIFIED",
                    "maxFileAge": 360
                },
                {
                    "name": "arcgisoutput",
                    "physicalPath": "D:\\arcgisserver\\directories\\arcgisoutput",
                    "directoryType": "OUTPUT",
                    "cleanupMode": "TIME_ELAPSED_SINCE_LAST_MODIFIED",
                    "maxFileAge": 10
                },
                {
                    "name": "arcgissystem",
                    "physicalPath": "D:\\arcgisserver\\directories\\arcgissystem",
                    "directoryType": "SYSTEM",
                    "cleanupMode": "NONE",
                    "maxFileAge": 0
                }
            ],
            "RegisteredDirectories": [
                {
                    "name": "BasemapsCacheDir",
                    "physicalPath": "D:\\arcgisserver\\additionaldirs\\cache",
                    "directoryType": "CACHE"
                },
                {
                    "name": "TestOutputDir",
                    "physicalPath": "D:\\arcgisserver\\additionaldirs\\testOutput",
                    "directoryType": "OUTPUT"
                },
                {
                    "name": "TestJobsDir",
                    "physicalPath": "D:\\arcgisserver\\additionaldirs\\testJobs",
                    "directoryType": "JOBS"
                }
            ],
            "PrimarySiteAdmin": {
                "UserName": "[arcgis_admin]",
                "Password": "[ma20id01cm]"
            }
        },
        "Portal": {
            "LicenseFilePath": "[D:\\ArcGIS\\Licenses]",
            "PortalLicenseUserTypeId": "[creatorUT]",
            "Installer": {
                "Path": "[D:\\ArcGIS\\PortalForArcGIS]",
                "WebStylesPath": "[Optional Parameter starting ArcGIS Enterprise 10.7.1 - Portal Web Styles Installer Path]",
                "InstallDir": "[D:\\Program Files\\ArcGIS\\Portal]",
                "ContentDir": "[D:\\arcgisportal",
                "PatchesDir": "[Path to Directory with Patches for Portal]"
            },
            "ContentDirectoryLocation":"D:\\arcgisportal\\content",
            "EnableAutomaticAccountCreation": "[False]",
            "DefaultRoleForUser": "[Optional - Values: account_user | account_publisher | <custom role ID>]",
            "DefaultUserLicenseTypeIdForUser": "[Optional (Valid for 10.7 and later) - Values: fieldWorkerUT | GISProfessionalStdUT | GISProfessionalBasicUT | GISProfessionalAdvUT | creatorUT | editorUT | viewerUT]",
            "PortalAdministrator": {
                "UserName": "[username]",
                "Email": "[email]",
                "Password": "[password]",
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": "vanilla"
            },
            "EmailSettings":{
                "SMTPServerAddress":"[SMTP Server Host Address]",
                "From":"[SMTP Server Host Email From]",
                "Label":"[SMTP Server Host Email From Label]",
                "AuthenticationRequired":"[SMTP Server Host Authentication required flag - False | True]",
                "SMTPPort":"[SMTP Server Host Port]",
                "UserName": "[SMTP Server Host Authentication Username]",
                "Password": "[SMTP Server Host Authentication Password]",
                "PasswordFilePath": "[SMTP Server Host Authentication Password File Path]",
                "EncryptionMethod": "[SMTP Server Host Encryption Method - SSL,TLS,NONE]"
            }
        },
        "DataStore": {
            "ContentDirectoryLocation": "[D:\\arcgisdatastore]",
            "EnableFailoverOnPrimaryStop": "[Optional - true | False]",
            "Installer": {
                "Path": "[D:\\ArcGIS\\ArcGISDataStore]",
                "InstallDir": "[D:\\Program Files\\ArcGIS\\DataStore]",
                "PatchesDir": "[Path to Directory with Patches for DataStore]"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "[WebAdaptor Installer Path]"
            }
        }
    }
}

Nothing is getting written to the logs

**Comment by cameronkroeker** [comment]
Thanks @crosss3.

Couple of notable items that may help. 

- If specifying an IP instead of hostname for "NodeName", ensure to add the IP to the trusted host list:

https://github.com/Esri/arcgis-powershell-dsc/wiki/Using-Internet-Protocol-(IP)-address-instead-of-Fully-Qualified-Domain-Names-(FQDN)#prerequisites

- Remove the square brackets from the `"Version": "[10.7.1]"` parameter. For example, `"Version": "10.7.1"`.

- When using module v3.0.0 you will need to move the Portal and Server primary site administrator accounts to the `"Credentials":{ }` block:

https://github.com/Esri/arcgis-powershell-dsc/wiki/ArcGIS-Server-Primary-Administrator-Account-and-Portal-for-ArcGIS-Initial-Administrator-Account-variables#arcgis-module-v300-and-below

- For additional logging pass the `-DebugSwitch` parameter along with the InvokeArcGISConfiguration command. For example:

```
Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\config\BaseDeployment.json -Mode InstallLicenseConfigure -DebugSwitch
```

https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters#parameters

**Comment by crosss3** [comment]
Awesome that did it!

Thank you!
