### ISSUE TITLE
ArcGIS_WebAdaptorInstall.psm1 does not support custom "Default Web Site"-name

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.0

### Affected Resource(s)

* ArcGIS_WebAdaptorInstall

### Configuration Files

```
N/A
```

### Expected Behavior

In a customer-environment, the IIS-site with ID "1" is named "ArcGIS" instead of "Default Web Site" due to security-requirements (the specific name is irrelevant for the issue, any other name than "Default Web Site" won't work).

The Web Adaptors for "portal" and "server" should have been installed properly.

### Actual Behavior

The Web Adaptor-setups have been executed properly and the "portal" and "server" sub-websites underneath the web site with ID 1, named "ArcGIS" in this case, have been created properly.

The DSC-routine for the Web Adaptor-Install still fails, due to a web-property that can't be set, whenever the WA-website is not called "Default Web Site".

The reason are (at least) two lines of code in `ArcGIS_WebAdaptorInstall.psm1` that contain `Default Web Site` as a hardcoded value.

Line 161 (Installation):
`Set-WebConfigurationProperty -pspath "MACHINE/WEBROOT/APPHOST/Default Web Site/$($Context)"  -filter "system.web/httpRuntime" -name "executionTimeout" -value "01:00:00"`

Line 177 (Deinstallation):
`Remove-WebConfigurationLocation -Name "Default Web Site/$($Context)"`

Possible solutions:
* Get the actual name of the web site, the WA-setups installed the "portal" and "server" sub-websites and use this value instead of `Default Web Site`.
* Introduce an additional (optional) JSON-config-parameter, for when a customer has renamed the `Default Web Site` and use this parameter-value instead of `Default Web Site`.

### Steps to Reproduce

Manually install IIS on the WA-node and rename the `Default Web Site` to anything else.
Run a DSC-installation.

### References

This behavior is also mentioned and described in https://github.com/Esri/arcgis-powershell-dsc/issues/286, however it is not solely related to upgrades, which is why I created this standalone issue.

**Comment by shailesh91** [comment]
@scma-esrich We will fix this in the upcoming release. Until then you can use the following to get the site name with id = 1.
```$IISWebSiteName = (Get-Website | Where-Object {$_.ID -eq 1}).Name```

**Comment by scma-esrich** [comment]
Thanks @shailesh91!

**Comment by scma-esrich** [comment]
Attention @shailesh91, there is another location, where this leads to problems, namely `ArcGISWebAdaptor.ps1`:
![image](https://user-images.githubusercontent.com/45851791/95096202-41dead80-072c-11eb-9b42-1ac5a686f19b.png)

We didn't realize that the first time, because on the other stage the "Default Web Site" was created, configured with a HTTPS-binding and renamed after that. In contrast, on this stage, the binding wasn't set and hence the ArcGIS_IIS_TLS-part was triggered.

**Comment by shailesh91** [comment]
@scma-esrich This week we plan to release a comprehensive fix that will take care of this as well. Thanks.

**Comment by cameronkroeker** [comment]
Hello @scma-esrich we have added a new parameter "WebSiteId" in release v.3.1.1
which will allow you to specify a specific website ID.

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.1.1

**WebSiteId** - (Optional) The WebSiteId parameter is used to specify the website where the ArcGIS Web Adaptor web application will be created. The value for WebSiteId is a number specific to each website on your server and assigned by IIS. The IDs for the websites on your server can be found in IIS Manager. The default website has a website ID of 1. By default, the WebSiteId parameter is set to the default website (even if multiple websites exist).

https://github.com/Esri/arcgis-powershell-dsc/blob/bd004e9b12fe31bf47918a9c1cf690e95640f414/SampleConfigs/v3/Base%20Deployment/BaseDeployment-SingleMachine.json#L144
