### ISSUE TITLE
Enable Datastore point in time recovery

### ISSUE THREAD

**Issue by JosWesterbeek** [Esri/arcgis-powershell-dsc#290]
Add a param to the DatastoreConfiguration that enables point in time recovery by triggering 'tools\changedbproperties.bat' with correct parameters. Like so:
Enable: changedbproperties.bat --store relational --pitr enable --prompt no 
Disable: changedbproperties.bat --store relational --pitr disable --prompt no

To be able to set pitr however a backuplocation needs to be set. Apparently changebackuplocation.bat (which is referred to in the current script) is obsolete in favour of configurebackuplocation.bat

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.0

### Affected Resource(s)

* ArcGIS_DataStore

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

**Comment by cameronkroeker** [comment]
Hi @JosWesterbeek,

We have added support for this in the latest release, v3.2.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0

Set **ConfigData.DataStore.EnablePointInTimeRecovery** to true.

https://github.com/Esri/arcgis-powershell-dsc/blob/78e488fc0aac6f8f4cdf574e1bdb50a7d39ed350/SampleConfigs/v3/v3.2.0/Base%20Deployment/BaseDeployment-SingleMachine.json#L134

Thanks,
Cameron K.
