### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is an empty string

### ISSUE THREAD

**Issue by cadams84** [Esri/arcgis-powershell-dsc#292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ArcGIS_Portal
*ArcGIS_Web_Adaptor

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,

{ 
    "AllNodes":[ 
       { 
          "NodeName":"powershelldsc",
          "Role":[ 
             "Portal",
             "PortalWebAdaptor"
          ],
          "SslCertificates":[ 
             { 
                "Path":"C:\\Certificates\\powershelldsc.pfx",
                "Password":"",
				"CNameFQDN":"powershelldsc",
                "Target":[ 
                   "Portal"
                ]
             },
             { 
                "Path":"C:\\Certificates\\powershelldsc.pfx",
                "Password":"",
                "CNameFQDN":"powershelldsc",
                "Target":[ 
                   "WebAdaptor"
                ]
             }
          ]
       }
    ],
    "ConfigData":{ 
       "Version":"10.8.1",
       "PortalContext":"portal",
	   "Credentials":{
	         "ServiceAccount":{
	            "UserName":"domain\\portal",
				"Password":"",
                "IsDomainAccount":true
		     } 
	      } 
       },
       "SslRootOrIntermediate":[ 
          { 
             "Alias":"root_cert_200924",
             "Path":"C:\\Certificates\\root_cert_200924.cer"
          }
       ],
       "Portal":{ 
          "LicenseFilePath": "C:\\Licences\\Portal_for_ArcGIS_1081.json",
          "PortalLicenseUserTypeId":"editorUT",
          "Installer":{ 
             "Path":"C:\\Media\\PortalForArcGIS\\Setup.exe",
             "InstallDir":"C:\\InstallFiles\\Portal",
             "ContentDir": "C:\\arcgisportal"
          },
          "ContentDirectoryLocation":"C:\\arcgisportal",
		  "EnableAutomaticAccountCreation": true,
		  "DefaultRoleForUser":"account_user",
		  "DefaultUserLicenseTypeIdForUser":"viewerUT",
		  "PortalAdministrator":{ 
             "UserName":"admin",
             "Email":"test@domain.com",
             "Password":"Password1*",
             "SecurityQuestionIndex":1,
             "SecurityAnswer":"vanilla"
          }
       },
       "WebAdaptor":{ 
          "AdminAccessEnabled":true,
          "Installer":{ 
             "Path":"C:\\Media\\WebAdaptorIIS\\Setup.exe"
          }
       }
    
 }

```

### Expected Behavior

Portal and web adaptor installed.

### Actual Behavior

10/13/2020 3:44:42 PM: Cannot bind argument to parameter 'Path' because it is an empty string.
10/13/2020 3:44:42 PM: Cannot bind argument to parameter 'Path' because it is an empty string.
10/13/2020 3:44:42 PM: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install Portal 
10/13/2020 3:44:42 PM: Cannot bind argument to parameter 'Path' because it is an empty string.
10/13/2020 3:44:42 PM: Cannot bind argument to parameter 'Path' because it is an empty string.
10/13/2020 3:44:42 PM: Filename: \\?\C:\inetpub\wwwroot\portal\web.config
Error: Cannot write configuration file

10/13/2020 3:44:42 PM: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install PortalWebAdaptor 
10/13/2020 3:44:42 PM: The SendConfigurationApply function did not succeed.

### Important Factoids

I had installed portal and web adaptor previously with this script but some wrong variables so uninstalled them and manually deleted the 'portal' folder from C:\inetpub\wwwroot. 

I am running powershell as administrator and running the install as an administrator account. 

Invoke-ArcGISConfiguration C:\Portal_Setup.json -Mode Install -Credential domain\deploy -DebugSwitch

**Comment by cameronkroeker** [comment]
Hi @cadams84 ,

A couple of questions to get a better understanding of the issue.

1. Did you use the PowerShell DSC module to uninstall the web adaptor (`Invoke-ArcGISConfiguration C:\Portal_Setup.json -Mode Uninstall)`or were they uninstalled using the utility from the Windows Control Panel?

It is odd that you had to manually remove  'portal' folder from C:\inetpub\wwwroot as I believe when the Web Adaptor is uninstalled it should take care of this.

2. Is the orchestrating machine same as the target machine?

Thanks,
Cameron K.

**Comment by cadams84** [comment]
Hi @cameronkroeker,

1. No i did a manual uninstall from add/remove programs. Outside of powershell DSC deployment testing I have found that if I uninstall the web adaptor it sometimes doesn't clean up the folder in wwwroot so manually deleted it to make sure I was starting from scratch when trying the deployment again. 

2. The orchestrating machine is the same as the target machine for this test.

**Comment by cadams84** [comment]
Hi @cameronkroeker,

To add, I get the same error running on a new Windows Server 2012 R2 VM. I took the following steps after deploying from Azure Marketplace:

1. Updated the transport security for the VM. If these commands are not run, WMF 5.1 fails:

Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

2. Installed WMF 5.1
3. Installed the ArcGIS Module:

Install-Module -Name ArcGIS

4. Ran the install command running powershell as admin:

Invoke-ArcGISConfiguration C:\Portal_Setup.json -Mode Install -DebugSwitch

**Comment by cadams84** [comment]
There must have been an issue with one of the variables. I copied the BaseDeployment-SingleMachine.json and re-populated the variable values and the installation succeeded.

**Comment by cameronkroeker** [comment]
> There must have been an issue with one of the variables. I copied the BaseDeployment-SingleMachine.json and re-populated the variable values and the installation succeeded.

Hi @cadams84, looks like there is an extra bracket in the "Credentials" block.

```
"Credentials": {
	        "ServiceAccount":{
	            "UserName":"domain\\portal",
		    "Password":"",
                    "IsDomainAccount":true
	         } 
    } 
},
```
This very well could have been the culprit.
