### ISSUE TITLE
How to install 64 bit background Geoprocessing for ArcGIS Desktop?

### ISSUE THREAD

**Issue by sofferm** [Esri/arcgis-powershell-dsc#294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ArcGIS_Desktop

### Configuration

`{
    "AllNodes": [
        {
            "NodeName": "vm0240",
            "Role": [
                "Desktop"
            ]
        }
    ],
    "ConfigData": {
        "DesktopVersion": "10.6.1",        
        "Desktop": {
            "SeatPreference": "Float",
            "InstallFeatures": "ALL",
            "ModifyFlexdAcl": "FALSE",
            "BlockAddIns": "0",
            "DesktopConfig": "true",
            "EsriLicenseHost": "licesri.server.com",
            "SoftwareClass": "Professional",
            "EnableEUEI": "False",
            "Installer": {
                "Path": "C:\\data\\installation\\ArcGIS Desktop 10.6.1\\ArcGIS_Desktop_1061_de_163866.exe",
                "InstallDir": "C:\\bin\\ArcGIS\\Desktop",
                "InstallDirPython": "C:\\bin\\Python27",
                "PatchesDir": ""
            }
        }
    }
}`

### Question

is it possible to install 64 bit background Geoprocessing? There is a separate installer, but I cannot find a place in the JSON config file to configure it to be installed. Is this not supported (yet)?

**Comment by cameronkroeker** [comment]
Hi @sofferm this is not currently supported. I have added the Enhancement label, so that it can be evaluated as a new feature for a future release.

Thanks,
Cameron K.

**Comment by compuguy** [comment]
This should support Background Geoprocessing, Data Interop, and Mapping and Charting Solutions for ArcGIS Desktop as well.

**Comment by cameronkroeker** [comment]
Hello @compuguy and @sofferm,

Support has been added for the following extensions in [v3.3.0](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.0):

### ArcGIS Desktop Extensions
* Data Interoperability
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.8.2
* Data Reviewer
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.8.2
* Workflow Manager Classic
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.8.2
* Location Referencing
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.8.2
* Mapping and Charting Solutions
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.8.2
* Background Geoprocessing (64Bit)
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.8.2

### ArcGIS Server Extensions
* Data Interoperability
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.9, 10.9.1
* Data Reviewer
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.9, 10.9.1
* Workflow Manager Classic
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.9, 10.9.1
* Location Referencing
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1
* Mapping and Charting Solutions
  * 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.9, 10.9.1

https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/v3.3.0/DesktopPro/Desktop-SingleUse.json
