### ISSUE TITLE
Powershell DSC 3.1.1 Fails with SendConfigurationApply function did not succeed.

### ISSUE THREAD

**Issue by daraobeirne** [Esri/arcgis-powershell-dsc#295]
Hi,

We kept receiving this message when we tried running the version 3.1.1 on our Enterprise upgrading from 10.7.1 to 10.8.1:

"DSC resource ArcGIS_Install failed to execute Set-TargetResource functionality with error message: Failed to install Datastore. The SendConfigurationApply function did not succeed."

This happened at each step of the way, on the Portal and Server upgrades, but when we reran after rebooting the server machine and logging in as the service account it would resolve. We could not get it resolve on the Datastore component.

The Datastore is on a separate machine than the Server and Portal components. 

I will say, when we started the process we ran an Update-Module ArcGIS and we noticed both versions 2.1.1 and 3.1.1 in our Powershell Modules directory. We're not sure if having both versions of the module in the directory would be an issue, but just wanted to mention that. Thanks!

**Comment by cameronkroeker** [comment]
Hi @daraobeirne,

I recommend having only one version of the module on the node at a time. Having multiple versions of the module can cause issues when upgrading.

Let's give the latest release, v320 a try:
https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0

I also recommend using `-DebugSwitch` and `-EnableMSILogging` which will provide additional logs which may help finding the cause of the failure.

https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters#parameters

```
Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\config\BaseDeployment.json -Mode Upgrade -EnableMSILogging -DebugSwitch
```

Thanks,
Cameron K.
