### ISSUE TITLE
Question: Variables for JSON configuration files

### ISSUE THREAD

**Issue by ryan-WORK** [Esri/arcgis-powershell-dsc#296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.10

### Affected Resource(s)

* ArcGIS_Portal

### Configuration Files

```
        "Portal": {
            "LicenseFilePath": "",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "D:\\Temp\\Portal_for_ArcGIS_Windows_1081_175214.exe",
                "InstallDir": "D:\\ArcGIS_Portal",
                "ContentDir": "D:\\arcgisportal"
            },
            "ContentDirectoryLocation": "\\\\GEO-01\\Share\\arcgisportal\\content",
            "PortalAdministrator": {
                "UserName": "administrator",
                "Email": "user@website.com",
                "Password": "xxxxxxxxxxxx",
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": "vanilla"
            }
        },
```

### My Question

Could you please help me understand this portion of the DSC?

Just looking for information regarding the [PortalLicenseUserTypeId](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files). 

* Can this be updated after the DSC runs? 
* Is this intended to be a list of options? 
* How to know what option to use? I see a few different ones within the authorization json...

### References

[PortalLicenseUserTypeId](https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files).

**Comment by cameronkroeker** [comment]
Hello @ryan-WORK,

This is a great question, thanks for asking! The `"PortalLicenseUserTypeId"` is the user type for the initial portal administrator account, which is defined during the create site operation (equivalent to the [userLicenseTypeId](https://developers.arcgis.com/rest/enterprise-administration/portal/create-site.htm)). Choose one of the following values:

**GISProfessionalStdUT | GISProfessionalBasicUT | GISProfessionalAdvUT | creatorUT**

The following link gives details on the different user types which may help in deciding which one of the four to use:
https://enterprise.arcgis.com/en/portal/latest/administer/windows/roles.htm

I imagine it can be changed later on via the portal home app or sharing API, however once the site is created the PowerShell DSC module won't be able to update/change it.

Thanks,
Cameron K.

**Comment by ryan-WORK** [comment]
@cameronkroeker 

Thank you for getting back to me, I really appreciate it. That looks like it answers my question. I will go ahead and close this out.
