### ISSUE TITLE
Portal not HTTPS only

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#3]
Setup: Portal and PortalWebadaptor are deployed at different machines.

The Webadaptor of Portal is configured through Port 7443 and Firewall Opens only Port 7443, which is SSL Port. 
If you try to Access Portal Website through WebAdaptor it switches to HTTP (no SSL) at several sites (e.g. after Login). The Webadaptor then tries to reach the Portal by Port 7080 (HTTP) which is not open and states 
```Could not Access any Portal machines```

Therefor the Portal should be configured to use HTTPS only.

**Comment by nshampur** [comment]
good find. Fix looks almost good.  We should however make sure it does not break any HTTP calls made by automation.  
Can you parameterize this and set the default to match current behavior.  
Our lab/test environments have firewalls disabled, so we likely missed this scenario.

**Comment by spitzerr** [comment]
If we parameterize this, the Firewall-Rule for Portal should be adjusted to open Port 7080 (-> non SSL-Port) if Switch is off.

**Comment by spitzerr** [comment]
> We should however make sure it does not break any HTTP calls made by automation.

I can't see any HTTP calls to Portal made by automation, so it should be fine from this perspective.


On the other hand the Firewall Rules for Portal seem a little bit messed up according to this Docu:
https://enterprise.arcgis.com/en/portal/latest/administer/linux/ports-used-by-portal-for-arcgis.htm
compared with 
https://github.com/Esri/arcgis-powershell-dsc/blob/2fcd4f56ad07870cc7e788308a2a94f40b1890d3/Modules/ArcGIS/Configuration/ArcGISConfigure.ps1#L751-L828

From my perspective:

- Open 7080 in first else branch as well.
- Don't open 6443 on any part as it is ArcGIS Server Port and is only necessary if ArcGIS Server is installed on that machine.
- Port 5703 is missing for HA-Portal (IsMultimachinePortal)
- According to Docu Ports 7120, 7220 and 7654 are only local ports (so Outbound should be sufficent)

Could you please advise on these findings?
