### ISSUE TITLE
TLS only works if webadaptor and server/portal are on the same machine

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#30]
Webadaptor and Server or Portal can be on different machines. Therefore it will be necessary to Support different certificates for Webadaptor and Server or Portal. Furthermore it could be necessary to Import Root or intermediate Certificates to Portal and Server.

I'll provide PR on this soon.

**Comment by shailesh91** [comment]
@spitzerr Can you please provide use cases for SslRootOrIntermediate in Config Data?

**Comment by spitzerr** [comment]
@shailesh91
It's from the documentation over here
https://enterprise.arcgis.com/en/server/latest/administer/windows/configuring-https-using-a-new-ca-signed-certificate.htm#ESRI_SECTION1_E0A984AB1249430A862B2AA6A8263FCD

If you run your own CA but cannot rollout the root certificate via AD

**Comment by spitzerr** [comment]
@shailesh91  and for Portal the documentation is like this:
https://enterprise.arcgis.com/en/portal/latest/administer/windows/import-a-certificate-into-the-portal.htm#ESRI_SECTION2_C2578EF79D3B475FB04E7C30D23C0DB6
