### ISSUE TITLE
Add Ability to update ArcGIS Data Store SSL Certificate

### ISSUE THREAD

**Issue by rlhadsel** [Esri/arcgis-powershell-dsc#305]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ArcGIS DataStore

### Issue

When using the PowerShell DSC to install ArcGIS Data Store on its own machine, there is no option to designate the Data Store as a 'Target' in the SslCertificates section (under 'AllNodes' object). The current workflow is to use the PowerShell DSC to automate the deployment, then use the ArcGIS Data Store command line utility to update the SSL certificate. This would reduce the number of steps required if it could be added to the configuration file.

**Comment by cameronkroeker** [comment]
Hello @rlhadsel,

We are excited to annouce that this enhancement request has been implemented in the latest release, v3.2.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0

Sample can be found here:

https://github.com/Esri/arcgis-powershell-dsc/blob/78e488fc0aac6f8f4cdf574e1bdb50a7d39ed350/SampleConfigs/v3/v3.2.0/Base%20Deployment/BaseDeployment-ThreeMachine-ssl-per-Node-Example1.json#L12-L21

Thanks,
Cameron
