### ISSUE TITLE
Add Ability to use multiple Cloud Storage Options

### ISSUE THREAD

**Issue by rlhadsel** [Esri/arcgis-powershell-dsc#306]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ArcGIS Enterprise
* ArcGIS Server
* Portal for ArcGIS

### Issue

Currently the Cloud Storage option is a global setting and only allows for one storage type per JSON configuration file. We've recently come across a case in which we need multiple cloud storage types (Azure Blob and Azure Files) for an ArcGIS Enterprise deployment using the PowerShell DSC. This is due to a limitation with splitting up the JSON configuration files and needing to manually designate the hosting server as the only option is currently 'GeneralPurposeServer'. In our case, we needed to automate the entire deployment from start to finish with no human interaction, therefore, we went with Azure Files as our file share option. Ideally, we could designate Portal and Server's content, config-stores, and directories to go to multiple cloud storage types in one configuration file.

**Comment by cameronkroeker** [comment]
Hi @rlhadsel,

We're excited to share that this enhancement request has been added to the latest release, v3.2.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0

Sample can be found here:

https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/v3.2.0/Base%20Deployment/BaseDeployment-SingleMachine-CloudStore.json

Happy Automating,
Cameron K.
