### ISSUE TITLE
Certificate Issue on Standby Portal Machine

### ISSUE THREAD

**Issue by Ayushyadav19** [Esri/arcgis-powershell-dsc#307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ArcGIS_Portal

### Issue

I am deploying ArcGIS Portal as a highly available portal for that I have prepared the config JSON file in which I have put the "**SslCertificates**" key for both the nodes, after deploying ArcGIS Portal through PowerShell DSC the primary portal machine got secured and the standby machine didn't get secured, and I didn't encounter any errors during the actual installation process.

### Expected Behavior

 Should secure the standby machine's URL also through the SSL certificate which I had given for both nodes

### Actual Behavior

Only secured the primary machine's URL by importing the SSL certificate.

**Comment by cameronkroeker** [comment]
Hi @Ayushyadav19 could you provide the DSC logs, and json config file used in the deployment (feel free to scrub out any sensitive information such as machine names, username\passwords, etc).

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
If this is still an issue please attach the DSC logs and json config file used in the deployment. We can then reopen to investigate it further.

Thanks!
