### ISSUE TITLE
Include ability to install Roads & Highways

### ISSUE THREAD

**Issue by runneals** [Esri/arcgis-powershell-dsc#316]
Need to include roads and highways install within the PS DSC environment.

**Comment by cameronkroeker** [comment]
Hello @runneals,

We have added support for ArcGIS Server and ArcGIS Desktop extensions in the latest release, v3.3.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.0

Here you can find sample config json files:

https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/v3.3.0/Gis%20Servers/GISServer-GeneralPurpose.json#L57

https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/v3.3.0/DesktopPro/Desktop-SingleUse.json#L46

Thanks,
Cameron K.
