### ISSUE TITLE
Include ability to install ArcGIS Insights

### ISSUE THREAD

**Issue by runneals** [Esri/arcgis-powershell-dsc#317]
Would be ideal to include ArcGIS Insights install through PS DSC since it needs to be included when it's being used.

**Comment by cameronkroeker** [comment]
Hello @runneals,

We have added support for ArcGIS Insights in the latest release, v3.3.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.0

Here you can find a sample config json file:

https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/v3.3.0/Base%20Deployment/BaseDeployment-SingleMachine-Insights.json

Thanks,
Cameron K.
