### ISSUE TITLE
Add ArcGIS Pro 2.7 support

### ISSUE THREAD

**Issue by sofferm** [Esri/arcgis-powershell-dsc#318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ArcGIS_Pro

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "DEV1234",
            "Role": [
                "Pro"
            ]
        }
    ],
    "ConfigData": {
        "ProVersion": "2.7",
        "Version": "2.7",
        "Pro": {
            "AuthorizationType": "NAMED_USER",
            "SoftwareClass": "Professional",
            "PortalList": "",
            "EsriLicenseHost": "https://www.arcgis.com",
            "EnableEUEI": "False",
            "CheckForUpdatesAtStartup": "True",
            "Installer": {
                "Path": "C:\\bin\\ArcGIS\\Pro",
                "InstallDir": "C:\\installation\\ArcGIS_Pro_2.7\\ArcGISPro_27_de_176628.exe",
                "PatchesDir": "C:\\installation\\ArcGIS_Pro_2.7\\Patch"
            }
        }
    }
}
```

### Expected Behavior

2.7 can be installed

### Actual Behavior

only <= 2.6 is supported:

```
Cannot validate argument on parameter 'Version'. The argument "2.7" does not belong to the set 
"2.0,2.1,2.2,2.3,2.4,2.5,2.6,10.4,10.4.1,10.5,10.5.1,10.6,10.6.1,10.7,10.7.1,10.8,10.8.1,2018.0,2018.1,2019.0,2019.1,2019.2,2020.0
```

### Important Factoids

The Parameter Version is needed because otherwise v3.1.1 wont install Pro:
https://github.com/Esri/arcgis-powershell-dsc/issues/299

**Comment by cameronkroeker** [comment]
Hi @sofferm we will add support for ArcGIS Pro 2.7 in the next release of ArcGIS Module (v3.2.0).

Thanks,
Cameron K.

**Comment by pfoppe** [comment]
Do you have an expected timeframe for v3.2.0 release?
Thanks!

**Comment by cameronkroeker** [comment]
Hi @pfoppe,

v3.2.0 is planned for release along side ArcGIS Enterprise 10.9, in May 2021.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @pfoppe,

Great news! We have added support for ArcGIS Pro 2.7 in the latest release v3.2.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0

Happy Automating,
Cameron K.
