### ISSUE TITLE
Add install ArcGIS Web Adaptor on Java Platform

### ISSUE THREAD

**Issue by jrascle** [Esri/arcgis-powershell-dsc#319]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ServerWebAdaptor
* PortalWebAdaptor

### Configuration Files

I work on this capabilities on a fork and I change many files of the project to install WebAdaptor on a tomcat. I success but i would like an integration in the default module. 

```
"WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "C:\\tmp\\ArcGIS_Web_Adaptor_Java_Windows_1081_175228.exe",
		"InstallDir": "C:\\ArcGIS"
            },
	**"Type": "Java"**,
	**"TomcatDir":"C:\\Tomcat9"**
        }
```

The installation on Web Adaptor Java Platform is very important to us.

**Comment by alexanderwalkowski** [comment]
Hi @cameronkroeker,
are there any plans to support JavaWebAdaptor with ArcGIS DSC? I would appreciate it.
kind regards,
Alexander Walkowski

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker, are there any plans to support JavaWebAdaptor with ArcGIS DSC? I would appreciate it. kind regards, Alexander Walkowski

Hi @alexanderwalkowski,

There aren't plans in the immediate road map to include support for the Java WebAdaptor (WA). However, I would be interested in the use case of using Java WA over IIS WA. What are the benefits or why do you prefer to use the Java WA over IIS? Also, which Java web server do you prefer (Apache Tomcat, Nginx, other)?

Thanks,
Cameron K.

**Comment by alexanderwalkowski** [comment]
Hi @cameronkroeker ,
in our setups we have additional componentes like con terra security.manager, map.apps and project specific implementations which are Java web applications, thus we use Apache httpd as reverse proxy and apache Tomcat as servlet container. Since we have already a Tomcat, I use the Java WebAdaptor to avoid an additional component, that needs to be maintained. Further more for me the integration of apache httpd and Tomcat is easier to setup than the ISAPI filter configuration for IIS.
kind regards,
Alexander

**Comment by jrascle** [comment]
We have an additional software which add functionnality for specific work. This software force the usage of WebAdaptor Java.  
We use always Apache Tomcat.

**Comment by cameronkroeker** [comment]
Support for ArcGIS WebAdaptor Java (Windows) has been added in release v4.2.0:
https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.2.0

**Sample Json:**
https://github.com/Esri/arcgis-powershell-dsc/blob/3d056fe815c68e9676789afe9d4ca71c05cefc8d/SampleConfigs/v4/v4.2.0/Base%20Deployment/BaseDeployment-SingleMachine-Java-WA.json#L190-L212

This will install and configure ApacheTomcat with a self-signed certificate. However, you can specify your own ssl certificate in the AllNodes.SSLCertificates section. 

The following pre-req's need to be met prior to running the module:
- Java JDK pre-configured
- Ensure JAVA_HOME environment variable is set
- Ensure AGSWEBADAPTORHOME environment variable is set to the web adaptor installation path
- Machine Reboot

Alternatively, if you wish to bring your own java web server you can omit `ConfigData.WebAdaptor.Installer.ApacheTomcat` section, and just set `ConfigData.WebAdaptor.IsJavaWebAdaptor` to true and specify the web app directory where the arcgis.war should be deployed to in `ConfigData.WebAdaptor.JavaWebServerWebAppDirectory`.

In the coming days/weeks we will publish a wiki page with additional details.

Thanks,
Cameron K.

**Comment by jrascle** [comment]
Hi @cameronkroeker ! 
First of all, thanks a lot to support this on new release. 
I test and it seems to work.
Isthere a way tocontrol the port used by tomcat during the processus ?

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker ! First of all, thanks a lot to support this on new release. I test and it seems to work. Isthere a way tocontrol the port used by tomcat during the processus ?

Glad to hear it worked. No we do not support specifying a custom port at this release. Feel free to submit a new feature request and we can evaluate it for a future release.

Thanks,
Cameron K.
