### ISSUE TITLE
upgrade from Entprise 10.8.1 to 10.9, ArcGIS Server failing to install

### ISSUE THREAD

**Issue by lachlanwainwright** [Esri/arcgis-powershell-dsc#323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* ArcGIS Server

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

Upgraded deployment of ArcGIS Enterprise 10.9 

### Actual Behavior

ArcGIS Server appears to have upgraded but not joined the site.
Snippet from running upgrade using the the -debugswitch

```
/12/2021 2:31:09 PM: [_Servername_]:  [[ArcGIS_ServerUpgrade]ServerConfigureUpgrade] Response:- {"status":"error","messages":["Could not find resource or operation 'upgrade' on the system."],"code":404}
```

The log for DataStoreUpgradeInstall has the following:
```
5/12/2021 4:21:04 PM: [_Servername_]:   [[ArcGIS_Install]DataStoreUpgrade] Installed Version 10.7.11595 10.9.26417
5/12/2021 4:21:04 PM: [_Servername_]: LCM:  [ End    Test     ]  [[ArcGIS_Install]DataStoreUpgrade]  in 0.0270 seconds.
```
Then in the DataStoreUpgradeConfigure:
```
5/12/2021 4:21:32 PM: [_Servername_]:  [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade] Response:- {"error":{"code":500,"message":"Machine 'https://_Servername_:6443/arcgis/admin/generateToken' returned an error. 'Local machine '_Servername_' is not participating in any Site. Please create a new Site or join an existing Site.'","details":null}}
5/12/2021 4:21:32 PM: [_Servername_]:    [[ArcGIS_DataStoreUpgrade]DataStoreConfigUpgrade] [Error] - You cannot call a method on a null-valued expression.
```

### Steps to Reproduce
Re-run upgrade

### Important Factoids
Single machine install that had 1071, recently upgrade to 1081 and now trying 109

All components appear to be upgraded, just not getting configured??

On first run of the upgrade the AGS install failed, unfortunately there are no logs 

If I go to https://_Servername_...:6443/arcgis/manager it is asking to create or join a site.

I have checked everything including restarting the server.
Checked and checked the config file and hoping I was having a shocker of screen blindness...so far I don't think so :)

**Comment by cameronkroeker** [comment]
Hello @lachlanwainwright,

Would you be able to pass along the json config file, and full DSC logs (feel free to scrub out sensitive information such as usernames/passwords/machine names, etc).

Also, with v3.2.0 we can now pass in **-EnableMSILogging** parameter to capture an msi install logs:

`Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\config\BaseDeployment.json -Mode Upgrade -EnableMSILogging`

https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters#parameters

Thanks,
Cameron K.

**Comment by lachlanwainwright** [comment]
closing issue as we are rebuilding the server due to the machine been a wreck.
the upgrade had failed due to a number of reasons, main reason, server was a dev box and had had too many 'alterations' over time.
