### ISSUE TITLE
Please update the variables reference page for the current 3.2.0-release

### ISSUE THREAD

**Issue by scma-esrich** [Esri/arcgis-powershell-dsc#326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

*Wiki/Documentation

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

The Variables Reference Page (see https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files) should have been updated for the 3.2.0-release.

### Actual Behavior

The Variables Reference Page (see https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files) is not (fully?) updated to the 3.2.0-release yet.

**Comment by cameronkroeker** [comment]
Hello @scma-esrich 

We have added the following variable reference page for v3.2.0:

https://github.com/Esri/arcgis-powershell-dsc/wiki/v3.2.0-Variables-reference-page-for-JSON-configuration-files

Thanks,
Cameron K.
