### ISSUE TITLE
Error in DSC 3.2.0: Domain-User as Service Account - The service did not start due to a logon failure

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

ArcGIS_Service_Account

### Configuration Files

{
    "AllNodes": [
        {
            "NodeName": "vm-img-g01.mydomain.com",
            "Role": [
                "Server"
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.8.1",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "Password": "fdsfdsfas",
                "UserName": "mydomain\\myuser",
                "IsDomainAccount": true
            }
        },
        "Server": {
            "LicenseFilePath": "C:\\arcgisautomation\\license\\ArcGIS_10.8.1\\server.ecp",
            "Installer": {
                "Path": "C:\\arcgisautomation\\setups\\esri\\ArcGIS_10.8.1\\ArcGIS_Server_Windows_1081_175203.exe",
                "InstallDir": "C:\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27 "
            },
            "ServerDirectoriesRootLocation": "C:\\arcgisserver\\directories",
            "ConfigStoreLocation": "C:\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": "siteadmin",
                "Password": "fdsfdsfas"
            }
        }
    }
}

### Expected Behavior

I expect to see the ArcGIS server service running with the specified domain user account.

### Actual Behavior

The default account was changed from "Local system" to my domain user account, but the service cannot start. If I try to start it manually I get: "Windows could not start the ArcGIS Server service on local Computer" Error 1069: The service did not start due to a logon failure"

After replacing the password of the set user in the LogOn tab of the ArcGIS Server service, I was able to start the service. It seems that the password is not correctly set. 
With the Powershell DSC Version 3.1.1 it worked with the same user with 10.8.1. But it does not work with 3.2.0 and 10.8.1/10.9.0. The server is a windows 2019 server.

It seems only a one shot problem. If once the password was set correctly and the service was running I switched back to "Local System" an ran the DSC configuration again and this time the service account was set correctly and was running.

### Steps to Reproduce
Just run an "InstallLicenseConfigure" Mode for simple ArcGIS Server deployment with a domain user as service account.
The DSC hangs after the restart of the service in the ArcGIS_Service_Account Module, because the service cannot start

### Important Factoids

Windows 2019 Server in Azure (Westeurope)

**Comment by lorenzmeyer77** [comment]
The problem is not the password, the problem is, that the service account user is no longer granted to "Log On as a service".
Check https://support.faxmaker.gfi.com/hc/en-us/articles/360015152239
The service user is no longer added to this policy.

**Comment by scma-esrich** [comment]
@spitzerr and @nme-esridech, FYI.

**Comment by cameronkroeker** [comment]
@lorenzmeyer77 

Instead of adding the domain account to the 'log on as a service' local security policy, we believe the better approach would to instead add the machine that is hosting ArcGIS Server to the 'log on locally' rights of the domain user:

https://enterprise.arcgis.com/en/server/latest/administer/windows/advanced-considerations-when-using-domain-accounts.htm#GUID-1355896B-C547-4FAD-9299-D2D35A0D3D75

**Comment by scma-esrich** [comment]
@cameronkroeker:
Your approach seems to be a leap back for me. Imagine a situation, where you bring up your infrastructure fully automated in a public cloud. Usually the GIS-team does not have edit-privileges within Active Directory. So, whilst all could be fully automated, the GIS-team would have to request this privilege-change being done by the cloud-team of the IT-department. This completely breaks an otherwise fully automatable workflow.

Or do you see possibilities to set such a privilege via a GPO rule-based? Something like: "If another machine named 'GIShost*' comes up, give user 'GISServiceUser' the privilege 'log on locally' there."?

**Comment by scma-esrich** [comment]
Any news concerning my input, @cameronkroeker?

**Comment by cameronkroeker** [comment]
> @cameronkroeker:
> Your approach seems to be a leap back for me. Imagine a situation, where you bring up your infrastructure fully automated in a public cloud. Usually the GIS-team does not have edit-privileges within Active Directory. So, whilst all could be fully automated, the GIS-team would have to request this privilege-change being done by the cloud-team of the IT-department. This completely breaks an otherwise fully automatable workflow.
> 
> Or do you see possibilities to set such a privilege via a GPO rule-based? Something like: "If another machine named 'GIShost*' comes up, give user 'GISServiceUser' the privilege 'log on locally' there."?

Hi @scma-esrich, I understand your point about your organizational structure, however we are still in the process of investigating\elevating this. 

Through various manual testing I have found the following observations:

a. If the username\password for the (local or domain) run-as account is passed through the silent install command via the setup, the run-as account is automagically added to the "Log on as a service" local security policy. If this account is removed from the "Log on as a service" local security policy the service fails to start with error 1069, until it is added back.

b. If the username\password for the run-as account isn't passed through the silent install command via the setup, then it defaults to Local System. Then if the configureserviceaccount.bat utility is used to change the Log On account from Local System (in services.msc) to a local\domain account this new account is not added to "Log on as a service" local security policy, but the service stops/starts successfully without an issue. However, if the local\domain run-as account is ever added to "Log on as a service" local security policy (manually) then removed, the service fails to start with error 1069, until its added back.

c. In some environments if the user does not belong to "Log on as a service" local security policy, when starting the service in services.msc the OS grants this privilege, but I have found that in some environments this is not the case:

![Log_On_As_A_Service](https://user-images.githubusercontent.com/48299621/121568446-91b8f700-c9d4-11eb-8ecc-b6a307243d46.png)


So my conclusion from this is that once the run-as account is added to "Log on as a service" local security policy then it must always remain or the service fails to start. However, if the run-as account was never added to "Log on as a service" local security policy then the service starts successfully as well.

So this begs the question, why does the setup add this user assignment but not the configureserviceaccount utility? And is it truly required or necessary for the run-as account to have "Log on as a service" local security policy rights? I feel once we have more clarity on this then we can decide how to handle it from a DSC perspective.

Stay tuned.

Thanks!

**Comment by cameronkroeker** [comment]
@scma-esrich 

My observations **b** and **c** above are incorrect/wrong. I have confirmed that the configureserviceaccount utilities for Portal/Server/DataStore/Mission Server/Notebook Server all do actually add the local\domain service account to the local security policy "Log On As A Service". I didn't realize that the Local Security Policy Desktop App needed to be fully closed, and reopened to see the change. So I have concluded that "Log On As A Service" is indeed actually required.

However, the ArcGIS_Service_Account resource does use the configureserviceaccount utilities (for Portal/DataStore/Mission Server/Notebook Server), and ServerConfigurationUtility.exe for Server to update the account. See the below snippet:

https://github.com/Esri/arcgis-powershell-dsc/blob/78e488fc0aac6f8f4cdf574e1bdb50a7d39ed350/Modules/ArcGIS/DSCResources/ArcGIS_Service_Account/ArcGIS_Service_Account.psm1#L139-L162

@lorenzmeyer77 I ran the following test, but was not able to reproduce the issue.

1. Created a VM using the ArcGIS Enterprise 10.9 Esri Azure Image from the Azure Marketplace
2. Joined the VM to a domain
3. Verified in services.msc that portal/server/datastore were all set to Manual, Stopped, and Local System as the Log On Account
4. Verified that my domain account was not granted "Log On As a Service"
4. Installed ArcGIS Module v3.2.0 from the PS Gallery and used the provided configuration file
5. Once the deployment completed, verified that the ArcGIS Server service in services.msc was set to Automatic for the Startup Type, the Log On Account was updated from Local System to my domain account, and the service stops/starts successfully
6. Also verified that the domain account had been granted "Log on as a Service" in local security policy

So I am still a bit confused as to how your domain account was not initially added to the Local Security Policy "Log on as a Service", as this should have been handled by the ServerConfigurationUtility for Server. Was this just a one off or are you able to consistently reproduce the issue?

**Comment by lorenzmeyer77** [comment]
@cameronkroeker My test still fails. So I'm able to reproduce the issue.
1. Created VM Windows Server 2019 from Azure Marketplace (NO Esri Image)
2. Joined the VM to a domain
3. Copyied DSC Module from GitHub Tag 3.2.0 to the machine, Copied setups, certificates and licenese as well.
4. Launched "InstallLicense" from the ArcGIS DSC Module 
5. Checked that in the services.msc the server was set to Local System and was running.
6. Stopped VM, created disk Snapshot
7. Started VM again
8. Ran "InstallLicenseConfigre" with the provided configuration file.
9. --> Deployment hangs. The service account has changed, but the service could not start. Tried to start the service manually --> See Warning
![2021-06-11 11_51_05-RDP-Manager](https://user-images.githubusercontent.com/24472585/121668432-93092300-caab-11eb-90a1-72cd7c729479.png)
![2021-06-11 11_45_51-RDP-Manager](https://user-images.githubusercontent.com/24472585/121668435-93a1b980-caab-11eb-93dd-6a03d3a2eed5.png)

**Comment by lorenzmeyer77** [comment]
@cameronkroeker 
If I run the ServerConfigurationUtility.exe from the ArcGIS 10.9.0 Server Installation manually, it does not work.
If I want to add the domain account as follows:
c:\ArcGIS\Server\bin>ServerConfigurationUtility.exe /username nt-sbb1\fs45057 /password mypassword
I get:
Domain user account nt-sbb1\fs45057 not found. 80070035: The network path was not found.

But I can add this user and domain manually on the service:
![image](https://user-images.githubusercontent.com/24472585/121670757-13308800-caae-11eb-968c-300279399e18.png)

**Comment by cameronkroeker** [comment]
@lorenzmeyer77 Ah I now understand the issue. In step 4, -Mode InstallLicense the domain service account should have been passed in with the silent setup.exe command during install. I suspect though it passed in Local System because it received the same error as you see when manually running the ServerConfigurationUtility. 

Are you connecting to the VM as the local account or as a domain account? 
I suspect the local account is unable to find the network path for the domain service account. 

In my case I was making the RDP connection with a domain account rather than a local account which would explain why it worked for me. 

What happens if you pass in the domain account using the -Credential parameter with the Invoke-ArcGISConfiguration command?

Thanks,
Cameron

**Comment by lorenzmeyer77** [comment]
I was logged in on the machine itself with the domain user (fs45057) and launched the dsc config. The same happens when I pass the credential with the -Credential parameter.

**Comment by cameronkroeker** [comment]
Thanks @lorenzmeyer77 for confirming. Looks like there are a few different known causes of the error `Domain user account not found. 80070035: The network path was not found.` from the ServerConfigUtility.exe. The following KB article from Esri Support explains a few in detail:

https://support.esri.com/en/technical-article/000012113

One additional known security policy that can cause this error is the "Remote calls to the Security Account Manager (SAM) must be restricted to Administrators." Typically this is enabled in STIG environments:

**Comment by lorenzmeyer77** [comment]
@cameronkroeker 
New cognitions with the DSC 3.3.0 version:
In fact the problem is the "ServerConfigurationUtility.exe" (Command-Line) or even the "ServerConfigurationUtilityUI.exe" on our Azure VMs. It does not work with our Domain-Users. The Command-Line tool  started inside the DSC does not return an error and no other output message, but when I run the tool in a normal Command prompt I get this error:
"Domain user account xxxx\yyyy not found. 80070035: The network path was not found"
I created an Esri support call for this issue (Esri Case #02947471). Investigation still ongoing. The domain account works, but the tool from Esri cannot find it somehow. 
We had this problem already with DSC 3.2.0 but there it then somehow worked, because in the "ArcGIS_Service_Account.psm" when the startup type for the service was fixed, also the user and the password were handed over. This has now been refactored with DSC 3.3.0 and now it doesn't work anymore. I had to fix it for myself. See https://github.com/lorenzmeyer77/arcgis-powershell-dsc/tree/feature/fixRunAsAccount

**Comment by cameronkroeker** [comment]
ArcGIS Module [v3.3.1](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.1) will now add the **ConfigData.Credentials.ServiceAccount.UserName** (ArcGIS Enterprise RunAsServiceAccount) to the Log On as a service local security policy.
