### ISSUE TITLE
Dsc v3.2.0 - LicenseManager 2021.0 (ArcGIS 10.9.0) not supported for installation

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* DSC Resource ArcGIS_Install --> ArcGISUtility.psm1 --> wrong validate set for component code?
### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
{
    "AllNodes": [
        {
            "NodeName": "vm-license-g01.mydomain.com",
            "Role": [
                "LicenseManager"
            ]
        }
    ],
    "ConfigData": {
        "LicenseManagerVersion": "2021.0",
        "LicenseManager": {
            "Installer": {
                "Path": "c:\\temp\\ArcGIS_License_Manager_Windows_2021_0_177928.exe",
                "InstallDir": "C:\\ArcGIS\\LM"
            }
        }
    }
}

### Expected Behavior

I expect to install the new license manager that comes with arcgis 10.9.0. The version ist 2021.0.

### Actual Behavior
DSC failes and tells me that this version of the license manager is not supported.

02.06.2021 18:27:20: Cannot validate argument on parameter 'Version'. The argument "2021.0" does not belong to the set "2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,10.4,10.4.1,10.5,10.5.1,10.6,10.6.1,10.7,10.7.1,10.8,10.8.1,10.9,2018.0,2018.1,2019.0,2019.1,2019.2,2020.0,2020.1" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
02.06.2021 18:27:21: You cannot call a method on a null-valued expression.
02.06.2021 18:27:21: You cannot call a method on a null-valued expression.
02.06.2021 18:27:21: The PowerShell DSC resource '[ArcGIS_Install]LicenseManagerInstall' with SourceInfo 'C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configurations-OnPrem\ArcGISInstall.ps1::405::21::ArcGIS_Install' threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
02.06.2021 18:27:21: The SendConfigurationApply function did not succeed.

Could it be that the list of component keys is wrong? I mean, there's not licensemanager with version 2020.1, but one for 2020.0 (arcgis 10.8.1) and one for 2021.0 (arcgis 10.9.0)

### Steps to Reproduce

Try to install the license manager 2021.0.

### Important Factoids

VM located in Azure westeurope

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
--->

**Comment by lorenzmeyer77** [comment]
@scma-esrich FYI

**Comment by cameronkroeker** [comment]
Hello @lorenzmeyer77,

Unfortunately, ArcGIS License Manager 2021.0 support did not make it into v3.2.0 due to timing. We had finalized v3.2.0 prior to when License Manager 2021.0 was ready/finalized. However, I have added this as an Enhancement and we plan to add it to the next release. 

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0

## Supported versions
ArcGIS Enterprise - 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1, 10.9
ArcGIS Desktop - 10.4, 10.4.1, 10.5, 10.5.1, 10.6, 10.6.1, 10.7, 10.7.1, 10.8, 10.8.1
ArcGIS Pro - 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7
**ArcGIS License Manager** - 2018.0, 2018.1, 2019.0, 2019.1, 2019.2, 2020.0, 2020.1
ArcGIS Notebook Server - 10.7, 10.7.1, 10.8, 10.8.1, 10.9
ArcGIS Mission Server - 10.8, 10.8.1, 10.9

Thanks,
Cameron K.

**Comment by lorenzmeyer77** [comment]
Hi Cameron

Thanks for the feedback. Good to know.

Cheers
Lorenz M.

**Comment by scma-esrich** [comment]
@spitzerr and @nme-esridech, FYI

**Comment by cameronkroeker** [comment]
Hello @lorenzmeyer77, @scma-esrich,

Support for ArcGIS License Manager 2021.0 and 2021.1 has been added to the latest release, v3.3.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.0

Thanks,
Cameron K.
