### ISSUE TITLE
Dsc v3.2.0 - ServerDirectoriesCloudStorageAccount with AzureBlob not working

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

{
    "AllNodes": [
        {
            "NodeName": "mymachine.mydomain.com",
            "Role": [
                "Server"
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.9",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "Password": "mySAUserPassword",
                "UserName": "mydomain\\mySAUser",
                "IsDomainAccount": true
            }
        },
        "Server": {
            "LicenseFilePath": "C:\\arcgisautomation\\license\\ArcGIS_10.9.0\\server_10.9.0.ecp",
            "Installer": {
                "Path": "C:\\arcgisautomation\\setups\\esri\\ArcGIS_10.9.0\\ArcGIS_Server_Windows_109_177775.exe",
                "InstallDir": "C:\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27 "
            },
            "ServerDirectoriesRootLocation": "C:\\arcgisserver\\directories",
            "ConfigStoreLocation": "C:\\arcgisserver\\config-store",
            "LocalRepositoryPath": "C:\\arcgisserver\\local-config-store",
            "PrimarySiteAdmin": {
                "UserName": "siteadmin",
                "Password": "somepassword"
            },
            "ConfigStoreCloudStorageAccount":{
                "UserName": "myazureaccount.blob.core.windows.net",
                "Password": "myazureaccountsecretkey",
                "CloudStorageType": "AzureBlob",
                "CloudNamespace": "myblobconfigstore"
            },
			"ServerDirectoriesCloudStorageAccount":{
                "UserName": "myazureaccount.blob.core.windows.net",
                "Password": "myazureaccountsecretkey",
                "CloudStorageType": "AzureBlob",
                "CloudNamespace": "myblobserverdirectories"
            } 			
        }
    }
}

### Expected Behavior
I would expect that in the storage account "myazuraccount" there would be some containers and tables for the config store and the server directories.

### Actual Behavior
The DSC configuration end in an error. "AzureBlob" seems not work for "ServerDirectoriesCloudStorageType".
`Finished DSC Job:- ArcGISLicense. Time Taken - 00:00:05.0527743
ArcGISLicense - Completed
Dot Sourcing the Configuration:- ArcGISServer
ArcGISServer : Cannot validate argument on parameter 'ServerDirectoriesCloudStorageType'. The argument "AzureBlob" does not belong to the set "AzureFiles" specified by
the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:231 char:25
+     &$ConfigurationName @Arguments -Verbose
+                         ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ArcGISServer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,ArcGISServer

Starting DSC Job:- ArcGISServer
Start-DscConfiguration : .\ArcGISServer is not a valid directory.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:240 char:131
+ ... tial }else{ Start-DscConfiguration -Path ".\$($ConfigurationName)" -F ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-DscConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDscConfigurationCommand`

### Steps to Reproduce

Try to run a similar configuration with cloud storage "blob" on Azure. With "only" the config store as cloud storage the configuration run, but with the config store and the server directories, the dsc modules terminates with an error.

### Important Factoids

Runnin OnPrem in Azure on a virtual machine with Windows 2019.

**Comment by lorenzmeyer77** [comment]
@scma-esrich FYI

**Comment by scma-esrich** [comment]
@spitzerr @nme-esrich, FYI

**Comment by cameronkroeker** [comment]
Hello @lorenzmeyer77,

This is a limitation with ArcGIS Server. ArcGIS Server directories cannot be placed inside an Azure Blob storage container, only the ArcGIS Server Config-Store can reside in an Azure Blob storage container. The ArcGIS Server directories can, however, reside in Azure Files or a Windows Files Share.

https://github.com/Esri/arcgis-powershell-dsc/blob/78e488fc0aac6f8f4cdf574e1bdb50a7d39ed350/SampleConfigs/v3/v3.2.0/Base%20Deployment/BaseDeployment-SingleMachine-CloudStore.json#L107

We will update the variable reference wiki page to reflect this as well.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
We have updated the v3.2.0 variable reference page.

**ConfigData.Server.ServerDirectoriesCloudStorageAccount.CloudStorageType**  - this can only be set to AzureFiles.

https://github.com/Esri/arcgis-powershell-dsc/wiki/v3.2.0-Variables-reference-page-for-JSON-configuration-files

Thanks,
Cameron K.
