### ISSUE TITLE
Winrm SSL compatability?

### ISSUE THREAD

**Issue by jsthusker** [Esri/arcgis-powershell-dsc#334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* ArcGIS_Portal

### Configuration Files

{
    "AllNodes": [
	        {
            "NodeName": "nodename", 
            "Role": [
                "Portal"
            ]
        },
        {
            "NodeName": "nodename", 
            "DataStoreTypes": [
                "Relational"
            ],
            "Role": [
                "DataStore"
            ]
        },
        {
            "NodeName": "nodename", 
            "Role": [
                "Server"
            ]
        },
		        {
            "NodeName": "server.domain", 
            "Role": [
                "ServerWebAdaptor",
                "PortalWebAdaptor"
            ],
            "SslCertificates": [
                {
                    "Path": "D:\\Install\\some.pfx", 
                    "Password": "password", 
                    "CNameFQDN": "giscatwa01.stone.ne.gov", 
                    "Target": [
                        "WebAdaptor" 
                    ]
                }
            ]
        }
    ],
	"ConfigData": {
        "Version": "10.8.1",
        "ServerContext": "host", 
        "PortalContext": "portal", 
        "Credentials": {
            "ServiceAccount": {
                "Password": "password",
                "UserName": "stn\\domain.account", 
                "IsDomainAccount": true,
                "IsMSAAccount": false 
            }
        },
	    "Portal": {
            "LicenseFilePath": "D:\\Install\\ArcGIS_Enterprise_Portal_1081_329921_20200909.json",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "D:\\Install\\Portal_for_ArcGIS_Windows_1081_175214.exe",
                "WebStylesPath": "D:\\Install\\Portal_for_ArcGIS_Web_Styles_Windows_1081_175215.exe",
                "InstallDir": "D:\\ArcGIS\\Portal",
                "ContentDir": "D:\\arcgisportal"
            },
            "ContentDirectoryLocation": "D:\\arcgisportal\\content",
            "ExternalLoadBalancer": "name.ne.gov", 
            "PortalAdministrator": {
                "UserName": "PortalAdmin",
                "Email": "name@email.com",
                "Password": "password",
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": "vanilla"
            }
        },
        "DataStore": {
            "ContentDirectoryLocation": "D:\\arcgisdatastore",
            "EnableFailoverOnPrimaryStop": false,
            "Installer": {
                "Path": "D:\\Install\\ArcGIS_DataStore_Windows_1081_175216.exe",
                "InstallDir": "D:\\ArcGIS\\DataStore"
            }
        },
        "Server": {
            "LicenseFilePath": "D:\\Install\\ArcGISGISServerStandard_ArcGISServer_945029.prvc",
            "Installer": {
                "Path": "D:\\Install\\ArcGIS_Server_Windows_1081_175203.exe",
                "InstallDir": "D:\\ArcGIS\\Server",
                "InstallDirPython": "D:\\Python27"
            },
            "ServerDirectoriesRootLocation": "D:\\arcgisserver\\directories",
            "ConfigStoreLocation": "D:\\arcgisserver\\config-store",
            "ExternalLoadBalancer": "name.ne.gov", 
            "PrimarySiteAdmin": {
                "UserName": "PortalAdmin", 
                "Password": "Password"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "D:\\Install\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_1081_175217.exe"
            }
        }
    }
}

### Expected Behavior

Install the base arcgis enterprise across 4 servers

### Actual Behavior

installed on 3 server except the web adaptor server which is in the dmz.  It requires winrm ssl.

### Steps to Reproduce

run invoke command

### Important Factoids

verified the https winrm listener works.

Are there any additional configurations I need to do to make this work over SSL on port 5986?

**Comment by jsthusker** [comment]
And why isn't -UseSSL a parameter?

**Comment by cameronkroeker** [comment]
Hello @jsthusker,

This feature request has been added in the latest release, v3.3.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.0

Ensure that WinRM HTTPS is enabled on all the target nodes within the deployment as well as the orchestrating node, and to use `-UseSSL` argument with the `-Credential` argument.

https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters#parameters

> Note: The -Credential argument requires a domain account that has access to all the nodes.

```powershell
Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\config\BaseDeployment.json -Mode InstallLicenseConfigure -UseSSL -Credential Domain\username
```

Thanks,
Cameron K.
