### ISSUE TITLE
Dsc v3.2.0 - Rasteranalytics Server - Wrong RasterDataStoreItem UNC path (wrong machine)

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#335]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

3.2.0

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

{
    "AllNodes": [
        {
            "NodeName": "myserver.mydomain.com",
            "Role": [
                "Server",
                "RasterDataStoreItem"
            ],
            "SslCertificates": [
                {
                    "Path": "C:\\setups\\certificates\\xxxx\\xxxxx.pfx",
                    "Password": "xxxxx",
                    "CNameFQDN": "myserver.mydomain.com",
                    "Target": [
                        "Server"
                    ]
                }
            ]
        },
        {
            "NodeName": "mywebadaptor.mydomain.com",
            "Role": [
                "ServerWebAdaptor"
            ],
            "SslCertificates": [
                {
                    "Path": "C:\\setups\\certificates\\xxxxx\\xxxxx.pfx",
                    "Password": "xxxx",
                    "CNameFQDN": "mywebadaptor.mydomain.com",
                    "Target": [
                        "WebAdaptor"
                    ]
                }
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.9",
        "ServerRole": "RasterAnalytics",
        "ServerContext": "imagesite",
        "Credentials": {
            "ServiceAccount": {
                "Password": "xxxxx
                "UserName": "xxxx",
                "IsDomainAccount": true
            }
        },
        "Server": {
            "LicenseFilePath": "xxxx",
            "Installer": {
                "Path": "C:\\setups\\ArcGIS_10.9.0\\ArcGIS_Server_Windows_109_177775.exe",
                "InstallDir": "C:\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27"
            },
            "ServerDirectoriesRootLocation": "\\\\xxxx.file.core.windows.net\\serverdirectories",
            "ConfigStoreLocation": "\\\\xxxx.file.core.windows.net\\configstores",
            "LocalRepositoryPath": "C:\\arcgisserver\\local-config-store",
            "ConfigStoreCloudStorageAccount":{
                "UserName": "xxxx.file.core.windows.net",
                "Password": "xxxxxx",
                "CloudStorageType": "AzureFiles",
                "AzureFileShareName": "configstores",
                "CloudNamespace": "imagesite"
            },
            "ServerDirectoriesCloudStorageAccount":{
                "UserName": "xxxx.file.core.windows.net",
                "Password": "xxxxxxx",
                "CloudStorageType": "AzureFiles",
                "AzureFileShareName": "serverdirectories",
                "CloudNamespace": "imagesite"
            },
            "PrimarySiteAdmin": {
                "UserName": "xxxx",
                "Password": "xxxxx"
            },
            "ExternalLoadBalancer": "mydomain.com"
        },
        "DataStoreItems": {
            "RasterStore": {
                "FileShareLocalPath": "F:\\ArcGISRasterDataStore",
                "FileShareName": "ArcGISRaster"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "C:\\setups\\ArcGIS_10.9.0\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_109_177789.exe"
            }
        },
        "Federation": {
            "PortalHostName": "mywebadaptor.mydomain.com",
            "PortalPort": "443",
            "PortalContext": "portal",
            "PortalAdministrator": {
                "UserName": "xxxx",
                "Password": "xxxx"
            }
        }
    }
}

### Expected Behavior

I expect, that on the image server a local directory f:\ArcGISRasterDataStore is created and shared with the name "ArcGISRaster" and that this path is registered as folder as a raster data store item.
The first part seems to work, that a local directory is created, but the registered item shows up with wrong path. It shows the UNC path with the machine starting the DSC Configuration. In our case we started the DSC Deployment from a jumphost.
![image](https://user-images.githubusercontent.com/24472585/124135047-beb47300-da83-11eb-9a52-be783e3b61f7.png)
![image](https://user-images.githubusercontent.com/24472585/124135088-c542ea80-da83-11eb-899b-d3cc2ca921a8.png)

### Actual Behavior
The registered Data Store Item has a wrong UNC pointing to the machine that started the DSC configuration instead of the machine, where the share has been created before.

### Steps to Reproduce

Run this DSC config from another machine than the image server.

### Important Factoids

Azure On-Prem Virtual Machines, Windows Server 2016 (no ArcGIS Images)

**Comment by lorenzmeyer77** [comment]
@scma-esrich FYI

**Comment by cameronkroeker** [comment]
Hello @lorenzmeyer77,

We will address this in a future release, however here is a workaround in the meantime:

https://github.com/Esri/arcgis-powershell-dsc/blob/78e488fc0aac6f8f4cdf574e1bdb50a7d39ed350/Modules/ArcGIS/Configurations-OnPrem/ArcGISRasterDataStoreItem.ps1#L67

Change to:

```
DataStorePath = if($ExternalFileSharePath){ $ExternalFileSharePath }else{ "\\$($Node.NodeName)\$($FileShareName)" }
```

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hello @lorenzmeyer77,

This has been addressed in the latest release, v.3.3.0.

Thanks,
Cameron K.
