### ISSUE TITLE
Include Variables from the PublishGISService example on Variables Page

### ISSUE THREAD

**Issue by runneals** [Esri/arcgis-powershell-dsc#337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.0

Would like to see the PublishGISService variables included on the Variables page, as they aren't on there.
Also, is it supported to point to a aprx file and have the script publish from that?

**Comment by cameronkroeker** [comment]
Thanks @runneals for this suggestion. We will work on getting the Wiki updated to include definitions for the PublishGISService.json variables.

To answer your question though, the PowerShell DSC ArcGIS Module is limited to publishing two ways, either a [service definition](https://enterprise.arcgis.com/en/server/latest/publish-services/windows/about-service-definition-files.htm#ESRI_SECTION1_4B52ED1F7A6E4ADD83C815E550E2C993) (.sd) file or json file. 

The sd file is published via `rest/services/System/PublishingTools/GPServer/Publish`, and the json file method uses the [Create Service](https://developers.arcgis.com/rest/enterprise-administration/server/createservice.htm) resource.

To publish GIS services use the `Invoke-PublishService` cmdlet command along with the `-ConfigurationParameterFile PublishGISService.json`.

**Example: Publishes a Map Server service type from an sd file and a Map Server service type from a  json file**

```
{
    "ServerNode": "server01",
    "ServerHostName": "server01.esri.com",
    "ServerPort": 443,
    "ServerContext": "server",
    "PublisherAccountCredential": {
        "UserName": "portaladmin",
        "Password": "portaladmin"
    },
    "PortalHostName": "server01.esri.com",
    "PortalPort": 443,
    "PortalContext": "portal",
    "GISServices": [
        {
            "Name": "SampleWorldCities",
            "Type": "MapServer",
            "PathToItemInfoFile": "",
            "PathToSourceFile": "C:\\gis_service_definition_files\\SampleWorldCities.sd",
            "Folder": "test"
        },
        {
            "Name": "SampleWorldCities2",
            "Type": "MapServer",
            "PathToItemInfoFile": "",
            "PathToSourceFile": "C:\\gis_service_json_files\\SampleWorldCities2.json",
            "Folder": "test"
        }
    ]
}
```

**Comment by cameronkroeker** [comment]
The following Wiki Page has been published:

https://github.com/Esri/arcgis-powershell-dsc/wiki/Publishing-GIS-Services-via-the-ArcGIS-Module
