### ISSUE TITLE
ArcGIS Server and Portal WebAdaptor 10.8.1 won't install on IIS

### ISSUE THREAD

**Issue by mareikekoc** [Esri/arcgis-powershell-dsc#340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* ArcGIS Portal und Server Web Adaptor 

### Configuration Files
```
{
    "AllNodes": [
        {
            "NodeName": "server.domain.tld",
            "DataStoreTypes": [
                "Relational",
		"Tile Cache"
            ],
            "Role": [
                "Server",
                "Portal",
                "DataStore",
                "ServerWebAdaptor",
                "PortalWebAdaptor"
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.8.1",
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "UserName": "username",
                "Password": "password",
                "IsDomainAccount": false,
                "IsMSAAccount": false
            }
	},
        "Server": {
            "LicenseFilePath": "C:\\Install\\ArcGISGISServerStandard_ArcGISServer_xxxxxx.prvc",
            "Installer": {
                "Path": "C:\\Installation\\Setup\\Setup.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27"
            },
            "ServerDirectoriesRootLocation": "C:\\arcgisserver\\directories",
            "ConfigStoreLocation": "C:\\arcgisserver\\config-store",
            "LocalRepositoryPath": "C:\\arcgisserver\\local",
            "ServerLogsLocation": "C:\\arcgisserver\\logs",
            "PrimarySiteAdmin": {
                "UserName": "admin",
                "Password": "password"
            }
        },
        "Portal": {
            "LicenseFilePath": "C:\\Install\\License\\ArcGIS_Enterprise_Portal_1081_xxxxxxx_xxxxxxxx.json",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "C:\\Installation\\Setup\\Setup.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\Portal",
                "ContentDir": "C:\\arcgisportal"
            },
            "ContentDirectoryLocation":"C:\\arcgisportal\\content",
            "PortalAdministrator": {
                "UserName": "aadmin",
                "Email": "e-mail",
                "Password": "password",
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": "vanilla"
            }
        },
        "DataStore": {
            "ContentDirectoryLocation": "C:\\arcgis\\datastore",
            "EnableFailoverOnPrimaryStop": false,
            "Installer": {
                "Path": "C:\\Installation\\Setup\\Setup.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\DataStore"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "C:\\Installation\\Setup\\Setup.exe"
            },
							"WebSiteId": 1
        }
	}	
}
```
### Expected Behavior

Installation of the Portal for ArcGIS and ArcGIS Server Web Adaptor.

### Actual Behavior

ArcGIS Server, Portal for ArcGIS and Data Store got installed succesfully with the script. The Installation of the web adaptor fails with the following error message.
```
Trace-DSCJob : 9/7/2021 7:36:43 AM: Filename: \\?\C:\inetpub\wwwroot\server\web.config
Error: Cannot write configuration file
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:240 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 9/7/2021 7:36:43 AM: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed
to Install ServerWebAdaptor
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:240 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 9/7/2021 7:36:43 AM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:240 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
```
### Steps to Reproduce

 Invoke-ArcGISConfiguration -ConfigurationParametersFileconfiguration.json -Mode Install -DebugSwitch

### Important Factoids

Windows Server 2019 Datacenter, empty machine. Nothing except this installation has been done on this machine. 
Machine in Azure (Netherlands)

Manually running WebAdaptorIIS_10.8.1 works fine on the machine (within minutes).

**Comment by cameronkroeker** [comment]
@mareikekoc a similar problem was also reported here:

https://github.com/Esri/arcgis-powershell-dsc/issues/268#issuecomment-646659860

Does the `C:\inetpub\wwwroot\server\web.config` file exist? To resolve the issue I believe they uninstalled the web adaptor, and removed that file.

Thanks,
Cameron K.

**Comment by mareikekoc** [comment]
Hi @cameronkroeker ,

Thanks for your answer. I already saw that thread. Unfortunately, I am not running into the same behaviour because on my testing machine (and two other -the problem ist reproducible) the portal/server folder, thus the web.config is not created in the wwwroot. 

Any other ideas?

Thanks.
Mareike K.

**Comment by cameronkroeker** [comment]
Hi @mareikekoc,

I suspect there is an issue with either the setup archive or extracted setup.exe being used for the installer. Perhaps its an invalid path or invalid file name.

```
"WebAdaptor": {
       "AdminAccessEnabled": true,
       "Installer": {
            "Path": "C:\\Installation\\Setup\\Setup.exe"
        },
	"WebSiteId": 1
 }
```

Could you double check `"Path": "C:\\Installation\\Setup\\Setup.exe"` to ensure its pointing to the correct installer file for ArcGIS Web Adaptor 10.8.1?

**Example 1: Using setup archive from My Esri (in this example dsc will extract it to C:\\Windows\\Temp)**
```
"Installer": {
     "Path": "C:\\archives\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_1081_175217.exe"
},
```

**Example 2: Using a pre-extracted setup (point to the full path where the setup archive was manually extracted to)**
```
"Installer": {
     "Path": "C:\\Users\<username>\\Documents\\ArcGIS 10.8.1\\WebAdaptorIIS\\Setup.exe"
},
```

If this checks out fine, then could you send the entire dsc log files?

Thanks,
Cameron K.

**Comment by mareikekoc** [comment]
Hi @cameronkroeker,

Interesting. Thanks for your notes again. 

You were absolutely right. I thought I had checked the Json 100 times but instead of the Web Adaptor.exe the Portal exe was standing by the Web Adaptor Installer path. This explains of course that why a manual install was successful while the installation with PowerShell failed. It still get a few error messages but the portal and server Web Adaptor got installed and I can go on with my research and testing form here.

Kind regards,
Mareike K.

**Comment by cameronkroeker** [comment]
Thanks @mareikekoc for providing an update! Glad to hear the original issue has been resolved. I'll go ahead and mark this issue as closed, but if you have any additional questions\issues feel free to open a new issue.

Happy Automating!
