### ISSUE TITLE
Support installing ArcGIS Pro 2.8

### ISSUE THREAD

**Issue by jhevenor** [Esri/arcgis-powershell-dsc#345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* ArcGIS Pro

### Configuration Files

```json
{
  ...
  "ProVersion": "2.8",
  ...
}
```

### Expected Behavior

Install ArcGIS Pro 2.8

### Actual Behavior
Installation fails with message 

> Cannot validate argument on parameter 'Version'. The argument "2.8" does not belong to the set
"2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,10.4,10.4.1

### Important Factoids

Setting the version to 2.7 but using the 2.8 installer yields a 'failed' result via DSC, but the installation looks fine otherwise.  It would be nice to throw out some warnings for these newer versions and still attempt the install.  Either that or shorten the release cycle on this project.  ArcGIS Pro is at 2.8.3 at this point, so calling it a new version is being generous. 

### References

A related issue for the same problem for [version 2.7](https://github.com/Esri/arcgis-powershell-dsc/issues/318)

**Comment by cameronkroeker** [comment]
Hello @jhevenor,

Support for ArcGIS Pro 2.8 and 2.9 has been added to v3.3.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.0

Thanks,
Cameron K.
