### ISSUE TITLE
"Uninstall" mode does not remove language packages

### ISSUE THREAD

**Issue by hoge6b01** [Esri/arcgis-powershell-dsc#347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

%

### Expected Behavior

When using the -Uninstall option ArcGIS Server Language Packages should be uninstalled.

### Actual Behavior

Language Packages have to be removed manually.

### Steps to Reproduce

%

### Important Factoids

%

### References

%

**Comment by cameronkroeker** [comment]
Support for uninstalling ArcGIS Server langauge packs has been added in [v3.3.1](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.1).
