### ISSUE TITLE
Support for installing Workflow Manager server and portal app.

### ISSUE THREAD

**Issue by hmelendez** [Esri/arcgis-powershell-dsc#348]
### Question

I found a sample configuration for deploying Workflow Manager Server but those values are not documented on the variables wiki. Also there is no reference as to how to install the Workflow Manager portal app. 
Is this supported? 
If not can I ask that this gets added in a future release?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### References
Sample Workflow Manager Configuration:
https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/v3.2.0/Gis%20Servers/GISServer-WorkflowManager.json

**Comment by cameronkroeker** [comment]
Hello @hmelendez,

Workflow Manager Server is partially supported in v3.2.0. It's not documented because there are a few issues with it such as the service may be in a stopped state at the end of the dsc run (should be able to manually start it). And there isn't support for the portal web app component.

However, we do plan on including full support for both Workflow Manager Server 10.8.1 through 10.9.1 and the portal web app 10.8.1 and 10.9, in the next ArcGIS Module release (v3.3.0).

Stay tuned this is coming soon!

> Note: The portal web app for Workflow Manager is included in the portal setup starting at 10.9.1.

Thanks,
Cameron K.

**Comment by hmelendez** [comment]
Thanks @cameronkroeker. Do you have an ETA on the next release (v3.3.0)?

**Comment by cameronkroeker** [comment]
Hi @hmelendez,

v3.3.0 has been officially release. It can be found in the PowerShell Gallery (`Install-Module ArcGIS`), or also here:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.0

**To install the Workflow Manager web app 10.8.1 or 10.9:**
https://github.com/Esri/arcgis-powershell-dsc/blob/v3.3.0/SampleConfigs/v3/v3.3.0/Base%20Deployment/BaseDeployment-SingleMachine-WorkflowManagerWebapp.json#L150-L154

> Note: Workflow Manager Web App is included in portal setup at 10.9.1, there is no longer a separate installer.

**To install Workflow Manager Server**:
https://github.com/Esri/arcgis-powershell-dsc/blob/v3.3.0/SampleConfigs/v3/v3.3.0/Gis%20Servers/GISServer-WorkflowManager.json

> Note: If you will be running this on the same node as the hosting server, you will need remove the federation block from the json file and manually federate.
