### ISSUE TITLE
Release 0.8.7 shows old version

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#35]
The Release https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v0.8.7-beta Points to an old commit https://github.com/Esri/arcgis-powershell-dsc/commit/5efd6260fcf70c9e1bb116d62970dfadee6e4091 with Version 0.8.3 in ArcGIS.psd1.
Shouldn't it Point to actual master branch https://github.com/Esri/arcgis-powershell-dsc/commit/8ddcf7e4869ccf5e6de1c6b9ed40935d5bde9769 ?

**Comment by nshampur** [comment]
@spitzerr . we are evaluating the best mechanism of delivering off cycle (distinct from ArcGIS Release) patches and the use of release specific branches versus into master.  We may request that you submit PRs off the "active" development branch.  Let us know if you had preferences.

**Comment by shailesh91** [comment]
@spitzerr @nshampur the release is now pointing to the correct branch.

**Comment by spitzerr** [comment]
@shailesh91 Thank you very much.

@nshampur I'd love to have a quick update-cycle for fixes and changes departed from ArcGIS Releases. To develope features, which are bound to new ArcGIS Versions like 10.6NEXT a development branch could be sufficient.
A branch per ArcGIS Version is from my perspective too much effort to merge fixes which rely to multiple versions. therefore tagging some commits as Release Version with hint to Supported ArcGIS Version could be good to go.

**Comment by shailesh91** [comment]
@spitzerr https://github.com/Esri/arcgis-powershell-dsc/tree/release-v0.8.7

**Comment by spitzerr** [comment]
@shailesh91  Thank you very much. 
I was still confused as the ArcGIS.psd1 differs on Github and on powershellgallery. And I was not sure if there are more differences maybe.

**Comment by shailesh91** [comment]
@spitzerr yes, ArcGIS.psd1 manifest file is a little different. We will try to keep it the same from the next release.
