### ISSUE TITLE
ArcGIS Workflow Manager Web App

### ISSUE THREAD

**Issue by dimesv** [Esri/arcgis-powershell-dsc#350]
Hi guys,

Thanks for adding the GISServer-WorkflowManager.json config sample and adding support for Workflow Manager Server role. Really useful.

I am installing ArcGIS Workflow Manager on the same machine acting as a hosting server. Everything seems to go fine except that I still need to go to the Portal and configure the hosting server also with the role of Workflow Manager Server. This is a supported configuration of Workflow Manager and seems to work fine.

Questions:
1. Shouldn't the DSC PowerShell also enable the Workflow Manager Server role when installing the software on the same machine used as a hosting server? 
2. Is there is a way to install ArcGIS Workflow Manager **Web App** as part of this config. This is a separate install to ArcGIS Workflow Manager Server.

Look forward to hear back from you.

Cheers,
Jose
Esri NZ

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

**Comment by cameronkroeker** [comment]
Hi @dimesv,

**1. Shouldn't the DSC PowerShell also enable the Workflow Manager Server role when installing the software on the same machine used as a hosting server?**

This is a limitation of the ArcGIS Module. You will need to run the GISServer-WorkflowManager.json without defining the federation block in the json and manually set it if ran from the same machine as the hosting server.

> Note: This will also be the case in the next release v3.3.0. But we can certainly make this as an enhancement request to be evaluated for a future release!

**2. Is there is a way to install ArcGIS Workflow Manager Web App as part of this config. This is a separate install to ArcGIS Workflow Manager Server.**

No, not in v3.2.0. However, we plan on supporting this in next release v3.3.0:
https://github.com/Esri/arcgis-powershell-dsc/issues/348#issuecomment-971189991

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Support for enabling WorkFlowManager Server role on the hosting server has been added in [v3.3.1](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.1). Additionally support for installing ArcGIS WorkflowManager Web App was added in v3.3.0.
