### ISSUE TITLE
[Error] Failed to Install Microsoft ODBC Driver 17 for SQL Server

### ISSUE THREAD

**Issue by dimesv** [Esri/arcgis-powershell-dsc#352]
Hi guys,

I have used the changes you have introduced with v3.3.0 and have few issues installing SQLServerClient.
My settings are as follows:

"SQLServerClient": [
            {
                "Name": "Microsoft ODBC Driver 17 for SQL Server",
                "InstallerPath": "C:\\Temp\\Microsoft_ODBC_Driver_17_SQL_Server_64bit_180251.exe",
                "ProductId": "72AFAF21-33FB-45A5-9468-A9EC07427F82",
                "Arguments": " /quiet /qn IACCEPTMSODBCSQLLICENSETERMS=YES ADDLOCAL=ALL"
            }
        ]

The software is installed, then the DSC moves on as follows:
- [[ArcGIS_InstallMsiPackage]AIMP_Microsoft_ODBC_Driver_17_for_SQL_Server] Validating the Microsoft ODBC Driver 17 for SQL Server Installation 
- [[ArcGIS_InstallMsiPackage]AIMP_Microsoft_ODBC_Driver_17_for_SQL_Server] Testing MSI Package - Attempt 1
- [[ArcGIS_InstallMsiPackage]AIMP_Microsoft_ODBC_Driver_17_for_SQL_Server] Testing MSI Package - Attempt 2
- [[ArcGIS_InstallMsiPackage]AIMP_Microsoft_ODBC_Driver_17_for_SQL_Server] Testing MSI Package - Attempt 3
- [[ArcGIS_InstallMsiPackage]AIMP_Microsoft_ODBC_Driver_17_for_SQL_Server] [Error] Failed to Install Microsoft ODBC Driver 17 for SQL Server

Do you guys have any idea what the issue might be? The sql client was downloaded from the myesri web site in the 10.9.1 downloads section.

Cheers,
Jose

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

**Comment by shailesh91** [comment]
@dimesv can you please make sure the product id for the Microsoft_ODBC_Driver_17_SQL_Server_64bit_180251.exe matches "72AFAF21-33FB-45A5-9468-A9EC07427F82"?

**Comment by cameronkroeker** [comment]
Hello @dimesv,

The correct product id for Microsoft_ODBC_Driver_17_SQL_Server_64bit_180251.exe is `7453C0F5-03D5-4412-BB8F-360574BE29AF`. 

```powershell
PS C:\Windows\System32> get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize

IdentifyingNumber                      Name                                      LocalPackage
-----------------                      ----                                      ------------
{7453C0F5-03D5-4412-BB8F-360574BE29AF} Microsoft ODBC Driver 17 for SQL Server   C:\windows\Installer\56d09309.msi
```

Thanks,
Cameron K.

**Comment by dimesv** [comment]
Hi @cameronkroeker ,

Thanks heaps for helping out. Super useful and worked perfectly.

Cheers,
Jose

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker ,
> 
> Thanks heaps for helping out. Super useful and worked perfectly.
> 
> Cheers, Jose

Glad to hear the installed worked.

Thanks,
Cameron K.
