### ISSUE TITLE
[Error] Upgrade Portal 10.9.1

### ISSUE THREAD

**Issue by chandenis** [Esri/arcgis-powershell-dsc#353]
Hi, when I try to upgrade an all-in-one Base Deployment from 10.9 to 10.9.1, it throw the following error.

![image](https://user-images.githubusercontent.com/3466977/142573946-b16ffc59-b3b9-4896-b11d-8dcc8931cf76.png)

And here is the log output
[PortalUpgradeV2-11-19-2021-2-33-31-AM-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/7568165/PortalUpgradeV2-11-19-2021-2-33-31-AM-Verbose.txt)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.0

### Affected Resource(s)

* ArcGIS_Portal

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Steps to Reproduce
Run the command  
Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\Software\BaseDeployment-SingleMachine_SampleUpgrade.json -Mode Upgrade -DebugSwitch

**Comment by shailesh91** [comment]
@chandenis did you add the parameter "OldVersion" to "ConfigData" block of your json before upgrading?

**Comment by chandenis** [comment]
@shailesh91 yes, i did.

This is the file used.

[BaseDeployment-SingleMachine_SampleUpgradeTEST.txt](https://github.com/Esri/arcgis-powershell-dsc/files/7570167/BaseDeployment-SingleMachine_SampleUpgradeTEST.txt)

**Comment by cameronkroeker** [comment]
Hi @chandenis,

This error/issue can be caused by having multiple versions of the ArcGIS Module on the same node. Let's remove all previous versions of the ArcGIS Module, close the powershell cmdlet, then re-launch, and re-run.

Check the following location: `C:\Program Files\WindowsPowerShell\Modules\ArcGIS`

Thanks,
Cameron K.

**Comment by chandenis** [comment]
Hi @cameronkroeker ,

Thanks. It works as expected after remove the previous version. 

Regards,
Denis

**Comment by chandenis** [comment]
Hi @cameronkroeker ,

after the upgrade, i found the server patch didn't installed (ArcGIS Server 10.9.1 Machine Rename Patch) even I put the PatchesDir parameter in the Server block. is it normal?

Regards,
Denis

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker ,
> 
> after the upgrade, i found the server patch didn't installed (ArcGIS Server 10.9.1 Machine Rename Patch) even I put the PatchesDir parameter in the Server block. is it normal?
> 
> Regards, Denis

Glad to hear the upgrade went through successfully after removing the previous versions of the module.

Yes, this is expected. Patches will only install with the following modes:

- `-Mode Install`
- `-Mode InstallLicense`
- `-Mode InstallLicenseConfigure`

Thanks,
Cameron K.

**Comment by scma-esrich** [comment]
@cameronkroeker, wouldn't it make sense to install patches after a successful upgrade still within the DSC-processes? Exactly for cases like this?

**Comment by cameronkroeker** [comment]
> @cameronkroeker, wouldn't it make sense to install patches after a successful upgrade still within the DSC-processes? Exactly for cases like this?

Hi @scma-esrich,

Yes, I agree this is a valid use case. It is something we can explore\evaluate adding support for in a future release.

Thanks,
Cameron K.

**Comment by pcsswamin** [comment]
@cameronkroeker<https://github.com/cameronkroeker> – I second this request. This would be valuable feature to add.
