### ISSUE TITLE
[Error] Install 10.9.1 Single Machine Base Deployment

### ISSUE THREAD

**Issue by vassilo** [Esri/arcgis-powershell-dsc#354]
Hi, when I try to do an all-in-one Base Deployment of 10.9.1, it throw the following error. I don't have any Workflow Manager configured to install.

![image](https://user-images.githubusercontent.com/6457056/142625694-140813a0-c533-4673-bf58-f1189a7ef8f9.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.0

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

Configuration to complete

### Actual Behavior

Fails

### Steps to Reproduce

Invoke-ArcGISConfiguration -ConfigurationParametersFile ""C:\Deploy\BaseDeployment-SingleMachine.json" -Mode InstallLicenseConfigure -DebugSwitch

**Comment by cameronkroeker** [comment]
Hi @vassilo,

Would you be able to share your json file used, and dsc logs? Feel free to remove all sensitive information such as passwords.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @vassilo,

The error you are experiencing can be caused by having multiple versions of the ArcGIS Module installed. Let's ensure all previous versions of the module are removed.

For example, check the following location `C:\Program Files\WindowsPowerShell\Modules\ArcGIS` to ensure only one version exists. If there are multiple versions, remove all but 3.3.0, close the powershell cmdlet, then re-launch a fresh cmdlet and re-run.

Thanks,
Cameron K.

**Comment by vassilo** [comment]
Hi @cameronkroeker 

It was indeed the fact that 3.2.0 was still in the module directory that was causing the problem. Once removed it carried on with the install and configuration.

Thanks,
Vassilo.

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker
> 
> It was indeed the fact that 3.2.0 was still in the module directory that was causing the problem. Once removed it carried on with the install and configuration.
> 
> Thanks, Vassilo.

Hi @vassilo,

Yay, glad to hear the issue has been resolved.

Thanks,
Cameron K.
