### ISSUE TITLE
Upgrade from 10.9 to 10.9.1 failing: WebAdaptorUninstall.ps1 missing

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.0

### Affected Resource(s)

* ArcGIS_WebAdaptor

### Configuration Files

[IndoorsDeployment_Upgrade_Anonymous.txt](https://github.com/Esri/arcgis-powershell-dsc/files/7583009/IndoorsDeployment_Upgrade_Anonymous.txt)

### Expected Behavior

Upgrade should start and webadaptor uninstalled.

### Actual Behavior

Upgrade does not start and I got the following error:
```
WebAdaptor Uninstall
Dot Sourcing the Configuration:- WebAdaptorUninstall
. : The term 'C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configurations-OnPrem\Upgrades\WebAdaptorUninstall.ps1' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:225 char:7
+     . "$PSScriptRoot\$($ConfigurationFolderPath)\$($ConfigurationName ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...orUninstall.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
& : The term 'WebAdaptorUninstall' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:227 char:6
+     &$ConfigurationName @Arguments -Verbose
+      ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (WebAdaptorUninstall:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
```
### Steps to Reproduce

Upgrade an ArcGIS Enterprise  from 10.9 to 10.9.1 using the config file below with the following command:
```
Invoke-ArcGISConfiguration -ConfigurationParametersFile D:\GIS\scripts\config\IndoorsDeployment_Upgrade.json -Credential (Get-Credential) -Mode Upgrade 
```

### Important Factoids

File seems indeed missing from 3.3.0 release:
https://github.com/Esri/arcgis-powershell-dsc/tree/v3.3.0/Modules/ArcGIS/Configurations-OnPrem/Upgrades

**Comment by cameronkroeker** [comment]
Hi @Biboba,

Could you please verify that all previous versions of the ArcGIS Module have been removed, and only v3.3.0 exists?

`C:\Program Files\WindowsPowerShell\Modules\ArcGIS`

The WebAdaptorUninstall has been moved into a different location with v3.3.0:

https://github.com/Esri/arcgis-powershell-dsc/blob/v3.3.0/Modules/ArcGIS/Configurations-OnPrem/Upgrades/WebAdaptorUpgrade.ps1#L55

Thanks,
Cameron K.

**Comment by Biboba** [comment]
Hi @cameronkroeker,

I am afraid there is only 3.3.p in ```C:\Program Files\WindowsPowerShell\Modules\ArcGIS```

Thanks

**Comment by Biboba** [comment]
Well... it was kind of related I guess. 
I restarted Powershell IDE and it worked...
Thanks for your quick reply !
