### ISSUE TITLE
Access Software on Network Shares

### ISSUE THREAD

**Issue by vassilo** [Esri/arcgis-powershell-dsc#356]
Hi,

We have a situation where all our development machines are not on the domain, and we would like to start using the DSC scripts to make our deployments more streamlined and standardised. However, as the DSC uses the LOCAL\SYSTEM account this makes it impossible to have the software sitting on a common fileserver (which is on the domain).

Is there any way around not having to copy the software onto the local machine before running the install?

Regards,
Vassilo

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.0

### Affected Resource(s)

* All

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Steps to Reproduce

Run the DSC installation

**Comment by cameronkroeker** [comment]
Hi @vassilo,

In order to use a common network file share that's on a domain you will need to grant each target node's NT\Authority System (LocalSystem) account access to the share. Here is a third party resource that may help:

https://serverfault.com/a/135874

Thanks,
Cameron K.

**Comment by vassilo** [comment]
Hi @cameronkroeker 

With the machines on the domain it is not a problem, that I have got working. It is more what to do with machines that are not on a domain but still need to access a common fileshare.

Regards,
Vassilo
