### ISSUE TITLE
Invoke-ArcGISConfiguration fails during installation from remote hosts

### ISSUE THREAD

**Issue by alexanderwalkowski** [Esri/arcgis-powershell-dsc#358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.0

### Affected Resource(s)

* ArcGIS Pro

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "server.domain.de",
            "Role": [
                "Pro"
            ]
        }
    ],
    "ConfigData": {
        "ProVersion": "2.9",
        "Pro": {
            "AuthorizationType": "NAMED_USER",
            "BlockAddIns": "0",
            "LockAuthSettings": false,
            "AllUsers": "1",
            "EnableEUEI": true,
            "CheckForUpdatesAtStartup": true,
            "Installer": {
                "Path": "C:\\data\\test\\installation\\ArcGISPro_29_179927.exe",
                "InstallDir": "C:\\bin\\ArcGIS\\Pro"
            }
        }
    }
}
```

### Expected Behavior
Invoke-ArcGISConfiguration allows to install ArcGIS Pro from a remote Host.

### Actual Behavior
The Command ``Invoke-ArcGISConfiguration -ConfigurationParametersFile ./Desktop-Float.json -Mode InstallLicenseConfigure -EnableMSILogging`` fails, if executed from a remote machine. Error Message translated from German is:
```
PS C:\data\dsc\ArcGISPro> Invoke-ArcGISConfiguration -ConfigurationParametersFile ./Pro-Named.json -Mode InstallLicenseConfigure -EnableMSILogging -DebugSwitch
Dot Sourcing the Configuration:- ArcGISInstall
Write-NodeMOFFile : Invalid MOF-Definition for Node "server.domain.de": Ecxeption during call of "ValidateInstanceText" with1 Argument:  "undefined property "EnableMSILogging".
 In line: 21, col: 2
 buffer:
 = "ArcGISInstall";
};^
insta
"
In C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2369 col:21
+ ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile
compilation error while processing Configuration "ArcGISInstall". 
In C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 col:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (ArcGISInstall:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration
```
With ArcGIS Desktop I tested, that the installation works, if I am on the target machine. Invocation from a remote host yielded in the same error.

### Steps to Reproduce
* copy Installation media to the target system
* install ArcGIS DSC module via powershell gallery on the target host as well on the source host
* execute the command ``Invoke-ArcGISConfiguration -ConfigurationParametersFile ./Pro-Named.json -Mode InstallLicenseConfigure -EnableMSILogging -DebugSwitch`` on the source host.

**Comment by cameronkroeker** [comment]
Hi @alexanderwalkowski,

Based on the error `"undefined property "EnableMSILogging"`, I suspect there could be older/previous versions of the ArcGIS Module on the source host, and/or target host.

Could you ensure all previous versions of the ArcGIS Module are removed, and only v3.3.0 remains? Then close the PowerShell Window, launch a fresh PowerShell Window and re-run.

Thanks,
Cameron K.

**Comment by alexanderwalkowski** [comment]
Hi @cameronkroeker,
Thank you for the quick response! Your are right, I had several older versions of the ArcGIS DSC module on my source machine, after uninstalling them (`Uninstall-Module -Name ArcGIS -AllVersions`) and installing the latest version, the remote execution works. At least it starts and fails with an error that the installation exe is not found or inaccessible.
Kind regards,
Alexander Walkowski

**Comment by alexanderwalkowski** [comment]
After fixing a typo the installation process starts and extracts the files. But after that, it fails with the message, that Setup.exe was not found.
```
01.12.2021 12:32:14: [DSC0004W]: LCM:  [ Start  Set      ]
01.12.2021 12:32:29: [DSC0004W]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]ProInstall]
01.12.2021 12:32:29: [DSC0004W]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]ProInstall]
01.12.2021 12:32:40: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Installed Version
01.12.2021 12:32:40: [DSC0004W]: LCM:  [ End    Test     ]  [[ArcGIS_Install]ProInstall]  in 9.5590 seconds.
01.12.2021 12:32:40: [DSC0004W]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]ProInstall]
01.12.2021 12:32:40: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Self Extracting Installer
01.12.2021 12:32:40: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Extracting C:\data\test\installation\ArcGISPro_29_179927.exe to C:\windows\TEMP\AD53732E-507C-4A7F-B451-BE7EA01D0832
01.12.2021 12:34:45: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Done Extracting. Waiting 15 seconds to allow the extractor to close files
01.12.2021 12:35:00: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Setup.exe not found in extracted contents
01.12.2021 12:35:00: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Executable .exe not found in extracted contents to install. Looking for .msi
01.12.2021 12:35:00: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Logs for Pro will be written to C:\windows\TEMP\Pro_install.log
01.12.2021 12:35:00: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Executing msiexec
01.12.2021 12:35:05: [DSC0004W]: LCM:  [ End    Set      ]  [[ArcGIS_Install]ProInstall]  in 143.2350 seconds.
```

In the mentioned temp directory is only a `ArcGISPro.msi`, but no .exe.

**Comment by cameronkroeker** [comment]
> After fixing a typo the installation process starts and extracts the files. But after that, it fails with the message, that Setup.exe was not found.
> 
> ```
> 01.12.2021 12:32:14: [DSC0004W]: LCM:  [ Start  Set      ]
> 01.12.2021 12:32:29: [DSC0004W]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]ProInstall]
> 01.12.2021 12:32:29: [DSC0004W]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]ProInstall]
> 01.12.2021 12:32:40: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Installed Version
> 01.12.2021 12:32:40: [DSC0004W]: LCM:  [ End    Test     ]  [[ArcGIS_Install]ProInstall]  in 9.5590 seconds.
> 01.12.2021 12:32:40: [DSC0004W]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]ProInstall]
> 01.12.2021 12:32:40: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Self Extracting Installer
> 01.12.2021 12:32:40: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Extracting C:\data\test\installation\ArcGISPro_29_179927.exe to C:\windows\TEMP\AD53732E-507C-4A7F-B451-BE7EA01D0832
> 01.12.2021 12:34:45: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Done Extracting. Waiting 15 seconds to allow the extractor to close files
> 01.12.2021 12:35:00: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Setup.exe not found in extracted contents
> 01.12.2021 12:35:00: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Executable .exe not found in extracted contents to install. Looking for .msi
> 01.12.2021 12:35:00: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Logs for Pro will be written to C:\windows\TEMP\Pro_install.log
> 01.12.2021 12:35:00: [DSC0004W]:                            [[ArcGIS_Install]ProInstall] Executing msiexec
> 01.12.2021 12:35:05: [DSC0004W]: LCM:  [ End    Set      ]  [[ArcGIS_Install]ProInstall]  in 143.2350 seconds.
> ```
> 
> In the mentioned temp directory is only a `ArcGISPro.msi`, but no .exe.

Hi @alexanderwalkowski, glad to hear removing the previous modules resolved the original issue. As for the second issue regarding the error of setup.exe not found this is expected and normal since ArcGIS Pro uses an msi. Here it states it cannot find an exe and its looking for .msi:

```
Executable .exe not found in extracted contents to install. Looking for .msi
```
Then next message states its creating an msi log file of the installation, so if the installation fails check this log along with Windows Event Viewer application logs:
```
Logs for Pro will be written to C:\windows\TEMP\Pro_install.log
```

And then it reports its executing the msi:
```
Executing msiexec
```

143 seconds is little over 2 minutes which is definitely too fast and didnt install properly. Since its running the install silently it will also fail silently. I recommend checking the msi installation log (C:\windows\TEMP\Pro_install.log) along with Windows Event Viewer application logs, there should be more clues in there as to why the install has failed.

I also recommend ensuring Microsoft .Net 4.8 is installed on the target node, as this is required for ArcGIS Pro. Perhaps this could be why the pro installation is failing.

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Deploy-an-ArcGIS-Pro-Named-User#prepare-your-deployment

https://pro.arcgis.com/en/pro-app/latest/get-started/arcgis-pro-system-requirements.htm#ESRI_SECTION1_B0E8A42B0E51439784E727AD94534B85

Thanks,
Cameron K.

**Comment by alexanderwalkowski** [comment]
Hi @cameronkroeker,
Thank you very much for your help! Indeed the .NET Framework 4.8 was missing. I assumed, that this would get installed by the arcgis-powershell-dsc framework as well. But after installing the .NET framework 4.8, the installation of ArcGIS Pro worked fine.
Thanks a lot and kind regards,
Alexander

**Comment by mjperez-usgs** [comment]
Hi, would it be possible to add this information about conflicting module versions to the wiki? I have spent many hours today trying to troubleshoot this issue when doing an upgrade - during which there will almost always be a previous version installed from the last install.
