### ISSUE TITLE
ArcMapRuntime and DotNetSupport are not installed when upgrading despite setting Parameters in config true

### ISSUE THREAD

**Issue by niol-esrich** [Esri/arcgis-powershell-dsc#359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

3.3.0

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files
![image](https://user-images.githubusercontent.com/95741390/145169283-2a135bdc-422c-432a-b6da-aa85830ed928.png)

```
"EnableArcMapRuntime": true
"EnableDotNetSupport": true
```

### Expected Behavior

Upgrading from ArcGIS Enterprise BaseDeployment from 10.8.1 or 10.9 to 10.9.1
With both Parameters set to true , the DotNet and ArcMap Runtime and Python 2.7 should be installed with mode -upgrading

### Actual Behavior

Both are not installed and need to be manually installed.
https://enterprise.arcgis.com/en/server/latest/administer/windows/disable-arcmap-runtime.htm

### Steps to Reproduce

Run
`Invoke-ArcGISConfiguration -ConfigurationParametersFile <config.json> -Mode upgrading`

**Comment by niol-esrich** [comment]
@scma-esrich

**Comment by niol-esrich** [comment]
Hi @shailesh91 
thank you for verifying this issue. 
Do you have any inputs or ideas for a possible workaround?
Best regards,
Olivier

**Comment by shailesh91** [comment]
@niol-esrich a possible workaround is replacing `$Version` with `$cf.ConfigData.Version` in the following lines

https://github.com/Esri/arcgis-powershell-dsc/blob/6a8456bedc0993b8ad4cf6fbaee56d4949b049b4/Modules/ArcGIS/ArcGIS.psm1#L2135-L2136
 
![image](https://user-images.githubusercontent.com/3657525/145253825-bf0e5e2f-c55b-4738-a833-f7629af22559.png)

**Comment by niol-esrich** [comment]
@shailesh91 
Thank you for your quick reply. With this workaround we were able to upgrade successfully.

**Comment by ZianAtFirstWatch** [comment]
The workaround resulted in a crash when I ran it with a configuration Json file that did not define the value for the EnableArcMapRuntime or EnableDotnetSupport properties. My workaround was to set those 2 values to $True and comment out the existing code inside ArcGIS.psm1 at the two lines that @shailesh91 mentioned.

**Comment by cameronkroeker** [comment]
This bug has been addressed in [v3.3.1](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.1).
