### ISSUE TITLE
Federation of Image and GeoEvent Server gets stuck "Get Portal oken from..."

### ISSUE THREAD

**Issue by mareikekoc** [Esri/arcgis-powershell-dsc#361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.0

### Affected Resource(s)

* ArcGIS Image Server
* ArcGIS GeoEvent Server
* ArcGIS Portal

### Expected Behavior

We installed a Mulit-Machine Deployment via DSC. Portal, Hosting Server, Data Store, GeoEvent Server and Image Server on seperate machines. 

Expectation would be that the compontens für ArcGS Image Server and GeoEvent Server get installed, licensed and then federated with Portal for ArcGIS.

### Actual Behavior

The installation of the base deployment went smoothly and the federation with the Hosting Server (also on a seperate machine) worked as well. With GeoEvent Server and ArcGIS Image Server the installation and licensing were completed successfully but both deployments get stuck while federating with Portal for ArcGIS. 

The logs state that the machines are trying to get a portal token
12/28/2021 9:59:56 AM: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
12/28/2021 9:59:56 AM: An LCM method call arrived from computer MACHINE with user sid S-1-5-21-3275456840-540740917-969043790-1251.
12/28/2021 10:00:01 AM: [Image Server]: LCM:  [ Start  Set      ]
12/28/2021 10:00:01 AM: [Image Server]: LCM:  [ Start  Resource ]  [[ArcGIS_Federation]Federate]
12/28/2021 10:00:01 AM: [Image Server]: LCM:  [ Start  Test     ]  [[ArcGIS_Federation]Federate]
12/28/2021 10:00:01 AM: [Image Server]:                            [[ArcGIS_Federation]Federate] Get Portal Token from Deployment 'machine.domain.de'

There is no error message shown. The installation just gets stuck at this point. 

### Steps to Reproduce
Since this behaviour occurs with two servers it could be a communicational problem. We checked if we can reach the the urls from the machines, ports are open and it workd fine with the Hosting server. 

Is this a known behaviour? Has anyone a idea what the reason for this behaviour could be?

**Comment by cameronkroeker** [comment]
Hi @mareikekoc,

Lets check the values used for the attributes within the **ConfigData.Federation** block. Is the federation going through the PortalWebAdaptor, ExternalLoadBalancer\Reverse Proxy or directly through the portal itself via 7443? 

For example, directly through portal using 7443:
```
"Federation": {
            "PortalHostName": "PortalMachine.domain.de",
            "PortalPort": "7443",
            "PortalContext": "arcgis",
            "PortalAdministrator": {
                "UserName": "portaladmin",
                "Password": "portaladmin"
            }
        }
```

this will construct the url as `https://PortalMachine.domain.de:7443/arcgis`

or PortalWebAdaptor:

```
"Federation": {
            "PortalHostName": "PortalWebAdaptorMachine.domain.de",
            "PortalPort": "443",
            "PortalContext": "portal",
            "PortalAdministrator": {
                "UserName": "portaladmin",
                "Password": "portaladmin"
            }
        }
```
this will construct the url as `https://PortalWebAdaptorMachine.domain.de/portal`

Perhaps it may be helpful to check the ArcGISFederation-Verbose.txt log file in the dsc logs from the hosting server run to see what values were used for the POST requests, and we can use these for the **ConfigData.Federation** block of the ArcGIS GeoEvent Server and Image Server.

Thanks,
Cameron K.

**Comment by mareikekoc** [comment]
Hey Cameron, 
Thanks a lot for your fast reply. It already helped :-)
We are quite new to PowerShell and thought that the PortalContext is just stating that the Server should be federated with the defined portal. But knowing it is the Web Adaptor Name it makes sense. 

We had
"Federation": {
            "PortalHostName": "PortalMachine.domain.de",
            "PortalPort": "7443",
            "PortalContext": "portal",
            "PortalAdministrator": {
                "UserName": "portaladmin",
                "Password": "portaladmin"
            }
        }

in the federation blog and changed it to 
"Federation": {
            "PortalHostName": "PortalMachine.domain.de",
            "PortalPort": "7443",
            "PortalContext": "arcgis",
            "PortalAdministrator": {
                "UserName": "portaladmin",
                "Password": "portaladmin"
            }
        }

and now it worked. 

Unfortunately the federated Server website in Portal looks strange. It shows a comma in front of Hosting Server and there is no Server role defined for GeoEvent Server:
![Federated_Server](https://user-images.githubusercontent.com/90269191/147742358-e0aee536-31d2-40cf-8d45-cc43bd87f261.jpg)

For Image Server Server it looks as it should be. As far as i can see this has no influence on the functionality. At least for the Hosting Server. Publishing works for example. 

Do you also have an idea what a reason for this behaviour could be?

Thanks a lot. 
Mareike K.
