### ISSUE TITLE
Error after GIS Server site creation - "Undefined property IsWorkflowManagerDeployment

### ISSUE THREAD

**Issue by vassilo** [Esri/arcgis-powershell-dsc#366]
After the ArcGIS GIS Server site has been created I am getting the following error, even though there is no Workflow Manager deployment involved.

![image](https://user-images.githubusercontent.com/6457056/150063891-6e25b27e-007d-409b-a0c3-2bf40b4a5357.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.0

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

```
"ConfigData": {    
        "Version": "10.8.1",
        "ServerContext": "hosting",
        "PortalContext": "portal",
        "FileShareLocalPath": "F:\\Software",
        "FileShareName": "\\\\mneu-d-a-agsh10.anglo.local\\Software",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "Password": "<removed>",
                "UserName": "<domain account>",
                "IsDomainAccount": true,
                "IsMSAAccount": false
            }
        },
        "Server": {
            "LicenseFilePath": "\\\\mneu-d-a-agsh10.anglo.local\\Software\\Esri\\ArcGIS\\10.8.1\\Licenses\\gis-server-adv.ecp",
            "Installer": {
                "Path": "\\\\mneu-d-a-agsh10.anglo.local\\Software\\Esri\\ArcGIS\\10.8.1\\Installs_DSC\\ArcGIS_Server_Windows_1081_175203.exe",
                "InstallDir": "E:\\Program Files\\ArcGIS\\Server",
                "InstallDirPython": "E:\\Python27",
                "PatchesDir": "\\\\mneu-d-a-agsh10.anglo.local\\Software\\Esri\\ArcGIS\\10.8.1\\Patches_DSC\\Server"
            },
            "ServerDirectoriesRootLocation": "F:\\arcgis\\hosting\\directories",
            "LocalRepositoryPath": "F:\\arcgis\\hosting\\local",
            "ServerLogsLocation": "F:\\arcgis\\hosting\\logs",            
            "ExternalLoadBalancer": "<removed>",
            "InternalLoadBalancer": "",
            "PrimarySiteAdmin": {
                "UserName": "siteadmin",
                "Password": "<removed>"
            },
            "ConfigStoreCloudStorageAccount":{
                "UserName": "mneustdevarcgishub001.file.core.windows.net",
                "Password": "<removed>",
                "CloudStorageType": "AzureFiles",
                "AzureFileShareName": "arcgis",
                "CloudNamespace": "dev"
            },
            "ServerDirectoriesCloudStorageAccount":{
                "UserName": "mneustdevarcgishub001.file.core.windows.net",
                "Password": "<removed>",
                "CloudStorageType": "AzureFiles",
                "AzureFileShareName": "arcgis",
                "CloudNamespace": "dev"
            }
        },
```

### Expected Behavior

It should carry on with the install.

### Actual Behavior

Failing to continue due to the error.

### Steps to Reproduce

I just run the script. Not sure what is causing the error.

**Comment by cameronkroeker** [comment]
Hi @vassilo,

The error you are experiencing can be caused by having multiple versions of the ArcGIS Module installed. Let's ensure all previous versions of the module are removed.

For example, check the following location C:\Program Files\WindowsPowerShell\Modules\ArcGIS to ensure only one version exists. If there are multiple versions, remove all but 3.3.0, close the powershell cmdlet, then re-launch a fresh cmdlet and re-run.

https://github.com/Esri/arcgis-powershell-dsc/issues/354#issuecomment-975073570

Thanks,
Cameron K.

**Comment by vassilo** [comment]
Hi @cameronkroeker 

I will go and hang my head in shame. It was indeed the problem. Should have checked that first before posting.
Thanks for the help.

Regards,
Vassilo
