### ISSUE TITLE
Portal License not applying with "The portal site has not been upgraded. Please upgrade the site and try again."

### ISSUE THREAD

**Issue by dmoiler** [Esri/arcgis-powershell-dsc#372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.0

### Affected Resource(s)

ArcGIS_Portal

### Configuration Files

```

{
    "AllNodes": [{
            "NodeName": "VMCLIENTDS1",
            "DataStoreTypes": [
                "Relational"
            ],
            "Role": [
                "DataStore"
            ]
        }, {
            "NodeName": "VMCLIENTWEB1",
            "Role": [
                "ServerWebAdaptor",
                "PortalWebAdaptor"
            ]
        }, {
            "NodeName": "VMCLIENTMAPS",
            "Role": [
                "Portal"
            ]
        }, {
            "NodeName": "VMCLIENTAGS1",
            "Role": [
                "Server"
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.9.1",
        "ServerContext": "agsmapservice",
        "PortalContext": "arcgis",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "Password": "secret",
                "UserName": "DOMAIN\\installer",
                "IsDomainAccount": true,
                "IsMSAAccount": false
            }
        },
        "Server": {
            "LicenseFilePath": "E:\\administration\\licenses\\10.9.1\\ArcGISGISServerStandard_ArcGISServer_1136407.prvc",
            "Installer": {
                "Path": "E:\\apps\\content\\Installs\\ArcGIS 10.9.1\\ArcGISServer\\Setup.exe",
                "InstallDir": "E:\\apps\\esri\\Server",
                "InstallDirPython": "E:\\apps\\python\\python-27\\",
                "EnableArcMapRuntime": "True",
                "EnableDotnetSupport": "False"
            },
            "ServerDirectoriesRootLocation": "E:\\agstore\\arcgisserver\\directories",
            "ConfigStoreLocation": "E:\\agstore\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": "admin",
                "Password": "secret"
            }
        },
        "Portal": {
            "LicenseFilePath": "E:\\administration\\licenses\\10.9.1\\ArcGIS_Enterprise_Portal_1091_374355_20220203.json",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "E:\\apps\\content\\Installs\\ArcGIS 10.9.1\\PortalForArcGIS\\Setup.exe",
                "InstallDir": "E:\\apps\\esri\\Portal",
                "ContentDir": "E:\\agstore\\arcgisportal"
            },
            "ContentDirectoryLocation": "E:\\agstore\\arcgisportal\\content",
            "PortalAdministrator": {
                "UserName": "admin",
                "Email": "blank@blank.com",
                "Password": "secret",
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": "secretanswer"
            }
        },
        "DataStore": {
            "ContentDirectoryLocation": "E:\\agstore\\relational",
            "EnableFailoverOnPrimaryStop": false,
            "Installer": {
                "Path": "E:\\apps\\content\\Installs\\ArcGIS 10.9.1\\ArcGISDataStore\\Setup.exe",
                "InstallDir": "E:\\apps\\esri\\DataStore"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "E:\\apps\\content\\Installs\\ArcGIS 10.9.1\\WebAdaptorIIS\\Setup.exe"
            },
            "AdminAccessEnabled": true
        }
    }
}

```

### Expected Behaviour

Portal should have authorised using json license file and finished initial site configuration.

### Actual Behaviour

I get a message indicating the portal site has not been upgraded. 
It's a fresh install, but understand these configuration commands are run as part of configuration so looks as though issues relate to license file not applying.

```
PowerShell DSC resource ArcGIS_Portal  failed to execute Set-TargetResource functionality with error message: 
[Error] - Response:- 
  {
      "status": "error",
      "messages": ["The portal site has not been upgraded. Please upgrade the site and try again."],
      "isUpgrade": true,
      "resources": ["license"],
      "isPortalLicensed": true,
      "isLicenseFileRequired": true,
      "isUserTypeLicensing": true,
      "version": "10.9.1"
  }
The SendConfigurationApply function did not succeed.
```

When accessing the portal site via browser it looks as though it could be continued if portal license is applied manually:

> Import License File and Continue Portal Upgrade

### Steps to Reproduce

Run the following:

> Invoke-ArcGISConfiguration E:\administration\configuration\install\BaseDeployment-MultiMachine.json

### Important Factoids

1. Running in an on premise Windows Server 2019.
2. The ArcGIS Server and Portal license file paths were initially incorrect and failures occurred due to bad file paths. These have been corrected and ArcGIS Server has authorised successfully via the script, but Portal does not want to continue.

**Comment by cameronkroeker** [comment]
Hi @dmoiler,

If this is a fresh installation, and not an upgrade, then portal is in a bad state. Portal appears to be stuck in "upgrade" mode, `"isUpgrade": true,` rather than fresh site mode.

You can confirm this by navigating to https://VMCLIENTMAPS.yourdomain.com:7443/arcgis/home, it likely says "Upgrade" rather than "Create or Join Site".

I recommend uninstalling, deleting the installation directory and content directory, and trying again.

Thanks,
Cameron K.

**Comment by dmoiler** [comment]
Hi Cameron,

Thanks for the quick response.

Yes Portal site gives me: Import License File and Continue Portal Upgrade

I will perform the uninstall and try running install once more as suggested and will report back with the outcome.

Thanks,

Dean

**Comment by dmoiler** [comment]
Hi Cameron,

After performing uninstall, clearing site content and then install all applications loaded as expected:

```
Invoke-ArcGISConfiguration E:\administration\configuration\install\BaseDeployment-MultiMachine.json -Mode Uninstall
Invoke-ArcGISConfiguration E:\administration\configuration\install\BaseDeployment-MultiMachine.json
```

Thanks again for your assistance..

Dean
