### ISSUE TITLE
Support for all licensing extensions and roles present in a single license file

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-powershell-dsc#377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

3.3.1

### Affected Resource(s)

ArcGIS_Server

### Configuration Files & Actual Behavior

This is a request that could possibly be satisfied by more clarifying documentation or may result in an enhancement request if there is a functionality gap.

In past versions of the ArcGIS module, I have found that if I use a single license file that contains the license codes for certain roles/ extensions for Stand-Alone ArcGIS Server (like Image Server or Network Analyst), only the base ArcGIS Server is licensed or more precisely only the first license code is used. I have had to run the licensing configuration again to get the role or extension to be activated on the same node. 

It adds several additional steps to create separate license files for each role/extension? and doing it for several environments makes it quite onerous.

Is this still true?

### Expected Behavior

All licensed features in a license file for ArcGIS Server should be detected and activated on the concerned node when the license mode of the DSC configuration is invoked.

**Comment by cameronkroeker** [comment]
Hi @pcsswamin,

With `-Mode InstallLicense` and `-Mode InstallLicenseConfigure` the ArcGIS Module passes in the provided license file from **ConfigData.Server.LicenseFilePath** to the ArcGIS Server software authorization wizard which performs a [silent authorization](https://enterprise.arcgis.com/en/server/latest/install/windows/authorize-arcgis-server.htm#ESRI_SECTION1_2EF08A7261D248F596B749D3ED825460). For example:

```
<System disk drive>\Program files\Common files\ArcGIS\bin\SoftwareAuthorization.exe /S /Ver 10.8 /LIF <path to .prvc authorization file>authorizationfile.prvc
```

I suspect this very well could be a limitation with .prvc license files. You may need to instead use a .ecp license file.

Thanks,
Cameron K.

**Comment by pcsswamin** [comment]
@cameronkroeker - Could you confirm that internally? Lot more customers are probably facing the same as well.

**Comment by cameronkroeker** [comment]
> @cameronkroeker - Could you confirm that internally? Lot more customers are probably facing the same as well.

Hi @pcsswamin,

Yes, I have confirmed this is a limitation with the software authorization wizard and .prvc files.

Thanks,
Cameron K.

**Comment by cleanlines** [comment]
Hi - @cameronkroeker also just hit this using a .prvc file - can the license path be updated to an array so multiple prvc files can be authorised?
Thanks

**Comment by Biboba** [comment]
Possible duplicate ? 
https://github.com/Esri/arcgis-powershell-dsc/issues/131
