### ISSUE TITLE
Official 7-zip download location has changed

### ISSUE THREAD

**Issue by nshampur** [Esri/arcgis-powershell-dsc#38]
Update 
http://www.7-zip.org/a/7z938-x64.msi
to
https://osdn.net/frs/redir.php?m=pumath&f=sevenzip%2F64449%2F7z938-x64.msi

since the earlier download location now redirects to sourceforge with a download page

**Comment by nshampur** [comment]
Impacts Install and WebAdaptorInstall DSC resources

**Comment by shailesh91** [comment]
@nshampur Paths have been updated.
