### ISSUE TITLE
"pvrs" File Should Be "prvs" in Documentation for License Manager

### ISSUE THREAD

**Issue by ZianAtFirstWatch** [Esri/arcgis-powershell-dsc#380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.1

### Affected Resource(s)

* https://github.com/Esri/arcgis-powershell-dsc/wiki/v3.3.1-Variables-reference-page-for-JSON-configuration-files

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

I expected the file extension at https://github.com/Esri/arcgis-powershell-dsc/wiki/v3.3.1-Variables-reference-page-for-JSON-configuration-files for "LicenseFilePath" to match the extension documented at https://desktop.arcgis.com/en/license-manager/latest/provisioning-files.htm#GUID-84548300-EDB1-49FB-9E69-60F14C891295 in the "Creating a provisioning file for the license manager" section.

### Actual Behavior

The documentation transposed two characters in the file extension.

### Steps to Reproduce

1. Go to https://github.com/Esri/arcgis-powershell-dsc/wiki/v3.3.1-Variables-reference-page-for-JSON-configuration-files
2. Go to https://desktop.arcgis.com/en/license-manager/latest/provisioning-files.htm#GUID-84548300-EDB1-49FB-9E69-60F14C891295
3. Look at the file extension on each page.

**Comment by cameronkroeker** [comment]
Great catch @ZianAtFirstWatch! I have made the correction.

Thanks,
Cameron K.
