### ISSUE TITLE
ArcGIS Enterprise upgrade 10.9 to 10.9.1 fails

### ISSUE THREAD

**Issue by jbiendara** [Esri/arcgis-powershell-dsc#382]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

3.3.0 and 3.3.1

### Affected Resource(s)

* Portal for ArcGIS (PortalUpgrade)

### Configuration Files

{
    "AllNodes": [
        {
            "NodeName": "xxxxxxxx",
            "DataStoreTypes": [
                "Relational"
            ],
            "Role": [
                "Server",
                "Portal",
                "DataStore",
				"PortalWebAdaptor",
				"ServerWebAdaptor"
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.9.1",
	"OldVersion": "10.9",
	"ForceLicenseUpdate": true,
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
...

### Expected Behavior

Complete upgrade of ArcGIS Enterprise from version 10.9 to version 10.9.1

### Actual Behavior

Trace-DSCJob : 3/7/2022 12:24:46 PM: Cannot validate argument on parameter 'Version'. The argument "10.9.1" does not belong to the set
"2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,10.4,10.4.1,10.5,10.5.1,10.6,10.6.1,10.7,10.7.1,10.8,10.8.1,10.9,2018.0,2018.1,2019.0,2019.1,2019.2,2020.0,2020.1" specified by the ValidateSet attribute. Supply an argument
that is in the set and then try the command again.

### Important Factoids

Copied/Exchanged PowerShell DSC Module ArcGIS to/in "C:\Program Files\WindowsPowerShell\Modules"
I am using the original json file for a single server deployment.
Only changes are:
-> Change "Version" from "10.9" to "10.9.1"
-> Add "OldVersion": = "10.9"
-> Paths to installer and license files, of course

**Comment by cameronkroeker** [comment]
Hi @jbiendara,

Can you check to see if there are previous versions of the ArcGIS Module installed on each deployment node and orchestrating node? If there are could you remove all but v3.3.1? I suspect that it could be picking up on older version(s) of the module and not v3.3.1.

`C:\Program Files\WindowsPowerShell\Modules`

Thanks,
Cameron K.

**Comment by jbiendara** [comment]
Hi Cameron,

After completely deleting and re-copying the ArcGIS modules I finally managed to get it running. Thanks for your help.

Best regards,
Jürgen
