### ISSUE TITLE
License Server Administrator: Windows Firewall Not Configured

### ISSUE THREAD

**Issue by ZianAtFirstWatch** [Esri/arcgis-powershell-dsc#383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.1

### Affected Resource(s)

* License Server Administrator

### Configuration Files

{
    "AllNodes": [{
            "NodeName": "FakePC",
            "DataStoreTypes": [
                "Relational"
            ],
            "Role": [
                "DataStore",
                "Server",
                "SQLServerClient",
                "LicenseManager"
            ],
            "SslCertificates": [{
                    "Path": "C:\\PowerShell DSC Installers\\SSLCertificates\\Wildcard\\example.pfx",
                    "Password": "abcd",
                    "Target": [
                        "Portal"
                    ]
                }
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.9.1",
        "LicenseManagerVersion": "2021.1",
        "ServerContext": "fw_arcgisserver",
        "PortalContext": "fw_arcgisportal",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "Password": "ABug",
                "UserName": "datacenter\\Little_Bug",
                "IsDomainAccount": true,
                "IsMSAAccount": false
            }
        },
        "SQLServerClient": [{
                "Name": "Microsoft ODBC Driver 17 for SQL Server",
                "InstallerPath": "C:\\PowerShell DSC Installers\\10.9.1\\ODBC17SQLServer_64\\msodbcsql_17.8.1_x64.msi",
                "ProductId": "7453C0F5-03D5-4412-BB8F-360574BE29AF",
                "Arguments": "/L*V \"C:\\users\\fwla\\desktop\\odbc installation.log\" /quiet /qn IACCEPTMSODBCSQLLICENSETERMS=YES ADDLOCAL=ALL"
            }
        ],
        "Server": {
            "LicenseFilePath": "C:\\PowerShell DSC Installers\\10.9.1\\ExampleFromMyEsriDotCom.prvc",
            "Installer": {
                "Path": "C:\\PowerShell DSC Installers\\10.9.1\\ArcGIS_Server_Windows_1091_180041.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27"
            },
            "ServerDirectoriesRootLocation": "C:\\arcgisserver\\directories",
            "ConfigStoreLocation": "C:\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": "HappyBug",
                "Password": "HappyBugPassword"
            }
        },
        "DataStore": {
            "ContentDirectoryLocation": "C:\\arcgisdatastore",
            "EnableFailoverOnPrimaryStop": false,
            "Installer": {
                "Path": "C:\\PowerShell DSC Installers\\10.9.1\\ArcGIS_DataStore_Windows_1091_180054.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\DataStore"
            }
        },
        "LicenseManager": {
            "LicenseFilePath ": "C:\\PowerShell DSC Installers\\ArcGISDesktopStandard_FailoverConcurrentUse_000000.prvs",
            "Installer": {
                "Path": "C:\\PowerShell DSC Installers\\ArcGIS_License_Manager_Windows_2021_1_180127.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\LicenseManager"
            }
        }
    }
}

### Expected Behavior

Since other components installed by the ArcGIS DSC module configure the firewall appropriately (e.g. https://github.com/Esri/arcgis-powershell-dsc/blob/35c53bca08644584440a19cb8738e7e307ecd2cf/Modules/ArcGIS/Configurations-OnPrem/ArcGISDataStore.ps1), I expected the DSC module to do the steps described at https://desktop.arcgis.com/en/license-manager/latest/configure-the-arcgis-license-manager-to-work-through-a-firewall.htm and configure the Windows Firewall.

### Actual Behavior

I could not connect to the License Server from another computer.

### Steps to Reproduce
1. Run DSC in a server.
```
$Credential=Get-Credential
Invoke-ArcGISConfiguration -ConfigurationParametersFile "C:\Users\FakePerson\Desktop\10.9.1 Initial Install Plus License Manager.json" -Mode InstallLicenseConfigure -Credential $Credential
```
2. Start ArcGIS Pro from another computer.
3. Select Settings.
4. Select Licensing.
5. Click on Configure your licensing options.
6. Change the license type to "Concurrent".
7. Enter the fully-qualified domain name of the server from step 1.
8. Click the Refresh button.
9. Wait a very long time.

### References
https://desktop.arcgis.com/en/license-manager/latest/configure-the-arcgis-license-manager-to-work-through-a-firewall.htm

**Comment by cameronkroeker** [comment]
Hi @ZianAtFirstWatch,

This is a great feature request recommendation. I have added the Enhancement label to the issue, for us to evaluate for a future release of the module.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @ZianAtFirstWatch,

I am pleased to share that in the latest release, v3.3.2 it will now add port 27000 to the allowed inbound firewall rules.

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.2

Thanks,
Cameron K.
