### ISSUE TITLE
Portal for ArcGIS license not updated with ForceLicenseUpdate to true

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#387]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.1

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

[ArcGIS_Enterprise_HA.txt](https://github.com/Esri/arcgis-powershell-dsc/files/8377542/ArcGIS_Enterprise_HA.txt)

### Expected Behavior

When specifying property "ForceLicenseUpdate": true", Portal for ArcGIS licence should be updated.

### Actual Behavior

Portal for ArcGIS license is not updated.
I also noticed that ArcGIS Server license get updated without specifying the property "ForceLicenseUpdate".

Did I miss anything ? 

### Steps to Reproduce

Run 'Invoke-ArcGISConfiguration' with the following command:
```
Invoke-ArcGISConfiguration -ConfigurationParametersFile \\pathto\ArcGIS_Enterprise_HA.json -Credential (Get-Credential) -Mode InstallLicense 
```

Thanks !

**Comment by Biboba** [comment]
Also, I would expect that datastore license to be updated as well but looking at the code, I am under the impression that it is not the case.
https://enterprise.arcgis.com/fr/data-store/latest/install/windows/data-store-utility-reference.htm#ESRI_SECTION1_3B306C70FBC94A3E95EFCB3448C2B925

Thanks !

**Comment by cameronkroeker** [comment]
Hi @Biboba,

Great catch! Apologies for the confusion, as the documentation is misleading indeed. The **ConfigData.ForceLicesnseUpdate** is meant to update components with .prvc|.ecp|.prvs license files. So this would be ArcGIS Server and ArcGIS Desktop or ArcGIS Pro licenses.

We will look to see if we can add support for updating portal licenses and data store in a future release.

Thanks,
Cameron K.

**Comment by Biboba** [comment]
Hi @cameronkroeker,

Thanks for the quick clarification about "Portal for ArcGIS" and "datastore" !

Do you also confirm that "ArcGIS Server" license get updated even without specifying the property "ForceLicenseUpdate" which to me is misleading as well ?

**Comment by Biboba** [comment]
Hi @cameronkroeker,
FYI, seems like the issue of ArcGIS Server license getting updated has been fixed at 4.0.1
https://github.com/Esri/arcgis-powershell-dsc/commit/2c7254dfca9d4948516bab100a258b5b1a928a0e#diff-92dab238151dfb5c3082403ab194ac1abdaafebfb03a3679a49d462106db7e76R188

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker,
> 
> Thanks for the quick clarification about "Portal for ArcGIS" and "datastore" !
> 
> Do you also confirm that "ArcGIS Server" license get updated even without specifying the property "ForceLicenseUpdate" which to me is misleading as well ?

Hi @Biboba,

We made some improvements with the authorization of ArcGIS Server in [v4.1.0](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.1.0). Some additional soft checks have been added to help with idempotency. So if ArcGIS Server is already authorized the expected behavior is for it to be skipped unless ForceLicenseUpdate is set to true.

Thanks,
Cameron K.

**Comment by Biboba** [comment]
Hi @cameronkroeker,

Thanks for your reply. Happy to read the authorization of ArcGIS Server has been improved. Will test that.
The original issue was about updating Portal for ArcGIS licence. 
I believe the authorization of datastore has been removed (I no longer find the command in the CLI and in the documentation), you now have improved ArcGIS Server authorization process and clarified the wiki but the enhancement remains I believe: being able to updade Portal for ArcGIS. Shall we keep it open for an enhancement ?

Thanks !

**Comment by cameronkroeker** [comment]
Hi @Biboba,

My apologies I will reopen it as I had lost track of what the original issue was. Thanks for clarifying/reminding me!

Thanks,
Cameron K.

**Comment by FeralCatColonist** [comment]
Another vote for updating Portal for ArcGIS licensing by running the DSC. Ran into it this morning as part of my organization's regular licensing renewal.
