### ISSUE TITLE
Test-WebAdaptor false for two Servers with likely Context

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#39]
If there are two WebAdaptors with a likely Context e.g.: `server` and `gaserver`
the Test-Webadaptor could be false.

Probably because of this if-clause:
https://github.com/Esri/arcgis-powershell-dsc/blob/1cd97d86ed7522e4e62bfcd3c5bc57491384a806/Modules/ArcGIS/DSCResources/ArcGIS_WebAdaptor/ArcGIS_WebAdaptor.psm1#L338

**Comment by shailesh91** [comment]
@spitzerr fixed.
