### ISSUE TITLE
Unable to connect to remote server after Patch-Installation

### ISSUE THREAD

**Issue by niol-esrich** [Esri/arcgis-powershell-dsc#391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

3.3.1

### Affected Resource(s)

ArcGIS_Server
ServerUpgrade
ServerInstallPatch

### Configuration Files

       "Server": {
            "ConfigStoreLocation": "D:\\share_serverroot\\config-store",
            "Installer": {
                "InstallDir": "C:\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27",
                "EnableArcMapRuntime": true,
                "EnableDotnetSupport": true,
                "Path": "\\\\share\\arcgis\\ArcGIS_Server_Windows_1091.exe",
                "PatchesDir": "\\\\share\\arcgis\\patches\\server",
                "PatchInstallOrder": ["ArcGIS-1091-S-SP-Patch.msp","ArcGIS-1091-S-Log4j-Patch.msp","ArcGIS-1091-S-UNDM1-Patch.msp", "ArcGIS-1091-S-VRPG-Patch.msp","ArcGIS-1091-S-MR-PatchB.msp"]
            },

### Expected Behavior

The Powershell DSC Scripts should go on uninstalling the Server Webadaptor 

### Actual Behavior

After installing patches and licensing ArcGIS Server the script fails to end the ServerConfigureUpgrade Ressource with the Error "Unable to connect to the remote server".

**in short**
LCM:  [ End    Resource ]  [[ArcGIS_Install]ServerUpgrade] 
LCM:  [ Start  Resource ]  [[ArcGIS_InstallPatch]ServerInstallPatch]
LCM:  [ End    Resource ]  [[ArcGIS_InstallPatch]ServerInstallPatch]
LCM:  [ Start  Resource ]  [[ArcGIS_License]ServerLicenseSERVERMACHINENODE]
LCM:  [ End    Resource ]  [[ArcGIS_License]ServerLicenseSERVERMACHINENODE]
LCM:  [ Start  Resource ]  [[ArcGIS_ServerUpgrade]ServerConfigureUpgrade]
13.04.2022 12:38:05: [SERVERMACHINENODE]: LCM:  [ Start  Test     ]  [[ArcGIS_ServerUpgrade]ServerConfigureUpgrade]
13.04.2022 12:38:10: [SERVERMACHINENODE]:                            [[ArcGIS_ServerUpgrade]ServerConfigureUpgrade] Response:-
13.04.2022 12:38:10: [SERVERMACHINENODE]:                            [[ArcGIS_ServerUpgrade]ServerConfigureUpgrade] Response from https://SERVERMACHINENODE.abc.lan:6443/arcgis/admin/upgrade is NULL
13.04.2022 12:38:10: [SERVERMACHINENODE]: LCM:  [ End    Test     ]  [[ArcGIS_ServerUpgrade]ServerConfigureUpgrade]  in 3.2050 seconds.
13.04.2022 12:38:10: [SERVERMACHINENODE]: LCM:  [ End    Set      ]
13.04.2022 12:38:11: Operation 'Invoke CimMethod' complete.
Trace-DSCJob : 13.04.2022 12:38:11: Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.3.1\ArcGIS.psm1:261 char:5
     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 13.04.2022 12:38:11: The PowerShell DSC resource '[ArcGIS_ServerUpgrade]ServerConfigureUpgrade' with SourceInfo 'C:\Program 
Files\WindowsPowerShell\Modules\ArcGIS\3.3.1\Configurations-OnPrem\Upgrades\ServerUpgrade.ps1::337::13::ArcGIS_ServerUpgrade' threw one or more 
non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.3.1\ArcGIS.psm1:261 char:5
     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 13.04.2022 12:38:11: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.3.1\ArcGIS.psm1:261 char:5
     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Logs Directory: C:\Admin\Logs
Finished DSC Job:- ServerUpgrade. Time Taken - 00:37:34.3545582
ServerUpgrade - Failed
Server Upgrade Failed
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.3.1\ArcGIS.psm1:2346 char:9
         throw "Server Upgrade Failed"
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Server Upgrade Failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Server Upgrade Failed


**Here you can find the detailed Debug-log output from Powershell DSC**
[debug_powershell_install_failure.txt](https://github.com/Esri/arcgis-powershell-dsc/files/8488000/debug_powershell_install_failure.txt)


### Steps to Reproduce

Run the script using the configuration details for server mentioned above.
The issue was reproduced multiple times.
Probably a time-out issue or it is related to the patch installation order.

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: Running in a Azure China/Germany/Government? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
--->

**Comment by niol-esrich** [comment]
FYI @scma-esrich @spitzerr

**Comment by cameronkroeker** [comment]
Hi @niol-esrich,

We have included a fix that addresses this issue in the latest release of the module, v3.3.2:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.3.2

Thanks,
Cameron K.

**Comment by niol-esrich** [comment]
Hi @cameronkroeker thank you for fixing the issue!
