### ISSUE TITLE
Trace-DSCJob transformation error

### ISSUE THREAD

**Issue by RonnieBlanco** [Esri/arcgis-powershell-dsc#395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.2

### Affected Resource(s)

Executing the `Invoke-ArcGISConfiguration` cmdlet, when the `Starting DSC Job: - ArcGISInstall` I am getting the following error: 

```
Trace-DSCJob: Cannot process argument transformation on parameter 'Job'. Cannot convert the "System.Management.Automation.ContainerParentJob" value of type "Deserialized.System.Management.Automation.ContainerParentJob" to type
"System.Management.Automation.Job2".

Finished DSC Job:- ArcGISInstall. Time Taken - 00:00:00.1736668
ArcGISInstall - Running
```

Azure Virtual Machines
OS -- Windows Server 2022 

Thanks!

**Comment by cameronkroeker** [comment]
Hi @RonnieBlanco,

Could you provide a bit more details? For example, if you could provide your json file, dsc logs (scrub out any sensitive information such as passwords and/or machine names), and exact `Invoke-ArcGISConfiguration` command used. Or even a detailed explanation/description/steps would be helpful.

Based on the current information that is provided, here are a few suggestions:

- Ensure PowerShell is version 5.x. Can run the following command to check the PSVersion: `$psversiontable`
- Run PowerShell as an Administrator (right click run-as Administrator).
- Ensure that ArcGIS Module v3.3.2 is the only version on the target and orchestrating nodes (`C:\Program Files\WindowsPowerShell\Modules`).

Thanks,
Cameron K.

**Comment by RonnieBlanco** [comment]
Hi Cameron, 

Figured it out, I was using PowerShell version 7.x. Switched over to version 5.x and it is running smoothly now. 

Thank you,
Ronnie B.
