### ISSUE TITLE
Change AzureFiles to AzureBlob

### ISSUE THREAD

**Issue by vassilo** [Esri/arcgis-powershell-dsc#401]
Hi,

Is it possible for the DSC scripts to change the config and content directories from and Azure Fileshare to and Azure Blob storage?

Regards,
Vassilo.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.2

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

After the script has been run the content and config locations change.

### Actual Behavior

The original locations are still being used.

### Steps to Reproduce

Original script sets up Portal and Server config and content locations to Azure Fileshare
Updated script to use Azure Blob storage from Azure Fileshare

**Comment by cameronkroeker** [comment]
Hi @vassilo,

If the portal and server site's already exist, the ArcGIS Module does not have the ability to update them. 

You will need to perform these operations manually:

**Available resources:**
https://enterprise.arcgis.com/en/portal/latest/administer/windows/changing-the-portal-content-directory.htm

https://enterprise.arcgis.com/en/server/latest/administer/windows/editing-a-server-directory-in-manager.htm

Thanks,
Cameron K.

**Comment by vassilo** [comment]
Hi @cameronkroeker 

Would this be something that will be looked at in the future, or will it always remain a manual process?

Regards,
Vassilo

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker
> 
> Would this be something that will be looked at in the future, or will it always remain a manual process?
> 
> Regards, Vassilo

Hi @vassilo,

This could be something we evaluate for a future release, but is not on the immediate roadmap.

Thanks,
Cameron K.

**Comment by vassilo** [comment]
Hi @cameronkroeker 

Thank you

Vassilo
