### ISSUE TITLE
ETA for ArcGIS Enterprise 11 ?

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#407]
Hi,

For organization sake, I was wondering what is the ETA for ArcGIS Enterprise 11 upgrade support ?

Thanks !

**Comment by cameronkroeker** [comment]
Hi @Biboba,

We are excited to announce v4.0.0 has been released for 11.0! Feel free to check it out:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.0.0

Thanks,
Cameron K.
