### ISSUE TITLE
Add ability to update SSL Certificates when using `-Mode Upgrade`

### ISSUE THREAD

**Issue by pfoppe** [Esri/arcgis-powershell-dsc#409]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.2

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal (Maybe?)

### Configuration Files

```
		{
			"NodeName": "servermachine",
			"Role": [
				"Server",
				"SQLServerClient"
			], 
			"SslCertificates": [
				{
					"Path": "\\\\fileserver\\share$\\Certificates\\cert_file.pfx",
					"Password": "REDACTED",
					"CNameFQDN": "cert_alias",
					"Target": ["Server"],
					"SslRootOrIntermediate": [
						{
							"Alias": "ROOT_ALIAS",
							"Path": "\\\\fileserver\\share$\\Certificates\\ca_root_cert_file.cer"
						}
					]
				}
			]
		}
```

### Expected Behavior

The "cert_file.pfx" is uploaded to the server and used when listening on port 6443
The "ca_root_cert_file.cer" is uploaded to the server as a Root or Intermediate Certificate

### Actual Behavior

Neither of the certificates were uploaded to the server when using "Mode=Upgrade".  
On Mode=InstallLicenseConfigure, the certificates are uploaded correctly (as expected).  
The issue appears to be around mode=upgrade

Note - we also believe this is an issue with Portal, but not 100% sure.

### Steps to Reproduce

Setup a JSON file (without the SSL Certificate information) and complete an InstallLicenseConfigure at a previous version (ex - v10.8.1)
Add the SSL Certificate information to the JSON file and complete a "Mode=Upgrade" to a new version (ex - v10.9.1)
Login to the back-end server admin API and observe the certificate listening on port 6443 is still the self-signed certificate (invalid) and neither certificate is uploaded to the server

### Important Factoids

N/A

### References
Related to https://github.com/Esri/arcgis-powershell-dsc/issues/398

**Comment by cameronkroeker** [comment]
Hi @pfoppe,

This is expected behavior. Currently uploading ssl certificates is a pre-upgrade\post-upgrade operation therefore there isn't any logic in `-Mode Upgrade` to handle ssl certificates.

I'll mark this as an enhancement request for it to be evaluated, and update the title. For now, its recommended to update ssl certificates with `-Mode InstallLicenseConfigure` either prior to the upgrade or after.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @pfoppe,

We appreciate the suggestion of adding the ability of uploading ssl certificates during upgrades, however, with much consideration and thought this feature won't be added anytime soon because it's a pre or post-upgrade operation which doesn't fit the definition of `-Mode Upgrade`. 

Thanks,
Cameron K.

**Comment by pfoppe** [comment]
Hi @cameronkroeker, 

Thanks for the response. What is your suggestion when we want to either add an SSL cert to the site, or required to update an existing one?  Is this something we would have to do manually after every upgrade since this setting will be ignored for `-Mode Upgrade` ?

SSL Certificates have a lifespan to them and do need to be updated from time to time.  For our internal CA certs, they expire at 1 year.  Many web browser companies are enforcing an expiration shortly after a year
REF - https://chromium.googlesource.com/chromium/src/+/master/net/docs/certificate_lifetimes.md

Thanks.

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker,
> 
> Thanks for the response. What is your suggestion when we want to either add an SSL cert to the site, or required to update an existing one? Is this something we would have to do manually after every upgrade since this setting will be ignored for `-Mode Upgrade` ?
> 
> SSL Certificates have a lifespan to them and do need to be updated from time to time. For our internal CA certs, they expire at 1 year. Many web browser companies are enforcing an expiration shortly after a year REF - https://chromium.googlesource.com/chromium/src/+/master/net/docs/certificate_lifetimes.md
> 
> Thanks.

Hi @pfoppe,

It's recommended to update ssl certificates with `-Mode InstallLicenseConfigure` either prior to the upgrade or after. The Module will take the existing certificate thumbprint and match it against the new certificate, if the thumbprints do not match then it will upload/replace the existing certificate with the new certificate (if they match then its skipped).

Thanks,
Cameron K.
