### ISSUE TITLE
The PowerShell DSC resource '[Script]CreatePortalContentFolder - Failed

### ISSUE THREAD

**Issue by patel1684** [Esri/arcgis-powershell-dsc#415]
9/14/2022 4:11:20 PM: The PowerShell DSC resource '[Script]CreatePortalContentFolder' with SourceInfo 'C:\Program Files\WindowsPowerShell\Modules\ArcGIS\3.3.2\Configurations-OnPrem\ArcGISPortal.ps1::284::13::Script' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
9/14/2022 4:11:20 PM: The SendConfigurationApply function did not succeed.

**Comment by shailesh91** [comment]
@patel1684 can you please provide more context for this issue. If possible please follow the GitHub template, which will provide the team enough facts to help. Thanks.

**Comment by patel1684** [comment]
Thanks @shailesh91  for the information, it's generated due to private Azure file share endpoint. Once i changed to public all works without any issue.
