### ISSUE TITLE
WARNING: It is not recommended to use domain credential for node

### ISSUE THREAD

**Issue by patel1684** [Esri/arcgis-powershell-dsc#417]
WARNING: It is not recommended to use domain credential for node '********.onmicrosoft.com'. In order to suppress the warning, you can add a property named 'PSDscAllowDomainUser' with a value of $true to your DSC configuration data for node '**********.onmicrosoft.com'.

**Comment by shailesh91** [comment]
@patel1684 can you please provide more context for this issue. Thanks.

**Comment by patel1684** [comment]
"ConfigData":{
      "Version":"10.9.1",
      "ServerContext":"hosting",
      "PortalContext":"portal",
      "ServerRole":"GeneralPurposeServer",
      "Credentials":{
         "ServiceAccount":{
            "Password":"*************",
            "UserName":"svc-arcgis-test",
            "IsDomainAccount":true,
            "IsMSAAccount":false
         }
      },

While using above configuration it create windows local account is it by script design or error in my configuration file?
While using either of these it's throw an warning
xxxxxx.xxxxxxx.onmicrosoft.com\\svc-arcgis-test
svc-arcgis-test@xxxxxxx.xxxxxxxx.onmicrosoft.com
 
WARNING: It is not recommended to use domain credential for node 'Server-test.xxxxxx.xxxxxxxx.onmicrosoft.com'. In order to suppress the warning, you can add a property named 'PSDscAllowDomainUser' with a value of $true to your DSC configuration data for node 'Server-test.xxxxxx.xxxxxxxx.onmicrosoft.com'.

**Comment by drugis73** [comment]
Seems like I've got the same situation at my hand. When running v4.0.0 release of ArcGIS PowerShell DSC Module and installing ArcGIS Server with credentials config set like this:

        "Credentials": {
            "ServiceAccount": {
                "Password": "xxx",
                "UserName": "domain\\svc-arcgis",
                "IsDomainAccount": true
            }
        },
I receive the same warning, when running the installation. When checking the installation the the ArcGIS Server Service is logged on as local system, not as the domain user specified in the config file.

**Comment by widsuoids** [comment]
https://learn.microsoft.com/en-us/powershell/dsc/configurations/configdatacredentials?view=dsc-1.1#domain-credentials

> (...) generates the warning that using a domain account for a credential is not recommended. Using a local account eliminates potential exposure of domain credentials that could be used on other servers.
> 
> When using credentials with DSC resources, prefer a local account over a domain account when possible.
> If there is a '\' or '@' in the Username property of the credential, then DSC will treat it as a domain account. There is an exception for "localhost", "127.0.0.1", and "::1" in the domain portion of the user name.

**Comment by cameronkroeker** [comment]
This issue has been addressed in release v4.2.0:
https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.2.0
