### ISSUE TITLE
 PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality

### ISSUE THREAD

**Issue by supermaro84** [Esri/arcgis-powershell-dsc#418]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

I am trying to create base deployment on a single machine with use og GISServer-GeneralPurpose json. I have tried also on v3. However I am facing access is denied . I have tried to enable all necessary permissions but stil no success.

**`Trace-DSCJob : 16.09.2022 12:42:45: Exception calling "Start" with "1" argument(s): "Access is denied"
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 16.09.2022 12:42:45: You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 16.09.2022 12:42:45: You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 16.09.2022 12:42:45: You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 16.09.2022 12:42:45: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functi
onality with error message: Install failed. Process exit code:- . Error -
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 16.09.2022 12:42:45: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob`**

**Comment by cameronkroeker** [comment]
Hi @supermaro84,

Let's ensure Powershell is being ran as an administrator (right click run as Administrator), and also try passing in an Administrator account for the -Credential parameter.

**Issue is similar to:**
https://github.com/Esri/arcgis-powershell-dsc/issues/414

**Comment by supermaro84** [comment]
Hi. 
 I have tried with both and still get the same message: 
From Error log:
21.09.2022 13:52:51: Exception calling "Start" with "1" argument(s): "Access is denied"
21.09.2022 13:52:51: You cannot call a method on a null-valued expression.
21.09.2022 13:52:51: You cannot call a method on a null-valued expression.
21.09.2022 13:52:51: You cannot call a method on a null-valued expression.
21.09.2022 13:52:51: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Install failed. Process exit code:- . Error -  
21.09.2022 13:52:51: The SendConfigurationApply function did not succeed.
And Verbose:
21.09.2022 13:52:46: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
21.09.2022 13:52:51: An LCM method call arrived from computer H1-A-GIS-APD04 with user sid S-1-5-21-1123561945-1292428093-725345543-265785.
21.09.2022 13:52:51: [H1-A-GIS-APD04]: LCM:  [ Start  Set      ]
21.09.2022 13:52:51: [H1-A-GIS-APD04]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]ServerInstall]
21.09.2022 13:52:51: [H1-A-GIS-APD04]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]ServerInstall]
21.09.2022 13:52:51: [H1-A-GIS-APD04]:                            [[ArcGIS_Install]ServerInstall] Installed Version
21.09.2022 13:52:51: [H1-A-GIS-APD04]: LCM:  [ End    Test     ]  [[ArcGIS_Install]ServerInstall]  in 0.2340 seconds.
21.09.2022 13:52:51: [H1-A-GIS-APD04]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]ServerInstall]
21.09.2022 13:52:51: [H1-A-GIS-APD04]:                            [[ArcGIS_Install]ServerInstall] Installing Software using installer at D:\Programvare\ArcGIS_11
21.09.2022 13:52:51: [H1-A-GIS-APD04]:                            [[ArcGIS_Install]ServerInstall] Installed Version
21.09.2022 13:52:51: [H1-A-GIS-APD04]:                            [[ArcGIS_Install]ServerInstall] Executing D:\Programvare\ArcGIS_11
21.09.2022 13:52:51: [H1-A-GIS-APD04]: LCM:  [ End    Set      ]  [[ArcGIS_Install]ServerInstall]  in 0.2040 seconds.
21.09.2022 13:52:51: [H1-A-GIS-APD04]: LCM:  [ End    Set      ]
21.09.2022 13:52:51: Operation 'Invoke CimMethod' complete.

**Comment by supermaro84** [comment]
Also passing a -credential argument with administrator account led to a prompt to insert password and then i got this message:
Trace-DSCJob : 22.09.2022 10:31:28: The WinRM client cannot process the request. The WinRM client tried to use Negotiat
e authentication mechanism, but the destination computer (localhost:5985) returned an 'access denied'
error. Change the configuration to allow Negotiate authentication mechanism to be used or specify one of the authentica
tion mechanisms supported by the server. To use Kerberos, specify the local computer name as the remote destination. Al
so verify that the client computer and the destination computer are joined to a domain. To use Basic, specify the local
 computer name as the remote destination, specify Basic authentication and provide user name and password. Possible aut
hentication mechanisms reported by server:       Kerberos
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

**Comment by cameronkroeker** [comment]
Hello @supermaro84,

The ArcGIS Module uses WinRM HTTP (port 5985) to connect to the Target node(s) so you'll need to ensure PowerShell Remoting is enabled and configured properly. Below are some resources I recommend checking out.

- [PowerShell Remote Troubleshooting](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_troubleshooting?view=powershell-7.2)

- Ensure [PowerShell Remoting](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enable-psremoting?view=powershell-7.2) is enabled on orchestrating node and all target nodes:
   - This will start the WinRM service and set its startup to automatic
   - It will create an HTTP listener
   - You can verify this by running `winrm enumerate winrm/config/listener`
   - It will enable the Windows Remote Management firewall rules
   - It will create and configure the LocalAccountTokenFilterPolicy registry key
   - It will reset the permissions on the four sessions hosts
   - You can verify this by running `Get-PSSessionConfiguration`

```powershell
PS C:\> Enable-PSRemoting
```

- https://learn.microsoft.com/en-us/archive/blogs/wmi/powershell-remoting-between-two-workgroup-machines
-  The following command will display useful information such as PSVersion and Permissions:

```powerhsell
PS C:\> Get-PSSessionConfiguration

Name          : microsoft.powershell
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\INTERACTIVE AccessAllowed, BUILTIN\Administrators AccessAllowed, BUILTIN\Remote Management Users AccessAllowed

```
- Can use [Test-WSMan](https://learn.microsoft.com/en-us/powershell/module/microsoft.wsman.management/test-wsman?view=powershell-7.2) to test the connection between Nodes:

```
Test-WSMan -ComputerName H1-A-GIS-APD04 -Authentication default -Port 5985 -Credential Administrator
```

- Also try using [New-CimSession](https://learn.microsoft.com/en-us/powershell/module/cimcmdlets/new-cimsession?view=powershell-7.2) to test the connection. For example:

```
New-CimSession -Port 5985 -ComputerName H1-A-GIS-APD04 -Authentication default -Credential Administrator
```

**Comment by stephen909tom** [comment]
Hello @cameronkroeker,
I have been working together with @supermaro84 on this issue. Thank you for your timely contributions to guide us through our execution.

- we were running Powershell as an admin, then as you suggested we added the - Credential as our adm account

The last piece of the jigsaw, which utlimately solved our issue,  was to specify the installer .exe in the installer path as pointed out in this post:
https://github.com/Esri/arcgis-powershell-dsc/issues/220#issuecomment-571470718

**Comment by maxsquires** [comment]
Sorry to comment on a closed thread, but this may be helpful to someone who is in the same, albeit uncommon, situation as me.

Something else to consider if none of the above works:
The installers are being extracted to c:/windows/temp/{guid} directory. If you have had failed attempts at deploying via dsc previously, you should try deleting the temp directories that are in question.  

As an additional note, due to the previously failed deployments I also needed to cancel all pending dsc jobs/*.mof and processes that were not responding by doing the following:
```
#Kill the LCM/DSC processes 
Get-Process wmi* | ? {$_.modules.ModuleName -like "*DSC*"} | stop-process -force

```

if that still doesn't work then I'd do the following as long as you know what other dsc jobs are supposed to be running currently and you don't mind blowing away other configuration settings:

```
#Remove all mof files (pending,current,backup,MetaConfig.mof,caches,etc) 
rm C:\windows\system32\Configuration\*.mof* 
```

otherwise the dsc was failing to get any job status updates and just hung indefinitely.
