### ISSUE TITLE
v4.0.0 - Portal EmailSettings - Credentials not working

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#419]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.0

### Affected Resource(s)

* ArcGIS_PortalSettings
* ArcGIS.psm1

### Configuration Files

            "EmailSettings": {
                "SMTPServerAddress": "smtp.test.com",
                "From": "test@test.com",
                "Label": "MyPortal",
                "AuthenticationRequired": true,
                "EncryptionMethod": "TLS",
                "SMTPPort": "325",
                "UserName": "mydomain\\myuser",
                "Password": "mypassword"
            },

### Expected Behavior

PortalEmail settings with credentials should have been set.

### Actual Behavior

The credentials are not set and an error is thrown. The credentials are not handed over from ArcGIS.psm1 to the ArcGISPortalSettings.ps1. The variable is wrong.

### Steps to Reproduce

Just use an email settings with credential for portal base deployment.

### Important Factoids

On-Prem Azure (westeurope)

**Comment by lorenzmeyer77** [comment]
ArcGIS.psm1 - Line 1378 should be:
$PortalSettingsArgs["EmailSettingsCredential"] = $EmailSettingsCredential

**Comment by lorenzmeyer77** [comment]
@scma-esrich fyi

**Comment by cameronkroeker** [comment]
Hello @lorenzmeyer77  and @scma-esrich this issue has been addressed in [v4.0.1](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.0.1).
