### ISSUE TITLE
v4.0.0 and v3.3.2 - ArcGIS_DataStoreBackup - TileCache fails on existing backup location

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.3.2
* 4.0.0

### Affected Resource(s)

* ArcGIS_DataStoreBackup

### Configuration Files

        "DataStore": {
            "ContentDirectoryLocation": "C:\\arcgisdatastore",
            "Installer": {
                "Path": "Z:\\setups\\esri\\ArcGIS_10.9.1\\ArcGIS_DataStore_Windows_1091_180054.exe",
                "InstallDir": "C:\\ArcGIS\\DataStore",
                "PatchesDir": "Z:\\setups\\esri\\ArcGIS_10.9.1\\Patches\\DataStore",
                "PatchInstallOrder" : ["ArcGIS-1091-DS-Log4j-Patch.msp", "ArcGIS-1091-DS-DE-Patch.msp"]
            },
            "EnablePointInTimeRecovery": true,
            "Backups":{
                "Relational":[{
                    "Name": "gsharp-rds-local-backup",
                    "Type": "fs",
                    "Location": "F:\\arcgisdatastorebackup\\relational",
                    "ForceBackupLocationUpdate": true,
                    "IsDefault": true
                }],
                "TileCache":[{
                    "Name": "gsharp-tcds-local-backup",
                    "Type": "fs",
                    "Location": "F:\\arcgisdatastorebackup\\tileCache",
                    "ForceBackupLocationUpdate": true,
                    "IsDefault": true
                }]
            }
        }

### Expected Behavior

If the backup location already exists, it should be ignored and not abort with an error. Or how can I run the deployment on an existing base deployment again?
And what exactly does the parameter config "ForceBackupLocationUpdate" on the tilecache? It is not documented and it does not have an effect what I specify there (true or false).

### Actual Behavior

On an existing base deployment when an tilecache backup already has run once the powershell dsc cannot configure the tilecache backup location. It aborts with an error:

`23.09.2022 08:10:35: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
23.09.2022 08:10:41: An LCM method call arrived from computer vm-jumphost-g01 with user sid S-1-5-21-301992139-443025867-1373009395-1342749.
23.09.2022 08:10:41: [vm-tcds-g01]: LCM:  [ Start  Set      ]
23.09.2022 08:10:41: [vm-tcds-g01]: LCM:  [ Start  Resource ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]
23.09.2022 08:10:41: [vm-tcds-g01]: LCM:  [ Start  Test     ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]
23.09.2022 08:10:41: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Version of DataStore is 10.9.1
23.09.2022 08:10:41: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup Tool:- C:\ArcGIS\DataStore\tools\configurebackuplocation.bat --operation list --store tileCache --prompt no
23.09.2022 08:10:41: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup location tool executed successfully.
23.09.2022 08:10:41: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] No Backup of type 'fs', location 'F:\arcgisdatastorebackup\tileCache' and name 'gsharp-tcds-local-backup' found for  TileCache Datastore
23.09.2022 08:10:41: [vm-tcds-g01]: LCM:  [ End    Test     ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]  in 2.6850 seconds.
23.09.2022 08:10:41: [vm-tcds-g01]: LCM:  [ Start  Set      ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]
23.09.2022 08:10:41: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Version of DataStore is 10.9.1
23.09.2022 08:10:41: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup Tool:- C:\ArcGIS\DataStore\tools\configurebackuplocation.bat --operation list --store tileCache --prompt no
23.09.2022 08:10:46: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup location tool executed successfully.
23.09.2022 08:10:46: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Registering Backup of type 'fs', location 'F:\arcgisdatastorebackup\tileCache' and name 'gsharp-tcds-local-backup' for  TileCache Datastore
23.09.2022 08:10:46: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup Tool:- C:\ArcGIS\DataStore\tools\configurebackuplocation.bat --operation register --store tileCache --prompt no --location type=fs;name=gsharp-tcds-local-backup;location=F:\arcgisdatastorebackup\tileCache
23.09.2022 08:10:46: [vm-tcds-g01]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] 
Error encountered: Machine 'https://VM-TCDS-G01.GIS-GDIDEV.AZURE.SBB.CH:2443/arcgis/datastoreadmin' returned an error. 'Backup location 'gsharp-tcds-local-backup' already exists.'
23.09.2022 08:10:46: [vm-tcds-g01]: LCM:  [ End    Set      ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]  in 5.7980 seconds.
23.09.2022 08:10:46: [vm-tcds-g01]: LCM:  [ End    Set      ]
23.09.2022 08:10:46: Operation 'Invoke CimMethod' complete.
`

### Steps to Reproduce

* Run a base deployment with a tilecache datastore and a default backup location
* Run a backup for the tilecache (for example through webgisdr.bat file)
* Run the base deployment again

### Important Factoids

On-Prem Azure (westeurope) de-ch

**Comment by lorenzmeyer77** [comment]
@scma-esrich @spitzerr fyi

**Comment by cameronkroeker** [comment]
Hi @lorenzmeyer77,

The ArcGIS Module will use the datastore tool `configurebackuplocation.bat --operation list` , in the test method, to check if there is an existing backup, if found then it will skip creating the backup. However, in your case for some reason the datastore backup tool did not find the existing backup:
```
[[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup Tool:- C:\ArcGIS\DataStore\tools\configurebackuplocation.bat --operation list --store tileCache --prompt no 

[[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup location tool executed successfully. 

[[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] No Backup of type 'fs', location 'F:\arcgisdatastorebackup\tileCache' and name 'gsharp-tcds-local-backup' found for TileCache Datastore 
```

Could you manually run the following command and share the results? Perhaps there is something in the return that made DSC think the backup doesn't exist.

```
C:\ArcGIS\DataStore\tools\configurebackuplocation.bat --operation list --store tileCache --prompt no
```

I performed the following steps, but was not able to replicate the issue:

1. Ran a base deployment with a tilecache datastore and a default backup location
```json
"DataStore":{
            "ContentDirectoryLocation":"C:\\arcgisdatastore",
            "Installer":{
                "Path":"\\\\fileserver\\software\\Esri\\1091_Final\\ArcGIS_DataStore_Windows_1091_180054.exe",
                "InstallDir":"C:\\Program Files\\ArcGIS\\DataStore"
            },
			"EnablePointInTimeRecovery": true,
			"Backups":{
				"Relational":[{
					"Name": "gsharp-rds-local-backup",
					"Type": "fs",
					"Location": "C:\\arcgisdatastorebackup\\relational",
					"ForceBackupLocationUpdate": true,
					"IsDefault": true
				}],
				"TileCache":[{
					"Name": "gsharp-tcds-local-backup",
					"Type": "fs",
					"Location": "C:\\arcgisdatastorebackup\\tileCache",
					"ForceBackupLocationUpdate": true,
					"IsDefault": true
				}]
			}
        },
```

3. Ran a backup for the tilecache using the following method:
```
C:\Program Files\ArcGIS\DataStore\tools>configurebackuplocation.bat --operation list --store tileCache
Backups locations for tile cache data store:
===========================================================================================================================================
Name                                                         Type  Location                                                     isDefault
===========================================================================================================================================
gsharp-tcds-local-backup                                     fs    C:/arcgisdatastorebackup/tileCache/                          true


Operation completed successfully.

C:\Program Files\ArcGIS\DataStore\tools>backupdatastore.bat --store tileCache --location C:/arcgisdatastorebackup/tileCache/
You are attempting to back up the data store. This process could take a long time, depending on the size of your data. Please do not interrupt the process once it has started.

Do you want to continue (Yes or No)?yes


Operation completed successfully.

C:\Program Files\ArcGIS\DataStore\tools>listbackups.bat --store tileCache
Backups in the tile cache data store:
================================================================================
Backup_Name                    Status          Backup_Time          Mode
================================================================================
tcs_7qb24dcd-20221007174818814 BackupComplete  2022-10-07 10:48     manual


Backups located at: 'C:/arcgisdatastorebackup/tileCache/(fs)'.

Operation completed successfully.
```
4. Ran the base deployment again

```
10/7/2022 11:02:10 AM: [DataStoreHostName]: LCM:  [ Start  Test     ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]
10/7/2022 11:02:10 AM: [DataStoreHostName]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Version of DataStore is 10.9.1
10/7/2022 11:02:10 AM: [DataStoreHostName]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup Tool:- C:\Program Files\ArcGIS\DataStore\tools\configurebackuplocation.bat --operation list --store tileCache --prompt no
10/7/2022 11:02:10 AM: [DataStoreHostName]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup location tool executed successfully.
10/7/2022 11:02:10 AM: [DataStoreHostName]:                            [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup] Backup with location 'C:\arcgisdatastorebackup\tileCache' found for  TileCache Datastore
10/7/2022 11:02:10 AM: [DataStoreHostName]: LCM:  [ End    Test     ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]  in 3.5700 seconds.
10/7/2022 11:02:10 AM: [DataStoreHostName]: LCM:  [ Skip   Set      ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]
10/7/2022 11:02:10 AM: [DataStoreHostName]: LCM:  [ End    Resource ]  [[ArcGIS_DataStoreBackup]TileCacheBackup-gsharp-tcds-local-backup]
10/7/2022 11:02:10 AM: [DataStoreHostName]: LCM:  [ End    Set      ]
10/7/2022 11:02:10 AM: [DataStoreHostName]: LCM:  [ End    Set      ]    in  3.7070 seconds.
```

**Comment by lorenzmeyer77** [comment]
Hi @cameronkroeker 
Thanks for the analysis. I tried it again and now I'm no longer able to reproduce the error I had. Funny...

I ran the base deployment, created a backup and then ran the base deployment again, without any error. 
I have no idea what happened.

So, we close the issue.

Thanks
