### ISSUE TITLE
Web Adaptor(s) being installed on port 80 vs 443

### ISSUE THREAD

**Issue by Digital-Buddha-8412** [Esri/arcgis-powershell-dsc#422]
Hey everyone,
I'm a DSC Noob, apologies if this is a basic question. When running the Web Adaptor Installer, I do not see a way to choose 443 vs. 80, which can be an issue with Portal Web Adaptor. What I have done is remove the port 80 binding prior to running our .json. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

**Comment by cameronkroeker** [comment]
Hello @Digital-Buddha-8412,

If port 80 is removed prior, and 443 is the only port/binding then the web adaptor install should default to using 443. However, if both port 80 and 443 exists, then I believe it will pick port 80 during install, but during configuration it will use 443.

Thanks,
Cameron K.
