### ISSUE TITLE
Undefined property DisableServiceDirectory Error when installing AGE 11.0

### ISSUE THREAD

**Issue by MartinBjorkenes** [Esri/arcgis-powershell-dsc#430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.1

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "vmkyst03",
            "Role": [
                "ServerWebAdaptor",
                "PortalWebAdaptor"
            ],
            "SslCertificates":[
               {
                  "Path": "E:\\GEODATA\\Install\\Sertifikat\\<REMOVED>",
                  "Password": <REMOVED>,
                  "CNameFQDN": <REMOVED>,
                  "Target":[
                     "WebAdaptor"
                  ]
               }
            ],
            "AdminAccessEnabled": true
        },
        {
            "NodeName": "vmkyst06",
            "DataStoreTypes": [
                "Relational"
            ],
            "Role": [
                "Server",
                "Portal",
                "DataStore"
            ],
            "SslCertificates":[
               {
                  "Path": "E:\\GEODATA\\Install\\Sertifikat\\<REMOVED>",
                  "Password": <REMOVED>,
                  "CNameFQDN": <REMOVED>,
                  "Target":[
                     "Server",
                     "Portal"
                  ]
               }
            ]
        }
    ],
    "ConfigData": {
        "Version": "11.0",
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "UserName": <REMOVED>,
                "Password": <REMOVED>,
                "IsDomainAccount": true
            }
        },
        "SslRootOrIntermediate":[
           {
              "Alias":"dev-root",
              "Path":"E:\\GEODATA\\Install\\Sertifikat\\<REMOVED>"
           },
           {
              "Alias":"dev-intermediate",
              "Path":"E:\\GEODATA\\Install\\Sertifikat\\<REMOVED>"
           }
        ],
        "Server": {
            "Installer": {
                "Path": "E:\\GEODATA\\Install\\esri\\11.0\\ArcGIS_Server_Windows_110_182874.exe",
                "InstallDir": "E:\\Program Files\\ArcGIS\\Server"
            },
            "LicenseFilePath": "E:\\GEODATA\\Install\\esri\\11.0\\lic\\ArcGISGISServerStandard_ArcGISServer_1252387.prvc",
            "ServerDirectoriesRootLocation": "E:\\arcgisserver\\directories",
            "ConfigStoreLocation": "E:\\arcgisserver\\config-store",            
            "PrimarySiteAdmin": {
                "UserName": "siteadmin",
                "Password": <REMOVED>
            },
            "EnableArcMapRuntime": false,
            "EnableDotnetSupport": false
        },
        "Portal": {
            "LicenseFilePath": "E:\\GEODATA\\Install\\esri\\11.0\\lic\\ArcGIS_Enterprise_Portal_110_402315_20221207.json",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "E:\\GEODATA\\Install\\esri\\11.0\\Portal_for_ArcGIS_Windows_110_182885.exe",
                "InstallDir": "E:\\Program Files\\ArcGIS\\Portal",
                "ContentDir": "E:\\arcgisportal"
            },
            "ContentDirectoryLocation":"E:\\arcgisportal\\content",
            "PortalAdministrator": {
                "UserName": "portaladmin",
                "Email": <REMOVED>,
                "Password": <REMOVED>,
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": <REMOVED>
            }
        },
        "DataStore": {
            "ContentDirectoryLocation": "E:\\arcgisdatastore",
            "EnableFailoverOnPrimaryStop": false,
            "Installer": {
                "Path": "E:\\GEODATA\\Install\\esri\\11.0\\ArcGIS_DataStore_Windows_110_182887.exe",
                "InstallDir": "E:\\Program Files\\ArcGIS\\DataStore"
            }
        },
        "WebAdaptor": {
            "Installer": {
                "Path": "E:\\GEODATA\\Install\\esri\\11.0\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_110_182888.exe"
            }
        }
    }
}
```

### Expected Behavior

Attempting to install Base Deployment of ArcGIS Enterprise 11.0 on two server (one webserver for the Web Adaptors, one server for Portal, ArcGIS Server and Data Store). All servers have arcgis module 4.0.1 (only) installed, as well as an E-drive with the required installation, license and certificate files.

### Actual Behavior

Job fails, running into the following error messages:

```
Dot Sourcing the Configuration:- ArcGISServerSettings
Write-NodeMOFFile : Invalid MOF definition for node 'vmkyst06': Exception calling "ValidateInstanceText" with "1" argument(s): "Undefined property
DisableServiceDirectory
 At line:27, char:2
 Buffer:
GISServerSettings";
};^
insta
"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2369 char:21
+ ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile
Compilation errors occurred while processing configuration 'ArcGISServerSettings'. Please review the errors reported in error stream and modify your
configuration code appropriately.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (ArcGISServerSettings:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration

```
### Steps to Reproduce

Full command run i PowerShell is:
```
Invoke-ArcGISConfiguration -ConfigurationParametersFile KYV-AGE-BaseDeployment.json -Mode InstallLicenseConfigure -DebugSwitch -EnableMSILogging
```

### Important Factoids
* Running the config with -Mode Install works just fine. The same with -Mode InstallLicense. However, it fails when running -Mode InstallLicenseConfigure.
* No errors are recorded in the Logs folder.
* DisableServiceDirectory is an optional parameter for Server, with false as default. I have tried to add it to the configuration, but it does not affect the result. 
* I have also tried to set EnableArcMapRuntime to false, but to no avail.

**Comment by cameronkroeker** [comment]
@MartinBjorkenes 

The error you are experiencing can be caused by having multiple versions (or a previous version) of the ArcGIS Module installed. Let's ensure all previous versions of the module are removed from all the target nodes and orchestrating node.

For example, check the following location `C:\Program Files\WindowsPowerShell\Modules\ArcGIS` on all the target nodes and orchestrating node to ensure only one version exists. If there are multiple versions, remove all but v4.0.1, close the powershell window, then re-launch a fresh powershell window and re-run.

**This is similar to:**
https://github.com/Esri/arcgis-powershell-dsc/issues/366

Thanks,
Cameron K.

**Comment by MartinBjorkenes** [comment]
> @MartinBjorkenes
> 
> The error you are experiencing can be caused by having multiple versions (or a previous version) of the ArcGIS Module installed. Let's ensure all previous versions of the module are removed from all the target nodes and orchestrating node.
> 
> For example, check the following location `C:\Program Files\WindowsPowerShell\Modules\ArcGIS` on all the target nodes and orchestrating node to ensure only one version exists. If there are multiple versions, remove all but v4.0.1, close the powershell window, then re-launch a fresh powershell window and re-run.
> 
> **This is similar to:** #366
> 
> Thanks, Cameron K.

Thank you so much Cameron! You were right! I did have both version 4.0.0 and 4.0.1 of the module installed on the orchestrating node. I misunderstood the update-module command, and thought it replaced the previous version. Having removed the older version from the node, the installation completed succesfully.

**Comment by cameronkroeker** [comment]
> Thank you so much Cameron! You were right! I did have both version 4.0.0 and 4.0.1 of the module installed on the orchestrating node. I misunderstood the update-module command, and thought it replaced the previous version. Having removed the older version from the node, the installation completed successfully.

Glad to hear the issue has been resolved!
