### ISSUE TITLE
Variable reference pages no longer working - Not found (Documentation missing)

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#431]
No DSC issue, but the variable reference pages no longer work. 
https://github.com/Esri/arcgis-powershell-dsc/v4.0.1-Variables-reference-page-for-JSON-configuration-files
https://github.com/Esri/arcgis-powershell-dsc/v4.0.0-Variables-reference-page-for-JSON-configuration-files

**Comment by cameronkroeker** [comment]
Thanks @lorenzmeyer77 for pointing this out. It appears to only be an issue with the quick links in the wiki side bar. For some reason its chopping off the `/wiki`. Try:

- https://github.com/Esri/arcgis-powershell-dsc/wiki/v4.0.1-Variables-reference-page-for-JSON-configuration-files
- https://github.com/Esri/arcgis-powershell-dsc/wiki/v4.0.0-Variables-reference-page-for-JSON-configuration-files

I suspect it's an issue with GitHub, but not sure. I will continue looking into it.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @lorenzmeyer77 and @lachlanwainwright,

I made some changes to the quick links in the sidebar to help resolve this issue.

Thanks,
Cameron K.
