### ISSUE TITLE
ArcGIS Enterprise 10.9.1 on AZURE, AGS not contactable when enabling IWA

### ISSUE THREAD

**Issue by lachlanwainwright** [Esri/arcgis-powershell-dsc#434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.1

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

machine1: Portal for ArcGIS, WebAdaptors (Server & Portal)
machine2: ArcGIS Server
machine3: Datastore: relational
```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior
Enabled IWA on Webadaptor and ArcGIS Enterprise should work as expected

### Actual Behavior
ArcGIS Server is not contactable.
1. Unable to see Settings from Portal, looks like this does some background checking with ags (hosting server)
2. Unable to connect to ArcGIS Server Manager, prompted to use siteadmin dialog

### Steps to Reproduce
Installed multi-machine enterprise 10.9.1 setup using 4.0.1 without any errors, gotta love DSC!!
We only have "ExternalLoadBalancer": "theDNSAlias.company.com" set as are using a DNS entry only, no load balancer setup yet
Everything was working like a charm, done it a bucket ton of times.

Went to IIS to enable IWA
Checked Portal Setting to validate AGS, get swirling vertical bars
Check AGS Manager, prompted to login using primary site account

### Important Factoids
Using DNS entry
Server are 2019 on **AZURE**
I have seen IWA and InternalLoadbalancer mentioned with #297, could setting this to servername.com:6443 noting we are using a DNS entry at the moment.

Look, just tossing it out there is anyone has seen this and has a silver bullet.
I'll even toss in a beverage (not top shelf though) if someone has got this scenario covered.

We'll be contacting ESRI support too.

**Comment by cameronkroeker** [comment]
Hello @lachlanwainwright,

When using IWA, the federated server admin url and privatePortalUrl needs to be set to an internally accessible url that by passes the web adaptor. I suggest setting **ConfigData.Portal.InternalLoadBalancer** attribute to the internal FQDN of the portal 7443 url (this will set the privatePortalUrl in system properties), and **ConfigData.Server.InternalLoadBalancer** to the internal FQDN of the server 6443 url (this will be used as the federated server admin url).

Thanks,
Cameron K.

**Comment by lachlanwainwright** [comment]
thanks @cameronkroeker excellent, most excellent
just to confirm, we are right to add these and rerun given it's already federated etc?

**Comment by cameronkroeker** [comment]
> thanks @cameronkroeker excellent, most excellent just to confirm, we are right to add these and rerun given it's already federated etc?

You will first need to unfederate prior to re-running so that it can re-federate with the new settings.

Thanks,
Cameron K.

**Comment by lachlanwainwright** [comment]
Hi
We followed the steps kindly outlined by @cameronkroeker and all is functioning as expected.
IWA is rocking and rolling
Thanks Cameron

**Comment by widsuoids** [comment]
@cameronkroeker Could you please add [this](https://github.com/Esri/arcgis-powershell-dsc/issues/434#issuecomment-1349107576) information to the wiki? Since unfederating is required, this is something that should be known prior running the dsc.
