### ISSUE TITLE
Downloading ArcGIS Installation Setups [wiki update]

### ISSUE THREAD

**Issue by natowi** [Esri/arcgis-powershell-dsc#437]
The ArcGIS Pro version is no longer correct, as 3.0 has been replaced by 3.0.3:
https://github.com/Esri/arcgis-powershell-dsc/wiki/Downloading-ArcGIS-Installation-Setups#arcgis-pro
<html><body>

3.0 | ArcGISPro_30_182209.exe | C:\\Software\\Archives\\ArcGISPro_30_182209.exe
-- | -- | --

</body>
</html>

It should be

3.0.3 | ArcGISPro_303_184244.exe | C:\\Software\\Archives\\ArcGISPro_303_184244.exe
-- | -- | --

</body>
</html>

**Comment by cameronkroeker** [comment]
Thanks, @natowi for catching this. If you need to install 3.0.3 using module v4.0.1, there is a workaround that can be used here:

https://github.com/Esri/arcgis-powershell-dsc/issues/440

**Comment by cameronkroeker** [comment]
Thanks @natowi, this wiki page has been updated, also support for ArcGIS Pro 3.0.3 has been added to module [v4.0.2](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.0.2).
