### ISSUE TITLE
Uploading certificate with a comma "," inside of one of the Issuer values results in error: "Error: - Data line '<whatever comes after comma>' is not in 'name=value' format"

### ISSUE THREAD

**Issue by BrendanEsri** [Esri/arcgis-powershell-dsc#439]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.1

### Affected Resource(s)

* ArcGIS_Server

### Expected Behavior

It should have uploaded the certificate even if there is a comma inside the Organization within the Issuer values
### Actual Behavior

It results in an error
"Error: - Data line ' Inc."' is not in 'name=value' format
### Steps to Reproduce

Upload a certificate to ArcGIS Server at 10.9.1 with v 4.0.1 that has a comma inside one of the values of the Issuer section within the certificate
### References

<img width="1035" alt="2023-01-03_14-56-01" src="https://user-images.githubusercontent.com/37840516/210436675-a01bf3a2-cdc3-484e-ba6d-703d660d60cf.png">

<img width="270" alt="2023-01-03_14-58-59" src="https://user-images.githubusercontent.com/37840516/210441409-84a5af84-f9f4-4d9f-a9eb-da473be4a7c2.png">

**Comment by cameronkroeker** [comment]
Hi @BrendanEsri,

As a temporary workaround, could you try commenting out the following 2 lines, and re-run?

https://github.com/Esri/arcgis-powershell-dsc/blob/918b1cee22a6eaddb227cae434e3be83f04e9760/Modules/ArcGIS/DSCResources/ArcGIS_Server_TLS/ArcGIS_Server_TLS.psm1#L813

and

https://github.com/Esri/arcgis-powershell-dsc/blob/918b1cee22a6eaddb227cae434e3be83f04e9760/Modules/ArcGIS/DSCResources/ArcGIS_Server_TLS/ArcGIS_Server_TLS.psm1#L816

Thanks,
Cameron K.

**Comment by BrendanEsri** [comment]
This worked, thank you!

**Comment by cameronkroeker** [comment]
Hi @BrendanEsri,

This issue has been addressed in [v4.0.2](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.0.2).

Thanks,
Cameron K.
