### ISSUE TITLE
Publishing Server Services Crashes

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#44]
There is only the Username passed and not the Credential. Line 111 ArcGIS_Server_Service.psm1

**Comment by shailesh91** [comment]
@spitzerr fixed.

**Comment by spitzerr** [comment]
As it is a bug in current Code Base it should be also fixed in master. Shouldn't it?

**Comment by shailesh91** [comment]
@spitzerr It isn't documented anywhere and is not supported officially yet. It was still in dev. So we can wait for the fix.
