### ISSUE TITLE
Possible to use with other DSC configurations?

### ISSUE THREAD

**Issue by codehtmai** [Esri/arcgis-powershell-dsc#442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.1

### Affected Resource(s)

* ArcGIS Web Adaptor
* Other DSC configuration

### Expected Behavior

Is it possible for the ArcGIS Powershell for DSC to be used alongside other custom configurations? For instance, I am looking to configure my webserver with IIS and other requirements through my own DSC configuration, but then also apply this module to install Web Adaptor. 

### Actual Behavior

Only the latest DSC configuration applied is active. Is it possible to append my own configuration to Esri's, or some other way to use them together?

**Comment by cameronkroeker** [comment]
Hi @codehtmai,

The `Invoke-ArcGISConfiguration` command can be embedded inside a powershell script (though not in an another DSC configuration). So you will first need to compile and run the other DSC configuration, check the status, and once its complete execute the `Invoke-ArcGISConfiguration` command.

Thanks,
Cameron K.
