### ISSUE TITLE
PowerShell DSC v4.0.1  error  Start-DscConfiguration : The computer name was not specified and the configuration directory does not have any configuration files.

### ISSUE THREAD

**Issue by noelperkins** [Esri/arcgis-powershell-dsc#444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

Apologies if this issues already exists I was unable to find anything on it.

### Module Version

 4.0.1

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files  BaseDeployment-SingleMachine.json (edited)
```
{
    "AllNodes": [
        {
            "NodeName": "ip here",
            "DataStoreTypes": [
                "Relational"
            ],
            "Role": [
                "Server",
                "Portal",
                "DataStore",
                "ServerWebAdaptor",
                "PortalWebAdaptor"
            ]
        }
    ],
    "ConfigData": {
        "Version": "11.0",
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "DownloadSetups": false,
        "DownloadPatches": false,
        "Credentials": {
            "ServiceAccount": {
                "UserName": "<domain\accountname>",
                "Password": "<password>",
                "IsDomainAccount": true,
                "IsMSAAccount": false
            }
        },
        "Server": {
            "LicenseFilePath": "C:\\Software\\AuthorizationFiles\\11.0\\ArcGISGISServerAdvanced.prvc",
            "Installer": {
                "Path": "C:\\Software\Archives\\ArcGIS\\11.0\\ArcGIS_Server_Windows_110_182874.exe",
                "InstallDir": "D:\\ArcGIS\\Server",
                "InstallDirPython": "D:\\Python27",
                "PatchesDir": "C:\\Software\\Archives\\Patches",
                "PatchInstallOrder": [
                    ""
                ],
                "EnableArcMapRuntime": "True",
                "EnableDotnetSupport": "True"
            },
            "ServerDirectoriesRootLocation": "D:\\arcgisserver\\directories",
            "ConfigStoreLocation": "D:\\arcgisserver\\config-store",
            "LocalRepositoryPath": "D:\\arcgisserver\\local",
            "ServerLogsLocation": "D:\\arcgisserver\\logs",
            "ServerDirectories": [
                {
                    "name": "arcgiscache",
                    "physicalPath": "D:\\arcgisserver\\directories\\arcgiscache",
                    "directoryType": "CACHE",
                    "cleanupMode": "NONE",
                    "maxFileAge": 0
                },
                {
                    "name": "arcgisjobs",
                    "physicalPath": "D:\\arcgisserver\\directories\\arcgisjobs",
                    "directoryType": "JOBS",
                    "cleanupMode": "TIME_ELAPSED_SINCE_LAST_MODIFIED",
                    "maxFileAge": 360
                },
                {
                    "name": "arcgisoutput",
                    "physicalPath": "D:\\arcgisserver\\directories\\arcgisoutput",
                    "directoryType": "OUTPUT",
                    "cleanupMode": "TIME_ELAPSED_SINCE_LAST_MODIFIED",
                    "maxFileAge": 10
                },
                {
                    "name": "arcgissystem",
                    "physicalPath": "D:\\arcgisserver\\directories\\arcgissystem",
                    "directoryType": "SYSTEM",
                    "cleanupMode": "NONE",
                    "maxFileAge": 0
                }
            ],
            "RegisteredDirectories": [
                {
                    "name": "BasemapsCacheDir",
                    "physicalPath": "D:\\arcgisserver\\additionaldirs\\cache",
                    "directoryType": "CACHE"
                },
                {
                    "name": "TestOutputDir",
                    "physicalPath": "D:\\arcgisserver\\additionaldirs\\testOutput",
                    "directoryType": "OUTPUT"
                },
                {
                    "name": "TestJobsDir",
                    "physicalPath": "D:\\arcgisserver\\additionaldirs\\testJobs",
                    "directoryType": "JOBS"
                }
            ],
            "PrimarySiteAdmin": {
                "UserName": "siteadmin",
                "Password": "<supersecretpassword>"
            },
            "EnableHTTPSOnly": "true",
            "EnableHSTS": "true"
        },
        "Portal": {
            "LicenseFilePath": "C:\\Software\\AuthorizationFiles\\11.0\\ArcGIS_Enterprise_Portal.json",
            "PortalLicenseUserTypeId": "CreatorUT",
            "Installer": {
                "Path": "C:\\Software\\Archives\\ArcGIS\\11.0\\Portal_for_ArcGIS_Windows_110_182885.exe",
                "WebStylesPath": "C:\\Software\\Archives\\ArcGIS\\11.0\\Portal_for_ArcGIS_Web_Styles_Windows_110_182886.exe",
                "InstallDir": "D:\\ArcGIS\\Portal",
                "ContentDir": "D:\\arcgisportal",
                "PatchesDir": "C:\\Software\\Archives\\Patches",
                "PatchInstallOrder": [
                    ""
                ]
            },
            "ContentDirectoryLocation":"D:\\arcgisportal\\content",
            "EnableAutomaticAccountCreation": true,
            "DefaultRoleForUser": "Viewer",
            "DefaultUserLicenseTypeIdForUser": "viewerUT",
            "PortalAdministrator": {
                "UserName": "siteadmin",
                "Email": "email",
                "Password": "<supersecretpassword>",
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": "bacon"
            },
            "EnableHSTS": "true"
        },
        "DataStore": {
            "ContentDirectoryLocation": "D:\\arcgisdatastore\"
            "EnableFailoverOnPrimaryStop": false,
            "EnablePointInTimeRecovery": false,
            "Installer": {
                "Path": "C:\\Software\\Archives\\ArcGIS\\11.0\\ArcGIS_DataStore_Windows_110_182887.exe",
                "InstallDir": "D:\\ArcGIS\\DataStore",
                "InstallAllFeatures": false,
                "PatchesDir": "C:\\Software\\Archives\\Patches",
                "PatchInstallOrder": [
                    ""
                ]
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "OverrideHTTPSBinding": true,
            "Installer": {
                "Path": "C:\\Software\\Archives\\ArcGIS\\11.0\ArcGIS_Web_Adaptor_for_Microsoft_IIS_110_182888.exe",
                "PatchesDir": "C:\\Software\\Archives\\Patches",
                "PatchInstallOrder": [
                    ""
                ]
            },
            "WebSiteId": 1
        }
    }
}
```
### Actual Behavior

I have edited the json file (single machine base deployment) for my unique situations.
When I run it I get the following:

Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\Software\BaseDeployment-SingleMachine.json -Mode InstallLicense -MappedDriveOverrideFlag $False -DebugSwitch

I get:

Dot Sourcing the Configuration:- ArcGISInstall
Starting DSC Job:- ArcGISInstall
Start-DscConfiguration : The computer name was not specified and the configuration directory does not have any
configuration files.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.1\ArcGIS.psm1:256 char:16
+ ...      $Job = Start-DscConfiguration -Path ".\$($ConfigurationName)" -F ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-DscConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDs
   cConfigurationCommand

Logs Directory: C:\software\Logs
Finished DSC Job:- ArcGISInstall. Time Taken - 00:00:00.0114646
ArcGISInstall -

### Important Factoids

I am running this on EC2 in AWS

**Comment by cameronkroeker** [comment]
Hi @noelperkins,

There could be an issue with Trusted Hosts. Use the following command to add all the machines in the deployment cluster and the orchestrating machine to each other's trusted host list. Run the command on every machine in the deployment.

`winrm s winrm/config/client '@{TrustedHosts="<IP address goes here>"}'`

> Note: Additional IP's are separated by a comma. For example:

`winrm s winrm/config/client '@{TrustedHosts="10.44.60.13,10.44.60.14"}'`

Additional resource for when using IP instead of hostnames:
https://github.com/Esri/arcgis-powershell-dsc/wiki/Using-Internet-Protocol-(IP)-address-instead-of-Fully-Qualified-Domain-Names-(FQDN)

Thanks,
Cameron K.

**Comment by noelperkins** [comment]
@cameronkroeker 

Thanks for the quick response. I ran the trusted host ps like you suggested as well as  -credential (account has admin privileges) and I still receive the same error.

Thanks,
Noel

**Comment by cameronkroeker** [comment]
Not sure if this is related to the issue or not, but I do notice the path for the server setup in the configuration json is missing an escape `\` after `C:\\Software`:

```"Path": "C:\\Software\Archives\\ArcGIS\\11.0\\ArcGIS_Server_Windows_110_182874.exe",```

Try:
```"Path": "C:\\Software\\Archives\\ArcGIS\\11.0\\ArcGIS_Server_Windows_110_182874.exe",```

**Comment by noelperkins** [comment]
I have made the correction, missed that one, but still same issue.

**Comment by cameronkroeker** [comment]
Found a couple more:

- Missing comma after **ConfigData.DataStore.ContentDirectoryLocation**, and trailing `\`:

```
"ContentDirectoryLocation": "D:\\arcgisdatastore\"
"EnableFailoverOnPrimaryStop": false,
```

change to:

```
"ContentDirectoryLocation": "D:\\arcgisdatastore",
"EnableFailoverOnPrimaryStop": false,
```

- Missing escape `\` in:

```
"Path": "C:\\Software\\Archives\\ArcGIS\\11.0\ArcGIS_Web_Adaptor_for_Microsoft_IIS_110_182888.exe",
```

change to

```
"Path": "C:\\Software\\Archives\\ArcGIS\\11.0\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_110_182888.exe",
```

**Comment by noelperkins** [comment]
Cameron,
I feel like an idiot and thank you for cleaning up my file. but sadly I am still getting the same error.  I have installed the ArcGIS powershell module, downloaded all the software and licensing into the proper folder locations the run the Invoke-ArcGISConfiguration command with all the parameters (to include -Credentials). I noticed it is creating the log folder but no log files, but I assuming that is because it is just in the beginning stages.

**Comment by cameronkroeker** [comment]
@noelperkins,

Let's try to see if the following commands are able to connect using the same IP that is specified for `NodeName`.

```
Test-WSMan -ComputerName insert-ip-here -Authentication default -Port 5985 -Credential insert-admininstrator-username-here
```

and

```
New-CimSession -Port 5985 -ComputerName insert-ip-here -Authentication default -Credential insert-admininstrator-username-here
```

Here is a third party link that gives some suggestions as well:
https://help.argent.com/ARTICLES/KBI_311471.php

Thanks,
Cameron K.

**Comment by noelperkins** [comment]
I am able to connect via the 2 commands. I also reviewed the 3rd party documentation and verified it against our process and they match.

**Comment by cameronkroeker** [comment]
Thanks @noelperkins. This is definitely strange. Could you provide a bit more details about the environment?

- Is the orchestrating node same as target node?
  - If they are different, then can you try running the `Invoke-ArcGISConfiguration` command from the Target Node?
- What version of Windows is the target node?
- Is the target node ec2 instance joined to a domain?
  - If it is, perhaps there is a group policy or security policy in place that is causing an issue?
- Ensure PowerShell is version 5.1
  - Run this command to check the version: `$PSVersionTable`
  - WMF 5.1 download: https://www.microsoft.com/en-us/download/details.aspx?id=54616
- Be sure to launch PowerShell as an Administrator (right click run-as admin).

I was able to run the following test, and ArcGISInstall was successful:
- Spun up a new EC2 instance in AWS console
   - Windows Server 2022 base
- RDP'd into the EC2 instance as the local Administrator account
- Launched PowerShell as an Administrator, and ran this command to add the local ipv4 address to Trusted Hosts
  - `winrm s winrm/config/client '@{TrustedHosts="10.0.1.76"}'`
- Ran this command to install v4.0.2 module from the PSGallery:
  - `Install-Module ArcGIS`
- Modified the json config file from above with the edits we discussed, and with some additional changes:
  -  My EC2 instance doesn't have a secondary drive, so I replaced all `D:\\` locations with `C:\\`
  - changed  `ConfigData.Credentials.IsDomainAccount` to `false` since my EC2 instance isn't joined to a domain
  - I also changed `ConfigData.DownloadSetups` (requires `ConfigData.Credentials.AGOCredential`) and `ConfigData.DownloadPatches` to `true` so that I wouldn't have to manually upload these to the target node.
  - Ran this command to start the deployment:
    - `Invoke-ArcGISConfiguration .\arcgis-enterprise-aws-11.0.json -Mode Install -DebugSwitch -EnableMSILogging -Credential Administrator`

**Comment by cameronkroeker** [comment]
@noelperkins this isn't the cause of the issue, but wanted to give you a heads up it will cause an issue later in the deployment. All Boolean (true|false) attributes within the json configuration file shouldn't be wrapped in quotes, and should be all lower case. For example:

```
"EnableHTTPSOnly": "true",
"EnableHSTS": "true"
```

**should instead be:**

```
"EnableHTTPSOnly": true,
"EnableHSTS": true
```

Otherwise you may see an error similar to:

```
Dot Sourcing the Configuration:- ArcGISServer
ArcGISServer : Cannot process argument transformation on parameter 'EnableHTTPSOnly'. Cannot convert value "System.String" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or
0.
```

**Comment by noelperkins** [comment]
I expected the new machine (no domain and no GPO) to run it just fine, but it did not same error. I am using the machine Administrator account.
I ran all previous setup suggestions and testing same results I then changed all the D:\\ to C:\\ and same results. I then set it up to download software and patches - same thing. 
The next thing is I am going to see if I can use a different AMI.

**Comment by cameronkroeker** [comment]
Thanks @noelperkins for the additional details and update. Is there a particular reason for using ip over hostname\fqdn for `NodeName` when the nodes are joined to the domain?

Another thing to try is adding the hostname, fully qualified domain name (fqdn), and ip to the winrm Trusted Hosts. Or for testing purposes I believe you can specify an `*` and it will trust all hostname/ip's (not secure so only recommended for testing/temporary purposes).

**Comment by noelperkins** [comment]
@cameronkroeker I should have stated that I have used both the hostname and fqdn also, all with the same results. I have tried trusting it via IP, hostname, fqdn and * with the same results.

**Comment by cameronkroeker** [comment]
Thanks @noelperkins for providing the additional details. Next let's check the [ExecutionPolicy](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.3&viewFallbackFrom=powershell-7.1) and `PSSessionConfiguration`.

```
PS C:\Users\Administrator\Desktop>Get-ExecutionPolicy -List

PS C:\Users\Administrator\Desktop> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine          Bypass
```
and
```
PS C:\Users\Administrator\Desktop> Get-PSSessionConfiguration


Name          : microsoft.powershell
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\INTERACTIVE AccessAllowed, BUILTIN\Administrators AccessAllowed, BUILTIN\Remote Management Users AccessAllowed

Name          : microsoft.powershell.workflow
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : BUILTIN\Administrators AccessAllowed, BUILTIN\Remote Management Users AccessAllowed

Name          : microsoft.powershell32
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\INTERACTIVE AccessAllowed, BUILTIN\Administrators AccessAllowed, BUILTIN\Remote Management Users AccessAllowed

Name          : microsoft.windows.servermanagerworkflows
PSVersion     : 3.0
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\INTERACTIVE AccessAllowed, BUILTIN\Administrators AccessAllowed
```

**Comment by noelperkins** [comment]
@cameronkroeker all good on my end
PS C:\Software> ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine          Bypass


PS C:\Software> Get-PSSessionCOnfiguration


Name          : microsoft.powershell
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\INTERACTIVE AccessAllowed, BUILTIN\Administrators AccessAllowed, BUILTIN\Remote
                Management Users AccessAllowed

Name          : microsoft.powershell.workflow
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : BUILTIN\Administrators AccessAllowed, BUILTIN\Remote Management Users AccessAllowed

Name          : microsoft.powershell32
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\INTERACTIVE AccessAllowed, BUILTIN\Administrators AccessAllowed, BUILTIN\Remote
                Management Users AccessAllowed

Name          : microsoft.windows.servermanagerworkflows
PSVersion     : 3.0
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\INTERACTIVE AccessAllowed, BUILTIN\Administrators AccessAllowed

**Comment by noelperkins** [comment]
@cameronkroeker ,
I was able to get back on this 2 things, 1) I was missing a comma after "ContentDirectoryLocation": "D:\\arcgisdatastore",  2) the other item was the machine was not recognizing the domain account for the Service. Both items have been resolved and it is installing. Now onto the configuration portion :) 

Thanks for all the help!
