### ISSUE TITLE
DSC resource ArcGIS_Server_TLS  failed to execute Set-TargetResource functionality with error message: ERROR: ArcGIS.Common.psm1 failed. Importing CA certificate failed.

### ISSUE THREAD

**Issue by minagim** [Esri/arcgis-powershell-dsc#446]
[

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.2

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal
* DataStore
* ServerWebAdaptor
* PortalWebAdaptor

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```
[BaseDeployment_SingleMachine.zip](https://github.com/Esri/arcgis-powershell-dsc/files/10495194/BaseDeployment_SingleMachine.zip)

![Capture](https://user-images.githubusercontent.com/60987985/214458239-f1b45de8-9c8f-4c05-8fd3-b76b6548aa6b.PNG)

![image](https://user-images.githubusercontent.com/60987985/214458422-07898bda-6dc2-46e5-887a-530bf2fabb1f.png)

### Expected Behavior

Install ArcGIS Data Store, Server, Portal, Server and Portal web adaptors on a single machine

### Actual Behavior

Installation failed with the following error message.
PowerShell DSC resource ArcGIS_Server_TLS  failed to execute Set-TargetResource functionality with error message: 
ERROR: ArcGIS.Common.psm1 failed. Importing CA certificate failed.  
The SendConfigurationApply function did not succeed.

### Steps to Reproduce

Run the attached script

**Comment by cameronkroeker** [comment]
Hi @minagim,

Thank you for providing the dsc deployment logs and json config file. I am curious does the certificate password contain any special characters (if so could you share which one(s))? Also, did the import succeed for portal? And lastly, does the certificate import successfully when manually imported using the ArcGIS Server Admin endpoint?

Thanks,
Cameron K.

**Comment by minagim** [comment]
Hi, Cameron.

Thanks for looking into my problem.
Yes, the password does include one special character *.  I can try it without.  I've done multi machine setups before in earlier versions and I didn't have any issues with the same password.

For the other question, I think the set up didn't reach the portal config yet.  This error was during the ArcGIS Server setup after installation.
Hope this helps. Please let me know if you have any other questions.

Thanks,

Mina

From: Cameron Kroeker ***@***.***>
Sent: Wednesday, January 25, 2023 12:09 PM
To: Esri/arcgis-powershell-dsc ***@***.***>
Cc: Kim, Mina (Parks) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Esri/arcgis-powershell-dsc] DSC resource ArcGIS_Server_TLS failed to execute Set-TargetResource functionality with error message: ERROR: ArcGIS.Common.psm1 failed. Importing CA certificate failed. (Issue #446)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.  Forward suspect email to ***@***.******@***.***> as an attachment (Click the More button, then forward as attachment).


Hi @minagim<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fminagim&data=05%7C01%7Cmina.kim%40parks.nyc.gov%7Cd45e3e5164b241eca48308dafef6d557%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638102633367780517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5b%2B2lTV%2FKPG2QsKZJWOzJlu7NXqJxyv5%2F7K2CP%2FRgd0%3D&reserved=0>,

Thank you for providing the dsc deployment logs and json config file. I am curious does the certificate password contain any special characters (if so could you share which one(s))? Also, did the import succeed for portal? And lastly, does the certificate import successfully when manually imported using the ArcGIS Server Admin endpoint?

Thanks,
Cameron K.

-

**Comment by minagim** [comment]
Hi, Cameron.

I just tested with the cert password changed with only letters and numbers and I got the same error message.

***@***.***

The ArcGIS Server is set up with DNS:6443 but not with the DNS alone with the certificate.

Mina

From: Kim, Mina (Parks)
Sent: Wednesday, January 25, 2023 12:23 PM
To: Esri/arcgis-powershell-dsc ***@***.***>; Esri/arcgis-powershell-dsc ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [EXTERNAL] Re: [Esri/arcgis-powershell-dsc] DSC resource ArcGIS_Server_TLS failed to execute Set-TargetResource functionality with error message: ERROR: ArcGIS.Common.psm1 failed. Importing CA certificate failed. (Issue #446)

Hi, Cameron.

Thanks for looking into my problem.
Yes, the password does include one special character *.  I can try it without.  I've done multi machine setups before in earlier versions and I didn't have any issues with the same password.

For the other question, I think the set up didn't reach the portal config yet.  This error was during the ArcGIS Server setup after installation.
Hope this helps. Please let me know if you have any other questions.

Thanks,

Mina

From: Cameron Kroeker ***@***.******@***.***>>
Sent: Wednesday, January 25, 2023 12:09 PM
To: Esri/arcgis-powershell-dsc ***@***.******@***.***>>
Cc: Kim, Mina (Parks) ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [Esri/arcgis-powershell-dsc] DSC resource ArcGIS_Server_TLS failed to execute Set-TargetResource functionality with error message: ERROR: ArcGIS.Common.psm1 failed. Importing CA certificate failed. (Issue #446)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.  Forward suspect email to ***@***.******@***.***> as an attachment (Click the More button, then forward as attachment).


Hi @minagim<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fminagim&data=05%7C01%7Cmina.kim%40parks.nyc.gov%7Cd45e3e5164b241eca48308dafef6d557%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638102633367780517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5b%2B2lTV%2FKPG2QsKZJWOzJlu7NXqJxyv5%2F7K2CP%2FRgd0%3D&reserved=0>,

Thank you for providing the dsc deployment logs and json config file. I am curious does the certificate password contain any special characters (if so could you share which one(s))? Also, did the import succeed for portal? And lastly, does the certificate import successfully when manually imported using the ArcGIS Server Admin endpoint?

Thanks,
Cameron K.

-
