### ISSUE TITLE
Portal Create New Site Unable to unzip portal content

### ISSUE THREAD

**Issue by lachlanwainwright** [Esri/arcgis-powershell-dsc#454]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.2

### Affected Resource(s)

* ArcGIS_Portal

### Configuration Files

3 machines setup in AZURE:
   - Machine 1: Portal, Portal Web Adaptor, Server Web Adaptor
   - Machine 2: ArcGIS Server
   - Machine 3: Datastore

**Shared configuration on AZURE file share** 

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

Portal site should have created

### Actual Behavior

**Run 1: Creating Portal Site issue**
```28/02/2023 9:53:26 AM: [portalmachine]:                            [[ArcGIS_Portal]Portalportalmachine] Using Content Store on File System at location \\azure\sharename\arcgisportal\content

28/02/2023 9:53:26 AM: [portalmachine]:                            [[ArcGIS_Portal]Portalportalmachine] Making request to https://macineURL.com:7443/arcgis/portaladmin/createNewSite to create the site

28/02/2023 10:11:51 AM: [portalmachine]:                            [[ArcGIS_Portal]Portalportalmachine] Response received from create site {
    "error":  {
                  "code":  500,
                  "message":  "Unable to unzip portal content.",
                  "details":  null
              }
}
28/02/2023 10:11:51 AM: [portalmachine]: LCM:  [ End    Set      ]  [[ArcGIS_Portal]Portalportalmachine]  in 1188.5050 seconds.
28/02/2023 10:11:51 AM: [portalmachine]: LCM:  [ End    Set      ]
28/02/2023 10:11:51 AM: Operation 'Invoke CimMethod' complete.
```

**Run 2: Created Portal Site all else went well but failed to register web adaptors**

**Run 3: Registered Web Adaptors, all other parts of config completed successfully**

**Run 4: Ran through without issues**

### Steps to Reproduce

I can't see any issues with the build yet, so the question is, has Portal installed correctly?

See checks in factoids, all appears aok.

If not, should I:
    1. start again: restore the snapshots for all servers, delete all content from shared config
    2. restore only the portal machine, clear out 

### Important Factoids
Reindexed Portal, all aok there

checked Portal logs and this message appears for:
    **SEVERE The process of creating a new site failed. Reverting site creation. Unable to unzip portal content.**
I am assuming it cleans itself up. Subsequent messages in logs appear things went swell with Portal Site creation.

Everything in Portal, AGS and DS appear to be working as expected.

**Comment by cameronkroeker** [comment]
Hi @lachlanwainwright,

Here are some additional validation checks to try:
 
1. Ensure hosting server federation validates in portal home -> settings -> servers (or can also check in portaladmin endpoint)
2. Ensure relational data store in server manager validates. As well as any other data stores types you may have like tile cache. 
3. Check system properties in portaladmin to ensure webcontexturl and private portal url are set as desired. 
4. Create some content, like publish a hosted feature layer or test some of the workflows out that your organization will be doing. 

If these checks pass then I think it is safe to say the deployment is golden.

Thanks,
Cameron K.

**Comment by lachlanwainwright** [comment]
Thanks Cameron
Checkes done and passed without issue.
I have also run a webgisdr as another check and that passed perfectly too.

None of the logs show any severe errors so it's **golden**.

Thanks again Cameron on the ESRI DSC crew
