### ISSUE TITLE
portal/sharing/rest Admin URL not pointing to Web Adaptor after Server Federation to Portal in HA

### ISSUE THREAD

**Issue by abakhtin9** [Esri/arcgis-powershell-dsc#457]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.2

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_DataStore

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "mrlangpent1",
            "DataStoreTypes": [
                "Relational",
                "TileCache"
            ],
            "Role": [
                "Server",
                "Portal",
                "DataStore"
            ]

        },
        {
            "NodeName": "mrlangplb1",
            "DataStoreTypes": [
                "Relational",
                "TileCache"
            ],
            "Role": [
                "Server",
                "Portal"
            ]

        },
        {
            "NodeName": "mrlangpweb1",
            "Role": [
                "ServerWebAdaptor",
                "PortalWebAdaptor"
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.9.1",
        "ServerContext": "arcgis",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "Password": password,
                "UserName": username,
                "IsDomainAccount": false,
                "IsMSAAccount": false
            }
        },
        "Server": {
            "LicenseFilePath": "E:\\DSC_PRD\\Licenses\\ArcGISServerStandard_ArcGISServer_SFPUC.prvc",
            "Installer": {
                "Path": "E:\\DSC_PRD\\Installers\\ArcGIS_Server_Windows_1091_180041.exe",
                "InstallDir": "E:\\ArcGIS\\Server",
                "InstallDirPython": "E:\\Python27",
                "EnableArcMapRuntime": "False"
            },
            "ServerDirectoriesRootLocation": "\\\\10.228.120.242\\share_01\\arcgisserver\\directories",
            "ConfigStoreLocation": "\\\\10.228.120.242\\share_01\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": username,
                "Password": password
            },
            "ExternalLoadBalancer": "client.domain.org",
            "InternalLoadBalancer": "mrlangpent1.local"
        },
        "Portal": {
            "LicenseFilePath": "E:\\DSC_PRD\\Licenses\\ArcGIS_Enterprise_Portal_1091_407009_20230126.json",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "E:\\DSC_PRD\\Installers\\Portal_for_ArcGIS_Windows_1091_180052.exe",
                "InstallDir": "E:\\ArcGIS\\Portal",
                "ContentDir": "E:\\arcgisportal\\content"
            },
            "ContentDirectoryLocation": "\\\\10.228.120.242\\share_01\\arcgisportal\\content",
            "PortalAdministrator": {
                "UserName": username,
                "Email": email,
                "Password": password,
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": "vanilla"
            },
            "ExternalLoadBalancer": "client.domain.org",
            "InternalLoadBalancer": "mrlangpent1.local"
        },
        "DataStore": {
            "ContentDirectoryLocation": "E:\\arcgisdatastore",
            "EnableFailoverOnPrimaryStop": true,
            "Installer": {
                "Path": "E:\\DSC_PRD\\Installers\\ArcGIS_DataStore_Windows_1091_180054.exe",
                "InstallDir": "E:\\ArcGIS\\DataStore"
            },
            "EnablePointInTimeRecovery": true
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "C:\\DSC_PRD\\Installers\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_1091_180055.exe"
            }
        }
    }
}
```

### Expected Behavior

The Admin URL should show the web adaptor machine for ArcGIS Server after federation, not the primary ArcGIS Server machine FQDN

### Actual Behavior

The Admin URL points to the server manager using the primary server's FQDN
![image](https://user-images.githubusercontent.com/19733454/230974815-a2f7fe8b-c234-4179-8c13-1bf334b60f6f.png)
```The Admin URL should say https://mrlangpweb1.local/arcgis```
### Steps to Reproduce

* Run configuration

### Important Factoids

* The three servers (all on-prem) that compose this environment are not part of a domain (part of WORKGROUP) nor is the service account being used to run each service a domain account. It is a local administrator that has been created on each server

**Comment by abakhtin9** [comment]
In looking at this again - would this actually be determined by the `InternalLoadBalancer` variable in the Server section?

**Comment by cameronkroeker** [comment]
> In looking at this again - would this actually be determined by the `InternalLoadBalancer` variable in the Server section?

Hi @abakhtin9, yes you are correct. When the **ConfigData.Server.InternalLoadBalancer** is defined in the config json then this is used as the federated server admin url.

If you remove **ConfigData.Server.InternalLoadBalancer**, then I believe it will fall back and use **ConfigData.Server.ExternalLoadBalancer** (since **ConfigData.WebAdaptor.AdminAccessEnabled** is set to true.)

However, since you want the federated server adminUrl to be `https://mrlangpweb1.local/arcgis`, then I suggest try using the following:

```
"ExternalLoadBalancer": "stormwater.sfpuc.org",
"InternalLoadBalancer": "mrlangpweb1.local",
"InternalLoadBalancerPort": "443"
```

Thanks,
Cameron K.

**Comment by abakhtin9** [comment]
Hi @cameronkroeker, thanks for the clarification. As it currently stands, we have this environment up and running. Could we just change the internal load balancer and add the port and re-run the configuration or would we need to do more than that to change it?

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker, thanks for the clarification. As it currently stands, we have this environment up and running. Could we just change the internal load balancer and add the port and re-run the configuration or would we need to do more than that to change it?

If it's already federated I do not believe the module has the ability to update or change the existing federated server adminUrl. You will need to first [unfederate](https://enterprise.arcgis.com/en/server/latest/deploy/windows/removing-an-arcgis-server-site-from-your-portal.htm) then re-run the module or manually update it using the steps outlined here:

https://community.esri.com/t5/arcgis-enterprise-questions/edit-portal-services-url/m-p/430617/highlight/true#M16656

Thanks,
Cameron K.
