### ISSUE TITLE
ArcGIS Server patch "ArcGIS-111-S-WSD-Patch.msp" always installed

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.1.0

### Affected Resource(s)

* ArcGIS_Install

### Configuration Files

[GisPortalAGSDeployment_anonymous.txt](https://github.com/Esri/arcgis-powershell-dsc/files/11403750/GisPortalAGSDeployment_anonymous.txt)

### Expected Behavior

Already installed patch should be reinstalled.

### Actual Behavior

Patch is always installed when running the configuration.

### Steps to Reproduce

Run the configuration twice: patch will be installed twice. On "Check for ArcGIS Enterprise updates" utility, it does appear as installed.

### Important Factoids

- Tested on Windows server 2022
- Get-QFEId
```
Get-QFEId -PatchLocation $PatchLocation
```
returns null

```
04.05.2023 22:00:50: [MAPSQA01]:                            [[ArcGIS_InstallPatch]ServerInstallPatch] Checking Patch File at \\pathto\patches\11.1\server\ArcGIS-111-S-WSD-Patch.msp
04.05.2023 22:00:50: [MAPSQA01]:                            [[ArcGIS_InstallPatch]ServerInstallPatch] Patch File at \\pathto\patches\11.1\server\ArcGIS-111-S-WSD-Patch.msp with QFE Id  not installed
```

**Comment by cameronkroeker** [comment]
Hi @Biboba,

This looks similar to the 10.9.1 log4j patch issue: https://github.com/Esri/arcgis-powershell-dsc/issues/394#issuecomment-1118923443.

Looks like the ArcGIS-111-S-WSD-Patch.msp is missing the QFE_ID. The module will extract the QFE_ID from the .msp file to use to compare with the Windows registry:

![image](https://user-images.githubusercontent.com/48299621/236564284-4f936be4-f5be-48fa-88d3-462a18e36401.png)

Since the msp doesn't contain the QFE_ID the idempotency check fails every time. I'm afraid there isn't much we can do within the Module to address this issue.

> Note: When ConfigData.DownloadPatches is set to true the module will obtain the QFE_ID from the internet to use and compare against the registry entry rather than the msp file.

Thanks,
Cameron K.

**Comment by Biboba** [comment]
Hi @cameronkroeker,

Thanks for your reply. I understand it is not related to DSC.... but it's annoying. I like to master patches installation timing so I am not fond of downloading them at runtime. 
Maybe you could do some lobbying to the team in charge of releasing patches ? Or do you think we should open a ticket with support to get that fixed ?

Thanks

**Comment by ceddc** [comment]
Hello @Biboba  @cameronkroeker 
The patch have been updated 👍 https://support.esri.com/en-us/patches-updates/2023/arcgis-server-11-1-wms-services-display-patch-8108

`Important Note May 16, 2023: The ArcGIS Server 11.1 WMS Services Display Patch setups have been updated to allow installation using a Chef Cookbooks or PowerShell DSC automation script. Please download and install the new setup. It is not necessary to uninstall the original patch, the new setup will install and replace the original patch.`

**Comment by Biboba** [comment]
Thanks for update @ceddc ! Very good news.
Closing then !
