### ISSUE TITLE
ArcGIS.Common.psm1 cannot be loaded ? 

### ISSUE THREAD

**Issue by CyientNam1** [Esri/arcgis-powershell-dsc#470]
I am trying to install ArcGIS Enterprise 11.1 on a single node deployment, I am facing the below error, any insights would be great, 

### Module Version 4.1.0

VERBOSE: Time taken for configuration job to complete is 0.028 seconds
5/22/2023 12:44:08 PM: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
5/22/2023 12:44:13 PM: An LCM method call arrived from computer DCA-DEV3029 with user sid S-1-5-21-847991084-1712597869-449653690-1895561.
5/22/2023 12:44:13 PM: [DCA-DEV3029]: LCM:  [ Start  Set      ]
5/22/2023 12:44:13 PM: [DCA-DEV3029]: LCM:  [ End    Set      ]
5/22/2023 12:44:13 PM: Operation 'Invoke CimMethod' complete.
Trace-DSCJob : 5/22/2023 12:44:13 PM: Importing module ArcGIS_RemoteFile failed with error - File C:\Program
Files\WindowsPowerShell\Modules\ArcGIS\Modules\ArcGIS.Common\ArcGIS.Common.psm1 cannot be loaded. The file C:\Program
Files\WindowsPowerShell\Modules\ArcGIS\Modules\ArcGIS.Common\ArcGIS.Common.psm1 is not digitally signed. You cannot run this script on the current system.
For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

**Comment by cameronkroeker** [comment]
Hi @CyientNam1,

Let's check the execution policy on the target and orchestrating node:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3

**Error:** 
```
The file C:\Program
Files\WindowsPowerShell\Modules\ArcGIS\Modules\ArcGIS.Common\ArcGIS.Common.psm1 is not digitally signed. You cannot run this script on the current system.
```

Try running the following Powershell command:

```powershell
Set-ExecutionPolicy RemoteSigned
```

Might also need to unblock the files within the Module:

```powershell
Get-ChildItem -Path 'C:\Program Files\WindowsPowerShell\Modules\ArcGIS' | Unblock-File
```

Thanks,
Cameron K.

**Comment by CyientNam1** [comment]
Awesome for the quick reply, Unblocking the file has resolved the issue
