### ISSUE TITLE
Unable to find the Variable definitions in Wiki page or PublishGISService.json

### ISSUE THREAD

**Issue by CyientNam1** [Esri/arcgis-powershell-dsc#471]
### Module Version

4.10

### Affected Resource(s)

* Publish Services 

### Expected Behavior

Can you please add the Variable definitions for the sample config : PublishGISService.json ?

**Comment by widsuoids** [comment]
https://github.com/Esri/arcgis-powershell-dsc/wiki/Publishing-GIS-Services-via-the-ArcGIS-Module
