### ISSUE TITLE
ArcGIS Pro Single Use license not authorizing

### ISSUE THREAD

**Issue by genspec** [Esri/arcgis-powershell-dsc#473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.0

### Affected Resource(s)

* ArcGIS Pro

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "2108-jxi",
            "Role": [
                "Pro"
            ]
        }
    ],
    "ConfigData": {
        "ProVersion": "3.1",
        "Pro": {
            "LicenseFilePath": "\\\\2108-jxi\\Deployment\\Licenses\\3.1\\ArcGISProStandard_SingleUse.prvc",
            "AuthorizationType": "SINGLE_USE",
            "LockAuthSettings": false,
            "BlockAddIns": "0",
            "SoftwareClass": "Editor",
            "PortalList": "https://jvs-portal/portal/",
            "DotnetDesktopRuntimePath": "\\\\2108-jxi\\Deployment\\Software\\Media\\11.1\\dotnet-hosting-6.0.16-win.exe",
            "AllUsers": "1",
            "EnableEUEI": false,
            "CheckForUpdatesAtStartup": false,
            "Installer": {
                "Path": "\\\\2108-jxi\\Deployment\\Software\\Media\\3.1\\ArcGISPro_31_184994.exe",
                "IsSelfExtracting": true,
                "InstallDir": "C:\\Program Files\\ArcGIS\\Pro",
                "PatchesDir": "\\\\2108-jxi\\Deployment\\Software\\Patches\\ArcGISPro\\3.1",
                "PatchInstallOrder": [
                    "ArcGIS_Pro_312_185016.msp"
                ]
            }
        }
    }
}
```

### Expected Behavior

After installation, ArcGIS Pro should open and make use of the Single Use license

### Actual Behavior

After installation, when ArcGIS Pro is opened, I am promted with the Licensing window and no licenses are authorized.

### Steps to Reproduce

I ran:
```
Invoke-ArcGISConfiguration -ConfigurationParametersFile "\\2108-JXI\Deployment\Templates\3.1\Development-Pro-SingleUse.json" -Mode Install
```
### Important Factoids

Tried this on my laptop and an Azure Virtual Machine.

**Comment by cameronkroeker** [comment]
Hello @genspec,

The `Invoke-ArcGISConfiguration -Mode Install` will only run the installation. To install and authorize the license, please use `-Mode InstallLicense`.

https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters#-mode

Thanks,
Cameron K.

**Comment by genspec** [comment]
Thanks @cameronkroeker, what a silly oversight from me.
