### ISSUE TITLE
ArcGIS Pro Single Use Ignoring DotnetDesktopRuntimePath

### ISSUE THREAD

**Issue by dimesv** [Esri/arcgis-powershell-dsc#474]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version
* 4.1.0

### Affected Resource(s)
* ArcGIS_Pro

### Expected Behavior
The setup installs Dotnet Desktop Runtime prior to installing Pro.

### Actual Behavior
The setup extracts the MSI, and runs it without installing the supplied Dotnet Desktop Runtime which is a pre-requisite. It ignores the property DotnetDesktopRuntimePath

Any idea why?

### Steps to Reproduce
Use the default Pro Single Use sample, set the property DotnetDesktopRuntimePath and run InstallLicense on a server without dotnet desktop runtime. The install will fail because the DSC will not install the supplied exe.

### References

**Comment by cameronkroeker** [comment]
Hi @dimesv,

What is the version of ArcGIS Pro is being installed? On the target node does the `windowsdesktop-runtime-6.0.5-win-x64.exe` already exist in the path specified for `DotnetDesktopRuntimePath`?

Thanks,
Cameron K.

**Comment by dimesv** [comment]
Hi @cameronkroeker ,

The ArcGIS Pro version being installed is 3.1 with a patch that moves it to 3.1.2.
My config is as per the attached image. The windowsdesktop-runtime-6.0.16-win-x64.exe exists in the shared path and the machine has proper access to the file. It just appears looking to the logs that the install never attempts to validate if this sdk is installed and install it if not. It jumps immediately to install Pro.

Let me know if you need further details.

Thanks,
Jose
(Esri NZ - Eagle Technology)

![image](https://github.com/Esri/arcgis-powershell-dsc/assets/5733148/ad7af473-0770-4e65-ab6c-2fce24edecec)

**Comment by cameronkroeker** [comment]
Thanks for sharing the json config file. In your json you have `DotnetDesktopRuntimePath` outside the Installer block. Could you try moving the `DotnetDesktopRuntimePath` attribute to inside the **ConfigData.Pro.Installer** block? For example:

https://github.com/Esri/arcgis-powershell-dsc/blob/8621f7a7256d6f8b9431caf4674e01c8d3bce249/SampleConfigs/v4/v4.1.0/DesktopPro/Pro-SingleUse.json#L22-L31

**Comment by dimesv** [comment]
Geez, can't believe I missed that. Thank you @cameronkroeker.

Cheers,
Cameron

**Comment by dimesv** [comment]
It worked just fine with the change.

Cheers,
Jose
