### ISSUE TITLE
The Module uses unapproved Verbs

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#48]
On Import of the Module there is the following warning:
```WARNING: The names of some imported commands from the module 'ArcGIS' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose
parameter. For a list of approved verbs, type Get-Verb.
VERBOSE: The 'Configure-ArcGIS' command in the ArcGIS' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Set".
VERBOSE: Importing function 'Configure-ArcGIS'.
VERBOSE: Importing function 'Get-FQDN'.
VERBOSE: Importing function 'Publish-WebApp'.
```

There are also some functions using unapproved verbs which are not exported.
https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx

**Comment by cameronkroeker** [comment]
Hello @spitzerr,

We have fixed this in the latest release, v3.0.0:

`Invoke-ArcGISConfiguration -ConfigurationParametersFile [[Path to Configuration JSON File]] -Mode [Install | InstallLicense | InstallLicenseConfigure | Uninstall | Upgrade] -Credential [Config RunAs - Optional] -MappedDriveOverrideFlag [$True | $False] -DebugSwitch`

or

`Invoke-ArcGISConfiguration [[Path to Configuration json File]] [Install | InstallLicense | InstallLicenseConfigure | Uninstall | Upgrade] -Credential [Config RunAs - Optional] -MappedDriveOverrideFlag [$True | $False] -DebugSwitch`
