### ISSUE TITLE
Webadaptor 11.1 patch installation failed

### ISSUE THREAD

**Issue by widsuoids** [Esri/arcgis-powershell-dsc#482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

4.1

### Affected Resource(s)

* Webadaptor 

* ArcGIS Enterprise is not usable. All components are installed correctly, however, the configuring step by the script did not execute. When setting the download Patches Option to false, there is no more Webadaptor related Error, but it still fails.

Trace-DSCJob :  The PowerShell DSC-Ressource "ArcGIS_Install" could not execute the function "Set-TargetResource". Error message: "Install failed. Process exit code:- 1619. Error - "

The function 'SendConfigurationApply' was not successful.

In C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.1.0\ArcGIS.psm1:261 Character:5

 Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

Based on the sample and default values

```
"WebAdaptor": {
            "AdminAccessEnabled": true,
            "OverrideHTTPSBinding": true,
            "Installer": {
                "Path": "D:\\downloads\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_111_185222.exe",
                "DotnetHostingBundlePath": "D:\\downloads\\",
                "DotnetHostingBundleDownloadUrl": "https://download.visualstudio.microsoft.com/download/pr/eaa3eab9-cc21-44b5-a4e4-af31ee73b9fa/d8ad75d525dec0a30b52adc990796b11/dotnet-hosting-6.0.9-win.exe",
                "WebDeployPath": "D:\\downloads\\",
                "WebDeployDownloadUrl": "https://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi",
                "IsSelfExtracting": true,
                "PatchesDir": "D:\\downloads\\"
            },
            "WebSiteId": 1
        }

```

### Expected Behavior

Successful installation

### Actual Behavior

Installation failed for patch 

### Steps to Reproduce

Download and install patch for Webadaptor 11.1

**Comment by cameronkroeker** [comment]
Hi @widsuoids,

The value specified for `"PatchesDir"` doesn't look complete.

`"PatchesDir": "D:\\downloads\\"`

Could you try either of these instead?

`"PatchesDir": "D:\\downloads"`

or

`"PatchesDir": "D:\\downloads\\someFolder"`

When `"DownloadPatches"` is set to false and `"PatchesDir"` is specified in the json config file the Module will look in the specified PatchesDir for patch files and install of them in random order. 

Thanks,
Cameron K.
