### ISSUE TITLE
LicensePassword and LicensePasswordFilePath are not supported/implemented for ArcGIS Pro

### ISSUE THREAD

**Issue by sverkerEsriSE** [Esri/arcgis-powershell-dsc#492]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.1.0

### Affected Resource(s)

* ArcGIS_Pro

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "MYCOMPUTER",
            "Role": [
                "Pro"
            ]
        }
    ],
    "ConfigData": {
        "ProVersion": "3.1",
        "Pro": {
            "LicenseFilePath": "C:\\ArcGISDSC\\License\\ArcGISProAdvanced_SingleUse_XXXXX.eslf",
            "LicensePassword": "thisisthepassword",
            "AuthorizationType": "SINGLE_USE",
            "LockAuthSettings": false,
            "BlockAddIns": "0",
            "SoftwareClass": "Professional",
            "AllUsers": "1",
            "EnableEUEI": false,
            "CheckForUpdatesAtStartup": true,
            "Installer": {
                "Path": "C:\\ArcGISDSC\\media\\ArcGISPro\\ArcGISPro.msi",
                "DotnetDesktopRuntimePath": "C:\\ArcGISDSC\\media\\windowsdesktop-runtime-6.0.21-win-x64.exe",
                "IsSelfExtracting": false,
                "InstallDir": "c:\\Program Files\\ArcGIS\\Pro",
                "PatchesDir": "C:\\ArcGISDSC\\media\\ArcGISPro\\Patches"
            }
        }
    }
}
```

### Expected Behavior

The software is installed and licensed properly using the provided .eslf file that is password protected

### Actual Behavior

We get an error message when the ArcGISLicense DSC Job is run:
_PowerShell DSC resource ArcGIS_License  failed to execute Set-TargetResource functi
onality with error message: <some inexpressive error message>_

### Steps to Reproduce

1. Prepare all the installation files and other stuff that's needed
2. Get a password protected .eslf licensing file from MyEsri (Note: many customers will probably not have this option)
3. Save the above config to Pro-SingleUse.json and modify to your liking
4. Run Invoke-ArcGISConfiguration -Mode InstallLicenseConfigure -ConfigurationParametersFile .\Pro-SingleUse.json
5. Wait for the licensing to fail

### References

See pull request #491

**Comment by cameronkroeker** [comment]
This has been added to release v4.2.0. Thanks!

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.2.0
