### ISSUE TITLE
DSC 4.1.0 - Missing .NET Desktop Runtime 6.0 (x64) for ArcGIS Server 11.1 - SOE/SOI .NET support

### ISSUE THREAD

**Issue by lorenzmeyer77** [Esri/arcgis-powershell-dsc#494]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.1.0

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

The current DSC module 4.1.0 supports ArCGIS 11.1 but one part is missing. If you would like to have Server Object Extensions or Server Object Interceptors (SOE and SOI) installed on your ArcGIS Server, you need to install .NET Dekstop 6.0 runtime support. It's mentioned here: https://developers.arcgis.com/enterprise-sdk/guide/net/net-6-support/ and here https://developers.arcgis.com/enterprise-sdk/guide/net/net-6-support/#deploy-net-6-soes-and-sois-to-arcgis-server

If this .NET Desktop runtime is installed, the optional feature ".NET extension support" for ArcGIS Server can be chosen to be installed. This .NET Desktop runtime configuration is currently missing. It is configurable for an ArcGIS Pro installation. See "DotnetDesktopRuntimeDownloadUrl " or "DotnetDesktopRuntimePath" from the variable reference page: https://github.com/Esri/arcgis-powershell-dsc/wiki/v4.1.0-Variables-reference-page-for-JSON-configuration-files

We would need the same for ArcGIS server as it is for ArcGIS Pro.

### Actual Behavior

Not implemented

### Steps to Reproduce

Completely missing

**Comment by cameronkroeker** [comment]
Support has been added for downloading and installing Microsoft Dot Net Desktop Runtime for ArcGIS Server in DSC ArcGIS Module v4.4.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.4.0

Sample Json:
```json
"Server": {
   "Installer": {
      "Path": "C:\\Software\\Archives\\11.3\\ArcGIS_Server_Windows_113_190188.exe",
      "VolumePaths": [
         "C:\\Software\\Archives\\11.3\\ArcGIS_Server_Windows_113_190188.exe.001"
      ],
     "InstallDir": "C:\\Program Files\\ArcGIS\\Server",
     "EnableDotnetSupport": true,
     "DotnetDesktopRuntimeDownloadUrl": "https://download.visualstudio.microsoft.com/download/pr/907765b0-2bf8-494e-93aa-5ef9553c5d68/a9308dc010617e6716c0e6abd53b05ce/windowsdesktop-runtime-8.0.8-win-x64.exe",
     "DotnetDesktopRuntimePath": "C:\\Software\\Archives\\11.3\\windowsdesktop-runtime-8.0.8-win-x64.exe"
   }
}
```
