### ISSUE TITLE
Configuring Licensing on Existing Installation

### ISSUE THREAD

**Issue by chetawesomelaser1** [Esri/arcgis-powershell-dsc#499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

4.1.0

### Affected Resource(s)

ArcGIS Pro 3.1.3

### Configuration Files
```
{
    "AllNodes": [
        {
            "NodeName": "[local host name]",
            "Role": [
                "Pro"
            ]
        }
    ],
    "ConfigData": {
        "ProVersion": "3.1",
        "LicenseManagerVersion": "2022.1",
        "Pro": {
            "AuthorizationType": "CONCURRENT_USE",
            "LockAuthSettings": false,
            "BlockAddIns": "0",
            "SoftwareClass": "Viewer",
            "PortalList": "",
            "AllUsers": "",
            "EsriLicenseHost": "@[licensing server name]",
            "EnableEUEI": true,
            "CheckForUpdatesAtStartup": true,
            "Installer": {
                "Path": "[local file path]",
                "IsSelfExtracting": false,
                "InstallDir": "C:\\Program Files\\ArcGIS",
                "PatchesDir": "",
                "PatchInstallOrder": [
                    "Array of patch names to install in the needed order"
                  ]
                   }
               },
               "LicenseManager": {
                   "LicenseFilePath": "[License File Path (*.prvs) - License Manager ]",
                   "Installer": {
                       "Path": "[License Manager Installer Path]",
                       "IsSelfExtracting": false,
                       "InstallDir": "[License Manager Install Dir - Ex. C:\\ArcGIS\\LicenseManager]"
                   }
               }
           }
       }
```

### Expected Behavior

I am trying to configure licensing on existing installations of ArcGIS Pro from a Named User license to a Concurrent Use license. 

### Actual Behavior

The scripts run successfully, but GIS neither configures for the desired license, nor seems to install at all.

### Steps to Reproduce

Install-module 'PSDscResources' -verbose
Install-Module -name ArcGIS -Verbose
[DSCLocalconfigurationManager()]
{
    Node LocalHost
    {
        Settings
        {
            ConfigurationMode = 'ApplyOnly'
        }
    }
}

Invoke-ArcGISConfiguration -ConfigurationParametersFile "C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configurations-OnPrem\Pro-Concurrent.json" -Mode Install -credential [admin account] -debugswitch 

### Important Factoids

I've edited out the portions of the JSON file that seemed irrelevant, which maybe my underlying problem. 

Our licensing server is in production, so I've removed the portions that refer to it, since it was unclear what the script was actually doing to it.

**Comment by chetawesomelaser1** [comment]
Also forgive my ignorance, if I am missing something fundamental about this tool.

**Comment by cameronkroeker** [comment]
Hi @chetawesomelaser1 this is an existing installation of ArcGIS Pro? If so, I do not believe DSC has the ability to modify an existing installation. Some of these parameters are passed in during the initial installation of Pro:

https://pro.arcgis.com/en/pro-app/latest/get-started/arcgis-pro-installation-administration.htm

AUTHORIZATION_TYPE
Use SINGLE_USE to install ArcGIS Pro as a Single Use seat, use CONCURRENT_USE to install it as a Concurrent Use seat, and use NAMED_USER for a Named User license.

SOFTWARE_CLASS
The value can be Viewer, Editor, or Professional. The Viewer value corresponds to an ArcGIS Pro Basic license, the Editor value corresponds to a Standard license, and the Professional value corresponds to an Advanced license.

DSC is idempotent, meaning it will check the Windows registry to see if the ArcGIS Pro product code exists, if found then installation is skipped. if the product code is not found then it will proceed with a silent installation passing the parameters from the json file to the Pro MSI.

Thanks,
Cameron K.

**Comment by chetawesomelaser1** [comment]
Ah that's what I was afraid of. I was hoping I misunderstood something. Well thank you for clarifying.
