### ISSUE TITLE
datastore waits endless for serverconfigtocomplete

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#50]
if there is the following configuration

- machine 1
  - WebAdaptor Server
  - WebAdaptore Portal
- Machine 2
  - Server
- Machine 3
  - Portal
  - DataStore

DataStore waits endless for Server to Complete. Most probably Server is already finished with everything and therefore released by DSC, when DataStore starts to WaitForAll Server.

**Comment by shailesh91** [comment]
@spitzerr Is it while testing single machine?

**Comment by shailesh91** [comment]
@spitzerr I will give this scenario a try.
