### ISSUE TITLE
Ability to Federate ArcGIS Server with the Administration URL set to the Public Services URL

### ISSUE THREAD

**Issue by dimesv** [Esri/arcgis-powershell-dsc#504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.2.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Expected Behavior

There should a flag in the DSC Federation section to use the same URL in both the Services URL and Administration URL. This simplifies the deployment as the services URL is already being load balanced and we don't require an internal load balancer routing requests through port 6443. **Note that we can already use WAF to apply security policies to only allow certain IPs to access the endpoints.**

### Actual Behavior

The DSC module federates the hosting server as well as all other ArcGIS Server sites with the administration URL set to either a specific machine or an internal load balancer using port 6443 which complicates the deployment further unnecessarily from our view.

If we change the federation settings after the fact, the next time we run the DSC module it acknowledges that the deployment is different than what has been set in the config, and the DSC module attempts to change it, which of course it can't resulting in an error  and a message that the site is already federated.

Our current workaround is to configure our Azure Pipelines to continue on error. We have a YAML pipeline that runs after we run our IaC that streamlines an entire GIS Platform deployment.

**Comment by dimesv** [comment]
Hi @cameronkroeker ,

Thanks for coming back to me.
This is precisely the point. We currently have these two parameters in place and we have tried pretty everything else to see if the Administration URL would be set to the public services URL and it doesn't seem to work. It always federates using port 6443, including the hosting server.

Thanks,
Jose

**Comment by cameronkroeker** [comment]
> Hi @cameronkroeker ,
> 
> Thanks for coming back to me. This is precisely the point. We currently have these two parameters in place and we have tried pretty everything else to see if the Administration URL would be set to the public services URL and it doesn't seem to work. It always federates using port 6443, including the hosting server.
> 
> Thanks, Jose

I see. Is there an ArcGIS Web Adaptor? If so then try setting `ConfigData.WebAdaptor.AccessEnabled` to `true` in the json configuration file(s). However, if there isn't a web adaptor then try making the following modification to the module:

**Change:**

https://github.com/Esri/arcgis-powershell-dsc/blob/3d056fe815c68e9676789afe9d4ca71c05cefc8d/Modules/ArcGIS/ArcGIS.psm1#L2094

**To:**

```
if(-not($WebAdaptorCheck) -or ($ConfigurationParamsHashtable.ConfigData.WebAdaptor.AdminAccessEnabled -or ($ServerRole -ieq 'NotebookServer') -or ($ServerRole -ieq 'MissionServer'))){
```

**Comment by dimesv** [comment]
Hi @cameronkroeker ,

I have tested the module with the change above and it still does not work. See error below.

![image](https://github.com/Esri/arcgis-powershell-dsc/assets/5733148/64b24eaf-506e-434d-a375-521a83ca8a1c)

Hope you can help us find out where the issue is.

Thanks,
Jose

**Comment by cameronkroeker** [comment]
Hi @dimesv,

If ArcGIS Server is already federated and the services url and admin url that is being passed in do not match the existing settings then it will first need to be unfederated manually prior to re-running the module. Be cautious though if there is already content then unfederating can significant consequences

https://developers.arcgis.com/rest/enterprise-administration/portal/unfederate-server.htm

Thanks,
Cameron K.

**Comment by dimesv** [comment]
Hi @cameronkroeker ,

We have changed the existing settings manually to have the Services URL the same as the Administration URL. Then we ran the DSC with the fix above. If the change worked well, then it shouldn't have complained about anything because it would have matched it. So this means that somewhere in the logic it still compares the Administration URL with the port 6443.

I can't unfederate the environment as this would have major consequences.

Thanks,
Jose

**Comment by dimesv** [comment]
Hi @cameronkroeker ,

Just as an example, take a look at the BaseDeploymentSingleTierConfiguration.ps1 file.

![image](https://github.com/Esri/arcgis-powershell-dsc/assets/5733148/ff41f14a-68bd-4b32-b602-5117fecf28dd)

It has hard-coded the ServerSiteAdminUrlPort to port 6443 and ServerSiteAdminUrlContext to arcgis. This is then passed to the ArcGIS_Federation.psm1 module which sets these values. Also note that in line 133 below, instead of using ServiceUrlHostName if the port is 443 it uses ServerSiteAdminUrlHostName which is the FQDN.

![image](https://github.com/Esri/arcgis-powershell-dsc/assets/5733148/da4e6946-1453-451f-8994-a447b8af18e0)

This is done the same way in other files.

In my opinion, if admin access has been enabled, and i have not specified an internal load balancer for the admin purposes, the Administration URL should be set to the Services URL.

Thanks,
Jose

**Comment by dimesv** [comment]
Hi @cameronkroeker ,

The issue was on my side, where the DSC was being cached. 
Found this useful: "Remove-DscConfigurationDocument -Stage Current, Pending, Previous -Verbose -Force" 

Can you your proposed changes to the next version? I would also add the following which is located below the changes you suggested:

From:
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/5733148/0cd59926-9446-4513-acca-6d7b4ed12161)

To: 
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/5733148/fddc0bee-20f3-4307-aa42-0001f02992aa)

This makes sure that the portal home URL is displayed in the output.

From:
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/5733148/22b3f23b-776d-46f1-99c8-85898a55ecf0)

To:
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/5733148/356a97dc-9568-49cf-b5ff-3f50af71c9fb)

This makes sure that the URLs displayed in the output show the correct admin URLs.

Thanks again for your help.
Jose
Esri NZ

**Comment by cameronkroeker** [comment]
Thanks @dimesv confirming the suggested modification worked. We can definitely include this and your suggestion of the URL output as well into the next release of the module. There isn't an exact time table yet but we do plan to release a minor update (v4.2.1) that will include it.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Hi @dimesv,

v4.2.1 has been officially released and includes the fixes for this issue.

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.2.1

Thanks,
Cameron K.

**Comment by shaylavi** [comment]
Hi @cameronkroeker , I'm using version 4.3.0 and experiencing the same issue.
I've deployed a base-deployment of 4 machines:
Portal
Server
DataStore
WebAdaptors

Federation for this base setting was successful with reference to the WebAdaptors machine, however, I have 2 other servers I have configured (image and general purpose) that were federated through port 6443 rather than the webadaptors machines
