### ISSUE TITLE
Trouble connecting dual web adaptors

### ISSUE THREAD

**Issue by jhevenor** [Esri/arcgis-powershell-dsc#506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

4.1.0

### Affected Resource(s)

ArcGIS_Server, Web Adaptor

### Configuration Files

**ags.json**
```
{
    "AllNodes": [

        {
            "NodeName": "10.155.22.234",
            "Role": [
                "Server",
                "ServerWebAdaptor"
            ]
        },
        {
            "NodeName": "10.155.22.250",
            "Role": [
                "Server",
                "ServerWebAdaptor"
            ]
        }
    ],
    "ConfigData": {
        "Version": "11.1",
        "ServerRole": "GeneralPurposeServer",
        "ServerContext": "maps",
        "DownloadPatches": true,
        "ForceLicenseUpdate": false,
        "Credentials": {
            "ServiceAccount": {
                "Password": "***",
                "UserName": "svcaccount",
                "IsDomainAccount": false
            }
        },
        "Server": {
            "PrimarySiteAdmin": {
                "UserName": "theadmin",
                "Email": "admin@domain.com",
                "Password": "***"
            },
            "ExternalLoadBalancer": "sub.domain.com",
            "LicenseFilePath": "C:\\geo-cfn-init\\resources\\licenses\\generated.prvc",
            "Installer": {
                "Path": "C:\\geo-ami-resources\\ArcGIS_Server_Windows_111_185208.exe",
                "InstallDir": "C:\\Program Files\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27",
                "PatchesDir": "C:\\temp\\patches",
                "PatchInstallOrder": [
                    ""
                ],
                "EnableArcMapRuntime": true,
                "EnableDotnetSupport":true
            },
            "ServerDirectoriesRootLocation": "\\\\10.155.22.229\\gis-server\\arcgisserver\\directories",
            "ConfigStoreLocation": "\\\\10.155.22.229\\gis-server\\arcgisserver\\config-store"
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "C:\\geo-ami-resources\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_111_185222.exe"
            }
        }
    }
}
```

### Expected Behavior

Two AWS VMs, each with ArcGIS Server and Web Adaptor installed. Should configure both web adaptors with both servers.  (Although I'd be fine with each server having its own web adaptor)

### Actual Behavior

```log
11/29/2023 2:27:40 PM: [EC2AMAZ-XYZ]:                            [[ArcGIS_WebAdaptor]ConfigureServerWebAdaptor10.155.22.234] Output of execution:- ERROR: Unable to connect to Web Adaptor URL : https://10.155.22.234/maps/webadaptor.
11/29/2023 2:27:40 PM: [EC2AMAZ-XYZ]: LCM:  [ End    Set      ]  [[ArcGIS_WebAdaptor]ConfigureServerWebAdaptor10.155.22.234]  in 102.6170 seconds.
11/29/2023 2:27:40 PM: [EC2AMAZ-XYZ]: LCM:  [ End    Set      ]
11/29/2023 2:27:40 PM: Operation 'Invoke CimMethod' complete.
Trace-DSCJob : 11/29/2023 2:27:40 PM: PowerShell DSC resource ArcGIS_WebAdaptor  failed to execute Set-TargetResource 

functionality with error message: [ERROR]:- ERROR: Unable to connect to Web Adaptor URL : 

https://10.155.22.234/maps/webadaptor. 

At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.1.0\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...

+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
 

Trace-DSCJob : 11/29/2023 2:27:40 PM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.1.0\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
```

### Steps to Reproduce

```powershell
# Running as the same user that runs ags (see tpl)
$pw = ConvertTo-SecureString "***" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ($usr, $pw)

# Call DSC
Invoke-ArcGISConfiguration `
  -ConfigurationParametersFile ags.json `
  -Mode InstallLicenseConfigure `
  -Credential $credential `
  -DebugSwitch
```

### Important Factoids

The end result looks to be fully functional. When I log into server manager I see both machines participating in the site, and both machines listed as web adaptors. The problem is that an ERROR log is being written, which it never did before, and my automation then passes that along.  Can work around I guess, but would love to know what's happening. 

Also, the error message says I can't reach `https://10.155.22.234/maps/webadaptor`   but when I remote into the machine and try the URL, I can reach it. I get a cert warning from chrome, but if I click through I can see it fine. Makes me think there may just be a timing issue?  I can't say for sure. 

### References
NA

**Comment by cameronkroeker** [comment]
@jhevenor Maybe to see if it is a timing related issue, can you see if it connects successfully on a second run?

Thanks,
Cameron K.

**Comment by jhevenor** [comment]
Hi @cameronkroeker, a manual run goes smoothly

```
Output of execution:-
Configuring the ArcGIS Enterprise Web Adaptor with ArcGIS Server.

Configuring Web adaptor...
```
Instead of the `Output of execution:- ERROR: Unable to connect to Web Adaptor URL` I received on the first run.  Not 100% apples to apples, as this ran in a powershell admin window, verses being launched via cfn-init which I think runs as the SYSTEM user (windows server 2019).

**Comment by cameronkroeker** [comment]
@jhevenor is the 10.155.1.241 address an external ip or the private ip? This looks like its an AWS environment, so I suspect the 10.155.1.241 is the external EIP which may not work to configure the web adaptor. I believe you will need to use the private ip.

Thanks,
Cameron K.

**Comment by jhevenor** [comment]
Hi @cameronkroeker ,  the 10.155 is an internal IP address. No public IPs are available on the VMs (accessed through app gateway).

**Comment by shaylavi-esriau** [comment]
Hi, was there a solution for this? I'm experiencing the same issue! internal IP as mentioned above

**Comment by shaylavi** [comment]
Hi, was there a solution for this? I'm experiencing the same issue! internal IP as mentioned above
