### ISSUE TITLE
11.1 to 11.2 Upgrade: ArcGIS_License failed to execute Set-TargetResource SoftwareAuthorization.exe not found

### ISSUE THREAD

**Issue by PartyPelican** [Esri/arcgis-powershell-dsc#507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

ArcGIS Module v4.2.0

### Affected Resource(s)

ArcGIS_License

### Configuration Files

```
{
  "AllNodes": [
    {
      "NodeName": "gis-svr",
      "Role": ["Server"],
      "SslCertificates": [
        {
          "Path": "C:\\Certs\\giscert.pfx",
          "Password": "PASSWORD",
          "CNameFQDN": "CNAMEFQDN",
          "Target": ["Server"]
        }
      ]
    },
    {
      "NodeName": "gis-ds",
      "DataStoreTypes": ["Relational"],
      "Role": ["DataStore"]
    },
    {
      "NodeName": "gis-wa",
      "Role": ["WebAdaptor"],
      "WebAdaptorConfig": [
	{
		"Role": "Portal"
	},
	{
		"Role": "Server"
	}
	],
      "SslCertificates": [
        {
          "Path": "C:\\Certs\\giscert.pfx",
          "Password": "PASSWORD",
          "CNameFQDN": "CNAMEFQDN",
          "Target": ["WebAdaptor"]
        }
      ]
    },
    {
      "NodeName": "gis-ps",
      "Role": ["Portal"]
    }
  ],
  "ConfigData": {
    "Version": "11.2",
    "OldVersion": "11.1",
    "ServerContext": "server",
    "PortalContext": "portal",
    "ServerRole": "GeneralPurposeServer",
    "Credentials": {
      "ServiceAccount": {
        "Password": "PASSWORD",
        "UserName": "USERNAME",
        "IsDomainAccount": true,
        "IsMSAAccount": false
      }
    },
    "Server": {
      "LicenseFilePath": "C:\\licensefiles\\ArcGISGISServerStandard_ArcGISServer_1403162.prvc",
      "Installer": {
        "Path": "C:\\licensefiles\\ArcGIS_Server_Windows_112_188239.exe",
        "InstallDir": "E:\\ArcGIS\\Server",
        "InstallDirPython": "E:\\Python27"
      },
      "ServerDirectoriesRootLocation": "E:\\arcgisserver\\directories",
      "ConfigStoreLocation": "E:\\arcgisserver\\config-store",
      "PrimarySiteAdmin": {
        "UserName": "USERNAME",
        "Password": "PASSWORD"
      }
    },
    "Portal": {
      "LicenseFilePath": "C:\\licensefiles\\ArcGIS_Enterprise_Portal_112_440808_20231207.json",
      "PortalLicenseUserTypeId": "creatorUT",
      "Installer": {
        "Path": "C:\\licensefiles\\Portal_for_ArcGIS_Windows_112_188250.exe",
        "InstallDir": "E:\\ArcGIS\\Portal",
        "ContentDir": "E:\\arcgisportal"
      },
      "ContentDirectoryLocation": "E:\\arcgisportal\\content",
      "PortalAdministrator": {
        "UserName": "USERNAME",
        "Email": "EMAIL",
        "Password": "PASSWORD",
        "SecurityQuestionIndex": 13,
        "SecurityAnswer": "ANSWER"
      }
    },
    "DataStore": {
      "ContentDirectoryLocation": "E:\\arcgisdatastore",
      "EnableFailoverOnPrimaryStop": false,
      "Installer": {
        "Path": "C:\\licensefiles\\ArcGIS_DataStore_Windows_112_188252.exe",
        "InstallDir": "E:\\ArcGIS\\DataStore"
      }
    },
    "WebAdaptor": {
      "AdminAccessEnabled": true,
      "Installer": {
        "Path": "C:\\licensefiles\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_112_188253.exe"
      }
    }
  }
}
```

### Expected Behavior

Upgrade ArcGIS Server 11.1 to 11.2 and license. 

### Actual Behavior

12/11/2023 1:41:33 PM: PowerShell DSC resource ArcGIS_License  failed to execute Set-TargetResource functionality with error message: E:\ArcGIS\Server\ E:\ArcGIS\Server\tools\SoftwareAuthorization\SoftwareAuthorization.exe not found 
12/11/2023 1:41:33 PM: The SendConfigurationApply function did not succeed.

Server Upgrade Failed

### Steps to Reproduce

1. Deploy a ArcGIS Enterprise 11.1 on a multi-machine configuration.
2. Upgrade from ArcGIS Enterprise 11.1 to 11.2 using powershell dsc version 4.2.0

Has anyone experienced this issue before? I appreciate any help.
![2023-12-11_14-36-24](https://github.com/Esri/arcgis-powershell-dsc/assets/153563161/4a85b640-5078-4841-a6e1-d371bc36da24)

**Comment by PartyPelican** [comment]
hmmm, interesting...

When the powershell dsc failed, I checked the path for the SoftwareAuthorization.exe on the server machine and it was present. However, after reverting back to my organizations working snapshot of the machine, that executable doesn't seem to be present. the only tools are in the photo I have attached. 
![2023-12-11_15-09-58](https://github.com/Esri/arcgis-powershell-dsc/assets/153563161/4b010728-74fe-4c38-8eb6-986b9a1dd0d6)

I've also attached the results of the Get-ProductDetails cmdlet.
![2023-12-11_15-14-04](https://github.com/Esri/arcgis-powershell-dsc/assets/153563161/ad1369ac-524c-42af-847d-b77e3ba5529c)

**Comment by cameronkroeker** [comment]
Hi @PartyPelican,

The SoftwareAuthorization.exe changed locations at 11.2, so you won't see it in the tools directory at 11.1. For example:

11.1  = `C:\Program Files\Common Files\ArcGIS\bin\SoftwareAuthorization.exe`
11.2 = `C:\Program Files\ArcGIS\Server\tools\SoftwareAuthorization\SoftwareAuthorization.exe`

Can you run this exact command instead?

```
(Get-ArcGISProductDetails -ProductName Server).InstallLocation
```

I suspect the output of this is showing 2 Install locations due to the Custom Data Feeds. I am wondering if this is causing the issue.

Thanks,
Cameron K.

**Comment by PartyPelican** [comment]
Thank you for the quick replies @cameronkroeker 

I've attached the result.
![2023-12-11_15-28-23](https://github.com/Esri/arcgis-powershell-dsc/assets/153563161/43609f63-1dbe-41ce-ac0a-b2b2d41ac9f7)

**Comment by cameronkroeker** [comment]
> Thank you for the quick replies @cameronkroeker
> 
> I've attached the result. ![2023-12-11_15-28-23](https://private-user-images.githubusercontent.com/153563161/289699654-43609f63-1dbe-41ce-ac0a-b2b2d41ac9f7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMzc5MzEsIm5iZiI6MTcwMjMzNzYzMSwicGF0aCI6Ii8xNTM1NjMxNjEvMjg5Njk5NjU0LTQzNjA5ZjYzLTFkYmUtNDFjZS1hYzBhLWIyYjJkNDFhYzlmNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQyMzMzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGUwNGVjZjYyODY0ZjRlZDI5NGQwMTdiY2IyMzdhNjQ0MmNhYzQ4MDg4NGIxMWNlMDU3NWZjMzJkZmZlNTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gg_r7-4MPFsSl-U8p_aMFM7-3xTb_yzg-F7XLfgMZUE)

@PartyPelican Thanks for sharing the result of the test and it confirms my original theory. This should resolve the issue:

**Change:**
https://github.com/Esri/arcgis-powershell-dsc/blob/3d056fe815c68e9676789afe9d4ca71c05cefc8d/Modules/ArcGIS/ArcGIS.psm1#L3314

**To:**
```
-or ($ProductName -ieq "ArcGIS Server" -and -not($DisplayName -imatch "Deep Learning Libraries for ArcGIS Server") -and -not($DisplayName -imatch "Custom Data Feeds")) `
```

> Note: This change will need to be made on each machine the module resides on, and the Invoke-ArcGISConfiguration command will need to be ran in a fresh powershell window.

**Comment by PartyPelican** [comment]
Hello @cameronkroeker,

thank you for the workaround. After replacing that line of code, the upgrade completed successfully. However, the custom data feeds the server was using no longer work. They were working prior to the upgrade but its unclear to me as to why they stopped working. I am going to poke around some more to see if I can find the cause. 
![2023-12-12_18-37-40](https://github.com/Esri/arcgis-powershell-dsc/assets/153563161/17a685fd-d5a1-41da-9f84-82ff4fff89be)

**Comment by PartyPelican** [comment]
Looks like the custom data fee
![2023-12-12_18-42-04](https://github.com/Esri/arcgis-powershell-dsc/assets/153563161/9c1c471a-b751-4ffc-abf1-a2d6ac471e12)
d version was not updated, is that something the powershell dsc could handle? or would I need to reinstall the custom data feed sdk post upgrade every time?

**Comment by cameronkroeker** [comment]
> Looks like the custom data feed version was not updated, is that something the powershell dsc could handle? or would I need to reinstall the custom data feed sdk post upgrade every time? ![2023-12-12_18-42-04](https://private-user-images.githubusercontent.com/153563161/290058686-9c1c471a-b751-4ffc-abf1-a2d6ac471e12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODY2MjIsIm5iZiI6MTcwMjQ4NjMyMiwicGF0aCI6Ii8xNTM1NjMxNjEvMjkwMDU4Njg2LTljMWM0NzFhLWI3NTEtNGZmYy1hYmYxLWEyZDZhYzQ3MWUxMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNjUyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmY1YjgxYzUzMjdhZGViMTZlN2M0MTUzMjNkM2NlMjRlZWQ5ZmEyODYwOWE2NTlkNWIyYWUyNmYzMDhiMGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.59E6PvYaLEeEzXrWyxqcQ51Nen4oMZ6yL-ovqYHm2Gk)

Hi @PartyPelican,

The ArcGIS Module doesn't support installing or upgrading ArcGIS Server Custom Data Feeds. I assume it must've been manually installed/configured at 11.1, therefore it will need to manually be upgraded. 

Thanks,
Cameron K.

**Comment by PartyPelican** [comment]
@cameronkroeker 

I uninstalled the 11.1 version of custom data feeds and then installed version 11.2; the CDF layers were loading correctly after that. Thank you for all the help.

**Comment by cameronkroeker** [comment]
Hi @PartyPelican,

This has been addressed in v4.2.1:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.2.1

Thanks,
Cameron K.

**Comment by H47110815G** [comment]
We move from 11.1 to 11.3. 
The licensing error for the server occurs with the scripts 4.2.1 in line 3533.


It's the AGE server 11.3 is installed in the seleben path like 11.1. 
There are 2 entries:
![image](https://github.com/user-attachments/assets/90665ce2-93b5-4cbe-8bc5-cbe410562f59)

![image](https://github.com/user-attachments/assets/4039892f-fa2c-4efe-8b23-2eaef9877a0f)

The path to SoftwareAuthorization.exe exists. I would have hoped that if I did the licensing manually, the DSC would take the license. But it breaks off again at the same place.

**Comment by H47110815G** [comment]
`-and -not($DisplayName -imatch "Sprachpaket Deutsch")
`
add this in line 3533 and the licensing works

**Comment by paulidermaulwurf** [comment]
The workaround provided by @H47110815G is also viable in version **4.4.0**.

- Upgrade from AGE 10.9.1 to AGE 11.3.
- Line **3615** was edited in ArcGIS.psm1.

I searched for `$ProductName -ieq 'ArcGIS Server'` to find the line, and then I added `-and -not($DisplayName -imatch 'Sprachpaket Deutsch')` as described above.

Cheers!
