### ISSUE TITLE
"Register an Enterprise Geodatabase with ArcGIS Server site" Links to devtopia.esri.com

### ISSUE THREAD

**Issue by ZianAtFirstWatch** [Esri/arcgis-powershell-dsc#511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* Latest version on GitHub

### Affected Resource(s)

* https://github.com/Esri/arcgis-powershell-dsc/wiki/Register-an-Enterprise-Geodatabase-with-ArcGIS-Server-site

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

The variables reference page for the latest version of the software should appear.

### Actual Behavior

I was sent to devtopia.esri.com (https://devtopia.esri.com/WebGIS/arcgis-automation-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files).

### Steps to Reproduce

1. Go to https://github.com/Esri/arcgis-powershell-dsc/wiki/Register-an-Enterprise-Geodatabase-with-ArcGIS-Server-site.
2. Click the "Variables reference" link in the "Edit the configuration file" section.

**Comment by cameronkroeker** [comment]
Great find @ZianAtFirstWatch. I've updated the wiki hyper link to the latest variable reference page. Thanks!
