### ISSUE TITLE
4.2: GISServer-GeneralPurpose-MultipleWA-MultiContext.json Uses AllNodes.WebAdaptorConfig.ServerContext Instead of AllNodes.WebAdaptorConfig.Context

### ISSUE THREAD

**Issue by ZianAtFirstWatch** [Esri/arcgis-powershell-dsc#516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.2

### Affected Resource(s)

* https://github.com/Esri/arcgis-powershell-dsc/blob/main/SampleConfigs/v4/v4.2.0/Gis%20Servers/GISServer-GeneralPurpose-MultipleWA-MultiContext.json

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

https://github.com/Esri/arcgis-powershell-dsc/wiki/v4.2.0-Variables-reference-page-for-JSON-configuration-files says WebAdaptorConfig should have a property named "Context".

### Actual Behavior

https://github.com/Esri/arcgis-powershell-dsc/blob/main/SampleConfigs/v4/v4.2.0/Gis%20Servers/GISServer-GeneralPurpose-MultipleWA-MultiContext.json does not have a property named "Context". Instead, it has a property named "ServerContext", which is not part of WebAdaptorConfig,.

### Steps to Reproduce

1. Look at https://github.com/Esri/arcgis-powershell-dsc/blob/main/SampleConfigs/v4/v4.2.0/Gis%20Servers/GISServer-GeneralPurpose-MultipleWA-MultiContext.json.

**Comment by ZianAtFirstWatch** [comment]
The documentation still says a Context property should exist.

**Comment by cameronkroeker** [comment]
> The documentation still says a Context property should exist.

Great catch! The samples for 4.2.0, 4.2.1, 4.3.0, and 4.4.0 have been corrected.

https://github.com/Esri/arcgis-powershell-dsc/blob/539a5adada7de60e3b5ce801a74020c0e3112d61/SampleConfigs/v4/v4.2.0/Gis%20Servers/GISServer-GeneralPurpose-MultipleWA-MultiContext.json#L9-L29
