### ISSUE TITLE
Enterprise 11.2 - Insights 2023.3

### ISSUE THREAD

**Issue by tallmanbrew** [Esri/arcgis-powershell-dsc#521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

Add support to deploy ArcGIS Enterprise 11.2 with Insights 2023.3.
Currently the only supported version by the deployment script is 2023.1, which is not supported by Enterprise 11.2

From the dsc wiki: https://github.com/Esri/arcgis-powershell-dsc/wiki/v4.2.0-Variables-reference-page-for-JSON-configuration-files
```
InsightsVersion - The software version of the different components that will be installed or upgraded to. All components of your deployment should be at the same software version.
Accepted values: 3.4, 3.4.1, 2020.1, 2020.2, 2020.3, 2021.1, 2021.1.1, 2021.2, 2021.2.1, 2021.3, 2021.3.1, 2022.1, 2022.1.1, 2022.2, 2022.3, 2023.1.
```

Compatibility chart https://doc.arcgis.com/en/insights/latest/administer/enterprise-compatibility.htm

**Comment by cameronkroeker** [comment]
Hi @tallmanbrew,

ArcGIS Insights 2023.2 and 2023.3 are now supported in module v4.2.1.

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.2.1

Thanks,
Cameron K.
