### ISSUE TITLE
Installing on AWS image with pre-installed server

### ISSUE THREAD

**Issue by jhevenor** [Esri/arcgis-powershell-dsc#525]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.20

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

Simple one machine test case. Using remote file share for config folders as we'll expand back to 2 machines once this is sorted. 

```json
{
    "AllNodes": [
        {
            "NodeName": "1.2.3.32",
            "Role": [
                "Server"
            ]
        }
    ],
    "ConfigData": {
        "Version": "11.1",
        "ServerRole": "GeneralPurposeServer",
        "ServerContext": "maps",
        "DownloadPatches": false
        "ForceLicenseUpdate": false
        "Credentials": {
            "ServiceAccount": {
                "Password": "xxxx",
                "UserName": "svcuser",
                "IsDomainAccount": false,
                "IsMSAAccount": false
            }
        },
        "Server": {
            "LicenseFilePath": "C:\\geo-cfn-init\\resources\\licenses\\lic.prvc",
            "Installer": {
                "IsSelfExtracting": false
                "Path": "c:\\path\\to\\install",
                "InstallDir": "C:\\Software\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27",
                "PatchesDir": "C:\\Software\\PatchDownloads",
                "PatchInstallOrder": [
                ]
            },
            "ServerDirectoriesRootLocation": "\\\\1.2.3.45\\share\\arcgisserver\\directories",
            "ConfigStoreLocation": "\\\\1.2.3.45\\share\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": "someuser",
                "Password": "xxxxx"
            }
        }
    }
}
```

### Expected Behavior

ArcGIS Server should install.

### Actual Behavior

```log
2/12/2024 1:51:10 PM: [EC2AMAZ-JD4S6MV]:                            [[ArcGIS_Server]Server1.2.3.32] Waiting for Server 'https://1.2.3.32:6443/arcgis/admin' to initialize
2/12/2024 1:54:10 PM: [EC2AMAZ-JD4S6MV]:                            [[ArcGIS_Server]Server1.2.3.32] [WARNING] Error while creating site on attempt 3 Error:- Unable to connect to the remote server
2/12/2024 1:54:10 PM: [EC2AMAZ-JD4S6MV]:                            [[ArcGIS_Server]Server1.2.3.32] [WARNING] Unable to create Site. Error:- Unable to connect to the remote server
2/12/2024 1:54:10 PM: [EC2AMAZ-JD4S6MV]:                            [[ArcGIS_Server]Server1.2.3.32] Unable to connect to the remote server
2/12/2024 1:54:10 PM: [EC2AMAZ-JD4S6MV]:                            [[ArcGIS_Server]Server1.2.3.32] Retrying site creation after 45 seconds
2/12/2024 1:54:55 PM: [EC2AMAZ-JD4S6MV]: LCM:  [ End    Set      ]  [[ArcGIS_Server]Server1.2.3.32]  in 1537.6380 seconds.
```

### Steps to Reproduce

1. Create an AWS machine image (AMI) with ArcGIS Server 11.1 pre-installed (not licensed or configured)
  a. I'm using Windows server 2019   
3. Deploy a new AWS EC2 instance based on this image
4. Invoke a similar DSC config as above

#### Old machine name still in use on new machine

What I've noticed is that there are references to the machine that the image was created from, which are no longer valid in the subsequent deployment.  I see the best evidence of this in the `C:\Software\ArcGIS\Server\usr\logs` folder, which contains logs from both the initial manual installation while setting up the AMI, and the subsequent install on a new VM.   Note the different machine names in the following screenshot:

![image](https://github.com/Esri/arcgis-powershell-dsc/assets/3680673/1b25c331-adb2-42ad-8a5b-ae393bb5110d)

#### Uninstall/Resinstall 

When I uninstall/reinstall on the new machine things run cleanly. 

#### 11.x vs 10.X

I've been using this approach for years on Azure and AWS since 10.6 and been having a fight getting my 11.x deployments to work. I'm not sure what's changed, but I'm hoping this is the cause and eventual solution.   

#### Pre-installing server

So, I recognize a workaround is to not pre-install ArcGIS Server.  I'm pretty sure that'll be how I need to move forward. I've always had the impression that I was saving a lot deployment time pre-installing server in the VM image.  Scanning the output of the successful reinstall I'm saving about 10min.  Maybe most of the time spent is in creating the site and joining all the machines together, but I'll take 10min if I can get it.

**Comment by cameronkroeker** [comment]
Hi @jhevenor,

Are you able to send the dsc run logs? Let's check the `C:\Software\ArcGIS\Server\framework\etc\hostname.properties` file to see if it was updated with the correct ip. Also check if the arcgis server service is started in services.msc and are you able to browse to https://1.2.3.32:6443/arcgis/admin in the web browser?

Thanks,
Cameron K.

**Comment by jhevenor** [comment]
Thanks @cameronkroeker.  
DSC logs attached. I had to rerun and I've tried to propagate the unnecessary obfuscation above, but note 10.155.1.219=1.2.3.32 if you come across it. 

`hostname.properties` contains `hostname=1.2.3.32`,  so correct?

The link to `/arcgis/admin` does not load. 

[issue-535-dsc-logs.zip](https://github.com/Esri/arcgis-powershell-dsc/files/14266758/issue-535-dsc-logs.zip)

**Comment by cameronkroeker** [comment]
Thanks @jhevenor. I am not seeing any issues within the dsc logs. Perhaps there are some clues within the logs of the following 2 directories?

- `C:\Software\ArcGIS\\Server\framework\runtime\tomcat\logs`
- `C:\Software\ArcGIS\Server\framework\etc\service\logs`

**Comment by jhevenor** [comment]
@cameronkroeker  I think I figured out what's happening.   My latest images I created a local windows user with the same username that I eventually use in my later automations.  But, the password changes when the new VMs are rolled out. I think some of the checks for the current state see that ArcGIS Server is installed and Windows Services exist, but the password change breaks something along the way.    

I've made new image using a different username and my truncated automations run smoothly. 

So, I'm not sure what you can do with that information, but at least you're aware.  I'm happy to collaborate on rooting out and remediating this specific quirk, but for now I'll close this ticket and move on.   Thanks for your time.

**Comment by cameronkroeker** [comment]
> @cameronkroeker I think I figured out what's happening. My latest images I created a local windows user with the same username that I eventually use in my later automations. But, the password changes when the new VMs are rolled out. I think some of the checks for the current state see that ArcGIS Server is installed and Windows Services exist, but the password change breaks something along the way.
> 
> I've made new image using a different username and my truncated automations run smoothly.
> 
> So, I'm not sure what you can do with that information, but at least you're aware. I'm happy to collaborate on rooting out and remediating this specific quirk, but for now I'll close this ticket and move on. Thanks for your time.

Glad you were able to find the culprit and get it resolved! The module does do a username comparison but not password comparison for the service account. Since the username's matched it skipped updating the service. However, to workaround this though you can set `ConfigData.Credentials.ServiceAccount.ForceUpdate` attribute in your json config to true.

```json
"Credentials": {
   "ServiceAccount": {
   "Password": "xxxx",
   "UserName": "svcuser",
   "IsDomainAccount": false,
   "IsMSAAccount": false,
   "ForceUpdate": true
}
```

Thanks,
Cameron K.
