### ISSUE TITLE
WebAdaptor fails to install with error SendConfigurationApply function did not succeed

### ISSUE THREAD

**Issue by decampo04** [Esri/arcgis-powershell-dsc#527]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.2

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_WebAdaptor

### Configuration Files

Single server with WebAdaptor (file GIS-Server-Portal.json).

```json
{
    "AllNodes": [
        {
            "NodeName": "hostname",
            "Role": [
                "Server",
                "WebAdaptor"
            ],
            "WebAdaptorConfig":[
                {
                    "Role": "Server",
                    "ServerContext": "server"
                }
            ]
        }
    ],
    "ConfigData": {
        "Version": "11.2",
        "ServerRole": "GeneralPurposeServer",
        "ServerContext": "server",
        "Credentials": {
            "ServiceAccount": {
                "Password": "Password123!",
                "UserName": "domain\\user",
                "IsDomainAccount": true,
                "IsMSAAccount": false
            }
        },
        "Server": {
            "LicenseFilePath": "C:\\ArcGISConfigFiles\\ArcGISGISServerAdvanced_ArcGISServer_11111111.prvc",
            "Installer": {
                "Path": "C:\\ArcGISConfigFiles\\ArcGIS_Server_Windows_112_188239.exe",
                "InstallDir": "C:\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python3",
                "EnableArcMapRuntime": true,
                "EnableDotnetSupport": true
            },
            "ServerDirectoriesRootLocation": "C:\\arcgisserver\\directories",
            "ConfigStoreLocation": "C:\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": "SiteAdmin",
                "Password": "Password456!"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "C:\\ArcGISConfigFiles\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_112_188253.exe",
                "DotnetHostingBundlePath": "C:\\ArcGISConfigFiles\\dotnet-hosting-6.0.26-win.exe",
                "WebDeployPath": "C:\\ArcGISConfigFiles\\WebDeploy_amd64_en-US.msi",
                "IsSelfExtracting": true
            }
        }
    }
}
```

### Expected Behavior

Server should install with site configuration, licence and WebAdaptor.

### Actual Behavior

Fails to install the WebAdaptor and no site is configured on the Server. The following error is output:

```powershell
14/02/2024 07:07:12: [hostname]:                            [[ArcGIS_Install]WebAdaptorIIS-Server-serverInstall] Self Extracting Installer
14/02/2024 07:07:12: [hostname]:                            [[ArcGIS_Install]WebAdaptorIIS-Server-serverInstall] Extracting C:\ArcGISConfigFiles\ArcGIS_Web_Adaptor_for_Microsoft_IIS_112_188253.exe to C:\Windows\TEMP\3F2DF3A0-0EB7-4DED-BA7F-A33B7B106252
14/02/2024 07:07:17: [hostname]:                            [[ArcGIS_Install]WebAdaptorIIS-Server-serverInstall] Done Extracting. Waiting 15 seconds to allow the extractor to close files
14/02/2024 07:07:32: [hostname]:                            [[ArcGIS_Install]WebAdaptorIIS-Server-serverInstall] Executing C:\Windows\TEMP\3F2DF3A0-0EB7-4DED-BA7F-A33B7B106252\ArcGIS 11.2\WebAdaptorIIS\Setup.exe
14/02/2024 07:07:32: [hostname]:                            [[ArcGIS_Install]WebAdaptorIIS-Server-serverInstall] Install process finished successfully.
14/02/2024 07:07:32: [hostname]:                            [[ArcGIS_Install]WebAdaptorIIS-Server-serverInstall] Validating the WebAdaptorIIS-Server-server Installation
14/02/2024 07:07:33: [hostname]:                            [[ArcGIS_Install]WebAdaptorIIS-Server-serverInstall] Checking if any of the installed Web Adaptor are installed with context server
14/02/2024 07:07:33: [hostname]: LCM:  [ End    Set      ]  [[ArcGIS_Install]WebAdaptorIIS-Server-serverInstall]  in 42.1720 seconds.
14/02/2024 07:07:33: [hostname]: LCM:  [ End    Set      ]
14/02/2024 07:07:33: Operation 'Invoke CimMethod' complete.

Trace-DSCJob : 14/02/2024 07:07:33: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install WebAdaptorIIS-Server-server
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 14/02/2024 07:07:33: The SendConfigurationApply function did not succeed.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Logs Directory: C:\Windows\system32\Logs
Finished DSC Job:- ArcGISInstall. Time Taken - 00:10:23.5376075
ArcGISInstall - Failed
```

### Steps to Reproduce

1. Create EC2 instance in VPC (no internet access) with SG rules that allow all inbound and outbound traffic within the VPC. 
2. Copy ArcGISConfiguration module to `C:\Windows\system32\WindowsPowerShell\v1.0\Modules` on host.
3. Add all required installation files to the local drive.
4. Issue command in PowerShell `Invoke-ArcGISConfiguration -ConfigurationParametersFile "C:\ArcGISConfigFiles\GIS-Server-Portal.json" -Mode InstallLicenseConfigure -DebugSwitch`

### Important Factoids

Latest .NET Core Runtime is installed 6.0.26 (no older versions installed) along with Microsoft WebDeploy. Same issue appears when installing the portal instead of the server (with appropriate JSON file).

**Comment by cameronkroeker** [comment]
Hi @decampo04,

The WebAdaptor setup.exe is exiting with an error silently. There are a few options to capture the error which might give some insight into what could be the cause for the failure.

- Pass in `-EnableMSILogging` flag with the `Invoke-ArcGISConfiguration` command. This will create an msi log file which may contain the error or reason for the web adaptor setup.exe failing.
- Check Windows Event Viewer application logs around the time of failure.
- Manually run the Web Adaptor setup.exe, the error may show when running it through the GUI method.

Thanks,
Cameron K.

**Comment by decampo04** [comment]
Hi @cameronkroeker, thanks for your suggestions.

I tried the above but still doesn't work, and the logs, or Event Viewer, are giving us anything more useful than the error:

```powershell
Trace-DSCJob : 21/02/2024 15:33:37: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install WebAdaptorIIS-Server-server
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 21/02/2024 15:33:37: The SendConfigurationApply function did not succeed.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
```

However, Esri support did respond on this and commented that they had since this before, and recommended the simply installing the WebAdaptor using PowerShell:

```powershell
# Setup
setup.exe /qb VDIRNAME=server WEBSITE_ID=4059640 PORT=443 CONFIGUREIIS=TRUE

# Configuration
% cd c:\Program Files\Common Files\ArcGIS\WebAdaptor\IIS\<current version>\Tools.

% ConfigureWebAdaptor.exe /m server /w https://webadaptorhost.domain.com/webadaptorname/webadaptor /g server.domain.com /u siteadmin /p secret /a false
```

Whilst the above does work, the PowerShell DSC is still not configuring the server site. Also, just to confirm, we use CIS hardening on our servers and they do not explicitly have internet access (though can be configured to through a proxy server with strict whitelist).

**Comment by jhevenor** [comment]
@decampo04, I was in a very similar looking situation last week (CIS hardened Win2019, dsc v4.2.0, although AGS 11.1). I think I had a few things going on, one of which was installing the wrong .net hosting version. I see you have that v6, so good. I do see issue #516 notes that the context settings seem to overlap, you might consider setting the `AllNodes[].WebAdaptorConfig[].ServerContext` as well.

**Comment by decampo04** [comment]
@jhevenor thanks for your suggestion, but unfortunately setting the `AllNodes[].WebAdaptorConfig[].ServerContext` made no difference and I still received the same error message.

Using the command `Get-DscLocalConfigurationManager` I could see the `LCMState` was in a `PendingConfiguration` state, so I executed the `Remove-DscConfigurationDocument -Stage current,pending,previous` command to set it back to `Idle` and re-executed the installation but that made no difference either. In addition, I also split the WebAdaptor config into it's own JSON file, and executed the configuration after the server but made no difference either.

**Comment by decampo04** [comment]
Resolve by last comment.
