### ISSUE TITLE
ArcGIS Enterprise Upgrade From 11.1 to 11.2 Failed to Install Portal 

### ISSUE THREAD

**Issue by patel1684** [Esri/arcgis-powershell-dsc#532]
ArcGIS Enterprise Deployment Upgrade
ArcGIS Portal Upgrade
Dot Sourcing the Configuration:- PortalUpgrade
Starting DSC Job:- PortalUpgrade
VERBOSE: Time taken for configuration job to complete is 0.073 seconds
4/7/2024 10:07:00 AM: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
4/7/2024 10:07:05 AM: An LCM method call arrived from computer NBR-WEB-PROD with user sid S-1-5-21-706932479-2320048282-1573431700-1126.
4/7/2024 10:07:05 AM: The -Force option was specified with the Stop operation. The current configuration has been successfully cancelled.
4/7/2024 10:07:35 AM: An LCM method call arrived from computer NBR-WEB-PROD with user sid S-1-5-21-706932479-2320048282-1573431700-1126.
4/7/2024 10:07:35 AM: [server]: LCM:  [ Start  Set      ]
4/7/2024 10:07:35 AM: [server]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]WFMExtensionUninstall]
4/7/2024 10:07:35 AM: [server]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]WFMExtensionUninstall]
4/7/2024 10:07:35 AM: [server]:                            [[ArcGIS_Install]WFMExtensionUninstall] Installed Version
4/7/2024 10:07:35 AM: [server]: LCM:  [ End    Test     ]  [[ArcGIS_Install]WFMExtensionUninstall]  in 0.0630 seconds.
4/7/2024 10:07:35 AM: [server]: LCM:  [ Skip   Set      ]  [[ArcGIS_Install]WFMExtensionUninstall]
4/7/2024 10:07:35 AM: [server]: LCM:  [ End    Resource ]  [[ArcGIS_Install]WFMExtensionUninstall]
4/7/2024 10:07:35 AM: [server]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]PortalUpgrade]
4/7/2024 10:07:35 AM: [server]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]PortalUpgrade]
4/7/2024 10:07:35 AM: [server]:                            [[ArcGIS_Install]PortalUpgrade] Installed Version 11.1.42869 11.1.42869
4/7/2024 10:07:35 AM: [server]: LCM:  [ End    Test     ]  [[ArcGIS_Install]PortalUpgrade]  in 0.2180 seconds.
4/7/2024 10:07:35 AM: [server]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]PortalUpgrade]
4/7/2024 10:07:35 AM: [server]:                            [[ArcGIS_Install]PortalUpgrade] Self Extracting Installer
4/7/2024 10:07:35 AM: [server]:                            [[ArcGIS_Install]PortalUpgrade] Extracting \Installer\11.2\Portal_for_ArcGIS_Windows_112_188250.exe to C:\Windows\TEMP\F03C23C1-1F2C-42D0-85C4-38F49B710035
4/7/2024 10:08:35 AM: [server]:                            [[ArcGIS_Install]PortalUpgrade] Done Extracting. Waiting 15 seconds to allow the extractor to close files
4/7/2024 10:08:50 AM: [server]:                            [[ArcGIS_Install]PortalUpgrade] Executing C:\Windows\TEMP\F03C23C1-1F2C-42D0-85C4-38F49B710035\ArcGIS 11.2\PortalForArcGIS\Setup.exe
4/7/2024 10:09:10 AM: [server]:                            [[ArcGIS_Install]PortalUpgrade] Install process finished successfully.
4/7/2024 10:09:10 AM: [server]:                            [[ArcGIS_Install]PortalUpgrade] Validating the Portal Installation
4/7/2024 10:09:10 AM: [server]:                            [[ArcGIS_Install]PortalUpgrade] Installed Version 11.1.42869 11.1.42869
4/7/2024 10:09:10 AM: [server]: LCM:  [ End    Set      ]  [[ArcGIS_Install]PortalUpgrade]  in 95.0860 seconds.
4/7/2024 10:09:10 AM: [server]: LCM:  [ End    Set      ]
4/7/2024 10:09:10 AM: Operation 'Invoke CimMethod' complete.
Trace-DSCJob : 4/7/2024 10:09:10 AM: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install Portal 
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.2.1\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
 
Trace-DSCJob : 4/7/2024 10:09:10 AM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.2.1\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
 
Logs Directory: C:\Windows\system32\Logs
Finished DSC Job:- PortalUpgrade. Time Taken - 00:02:10.8034959
PortalUpgrade - Failed
Portal Upgrade Install Step Failed
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.2.1\ArcGIS.psm1:2603 char:9
+         throw "Portal Upgrade Install Step Failed"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Portal Upgrade Install Step Failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Portal Upgrade Install Step Failed
 

PS C:\Windows\system32> get-module arcgis -listavailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Manifest   4.2.1      ArcGIS                              {Get-FQDN, Invoke-ArcGISConfiguration, Invoke-PublishWebApp, Invoke-BuildArcGISAzureImage...}

**Comment by cameronkroeker** [comment]
Hi @patel1684 looks like the portal setup.exe failed to run. Since it is a silent install it does not exit with an error. Some suggestions that may help with gathering some clues to what could be causing the failure:

- Pass in `-EnableMSILogging` flag with the `Invoke-ArcGISConfiguration` command. This will create an msi log file which may contain the error of the failed installation.
- Review Windows Event application logs to see if there is an error related to the setup.exe
- Manually run the portal setup.exe (go through each step but not actually clicking the final step) to see if there is a useful error that occurs.

Also, this can happen when the ArcGIS service account password has changed but not been updated within the json configuration file. So may want to verify the password is valid within the json config file, and also check to ensure the account is not locked out.

Thanks,
Cameron K.

**Comment by patel1684** [comment]
Hi  Cameron,

I have run the installation manually and got an error message for the
service account.
"IsDomainAccount":true, --- True for the domain account
 "IsMSAAccount":true, --- this for?
"ForceUpdate": true -- what it will do?


[image: Capture.JPG]

*Thanks and Regards,*

*Avinash Patel,* B.E., PGD (GIS), ITIL

GIS Solution Architect & Administrator

Mo. +91-9990219312

Noida, Uttar Pradesh -201 301

**Comment by patel1684** [comment]
Thanks for your email, All looks good after the domain account update and
manual installation works fine for me. please close the reported issue.

Thanks,
Avinash Patel
+91-9990219312
