### ISSUE TITLE
WebAdaptors fails to install in a base deployment with error SendConfigurationApply function did not succeed

### ISSUE THREAD

**Issue by minagim** [Esri/arcgis-powershell-dsc#537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.2

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal
* ArcGIS_WebAdaptor

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.

11.2 Base deployment with 4 servers

Invoke-ArcGISConfiguration -ConfigurationParametersFile d:\BaseDeployment-MultiMachine_11_2.json -Mode InstallLicenseConfigure -EnableMSILogging
{
    "AllNodes": [
                    {
                        "NodeName": "datastore server fqdn",
                        "DataStoreTypes": [
                                            "Relational"
                                          ],
                        "Role": [
                                    "DataStore"
                                ],
                        "SslCertificates": [
                                                {
                                                    "Path": "d:\\Certificates\\DataStore_Cert.pfx",
                                                    "Password": "password",
                                                    "CNameFQDN": "datastore server cname fqdn",
                                                    "Target": [
                                                                    "DataStore"
                                                              ]
                                                }
                                           ]
                    },
                    {
                        "NodeName": "webAdaptor server fqdn",
                        "Role": [
                                    "WebAdaptor"
                                ],
                        "WebAdaptorConfig":[
                                                {
                                                    "Role": "Portal"
                                                },
                                                {
                                                    "Role": "Server"
                                                }
                                           ],
                        "SslCertificates": [                                                
                                                {
                                                    "Path": "d:\\Certificates\\Web_Cert.pfx",
                                                    "Password": "password",
                                                    "CNameFQDN": "webAdaptor server cname fqdn",
                                                    "Target": [
                                                                "WebAdaptor"
                                                              ]
                                                }
                                           ]
                    },
                    {
                        "NodeName": "portal server fqdn",
                        "Role": [
                                    "Portal"
                                ],
                        "SslCertificates": [
                                                {
                                                    "Path": "d:\\Certificates\\Portal_Cert.pfx",
                                                    "Password": "password",
                                                    "CNameFQDN": "portal server cname fqdn",
                                                    "SslRootOrIntermediate": [
                                                                                {
                                                                                    "Alias": "PortalRootCert",
                                                                                    "Path": "d:\\Certificates\\Portal_Root_Cert.cer"
                                                                                },
                                                                                {
                                                                                    "Alias": "PortalIntCert",
                                                                                    "Path": "d:\\Certificates\\Portal_Int_Cert.cer"
                                                                                }
                                                                            ],
                                                    "Target": [
                                                                "Portal"
                                                              ]
                                                }
                                           ]
                    },
                    {
                        "NodeName": "ags server fqdn",
                        "Role": [
                                    "Server"
                                ],
                        "SslCertificates": [
                                                {
                                                    "Path": "d:\\Certificates\\AGS_Cert.pfx",
                                                    "Password": "password",
                                                    "CNameFQDN": "ags server cname fqdn",
                                                    "SslRootOrIntermediate": [
                                                                                {
                                                                                    "Alias": "agsRootCert",
                                                                                    "Path": "d:\\Certificates\\ags_Root_Cert.cer"
                                                                                },
                                                                                {
                                                                                    "Alias": "agsIntCert",
                                                                                    "Path": "d:\\Certificates\\ags_Int_Cert.cer"
                                                                                }
                                                                            ],
                                                    "Target": [
                                                                "Server"
                                                              ]
                                                }
                                           ]
                    }
                ],
    "ConfigData": {
                    "Version": "11.2",
                    "ServerContext": "server",
                    "PortalContext": "portal",
                    "FileShareLocalPath": "",
                    "FileShareName": "",
                    "ServerRole": "GeneralPurposeServer",
                    "Credentials": {
                                        "ServiceAccount": {
                                                            "Password": "password",
                                                            "UserName": "ad\\serviceAccount",
                                                            "IsDomainAccount": true,
                                                            "IsMSAAccount": false
                                                          }
                                   },
                    "Server": {
                                "LicenseFilePath": "d:\\Enterprise\\ArcGISGISServerAdvanced_ArcGISServer.prvc",
                                "Installer": {
                                                "Path": "d:\\Enterprise\\ArcGIS_Server_Windows_112_188239.exe",
                                                "InstallDir": "d:\\ArcGIS\\Server",
                                                "InstallDirPython": "C:\\Python27",
                                                "EnableArcMapRuntime": true,
                                                "EnableDotnetSupport": true
                                            },
                                "ServerDirectoriesRootLocation": "d:\\arcgisserver\\directories",
                                "ConfigStoreLocation": "d:\\arcgisserver\\config-store",
                                "ExternalLoadBalancer": "",
                                "InternalLoadBalancer": "",
                                "PrimarySiteAdmin": {
                                                        "UserName": "primarysiteadminuser",
                                                        "Password": "password"
                                                    }
                              },
                    "Portal": {
                                "LicenseFilePath": "d:\\Enterprise\\ArcGIS_Enterprise_Portal_112.json",
                                "PortalLicenseUserTypeId": "creatorUT",
                                "Installer": {
                                                "Path": "d:\\Enterprise\\Portal_for_ArcGIS_Windows_112_188250.exe",
                                                "WebStylesPath": "d:\\Enterprise\\Portal_for_ArcGIS_Web_Styles_Windows_112_188251.exe",
                                                "InstallDir": "d:\\ArcGIS\\Portal",
                                                "ContentDir": "d:\\arcgisportal"
                                             },
                                "ContentDirectoryLocation": "d:\\arcgisportal\\content",
                                "ExternalLoadBalancer": "",
                                "InternalLoadBalancer": "",
                                "PortalAdministrator": {
                                                            "UserName": "portaladminuser",
                                                            "Email": "",
                                                            "Password": "password",
                                                            "SecurityQuestionIndex": 1,
                                                            "SecurityAnswer": "vanilla"
                                                       }
                              },
                    "DataStore": {
                                    "ContentDirectoryLocation": "d:\\arcgisdatastore",
                                    "EnableFailoverOnPrimaryStop": false,
                                    "EnablePointInTimeRecovery": false,
                                    "Installer": {
                                                    "Path": "d:\\Enterprise\\ArcGIS_DataStore_Windows_112_188252.exe",
                                                    "InstallDir": "d:\\ArcGIS\\DataStore"
                                                 }
                                 },
                    "WebAdaptor": {
                                    "AdminAccessEnabled": true,
                                    "Installer": {
                                                    "Path": "d:\\Enterprise\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_112_188253.exe"
                                                 }
                                  }
                  }
}
```

### Expected Behavior

Server and portal web adaptors should install with the right configurations for the base deployment.

### Actual Behavior

Datastore, server and portal installed with no issues but the web adaptors failed to install with the following error messages in the log.

PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install WebAdaptorIIS-Portal-portal 
PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install WebAdaptorIIS-Server-server 
The SendConfigurationApply function did not succeed.

![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/3a177e42-e186-4a27-a6e8-8be8b6912fae)

![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/b637c772-5e16-4f78-9503-495cd580c4bb)

### Steps to Reproduce

1. VMs on Azure East US 2 with windows 2022 datacenter
2. Copy the ArcGIS module to the C:\Program Files\WindowsPowerShell\Modules folder
3. Copy the software, licenses and ssl certificates to the servers
4. Run Invoke-ArcGISConfiguration -ConfigurationParametersFile d:\BaseDeployment-MultiMachine_11_2.json -Mode InstallLicenseConfigure -EnableMSILogging

**Comment by cameronkroeker** [comment]
@minagim can you check to see if [Microsoft Web Deploy 3.6](https://links.esri.com/download-web-deploy) and [ASP.NET Core Runtime - Windows Hosting Bundle 6.x](https://links.esri.com/download-hosting-bundle) are installed on the target node?

https://enterprise.arcgis.com/en/system-requirements/latest/windows/arcgis-web-adaptor-system-requirements.htm#ESRI_SECTION1_B79830AA8CCE4FE4AD1E0981E8BAA2D1

You can have the Module install them by adding these attributes to your json config:
https://github.com/Esri/arcgis-powershell-dsc/blob/1348e09ae3b6a7d69a3530d3e3766111b8425397/SampleConfigs/v4/v4.2.1/Base%20Deployment/BaseDeployment-SingleMachine.json#L179-L182

https://github.com/Esri/arcgis-powershell-dsc/wiki/v4.2.1-Variables-reference-page-for-JSON-configuration-files

<img width="860" alt="Screenshot 2024-04-25 at 11 38 12 AM" src="https://github.com/Esri/arcgis-powershell-dsc/assets/48299621/16070258-1712-41f5-b609-84871537d274">

Thanks,
Cameron K.

**Comment by minagim** [comment]
thanks for the info, Cameron and sorry for the delayed response.  I installed MS Web Deploy 3.6 and reinstalled ASP.NET Core Runtime - Windows Hosting Bundle 6.x and resolve the issue.  However, i am stuck with one of our ssl certificates at the server level in the configurations and troubleshooting the issue.  I will let you know if I need your help on this.  Please close the case and thanks for your help on this.

**Comment by minagim** [comment]
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/babf76e9-45c1-4a1a-9cd7-c9477901e85b)
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/221513fe-0f7a-462b-a469-8a2f5f28ac2b)
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/e20a8170-5c3a-40ad-9545-4fbe3a298d4b)

i am getting the above error and it sounds like it is expecting the Federation context.  do i need it for the base deployment?

**Comment by cameronkroeker** [comment]
> ![image](https://private-user-images.githubusercontent.com/60987985/329413511-babf76e9-45c1-4a1a-9cd7-c9477901e85b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTExMDIsIm5iZiI6MTcxNTMxMDgwMiwicGF0aCI6Ii82MDk4Nzk4NS8zMjk0MTM1MTEtYmFiZjc2ZTktNDVjMS00YTFhLTljZDctYzk0Nzc5MDFlODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAzMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYjA4ZTA2NWM1MTNiZjdmOWM4YWMzZTM3ZjMzMzM0NjgzOTQ0NzlkMGZhYzJiNWJlMzZhMTdjYWEwOTQyMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.knVJep63m5oZxahvcprrvVPE5G0LfCuZsPEQ8jhw6BM) ![image](https://private-user-images.githubusercontent.com/60987985/329413539-221513fe-0f7a-462b-a469-8a2f5f28ac2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTExMDIsIm5iZiI6MTcxNTMxMDgwMiwicGF0aCI6Ii82MDk4Nzk4NS8zMjk0MTM1MzktMjIxNTEzZmUtMGY3YS00NjJiLWE0NjktOGEyZjVmMjhhYzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAzMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDBhNDUyODhiYjY5MDNmNGFlMmQ0YThjYWE2YmQzYmI4ZjdmMjYzZTEyODE4NWY4NTZlZjI4ZjZiZThkZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_hXelMEAp6JCoqE0nCRUoHGPBhEEwNTnGHXLsfCmCc) ![image](https://private-user-images.githubusercontent.com/60987985/329413555-e20a8170-5c3a-40ad-9545-4fbe3a298d4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTExMDIsIm5iZiI6MTcxNTMxMDgwMiwicGF0aCI6Ii82MDk4Nzk4NS8zMjk0MTM1NTUtZTIwYTgxNzAtNWMzYS00MGFkLTk1NDUtNGZiZTNhMjk4ZDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAzMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MzFmMzJjOTExNTQyZDgxNzViMGIzZWRhYjNlMDNlZGIzMWU5MGMxZWM5ZDQzNDIwNDY0OTVlMDA1MjZjMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mSdHjf2Ny7jcM_zO4TJV4VGtVeN25rZd2_jkIhF8r10)
> 
> i am getting the above error and it sounds like it is expecting the Federation context. do i need it for the base deployment?

Hi @minagim, 

I suspect this error is happening because `"ExternalLoadBalancer"`, and `"InternalLoadBalancer"` are set to blank values within the json config file. If these are not going to be used then let's remove them from the json config. This is because they are used for federation:

https://github.com/Esri/arcgis-powershell-dsc/blob/1348e09ae3b6a7d69a3530d3e3766111b8425397/Modules/ArcGIS/ArcGIS.psm1#L2080

Thanks,
Cameron K.

**Comment by minagim** [comment]
[BaseDeployment-MultiMachine 11_2.json](https://github.com/Esri/arcgis-powershell-dsc/files/15278906/BaseDeployment-MultiMachine.11_2.json)
i removed those 2 parameters from the arcgis server and portal and now i am getting the following error even if the portaladmin credentials are specified and i can log into the portal manually.
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/3e0b852d-6958-4dc7-b7fa-6dc4a33975fd)
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/fe6136a1-4df4-48dc-a1dd-f35095ed2833)
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/56b4464a-88a0-47af-af10-04f56d4066da)

**Comment by cameronkroeker** [comment]
> [BaseDeployment-MultiMachine 11_2.json](https://github.com/Esri/arcgis-powershell-dsc/files/15278906/BaseDeployment-MultiMachine.11_2.json) i removed those 2 parameters from the arcgis server and portal and now i am getting the following error even if the portaladmin credentials are specified and i can log into the portal manually. ![image](https://private-user-images.githubusercontent.com/60987985/329691717-3e0b852d-6958-4dc7-b7fa-6dc4a33975fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjg0MTUsIm5iZiI6MTcxNTM2ODExNSwicGF0aCI6Ii82MDk4Nzk4NS8zMjk2OTE3MTctM2UwYjg1MmQtNjk1OC00ZGM3LWI3ZmEtNmRjNGEzMzk3NWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE5MDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzZiNjU4NDAxOWU0NTg4YTYxYjE1ZTljNjEzOTM0MjM1ZWYwY2IzMTIwOTE5Y2VkZTg2YjBlMjMyYTczODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ngkil4tEMA-qqW6fgctfOJ3lMJJ0LVUErNweU5VbyKY) ![image](https://private-user-images.githubusercontent.com/60987985/329691796-fe6136a1-4df4-48dc-a1dd-f35095ed2833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjg0MTUsIm5iZiI6MTcxNTM2ODExNSwicGF0aCI6Ii82MDk4Nzk4NS8zMjk2OTE3OTYtZmU2MTM2YTEtNGRmNC00OGRjLWExZGQtZjM1MDk1ZWQyODMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE5MDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiN2U0YWFjMWY1YjUyYjViMTE4NTU5ZWI1ZDZkOTI3OTlhMzY4ZmRkMzZlYjcwYTBlYjdmZmNiNTMwNzFiNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmA-_oQFo6y467f1VzV04qt_eNUDS2pbDikaz-NNBn4) ![image](https://private-user-images.githubusercontent.com/60987985/329692085-56b4464a-88a0-47af-af10-04f56d4066da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjg0MTUsIm5iZiI6MTcxNTM2ODExNSwicGF0aCI6Ii82MDk4Nzk4NS8zMjk2OTIwODUtNTZiNDQ2NGEtODhhMC00N2FmLWFmMTAtMDRmNTZkNDA2NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE5MDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMGE0OTRlYTYwMTY3YzRiMGQ3ZjIwYTllYzljNjIxNjBiNThhMDhhMDBjMzI4ODIwMGRiNDkxYmU1NjI5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e9Zm1A_ZdXs441xUh5uFyMBOL2nQz3UwtTaoSv8PJ9M)

@minagim 
From the node where ArcGIS Server is installed, can you successfully access the following url and generate a token?

`https://portal server cname fqdn:7443/arcgis/sharing/rest/generateToken`

Since the `"InternalLoadBalancer` attribute is no longer present, and SSLCertificates.CNameFQDN attribute is defined the module will use CNameFQDN this to construct the url:

https://github.com/Esri/arcgis-powershell-dsc/blob/1348e09ae3b6a7d69a3530d3e3766111b8425397/Modules/ArcGIS/ArcGIS.psm1#L2080

InternalLoadBalancer -> SSLCertificate.CName -> PrimaryPortalMachine.NodeName

**Comment by minagim** [comment]
yes, i was able to access the portal token generate page from the hosting arcgis server.
![image](https://github.com/Esri/arcgis-powershell-dsc/assets/60987985/f851207d-ba7e-4887-bed0-bf3c34eb6945)

**Comment by cameronkroeker** [comment]
> correction: i was able to access the portal token generate page with the machine name from the hosting arcgis server machine but not the cname. ![image](https://private-user-images.githubusercontent.com/60987985/329702547-f851207d-ba7e-4887-bed0-bf3c34eb6945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzE1NTUsIm5iZiI6MTcxNTM3MTI1NSwicGF0aCI6Ii82MDk4Nzk4NS8zMjk3MDI1NDctZjg1MTIwN2QtYmE3ZS00ODg3LWJlZDAtYmYzYzM0ZWI2OTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIwMDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MTllYzZkMDExMWNjYzRiYTc4MjQxMDZiY2M1Yzk1MjdmMjk5ZDA4NDgzMmQ3MGU5NjMxZTRhNTQ3ZmZhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vKHftwEausfXqpvNIP2l_eMsAfyWROPK-YTxS8DaEj4)
> 
> how can i correct this issue?

I suggest using the portal server fqdn for the SSLCertificates.CNameFQDN attribute value.

**Comment by minagim** [comment]
Thanks, Cameron, changing the Cname to the portal fqdn worked.  Is there any pros and cons in using Cname or server fqdn for the datastore, map server and portal server?
