### ISSUE TITLE
Powershell Error on Install 4.3.0

### ISSUE THREAD

**Issue by runneals** [Esri/arcgis-powershell-dsc#549]
Seems like something isn't working correctly with the module. I found a [related question/reply on Microsoft forum](https://learn.microsoft.com/en-us/answers/questions/1340401/while-deploying-the-dsc-configuration-getting-belo), and tried the answer, and it seems like everything include the ArcGIS_Install module is registered correctly, but Powershell doesn't like it for whatever reason. Have tried on a couple different machines now even!

Here's the error I'm getting:
```
The PowerShell DSC resource ArcGIS_Install from module <ArcGIS,4.3.0> does not exist at the PowerShell module path nor is it registered as a WMI DSC 
resource.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
```

**Comment by cameronkroeker** [comment]
Hi @runneals,

Are you grabbing it from the PSGallery via `Install-Module ArcGIS` on the orchestrating node and all target nodes? Or are you grabbing it from GitHub (extracting the .zip into the module path `C:\Program Files\WindowsPowerShell\Modules\ArcGIS`?

Thanks,
Cameron K.

**Comment by runneals** [comment]
I tried both methods

**Comment by cameronkroeker** [comment]
Could you share some more details such as the following?

- Windows version?
- PowerShell version?
   - `$PSVersionTable`
- Is `PSModulePath` set to `%ProgramFiles%\WindowsPowerShell\Modules` in environment system variables?
- Is the orchestrating machine same as target machine and how many target machines are there?
- What is the Execution policy set to on all nodes?
   - `Get-ExecutionPolicy -List`

**Comment by runneals** [comment]
Windows Server 2022
Was trying 5.1 and decided to try also installing 7.4, but getting other errors with the PSDesiredStateConfiguration for 7.4, so thinking I'm just going to use 5.1.
Yes, PSModulePath is set to that.
The Orchestrating machine is a different machine then the others.
And I manually needed to set that to bypass for the current user on the orchestrating machine. I assume I need to set this on all the target machines?

**Comment by cameronkroeker** [comment]
> Windows Server 2022 Was trying 5.1 and decided to try also installing 7.4, but getting other errors with the PSDesiredStateConfiguration for 7.4, so thinking I'm just going to use 5.1. Yes, PSModulePath is set to that. The Orchestrating machine is a different machine then the others. And I manually needed to set that to bypass for the current user on the orchestrating machine. I assume I need to set this on all the target machines?

Thanks. Yes please use 5.1 as powershell 7 is not currently supported with the ArcGIS module. I believe you will need to set the execution policy to remote signed for LocalMachine on all nodes:

```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
```

**Comment by runneals** [comment]
Getting this error with that execution policy:
Import-Module : File C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1 cannot be loaded. The file C:\Program 
Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1 is not digitally signed. You cannot run this script on the current system.

**Comment by runneals** [comment]
Just tried that (moved to running the script on a target machine as the orchestration machine's powershell is borked. Getting the same original error that the resource doesn't exist

**Comment by runneals** [comment]
Update: Does seem to run the web adaptor first and fail with my original error, but is still running, so we'll see how it works. Will let you know. It should include these things you mentioned above (PS version and execution policies) as a documented prereq on the front page (readme.md)

**Comment by cameronkroeker** [comment]
> Update: Does seem to run the web adaptor first and fail with my original error, but is still running, so we'll see how it works. Will let you know. It should include these things you mentioned above (PS version and execution policies) as a documented prereq on the front page (readme.md)

Thanks @runneals. We do have it in the "Getting Started" wiki doc which can be found in the side bar:

https://github.com/Esri/arcgis-powershell-dsc/wiki/V4.-Getting-Started

Perhaps though this should also be linked within the main wiki [Home](https://github.com/Esri/arcgis-powershell-dsc/wiki) page as well for better visibility.

**Comment by runneals** [comment]
> > Update: Does seem to run the web adaptor first and fail with my original error, but is still running, so we'll see how it works. Will let you know. It should include these things you mentioned above (PS version and execution policies) as a documented prereq on the front page (readme.md)
> 
> Thanks @runneals. We do have it in the "Getting Started" wiki doc which can be found in the side bar:
> 
> https://github.com/Esri/arcgis-powershell-dsc/wiki/V4.-Getting-Started
> 
> Perhaps though this should also be linked within the main wiki [Home](https://github.com/Esri/arcgis-powershell-dsc/wiki) page as well for better visibility.

Yes it definitely should! 2 of us didn't even see the getting started page, so calling it out more explicitly like the main wiki page and even the readme would be great.
