### ISSUE TITLE
Trace-DSCJob Errors

### ISSUE THREAD

**Issue by runneals** [Esri/arcgis-powershell-dsc#550]
We're running into this similar but different error with Trace-DSCJob on line 261.
```
Trace-DSCJob : 7/2/2024 9:00:15 AM: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install WebAdaptorIIS-Server-arcgis 
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.3.0\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 7/2/2024 9:00:15 AM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.3.0\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
```

**Comment by cameronkroeker** [comment]
> This was resolved by installing the ArcGIS Enterprise prereqs... In our case, it was resolved by doing it for the Web Adaptor:
> 
> * Install [Microsoft Web Deploy amd64 version](https://links.esri.com/download-web-deploy)
> * Install [ASP.NET 6.x Core Runtime Hosting Bundle](https://links.esri.com/download-hosting-bundle) OR [ASP.NET 8.x Core Runtime Hosting Bundle](https://links.esri.com/download-hosting-bundle-8x)

Glad you were able to resolve the issue. The ArcGIS Module can also install these pre-req's:

https://github.com/Esri/arcgis-powershell-dsc/blob/4e1ea910cf3c237c378dfcfc1130a296de3c4bcb/SampleConfigs/v4/v4.3.0/Base%20Deployment/BaseDeployment-SingleMachine.json#L189-L205

https://github.com/Esri/arcgis-powershell-dsc/wiki/v4.3.0-Variables-reference-page-for-JSON-configuration-files

<img width="863" alt="Screenshot 2024-07-02 at 7 42 04 AM" src="https://github.com/Esri/arcgis-powershell-dsc/assets/48299621/c98203f1-3ebd-48a5-a742-e8aa78af17b6">

**Comment by runneals** [comment]
Thanks! Some how I missed that *facepalm*
