### ISSUE TITLE
11.3 Installation failed: The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by widsuoids** [Esri/arcgis-powershell-dsc#554]
### Module Version

* 4.3.0

### Affected Resource(s)

* ArcGIS_Portal
* ArcGIS_Data Store

### Configuration Files
Single Machine deployment on Windows

### Expected Behavior

Portal and Data Store are installed and configure

### Actual Behavior

Exception calling "Start" with "1" argument(s): "The specified executable is not a valid application for this OS platform."
You cannot call a method on a null-valued expression.
PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Install failed. Process exit code:- . Error -  

When the DSC configuration and cache was cleared and the installlicenseconfigure command was run again, the Portal error vanished.
The Data Store still threw the same message.
When the command was run again, the error reappeared for both products...

### Steps to Reproduce

unsure. The configuration worked on another machine. Only node name changed from TDev to TPod and the passwords (no special characters for this test run)

### Important Factoids

Running single machine deployment on Azure

**Comment by cameronkroeker** [comment]
Hi @widsuoids,

Additional information is required to help understand the issue. Can you please provide the following?

- Version of Windows?
- Version of ArcGIS Enterprise?
- Can you provide a sanitized copy of the json configuration file used?
- Can you provide the DSC logs?

**Please ensure the following system requirements are met:**
https://github.com/Esri/arcgis-powershell-dsc/wiki/V4.-Getting-Started

Thanks,
Cameron K.

**Comment by widsuoids** [comment]
Probably something was not downloaded correctly from MyEsri. We validated the checksum, which turned out as expected. However removing and downloading the software again solved the issue.

I´d recommend to implement some better error message, that provide some hints on how to resolve it: "The specified executable is not a valid application for this OS platform: validate the checksum of the installers and the intended OS. Downloading the installers again may fix the problem. Make sure for Enterprise 11.3+ the second part of the installers is available."
