### ISSUE TITLE
Several issues encountered upgrade 11.1 to 11.3

### ISSUE THREAD

**Issue by app-EL** [Esri/arcgis-powershell-dsc#555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.3.0

### Affected Resource(s)

* ArcGIS_Server and ArcGIS Webadaptor for Server

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

PSDSC should have processed upgrade.
### Actual Behavior

Several issues caused scripts to error out in multiple steps.
### Important Factoids
During upgrade of environment from 11.1 to 11.3 several failures where encountered which should have processed correctly.
* Living Atlas Subscriber PW invalid should have been a warning but caused the script to error and fail. Would not process until had reset the subscriber PW in AGOL and updated it in Portal.
* PSDSC download of both webadaptor dependencies failed to process the upgrade. Required manually downloading and staging the webadaptor dependencies.
* Base deployment -  Webadaptor step for hosting site failed dependency stage and left the web server in a shutdown state. Portal processed correctly.
* ArcGIS Webadaptor upgrade failed to delete 11.1 IIS server folder (x2). This caused 11.3 server upgrade to fail.
* Federated server site - ArcGIS Server in HA mode failed to re-join 2'nd server to site. Left disconnected.
* Federated server sites (multiple) and standalone server (multiple times) - "Trace-DSCJob : 7/13/2024 12:08:43 AM: PowerShell DSC resource ArcGIS_ServerUpgrade  failed to execute Set-TargetResource functionality with error message: Error:- {"status":"error","messages":["Could not find resource or operation \u0027upgrade\u0027 on 
the system."],"code":404} At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.3.0\ArcGIS.psm1:261 char:5 Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ... CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
-- This was a random issue encountered during the server upgrade itself. 
-- Re-processing script did not clear issue. Only way found to resolve was to restore from snapshot and re-process from beginning.
* After the upgrade WebGISDR fails after initiation - finding that the DataStore service account was corrupted during the upgrade process. Re-configuring the service account manually for all DataStore machines fixes the incomplete service account application and allows WebGISDR to run.

I'm fairly certain that all but the top and bottom bullet in the above list probably come down to issues with the Webadaptor and its new .NET assemblies. 

This issue report is just informational. Was able to workaround all issues.

Server 2019, IIS, Base deployment with 3 federated server sites and two standalone server sites.

**Comment by BrendanEsri** [comment]
Similar to issue #560
