### ISSUE TITLE
Automated Data Store Configuration 

### ISSUE THREAD

**Issue by ae-daenchrisarmada** [Esri/arcgis-powershell-dsc#565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.3.0

### Affected Resource(s)

* ArcGIS_DataStore

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "EC2AMAZ-UPRFRTV",
            "DataStoreTypes": [
                "Relational"
            ],
            "Role": [
                "DataStore",
            ],
            "WebAdaptorConfig":[
                {
                    "Role": "Portal"
                },
                {
                    "Role": "Server"
                }
            ]
        }
    ],
    "ConfigData": {
        "Version": "11.1",
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "DownloadSetups": false,
        "DownloadSetupsToSharedPath": false,
        "DownloadPatches": false,
        "SkipPatchInstalls": false,
        "DataStore": {
            "ContentDirectoryLocation": "C:\\arcgisdatastore",
            "EnableFailoverOnPrimaryStop": false,
            "EnablePointInTimeRecovery": false,
            "Installer": {
                "Path": "C:\\s3\\ArcGIS_DataStore_Windows_111_185221.exe",
                "IsSelfExtracting": false,
                "InstallDir": "C:\\ArcGIS\\DataStore",
                "InstallAllFeatures": true
            }
        }
    }
}
```

### Expected Behavior

I expect that the GIS Server, Username and Password can be autoamtically configured.

### Actual Behavior

Only installs the ArcGIS DataStore Configuration then Data

**Comment by cameronkroeker** [comment]
Hi @ae-daenchrisarmada,

You will need to pass in the `Server` Role node attributes, and **ConfigData.Server** attributes, otherwise the DSC ArcGIS module won't be able to construct the parameters needed to register the data store with server (like the server url, and site username/password).

Thanks,
Cameron K.

**Comment by ae-daenchrisarmada** [comment]
Which **ConfigData.Server** attributes are required? I only aim to have a **Relational** Type when I check the DataStores page in the Server Manager
