### ISSUE TITLE
Upgrade 11.1 to 11.3 - Portal Upgrade Install Step Failed | Error 28809 - Could not validate the credentials

### ISSUE THREAD

**Issue by tigerwoulds** [Esri/arcgis-powershell-dsc#583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.4.0

### Affected Resource(s)

* ArcGIS_Portal

### Configuration Files

```
{
    "AllNodes": [
        {
            "NodeName": "[REDACTED]",
            "Role": [
                "Portal"
            ]   
        },
        {
            "NodeName": "[REDACTED]",
            "Role": [
                "Server"
            ]
        },
		{
            "NodeName": "[REDACTED]",
            "DataStoreTypes": [
                "Relational",
		"Tilecache"
            ],
            "Role": [
                "DataStore"
            ]
        },
		{
            "NodeName": "[REDACTED]",
            "DataStoreTypes": [
                "SpatioTemporal"   
            ],
            "Role": [
                "DataStore"
            ]
        },
		{
            "NodeName": "[REDACTED]",
            "Role": [
                "WebAdaptor"
            ],
            "WebAdaptorConfig":[
                {
                    "Role": "Portal",
                    "Context": "portal",
                    "AdminAccessEnabled": true,
                    "WebSiteId": 1
                },
                {
                    "Role": "Server",
                    "Context": "server",
                    "AdminAccessEnabled": true,
                    "WebSiteId": 1
                }
            ],
            "SslCertificates": [
		{
			"Path": "[REDACTED]",
			"Password": "[REDACTED]",
			"CNameFQDN": "[REDACTED]",
			"Target": [
				"WebAdaptor"
			]
		}
            ]   
        }
    ],
    "ConfigData": {
        "Version": "11.3",
        "OldVersion": "11.1",
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "Credentials": {
            "ServiceAccount": {
                "Password": "[REDACTED]",
                "UserName": "domain\\service_acct",
                "IsDomainAccount": true,
                "IsMSAAccount": false
            },
            "AGOCredential":{
                "UserName": "[REDACTED]",
                "Password": "[REDACTED]"
             }
        },
        "DownloadSetups": true,
        "DownloadPatches": false,
        "Server": {
            "LicenseFilePath": "[REDACTED]",
            "Installer": {
                "Path": "D:\\software\\ArcGIS_Server_Windows_113_190188.exe",
                "VolumePaths": [
                   "D:\\software\\ArcGIS_Server_Windows_113_190188.exe.001"
                ],
                "InstallDir": "D:\\ArcGIS\\Server",
                "EnableArcMapRuntime": false,
                "EnableDotnetSupport": false
            },
            "ServerDirectoriesRootLocation": "D:\\arcgisserver\\directories",
            "ConfigStoreLocation": "D:\\arcgisserver\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": "[REDACTED]",
                "Password": "[REDACTED]"
            },
	    "ExternalLoadBalancer": "[REDACTED]",
            "InternalLoadBalancer": "[REDACTED]"
        },
        "Portal": {
            "LicenseFilePath": "[REDACTED]",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "D:\\software\\Portal_for_ArcGIS_Windows_113_189790.exe",
                "VolumePaths": [
                   "D:\\software\\Portal_for_ArcGIS_Windows_113_189790.exe.001"
                ],
                "InstallDir": "D:\\ArcGIS\\Portal",
                "WebStylesPath": "",
                "ContentDir": "D:\\arcgisportal"
            },
            "ContentDirectoryLocation":"D:\\arcgisportal\\content",
            "PortalAdministrator": {
                "UserName": "[REDACTED]",
                "Email": "[REDACTED]",
                "Password": "[REDACTED]",
                "SecurityQuestionIndex": 1,
                "SecurityAnswer": "[REDACTED]"
            },
	    "ExternalLoadBalancer": "[REDACTED]",
            "InternalLoadBalancer": "[REDACTED]"
        },
        "DataStore": {
            "ContentDirectoryLocation": "D:\\arcgisdatastore",
            "EnableFailoverOnPrimaryStop": false,
            "Installer": {
                "Path": "D:\\software\\ArcGIS_DataStore_Windows_113_190233.exe"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "D:\\software\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_113_190234.exe",
		"DotnetHostingBundlePath": "D:\\software\\dotnet-hosting-6.0.33-win.exe",
		"WebDeployPath": "D:\\software\\WebDeploy_amd64_en-US.msi"
            }
        }
    }
}
```

### Expected Behavior

Portal should upgrade from 11.1 to 11.3

### Actual Behavior

Error encountered during Portal upgrade
```
Trace-DSCJob : 11/22/2024 7:32:29 PM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.4.0\ArcGIS.psm1:263 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
 
Logs Directory: C:\Windows\system32\Logs
Finished DSC Job:- PortalUpgrade. Time Taken - 00:02:30.4714472
PortalUpgrade - Failed
Portal Upgrade Install Step Failed
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.4.0\ArcGIS.psm1:2840 char:9
+         throw "Portal Upgrade Install Step Failed"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Portal Upgrade Install Step Failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Portal Upgrade Install Step Failed
```

Windows event logs on the Portal host return ```Error 28809 - Could not validate the credentials for account domain\service_acct. Confirm the credentials are correct and attempt the installation again. The setup will now exit. ```

This is an Active Directory account on our domain. The account is currently used for our 11.1 deployment. In fact, I did a fresh install of 11.1 today using the same AD account. The password does not contain any special characters.

### Steps to Reproduce

- Install ArcGIS module version 4.4.0 on orchestration, portal, arcgis server, data store, web adaptor hosts
- Deploy multi-machine ArcGIS Enterprise 11.1 using a domain account as the service account
- Run DSC in upgrade mode

### References

https://github.com/Esri/arcgis-powershell-dsc/issues/309

**Comment by cameronkroeker** [comment]
Hi @tigerwoulds,

Based on the error message it sounds like the portal setup.exe is not able to validate the windows service run as account for portal. Could you check the following items:

1. Check to ensure the password defined for ConfigData.Credentials.ServiceAccount.Password matches the actual password. There could be perhaps an extra space in the beginning or end of the value that is difficult to spot. This can happen often when using copy/paste. For example:

```
"Password": "[REDACTED] ",
```

or

```
"Password": " [REDACTED]",
```

Validate the correct values are being passed in via Task Manager. Prior to kicking off the upgrade, on the portal node launch task manager and select the details tab. Right click the column bar and select columns to enable command line:

<img width="386" alt="Screenshot 2024-11-27 at 8 32 38 AM" src="https://github.com/user-attachments/assets/db952e9a-b277-4fb9-84aa-c55e34612250">

Then when you kick off the upgrade, monitor task manager for the portal setup.exe process to see what values are being passed in:

<img width="2112" alt="Screenshot 2024-11-27 at 8 35 26 AM" src="https://github.com/user-attachments/assets/84802f35-d1eb-4f29-b9ad-08d17f899386">

Thanks,
Cameron K.

**Comment by tigerwoulds** [comment]
> Hi @tigerwoulds,
> 
> Based on the error message it sounds like the portal setup.exe is not able to validate the windows service run as account for portal. Could you check the following items:
> 
> 1. Check to ensure the password defined for ConfigData.Credentials.ServiceAccount.Password matches the actual password. There could be perhaps an extra space in the beginning or end of the value that is difficult to spot. This can happen often when using copy/paste. For example:
> 
> ```
> "Password": "[REDACTED] ",
> ```
> 
> or
> 
> ```
> "Password": " [REDACTED]",
> ```
> 
> Validate the correct values are being passed in via Task Manager. Prior to kicking off the upgrade, on the portal node launch task manager and select the details tab. Right click the column bar and select columns to enable command line:
> 
> <img alt="Screenshot 2024-11-27 at 8 32 38 AM" width="386" src="https://private-user-images.githubusercontent.com/48299621/390495158-db952e9a-b277-4fb9-84aa-c55e34612250.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5OTkyNzMsIm5iZiI6MTczMjk5ODk3MywicGF0aCI6Ii80ODI5OTYyMS8zOTA0OTUxNTgtZGI5NTJlOWEtYjI3Ny00ZmI5LTg0YWEtYzU1ZTM0NjEyMjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDIwMzYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjY2VhMzQyOGRhMTM3Y2YzMDE3YTE3MWQ1ZTEzOTViMGQ2ZTkwN2M5M2I0ZjBjM2I2Y2U2ZTc0NTZiMTA5YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S2HcIJdI2BW3c_ENKpXebN3nfhB8FaDJRaZSOMm2HSU">
> Then when you kick off the upgrade, monitor task manager for the portal setup.exe process to see what values are being passed in:
> 
> <img alt="Screenshot 2024-11-27 at 8 35 26 AM" width="2000" src="https://private-user-images.githubusercontent.com/48299621/390496865-84802f35-d1eb-4f29-b9ad-08d17f899386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5OTkyNzMsIm5iZiI6MTczMjk5ODk3MywicGF0aCI6Ii80ODI5OTYyMS8zOTA0OTY4NjUtODQ4MDJmMzUtZDFlYi00ZjI5LWI5YWQtMDhkMTdmODk5Mzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDIwMzYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYzMwZTcyNGNjMTJiMWYxMjFlNzBlMDRlMzYwODA0NDMxMTQxMDU1Mjk5M2U0ZDYxMGU4MThlNDNhYjFkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0VyjaF7alwjp-Yv10RHPqRdhWoV7SLZeAx3kUl28rdQ">
> Thanks, Cameron K.

**Comment by tigerwoulds** [comment]
Thanks @cameronkroeker. Confirmed there are no leading or trailing spaces in my config file for the username and password. I also enabled command line the task manager and monitored the setup.exe process when I kick off DSC. The credentials there are correct.
