### ISSUE TITLE
Password for Service_Account is not well escaped

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#60]
If you have an Run-As-Account for ArcGIS DataStore where the Password contains an ampersand (&) ist not well escaped and won't work.

**Comment by shailesh91** [comment]
@spitzerr can you give sample passwords and what happens when it is not escaped?

**Comment by spitzerr** [comment]
@shailesh91  as stated in the issue right now it affects Passwords containing an ampersand ```&```
e.g.
```PowerShell&Esri```
The commandline-tool to Change the account for DataStore splits the command at the ampersand and tries Esri as ```Password``` and ```Esri``` as additional command. This Fails obviously.
If you think of Fixing it think also about Password with (double)quotes ```"```. As this Needs to be escaped for the cmd by doubeling it ```""```. Se my fix for Details.
