### ISSUE TITLE
Test Service_Account always false

### ISSUE THREAD

**Issue by spitzerr** [Esri/arcgis-powershell-dsc#7]
Test for Filepermissions of Service_Account is always false for domain-user.

**Comment by nshampur** [comment]
@spitzerr  .. 
we see the bug

https://github.com/Esri/arcgis-powershell-dsc/blob/master/Modules/ArcGIS/DSCResources/ArcGIS_Service_Account/ArcGIS_Service_Account.psm1#L371
Where {$_.IdentityReference -ieq "$env:ComputerName\$RunAsUserName"} 

Feel free to PR a fix :)

**Comment by spitzerr** [comment]
Still not fixed. Please see PR #12 for fix

**Comment by nshampur** [comment]
@spitzerr .. apologies for the delay.   @shailesh91 is OOF till next week and the team is busy with EPC/DevSummit prep. work.
We'll review early next week and merge the PR.  Thanks for you issue reports and quick contributions and bug fixes.
