### ISSUE TITLE
Issues related to proxy/http error, blocked files, and Install-PreReqs1.ps1

### ISSUE THREAD

**Issue by prez13** [Esri/arcgis-powershell-dsc#76]
We wanted to use those PowerShell scripts to upgrade our six standalone ArcGIS Server machines. They look really promising, but we have encountered a few issues and were only able to finish one server partially. We are running on Windows Server 2012.

1. The Install-PreReqs.ps1 (Appendix B) did not work for us. It recursively created ArcGIS folders on the remote machine, which lead to this structure: "<path of PowerShell modules>\ArcGIS\ArcGIS\ArcGIS\ArcGIS\...\ArcGIS" 

2. Initially, the local Windows user was not able to connect to the Internet in order to download 7-zip and to licence the software. We had to set a proxy to do that. This helped to download 7-zip, but later in the process the script failed again with the error message: "The WinRM client sent a request to an HTTP server and got a response saying the requested HTTP URL was not available. This is usually returned by a HTP server that does not support the WS-Management protocol". The strange thing here is that we did the installation locally on the server. It would be useful if a proxy could be set in the command line, but it would need to deal with this http error. 

3. On our test machine, the files of the ArcGIS Module could not be executed for security reasons because they origin from a different computer. We could use a PowerShell command to unblock all of them recursively. It would be useful if this unblock process could be included in Install-PreReqs.ps1.

Thanks for the great product, hopefully we will be able to use it in production soon!

Prez.

**Comment by nshampur** [comment]
Hello @prez13 
Thank you for the feedback.

1, Can you provide the parameters you provided as input to Install-PreReqs.ps? In particular the ModuleSourcePath parameter.
2. If you install 7-zip manually, the script should not attempt to install/download it again. Can you check if 7-zip was installed correctly in ProgramFiles\7-Zip\7z.exe
3. Good point. We assume the execution policy can be set to execute remote script.  Using the Unblock-File commandlet is a possible option.

Please continue to provide feedback and we welcome your contributions as well.

**Comment by RQF4** [comment]
Hi @prez13, 

I didn't encounter your first issue but here are a couple suggestions for the other two you might try. I install NuGet and Chocolaty, which I then use to get 7-zip and the dsc modules, all in the Pre-Reqs script (which I expanded). I make sure to run the dsc piece on my local and the remote machines to keep them in sync. 

```PowerShell
function Install-NuGet {
    if (Test-Path -Path "C:\Program Files\PackageManagement\ProviderAssemblies\nuget") {
        Write-Output "NuGet is already installed"
    }
    else {
        Write-Output "Installing NuGet"
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Import-PackageProvider -Name NuGet -RequiredVersion 2.8.5.201
        Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
    }
}

function Install-Choco {
    Write-Output "Checking Choco"
    Get-PackageProvider -Name "Chocolatey" -ForceBootstrap
}

function Install-7zip {
    if (Test-Path -Path "C:\Program Files\7-Zip\7z.exe") {
        Write-Output "7zip is already installed"
    }
    else {
        Write-Output "Installing 7zip"
        Install-Package -Name "7zip" -ProviderName "Chocolateyget"
    }
}

function Install-ArcgisDSC {
    Import-Module -Name PSDesiredStateConfiguration
    if (Get-DscResource -Module "ArcGIS") {
        Write-Output "ArcGIS DSC is already installed, updating..."
        Install-Module ArcGIS -Force
    }
    else {
        Write-Output "Installing ArcGIS DSC Library"
        Install-Module ArcGIS -Force
    }
}
```

**Comment by shailesh91** [comment]
@RQF4 Thanks for the contribution. This is a very good script to have when all the machines have access to the internet and have WMF 5 installed. 
@prez13 I have made some changes to address issues 1 and 3 with the changes I have made to [`Appendix B`](https://github.com/Esri/arcgis-powershell-dsc/wiki/Scripts-to-push-the-ArcGIS-Module/77a4119daf3a47d06e07a3d3d8a998be7777b203).

**Comment by shailesh91** [comment]
Closing the issue. If the issue still persists please reopen.
