### ISSUE TITLE
The SendConfigurationApply function did not succeed

### ISSUE THREAD

**Issue by fraruilo** [Esri/arcgis-powershell-dsc#79]
Hello,
I am facing an issue with the ArcGIS DSC and I was wondering if somebody else also struggled with it...

I have a coupe of fresh boxes (W2012R2 with WMF5) and I have installed AGS (General purpose single machine) 10.4.1 from scratch using a Push from Machine A to Machine B. Everything worked like a charm. Then I wanted to update this box where I had just install to a newer ArcGIS Server version, but I get an error (below). The upgrade JSON is quite similar to the install one, I have just updated the paths and added the old version parameter.

```
[]Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
[]The PowerShell DSC resource '[ArcGIS_ServerUpgrade]ServerConfigureUpgrade' with SourceInfo 'C:\Program Files\WindowsPo
werShell\Modules\ArcGIS\Configuration\Upgrades\ServerUpgrade.ps1::85::9::ArcGIS_ServerUpgrade' threw one or more non-ter
minating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called M
icrosoft-Windows-DSC/Operational. Refer to this channel for more details.
[]The SendConfigurationApply function did not succeed.
```

Upgrading the server fails, and later on, when the web adaptor is installed, it cannot connect to the server. Leaving the system in an inconsistent state.

I attach the Powershell output, and the verbose for the WA Install and server upgrade.
[Powershell Upgrade LOG.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2197873/Powershell.Upgrade.LOG.txt)
[ServerUpgrade_Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2197874/ServerUpgrade_Verbose.txt)
[WAInstall_Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2197875/WAInstall_Verbose.txt)

The Windows event viewer logs for DSC show this description:

_Job {F6626FDA-88E7-11E8-80D1-080027D91466} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [ArcGIS_ServerUpgrade]ServerConfigureUpgrade and Source Info is C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configuration\Upgrades\ServerUpgrade.ps1::85::9::ArcGIS_ServerUpgrade. Error Message is The PowerShell DSC resource '[ArcGIS_ServerUpgrade]ServerConfigureUpgrade' with SourceInfo 'C:\Program Files\WindowsPowerShell\Modules\ArcGIS\Configuration\Upgrades\ServerUpgrade.ps1::85::9::ArcGIS_ServerUpgrade' threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.._

Do you have any suggestions?

**Comment by shailesh91** [comment]
@fraruilo this is a very generic error received when an API call errors out. Possibly, I can help you debug it over Skype. Btw, have you tried running the same upgrade config again? (Since this is an idempotent it will try to bring back any of the components out of state to the defined state.)

**Comment by fraruilo** [comment]
@shailesh91 thanks for the feedback. I made those boxes for testing out, I am open to a screen sharing, but I don't think we need to invest time into debugging them. 
I tried several times. The only thing I can think of is the fact that AGS10.4.1 installs with a self signed certificate, even though I provide my own root and domain certs. I will test further and provide more information.

**Comment by prez13** [comment]
@shailesh91 , @fraruilo Did you ever find a solution to this problem? We are currently facing the exact same challenge, upgrading from 10.5.1 to 10.6.1. We would be open to a Skype session.

**Comment by shailesh91** [comment]
@prez13 the error is the above was not related to licensing. But accessing the following endpoint "https://$($ServerHostName):6443/arcgis/admin/upgrade". Probably this was rectified when Server was restarted. Were you able to repro this issue multiple time?

**Comment by cameronkroeker** [comment]
closing dude to inactivity and also looks to be resolved by the following steps:

1. Restarted the server
2. Logged in as user that is set as ServiceAccount in the PowerShell DSC config json file
Enabled internet access for that user (set up proxy in IE, lowered server security)
