### ISSUE TITLE
Defect template for users

### ISSUE THREAD

**Issue by PleaseStopAsking** [Esri/arcgis-powershell-dsc#81]
It might be helpful to provide a template for users to use when submitting defects/requests. Attached is a example in markdown format already.

[template.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2253831/template.txt)

**Comment by nshampur** [comment]
that's an excellent suggestion. I've seen this on other open source projects.

We'll implement. Thanks for sharing.

**Comment by cameronkroeker** [comment]
@PleaseStopAsking 

This has been added.
