### ISSUE TITLE
SSL/TLS secure channel failure

### ISSUE THREAD

**Issue by PleaseStopAsking** [Esri/arcgis-powershell-dsc#82]
### Module Version

ModuleVersion = '1.0.0'

### Affected Resource(s)

ArcGIS_DataStore

### Configuration Files

```
ArcGIS_DataStore arcgisDatastore {
    Ensure = 'Present'
    ServerHostName = $env:COMPUTERNAME.Substring(0,$env:COMPUTERNAME.Length -5) + "ags01"
    ContentDirectory = $dataStoreContentLocation
    DataStoreTypes = 'relational'
    RunAsAccount = $serviceAccountCredential
    SiteAdministrator = $psaCredential
    DependsOn = @('[xFirewall]arcgisDatastoreFirewallRules')
}
```

### Expected Behavior

Datastore should be configured with the ArcGIS Server site.

### Actual Behavior

The standard output shows
```
... failed to execute Set-TargetResource functionality with error message: Register Data Store Failed after multiple attempts.
```

Checking the dsc logs, found the following error
```
[WARNING]:- The request was aborted: Could not create SSL/TLS secure channel.
```

### Important Factoids

- Using Esri 10.6.1 image in Azure Marketplace
- Digging into the ArcGIS_DataStore module, found that the issue is located in the Register-DataStore function, specifically when setting the certificate callback to $true. To get around the issue, I added the following line immediately below the callback.
```
[System.Net.ServicePointManager]::SecurityProtocol = "tls11, tls12"
```

I am sure there is a more appropriate solution but this is what I came up with. Issue does not seem to occur when using the Esri 10.6 image in the Azure Marketplace which likely means this is related to changes in ArcGIS 10.6.1.

**Comment by nshampur** [comment]
is this on a single machine deployment or a multi machine deployment?

**Comment by PleaseStopAsking** [comment]
Multi-machine deployment. Server, Portal and DataStore are all on different machines.

**Comment by nshampur** [comment]
is data store in HA config?

**Comment by PleaseStopAsking** [comment]
No, single only.

**Comment by PleaseStopAsking** [comment]
Reviewing the .psm1 directly in Gitub, it looks like I was missing
```[Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls```

in my file for some reason which explains why it works after I added ```[System.Net.ServicePointManager]::SecurityProtocol = "tls11, tls12"```

I am running my tests again after making a new copy of the updated module and believe it will work. Will update shortly.
