### ISSUE TITLE
GeoEvent federation error message

### ISSUE THREAD

**Issue by jbiendara** [Esri/arcgis-powershell-dsc#88]
Hello,

I've created a single machine Enterprise environment (BaseDeployment-SingleMachine.json) with GeoEvent Server (GISServer-GeoEvent.json). The installation executed without problems but for the federation of the GeoEvent Server with Portal. This final step raised an error (see attached screenshot). Also, the server URLs in the PowerShell output are not complete.
Nevertheless, the GeoEvent server seems to be federated with Portal correctly for when I access the GeoEvent manager I am redirected to the Portal login page.

Any idea what's wrong?

Thank you very much, best regards,
Jürgen

[ArcGISConfigure-22.08.2018-09-28-52-Error.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2310527/ArcGISConfigure-22.08.2018-09-28-52-Error.txt)
[ArcGISConfigure-22.08.2018-09-28-52-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2310528/ArcGISConfigure-22.08.2018-09-28-52-Verbose.txt)
![geoeventfederationerror](https://user-images.githubusercontent.com/42602939/44466848-93e21900-a621-11e8-9da6-daa5f20e1a6a.jpg)

**Comment by shailesh91** [comment]
Hey Jürgen,

Have you tried running this Configuration again? Since all Powershell DSC is idempotent it should skip all the components installed and configured correctly. It should jump directly to the Federation part. And please check the parameter values in the federation block once again.
For a little more verbosity on the Powershell Window Screen, you can use -DebugSwitch option with the Configure-ArcGIS command.
If you have any further questions, do let me know.

**Comment by jbiendara** [comment]
Hi Shailesh,
I re-checked the parameters in the federation block, they are correct. I also ran the GeoEvent server configuration a second time, but to no avail. The error is the same at "Get Portal Token from Deployment 'durowa.esri-de.com'": Error getting Token for Federation ! Waiting for 1 Minutes to try again
Any idea, how I can debug this any further?
Thank you very much, best regards,
Jürgen

**Comment by shailesh91** [comment]
Jürgen, 
Is there any chance you can mail me the JSON configuration files for both the deployments. 
Regards,
Shailesh

**Comment by jbiendara** [comment]
Hey Shailesh,

Please find attached the two JSON configuration files.

Best regards,
Jürgen


Von: Shailesh Goel <notifications@github.com>
Gesendet: Donnerstag, 23. August 2018 21:57
An: Esri/arcgis-powershell-dsc <arcgis-powershell-dsc@noreply.github.com>
Cc: Jürgen Biendara <j.biendara@conterra.de>; Author <author@noreply.github.com>
Betreff: Re: [Esri/arcgis-powershell-dsc] GeoEvent federation error message (#88)


Jürgen,
Is there any chance you can mail me the JSON configuration files for both the deployments.
Regards,
Shailesh

**Comment by shailesh91** [comment]
Hey Jürgen,
You forgot to attach the configuration files.
Regards,
Shailesh
