### ISSUE TITLE
Errors when running install command

### ISSUE THREAD

**Issue by mmclamb** [Esri/arcgis-powershell-dsc#89]
I am receiving the following errors when running the install. The web server is in in the DMZ on a different domain. I have added a record in the host file, but it still cannot access it via IP or name. Secondly, I don't need a FileShare as I am not setting up a HA environment, but I don't see how to get around that requirement. Any thoughts?

[MACHINENAME] Connecting to remote server MACHINENAME failed with the following error message : WinRM cannot process
the request. The following error occurred while using Kerberos authentication: Cannot find the computer MACHINENAME.
Verify that the computer exists on the network and that the name provided is spelled correctly. For more information,
see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (MACHINENAME:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : NetworkPathNotFound,PSSessionStateBroken
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\1.0.1\ArcGIS.psm1:630 char:13
+             $ConfigurationParamsHashtable.AllNodes[$i].WMFVersion = [ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

FileShare not present required for HA Setup!
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\1.0.1\ArcGIS.psm1:726 char:17
+                 throw "FileShare not present required for HA Setup!"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (FileShare not p...d for HA Setup!:String) [], RuntimeException
    + FullyQualifiedErrorId : FileShare not present required for HA Setup!

**Comment by nshampur** [comment]
@mmclamb  . Can you share your configuration (Sans sensitive information).  Note - you don't need a dedicated node for the file share, just need to define a node that will serve as the location for the portal content store and configuration store

**Comment by mmclamb** [comment]
I have the install path populated in mine along with machine names and un/pw's. I did make a note which machine is referenced by IP. 

[BaseDeployment-MultiMachine.zip](https://github.com/Esri/arcgis-powershell-dsc/files/2328914/BaseDeployment-MultiMachine.zip)

**Comment by nshampur** [comment]
@mmclamb .. On which machine (1,2,3,4,5) do you plan to host the server config store and portal content store.  Please add the "FileShare" role to that machine.

On the machine 2 that is on a separate domain.  Can you check if the machine is accessible using the Resolve-DnsName powershell commandlet.  You may need to configure WinRM trust from that machine to the other hosts. 
https://technet.microsoft.com/en-us/library/ff700227.aspx

**Comment by mmclamb** [comment]
@nshampur Machine 1 will host the server config store and Machine 3 will host the portal content store. Any issue with them being separated?

The DNS name was able to be resolved using Resolve-DnsName in PS.

**Comment by shailesh91** [comment]
Issue Fixed in #95. Closing this issue. Please open again if any further issues.
