### ISSUE TITLE
Set-up of image server

### ISSUE THREAD

**Issue by jbiendara** [Esri/arcgis-powershell-dsc#91]
Hello,

I want to set up an image server in a multi machine environment. Since there is no specific sample configuration file I will use the GISServer-GeneralPurpose.json template. Is this the correct way and if yes, is there a way to directly configure this new server as image server in portal with PowerShell?

Regards,
Jürgen

**Comment by nshampur** [comment]
Hello 
Please take a look at https://github.com/Esri/arcgis-powershell-dsc/wiki/Deploy-an-ArcGIS-Image-Server-site-on-one-machine

**Comment by nshampur** [comment]
https://github.com/Esri/arcgis-powershell-dsc/blob/bfae4eb747903d76d640d9edfb5f67daf87d15e3/SampleConfigs/Gis%20Servers/GISServer-GeoEvent.json#L12   .. Set ServerRole accordingly  to "ImageHosting" or "RasterAnalytics" according to which the Image Server is being used.

**Comment by shailesh91** [comment]
@jbiendara doc has been updated.

Thanks,
Shailesh
