### ISSUE TITLE
Multi machine setup - issues

### ISSUE THREAD

**Issue by jbiendara** [Esri/arcgis-powershell-dsc#93]
Hello,

I've set up a five machine environment (Portal, hosted Server, Data Store, Image Server, GeoEvent Server). I used three configuration files:

1. BaseDeployment-ThreeMachine-10.6-ssl
2. GISServer-GeoEvent
3. GISServer-GeneralPurpose

During and after the installation, I see two issues:

1. Configurations 2. (GeoEvent Server) and 3. (Image Server) display incomplete server URLs.
![incompleteurl](https://user-images.githubusercontent.com/42602939/45080566-7028d380-b0f5-11e8-9065-02e305cba05b.jpg)

2. The various servers are federated in portal with different ports (443 and 6443 respectively), although in all three configuration files I declared port 443 as "Federation - PortalPort".
![federatedservers](https://user-images.githubusercontent.com/42602939/45080825-0b21ad80-b0f6-11e8-94bb-6b05aaedbfde.jpg)

Any idea or explanation for these issues?

Thank you very much, best regards,
Jürgen

**Comment by shailesh91** [comment]
Pull request #95 should solve this issue. You can fork the PR and try it out.

**Comment by shailesh91** [comment]
Closing the issue. Please open again if you have any further issues.
